### ISSUE TITLE
Obfuscate vfs passwords in stacktraces

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-ei#1041]
Sometimes when an exception occur in VFS components, the exception stack trace shows the full VFS URI. So this stack trace may contain vfs password too. These passwords should be masked for better security. Most of these passwords are masked in synapse level but if the exception is originated in commons-vfs or any other level the passwords might be visible in the stack trace.

ex :- 
org.apache.commons.vfs2.FileNotFoundException: Could not read from "ftp://localhost:***@server-ftp1/ftp2esb/ESBPROD/in/api.edi?vfs.passive=true" because it is a not a file.
at org.apache.commons.vfs2.provider.AbstractFileObject.getInputStream(AbstractFileObject.java:1316)
at org.apache.commons.vfs2.provider.DefaultFileContent.getInputStream(DefaultFileContent.java:397)
at org.apache.synapse.transport.vfs.VFSTransportListener.processFile(VFSTransportListener.java:601)
at org.apache.synapse.transport.vfs.VFSTransportListener.scanFileOrDirectory(VFSTransportListener.java:335)
at org.apache.synapse.transport.vfs.VFSTransportListener.poll(VFSTransportListener.java:159)
at org.apache.synapse.transport.vfs.VFSTransportListener.poll(VFSTransportListener.java:108)
at org.apache.axis2.transport.base.AbstractPollingTransportListener$1$1.run(AbstractPollingTransportListener.java:67)
at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: ftp://localhost:visiblepassword@server-ftp1/ftp2esb/ESBPROD/in/api.edi?vfs.passive=true
at org.apache.commons.vfs2.provider.ftp.FtpFileObject.doGetInputStream(FtpFileObject.java:610)
at org.apache.commons.vfs2.provider.AbstractFileObject.getInputStream(AbstractFileObject.java:1308)

**Comment by a5anka** [comment]
This is fixed in https://github.com/wso2/wso2-commons-vfs/pull/38

**Comment by a5anka** [comment]
Please check if the dependency is added to product-ei before closing the issue

**Comment by nandika** [comment]
The relevant pull request is merged and vfs version and synapse version is updated
