### ISSUE TITLE
Tenant not loading when multiple requests hits to tenant url at initial server startup

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/product-ei#1107]
**Description:**
The issue is related to carbon kernel and multi-tenancy. Tenant create programmatically with TenantInfoBean#setActive() set to true but, tenant persisting with false. This cause race condition when simultaneous requests sent to tenant url at the initial server startup and tenant not loading properly. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2ei-6.1.1

**OS, DB, other environment details and versions:**    
ubuntu 

**Steps to reproduce:**
- There is an OSGi component written to create tenant programmatically at server startup reading set of system variable such as TENANT_PASSWORD, TENANT_ID, TENANT_DOMAIN.
- A carbon app that has sample API copied to wso2esb-5.0.0/repository/tenants/$TENANAT_ID/carbonapps folder.
- When request hit to carbon app URL (tenant URL), esb throwing following exception and tenant doesn't load.
- Tenant load after 15 min, `<DefaultCacheTimeout>` hits.
```
[2017-09-29 14:23:05,105] [EI-Core] ERROR - ServerWorker Error processing GET reguest for : /t/a.com/container/endpoints. Error detail: Trying to access inactive tenant domain : a.com.
java.lang.RuntimeException: Trying to access inactive tenant domain : a.com
    at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.getTenantConfigurationContext(TenantAxisUtils.java:130)
    at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRequest(MultitenantMessageReceiver.java:222)
    at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:83)
    at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
    at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)
    at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
    at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
```
**Related Issues:**

**Comment by indikasampath2000** [comment]
Fixed with https://github.com/wso2/carbon-kernel/commit/5a8d2137bd2bcf93b1274ce31847fee0a85ea51f
