### ISSUE TITLE
"java.lang.ArrayIndexOutOfBoundsException" was thrown when refresh the system logs under Monitor tab

### ISSUE THREAD

**Issue by aparnawso2** [wso2/product-ei#114]
Following error was thrown when refresh the system logs 
Pack: M2
OS: Debian 8
Java: jdk8

[2017-02-01 11:17:39,512] [EI-Core] ERROR - ServerWorker Error processing GET reguest for : /carbon/yui/build/yahoo/yahoo-min.js. Error detail: -1. 
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.fastRemove(ArrayList.java:546)
	at java.util.ArrayList.remove(ArrayList.java:529)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.removePreserveHttpHeader(PassThroughHttpSender.java:319)
	at org.wso2.carbon.integrator.core.handler.IntegratorSynapseHandler.handleRequestInFlow(IntegratorSynapseHandler.java:99)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.invokeHandlers(Axis2SynapseEnvironment.java:1084)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:242)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:78)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:325)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-01 11:17:39,515] [EI-Core]  WARN - PassThroughHttpSSLSender Trying to submit a response to an already closed connection : http-incoming-23
[2017-02-01 11:17:39,517] [EI-Core] ERROR - IntegratorSynapseHandler Error occurred in integrator handler.
java.lang.ArrayIndexOutOfBoundsException

**Comment by madhawa-gunasekara** [comment]
Seems this is a bug in synapse. We will fix it :+1:
