### ISSUE TITLE
[Windows][Analatics]Backend gives an error while starting the pack

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#116]
**Enviornment**
OS-windows 2008
JAVA-jdk 1.8.0
wso2ei-6.0.0-m2 pack

**Steps**

1. Start the M2 pack in Windows using start_all script
2. When starting the analytic runtime, following error could be seen in backend 

`[2017-01-31 22:29:28,556] [EI-Analytics] ERROR {org.wso2.siddhi.core.util.Siddhi
ExtensionLoader} -  Error viewing zip file for jar:C:\Program Files\Java\jre1.8.
0_101\lib\tools.jar
java.io.FileNotFoundException: C:\Program Files\Java\jre1.8.0_101\lib\tools.jar
(The system cannot find the file specified)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at org.wso2.siddhi.core.util.SiddhiExtensionLoader.getContentFromJarFile
(SiddhiExtensionLoader.java:114)
        at org.wso2.siddhi.core.util.SiddhiExtensionLoader.getContent(SiddhiExte
nsionLoader.java:85)
        at org.wso2.siddhi.core.util.SiddhiExtensionLoader.getResources(SiddhiEx
tensionLoader.java:74)
        at org.wso2.siddhi.core.util.SiddhiExtensionLoader.loadSiddhiExtensions(
SiddhiExtensionLoader.java:54)
        at org.wso2.siddhi.core.config.SiddhiContext.<init>(SiddhiContext.java:4
5)
        at org.wso2.siddhi.core.SiddhiManager.<init>(SiddhiManager.java:49)
        at org.wso2.carbon.event.processor.core.internal.ds.EventProcessorServic
eDS.activate(EventProcessorServiceDS.java:98)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(Servi
ceComponent.java:260)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(S
erviceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(Serv
iceComponentProp.java:345)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(Instan
ceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(Insta
nceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:34
3)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.
java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.ser
viceChanged(FilteredServiceListener.java:107)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEv
ent(BundleContextImpl.java:861)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventM
anager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchr
onous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServ
iceEventPrivileged(ServiceRegistry.java:819)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServ
iceEvent(ServiceRegistry.java:771)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.reg
ister(ServiceRegistrationImpl.java:130)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerSer
vice(ServiceRegistry.java:214)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerSe
rvice(BundleContextImpl.java:433)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerSe
rvice(BundleContextImpl.java:451)
        at org.wso2.carbon.ndatasource.core.internal.DataSourceServiceComponent.
registerServices(DataSourceServiceComponent.java:126)
        at org.wso2.carbon.ndatasource.core.internal.DataSourceServiceComponent.
initSuperTenantUserDataSources(DataSourceServiceComponent.java:221)
        at org.wso2.carbon.ndatasource.core.internal.DataSourceServiceComponent.
checkInitTenantUserDataSources(DataSourceServiceComponent.java:206)
        at org.wso2.carbon.ndatasource.core.internal.DataSourceServiceComponent.
setRegistryService(DataSourceServiceComponent.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(Compone
ntReference.java:376)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindRefere
nce(ServiceComponentProp.java:430)
        at org.eclipse.equinox.internal.ds.InstanceProcess.dynamicBind(InstanceP
rocess.java:416)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:33
4)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.
java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.ser
viceChanged(FilteredServiceListener.java:107)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEv
ent(BundleContextImpl.java:861)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventM
anager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchr
onous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServ
iceEventPrivileged(ServiceRegistry.java:819)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServ
iceEvent(ServiceRegistry.java:771)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.reg
ister(ServiceRegistrationImpl.java:130)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerSer
vice(ServiceRegistry.java:214)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerSe
rvice(BundleContextImpl.java:433)
        at org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent.a
ctivate(RegistryCoreServiceComponent.java:129)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(Servi
ceComponent.java:260)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(S
erviceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(Serv
iceComponentProp.java:345)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(Instan
ceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(Insta
nceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:34
3)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.
java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.ser
viceChanged(FilteredServiceListener.java:107)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEv
ent(BundleContextImpl.java:861)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventM
anager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchr
onous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServ
iceEventPrivileged(ServiceRegistry.java:819)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServ
iceEvent(ServiceRegistry.java:771)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.reg
ister(ServiceRegistrationImpl.java:130)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerSer
vice(ServiceRegistry.java:214)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerSe
rvice(BundleContextImpl.java:433)
        at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.ja
va:69)
        at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleC
heckActivator.java:61)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(Bund
leContextImpl.java:711)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActiv
ator(BundleContextImpl.java:702)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(Bund
leContextImpl.java:683)
        at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(Bundl
eHost.java:381)
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(Abstra
ctBundle.java:390)
        at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Frame
work.java:1176)
        at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBund
les(StartLevelManager.java:559)
        at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBund
les(StartLevelManager.java:544)
        at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(St
artLevelManager.java:457)
        at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStart
Level(StartLevelManager.java:243)
        at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEv
ent(StartLevelManager.java:438)
        at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEv
ent(StartLevelManager.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventM
anager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(Even
tManager.java:340)`

**Comment by chalitha87** [comment]
verified in alpha pack on 15th of Feb. Couldn't see the above error
