### ISSUE TITLE
DBReport mediator not working in transaction mode when the datasource is defined inline

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#1176]
**Description:**
When the data sources are defined inline and when useTransaction="true" db report mediator gives following exception,

java.lang.ClassCastException: org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper cannot be cast to javax.sql.PooledConnection
        at org.apache.synapse.commons.transaction.TranscationManger.addConnection(TranscationManger.java:179)
        at org.apache.synapse.mediators.db.DBReportMediator.processStatement(DBReportMediator.java:57)
        at org.apache.synapse.mediators.db.AbstractDBMediator.mediate(AbstractDBMediator.java:143)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:81)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:48)
        at org.apache.synapse.mediators.filters.InMediator.mediate(InMediator.java:61)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:81)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:48)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:149)
        at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:274)
        at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:83)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
        at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:317)
        at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:363)
        at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:142)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse" name="dbReportMediatorUseTransactionTestProxy" transports="https http" startOnLoad="true" trace="disable">
    <description/>
    <target>
        <inSequence>
            <send>
                <endpoint>
                    <address uri="http://localhost:9000/services/SimpleStockQuoteService"/>
                </endpoint>
            </send>
        </inSequence>
        <outSequence>
            <transaction action="new"/>
            <log level="custom">
                <property name="text" value="** Reporting to the Database testdb_dbreport1**"/>
            </log>
            <dbreport useTransaction="true" xmlns="http://ws.apache.org/ns/synapse">
                <connection>
                    <pool>
                        <driver>org.h2.Driver</driver>
                        <url>jdbc:h2:file:./samples/data-services/database/DATA_SERV_SAMP1</url>
                        <user>esb</user>
                        <password>esb</password>
                    </pool>
                </connection>
                <statement>
                    <sql>delete from company where name =?</sql>
                    <parameter expression="//m0:return/m1:symbol/child::text()"
                            xmlns:m0="http://services.samples" xmlns:m1="http://services.samples/xsd"
                            type="VARCHAR"/>
                </statement>
            </dbreport>
            <log level="custom">
                <property name="text" value="** Reporting to the Database testdb_dbreport2**"/>
            </log>
            <dbreport useTransaction="true" xmlns="http://ws.apache.org/ns/synapse">
                <connection>
                    <pool>
                        <driver>org.h2.Driver</driver>
                        <url>jdbc:h2:file:./samples/data-services/database/DATA_SERV_SAMP2</url>
                        <user>esb</user>
                        <password>esb</password>
                    </pool>
                </connection>
                <statement>
                    <sql>INSERT into company values (?,'c4',?)</sql>
                    <parameter expression="//m0:return/m1:symbol/child::text()"
                            xmlns:m1="http://services.samples/xsd" xmlns:m0="http://services.samples"
                               type="VARCHAR"/>
                    <parameter expression="//m0:return/m1:last/child::text()"
                            xmlns:m1="http://services.samples/xsd" xmlns:m0="http://services.samples"
                               type="DOUBLE"/>
                </statement>
            </dbreport>
            <transaction action="commit"/>
            <send/>
        </outSequence>
        <faultSequence>
            <log level="custom">
                <property name="text" value="** Rollback Transaction**"/>
            </log>
            <transaction action="rollback"/>
            <send/>
        </faultSequence>
    </target>
</proxy>

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by markbuttle** [comment]
Hi - did you get anywhere with this issue as I'm seeing this also on the Oracle JDBC driver and can't seem to find a suitable work-around or solution. Any help much appreciated?

**Comment by chanikag** [comment]
Hi,

You can define the datasource in the master-datasource.xml, and use the JNDI name on the synpase config. Integration test for the above scenario was added in the PR [1]

[1] https://github.com/wso2/product-ei/pull/1181

Thanks
