### ISSUE TITLE
WSO2EI 6.1.1: Cannot use a custom keystore Path with Cipher Tool

### ISSUE THREAD

**Issue by mathieubouchard** [wso2/product-ei#1198]
**Description:**
WSO2 Enterprise Integrator has configuration files in the <WSO2_EI_HOME>/conf/ directory instead of <WSO2_EI_HOME>/repository/conf/.

The Cipher Tool tries to load the <WSO2_EI_HOME>/repository/conf/carbon.xml to read the keystore location and other configuration values and fall back to default configuration values if the file doesn't exist.

Since WSO2 EI has it's configuration files in <WSO2_EI_HOME>/conf/, the configured values are never read, so it is impossible to configure a custom keystore file because the cipher tool tries to load the old keystore.

In the best outcome, the file is not found and we have the following exception:
```
Exception in thread "main" org.wso2.ciphertool.exception.CipherToolException: Error loading keyStore from ' repository/resources/security/wso2carbon.jks '
        at org.wso2.ciphertool.utils.KeyStoreUtil.getKeyStore(KeyStoreUtil.java:83)
        at org.wso2.ciphertool.utils.KeyStoreUtil.initializeCipher(KeyStoreUtil.java:54)
        at org.wso2.ciphertool.CipherTool.main(CipherTool.java:53)
Caused by: java.io.FileNotFoundException: repository\resources\security\wso2carbon.jks (Le fichier spécifié est introuvable)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.wso2.ciphertool.utils.KeyStoreUtil.getKeyStore(KeyStoreUtil.java:76)
        ... 2 more
```

At worst, the default keystore is used, so the values are encrypted with the wrong key.

**Suggested Labels:**
wso2ei
ciphertool

**Affected Product Version:**
WSO2 Enterprise Integrator 6.1.1

**OS, DB, other environment details and versions:**    
Windows / JDK8 / Google Chrome
RHEL6 / JDK8 / Mozilla Firefox

**Steps to reproduce:**
Delete the default wso2 keystore from <WSO2_EI_HOME>/repository/resources/security/wso2carbon.jks
Create a new keystore (ex: <WSO2_EI_HOME>/repository/resources/security/wso2encryption.jks)
Modify <WSO2_EI_HOME>/conf/carbon.xml to configure the keystore PATH
Run the Cipher Tool (bin/ciphertool.sh -Dconfigure)

**Comment by mathieubouchard** [comment]
Pull request that fix the issue:
https://github.com/wso2/cipher-tool/pulls

**Comment by chanikag** [comment]
Fixed with https://github.com/wso2/cipher-tool/pull/32
