### ISSUE TITLE
Intermittent failure of Sample8Testcase due to excpetion at artifact deployment

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/product-ei#1229]
**Description:**
org.wso2.carbon.esb.samples.test.mediation.Sample8TestCase fails intermittently due to the faollowing failure.
org.apache.axis2.AxisFault: Read timed out
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:199)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:77)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:430)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.mediation.configadmin.stub.ConfigServiceAdminStub.updateConfiguration(ConfigServiceAdminStub.java:1340)
	at org.wso2.esb.integration.common.clients.mediation.SynapseConfigAdminClient.updateConfiguration(SynapseConfigAdminClient.java:174)
	at org.wso2.carbon.esb.samples.test.mediation.Sample8TestCase.uploadSynapseConfig(Sample8TestCase.java:48)

**Comment by sdkottegoda** [comment]
Related to:https://github.com/wso2/product-ei/issues/2848 
Closing since the related issue is resolved.
