### ISSUE TITLE
SSLEngine output buffer exception in message broker

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/product-ei#1242]
**Description:**
This issue happens intermittently when JMS client uses SSL transport. It thows following exceptions and consumers not able to receive messages.

```
TID: [] [] [2017-10-18 11:34:14,955000] ERROR {org.wso2.andes.transport.network.mina.MinaNetworkHandler} -  Exception caught by Mina {org.wso2.andes.transport.network.mina.MinaNetworkHandler}
javax.net.ssl.SSLException: Received fatal alert: bad_record_mac
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1639)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1607)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1776)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1068)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:890)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:764)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.apache.mina.filter.support.SSLHandler.unwrap0(SSLHandler.java:657)
	at org.apache.mina.filter.support.SSLHandler.unwrap(SSLHandler.java:595)
	at org.apache.mina.filter.support.SSLHandler.decrypt(SSLHandler.java:423)
	at org.apache.mina.filter.support.SSLHandler.messageReceived(SSLHandler.java:308)
	at org.apache.mina.filter.SSLFilter.messageReceived(SSLFilter.java:392)
	at org.apache.mina.common.support.AbstractIoFilterChain.callNextMessageReceived(AbstractIoFilterChain.java:299)
	at org.apache.mina.common.support.AbstractIoFilterChain.access$1100(AbstractIoFilterChain.java:53)
	at org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.messageReceived(AbstractIoFilterChain.java:648)
	at org.apache.mina.common.support.AbstractIoFilterChain$HeadFilter.messageReceived(AbstractIoFilterChain.java:499)
	at org.apache.mina.common.support.AbstractIoFilterChain.callNextMessageReceived(AbstractIoFilterChain.java:299)
	at org.apache.mina.common.support.AbstractIoFilterChain.fireMessageReceived(AbstractIoFilterChain.java:293)
	at org.apache.mina.transport.socket.nio.SocketIoProcessor.read(SocketIoProcessor.java:228)
	at org.apache.mina.transport.socket.nio.SocketIoProcessor.process(SocketIoProcessor.java:198)
	at org.apache.mina.transport.socket.nio.SocketIoProcessor.access$400(SocketIoProcessor.java:45)
	at org.apache.mina.transport.socket.nio.SocketIoProcessor$Worker.run(SocketIoProcessor.java:485)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:51)
	at java.lang.Thread.run(Thread.java:745)
.................................................................
TID: [] [] [2017-10-18 11:34:36,754000] ERROR {org.wso2.andes.transport.network.mina.MinaNetworkHandler} -  Exception caught by Mina {org.wso2.andes.transport.network.mina.MinaNetworkHandler}
javax.net.ssl.SSLException: SSLEngine error during encrypt: BUFFER_OVERFLOW src: java.nio.HeapByteBuffer[pos=16384 lim=16487 cap=16487]outNetBuffer: java.nio.DirectByteBuffer[pos=16453 lim=32974 cap=32974]
	at org.apache.mina.filter.support.SSLHandler.encrypt(SSLHandler.java:377)
	at org.apache.mina.filter.SSLFilter.filterWrite(SSLFilter.java:479)
	at org.apache.mina.common.support.AbstractIoFilterChain.callPreviousFilterWrite(AbstractIoFilterChain.java:361)
	at org.apache.mina.common.support.AbstractIoFilterChain.access$1300(AbstractIoFilterChain.java:53)
	at org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.filterWrite(AbstractIoFilterChain.java:659)
	at org.apache.mina.common.IoFilterAdapter.filterWrite(IoFilterAdapter.java:90)
	at org.apache.mina.common.support.AbstractIoFilterChain.callPreviousFilterWrite(AbstractIoFilterChain.java:361)
	at org.apache.mina.common.support.AbstractIoFilterChain.access$1300(AbstractIoFilterChain.java:53)
	at org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.filterWrite(AbstractIoFilterChain.java:659)
	at org.apache.mina.filter.executor.ExecutorFilter.filterWrite(ExecutorFilter.java:236)
	at org.apache.mina.common.support.AbstractIoFilterChain.callPreviousFilterWrite(AbstractIoFilterChain.java:361)
	at org.apache.mina.common.support.AbstractIoFilterChain.access$1300(AbstractIoFilterChain.java:53)
	at org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.filterWrite(AbstractIoFilterChain.java:659)
	at org.apache.mina.common.IoFilterAdapter.filterWrite(IoFilterAdapter.java:90)
	at org.apache.mina.common.support.AbstractIoFilterChain.callPreviousFilterWrite(AbstractIoFilterChain.java:361)
	at org.apache.mina.common.support.AbstractIoFilterChain.access$1300(AbstractIoFilterChain.java:53)
	at org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.filterWrite(AbstractIoFilterChain.java:659)
	at org.apache.mina.common.support.AbstractIoFilterChain$TailFilter.filterWrite(AbstractIoFilterChain.java:587)
	at org.apache.mina.common.support.AbstractIoFilterChain.callPreviousFilterWrite(AbstractIoFilterChain.java:361)
	at org.apache.mina.common.support.AbstractIoFilterChain.fireFilterWrite(AbstractIoFilterChain.java:355)
	at org.apache.mina.transport.socket.nio.SocketSessionImpl.write0(SocketSessionImpl.java:166)
	at org.apache.mina.common.support.BaseIoSession.write(BaseIoSession.java:177)
	at org.apache.mina.common.support.BaseIoSession.write(BaseIoSession.java:168)
	at org.wso2.andes.transport.network.mina.MinaSender.send(MinaSender.java:52)
	at org.wso2.andes.transport.network.mina.MinaSender.send(MinaSender.java:34)
	at org.wso2.andes.server.protocol.AMQProtocolEngine$2.run(AMQProtocolEngine.java:504)
	at org.wso2.andes.pool.Job.processAll(Job.java:111)
	at org.wso2.andes.pool.Job.run(Job.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
MB 3.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
There is a fix already introduce by the Apache Mina and the diff is attached to the [ticket](https://issues.apache.org/jira/browse/DIRMINA-637). Please fork the Mina and apply the patch. Next, we have to build the andes with the forked mina to overcome the issue.

**Related Issues:**

**Comment by himasha** [comment]
Fixed with https://github.com/wso2/wso2-mina/pull/2
