### ISSUE TITLE
Broker profile failed to start in 6.2.0-SNAPSHOT. 

### ISSUE THREAD

**Issue by nuwanw** [wso2/product-ei#1275]
Getting below error when starting the broker profile

[2017-11-08 17:59:04,626] [EI-Broker] ERROR {org.apache.catalina.core.StandardContext} -  Exception starting filter org.wso2.carbon.webapp.mgt.filter.AuthorizationHeaderFilter
java.lang.ClassNotFoundException: org.wso2.carbon.webapp.mgt.filter.AuthorizationHeaderFilter
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1892)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:495)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:477)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:113)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:258)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4958)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5652)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1571)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1561)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2017-11-08 17:59:04,633] [EI-Broker] ERROR {org.apache.catalina.core.StandardContext} -  One or more Filters failed to start. Full details will be found in the appropriate container log file

**Comment by VijithaEkanayake** [comment]
ixed with https://github.com/wso2/product-ei/pull/1287
