### ISSUE TITLE
[BPS 3.6.0] Server Startup Error when encrypting only the passwords in carbon.xml

### ISSUE THREAD

**Issue by hastef88** [wso2/product-ei#1326]
**Description:**
Following error occurs when trying to encrypt credentials in wso2bps-3.6.0 while encrypting only one password in carbon.xml (keystore password). 

FATAL
{org.wso2.carbon.tomcat.internal.TomcatBundleActivator}
- Error while starting server NOT_FOUND_ERR: An attempt is made to reference a node in a context where it does not exist.
org.w3c.dom.DOMException: NOT_FOUND_ERR: An attempt is made to reference a node in a context where it does not exist.
at org.apache.xerces.dom.AttributeMap.internalRemoveNamedItem(Unknown Source)
at org.apache.xerces.dom.AttributeMap.removeNamedItem(Unknown Source)
at org.wso2.carbon.tomcat.internal.ServerManager.init(ServerManager.java:98)
at org.wso2.carbon.tomcat.internal.TomcatBundleActivator.start(TomcatBundleActivator.java:45)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
at java.security.AccessController.doPrivileged(Native Method)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
[2017-11-13 20:32:14,300] INFO

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

BPS 3.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Try to start the server after encrypting only one password in carbon.xml (keystore password).

**Comment by hastef88** [comment]
Already fixed in master with : https://github.com/wso2/carbon-kernel/pull/1322/commits/213bacaa7ecdd5a16ce1b73f8333c35ef136ce65
