### ISSUE TITLE
ERROR - ForwardingService BlockingMessageSender of message processor [ProcessorXYZ] failed to send message to the endpoint with or without OUT_ONLY scenario for HL7 messages

### ISSUE THREAD

**Issue by marcses** [wso2/product-ei#1337]
**Description:**

I tried to store and forward HL7 messages without success. I have used a JDBCMessageStore for store the messages. I have used a ScheduledMessageForwardingProcessor for forward the messages.
I tried with o without OUT_ONLY scenario.
The destination endpoint receive correctly the messages in both scenarios but the ESB print the error: "failed to send message to the endpoint"

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 6.1.0, EI 6.1.1
**OS, DB, other environment details and versions:**    
Windows seven pro.
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Steps to reproduce:**
1) **Create a JDBCMessageStore**
```
<messageStore class="org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore" name="jdbcStore" xmlns="http://ws.apache.org/ns/synapse">
    <parameter name="store.jdbc.driver">com.microsoft.sqlserver.jdbc.SQLServerDriver</parameter>
    <parameter name="store.producer.guaranteed.delivery.enable">false</parameter>
    <parameter name="store.jdbc.username">hl7Store</parameter>
    <parameter name="store.jdbc.connection.url">jdbc:sqlserver://127.0.0.1;databaseName=HL7Store;instanceName=SQLEXPRESS;sendStringParametersAsUnicode=false</parameter>
    <parameter name="store.jdbc.password">xxxxxxx</parameter>
    <parameter name="store.jdbc.table">jdbc_message_store</parameter>
</messageStore>
```

2) **Create a messageProcessor**
```
<messageProcessor class="org.apache.synapse.message.processor.impl.forwarder.ScheduledMessageForwardingProcessor" messageStore="jdbcStore" 
	name="ProcessorXYZ" targetEndpoint="forward-ep" xmlns="http://ws.apache.org/ns/synapse">
    <parameter name="client.retry.interval">10000</parameter>
    <parameter name="max.delivery.attempts">1</parameter>
    <parameter name="member.count">1</parameter>
    <parameter name="message.processor.reply.sequence">reply-seq</parameter>
    <parameter name="message.processor.fault.sequence">fault-seq</parameter>
    <parameter name="max.delivery.drop">Disabled</parameter>
    <parameter name="interval">10000</parameter>
    <parameter name="is.active">false</parameter>
</messageProcessor>
```

3) **Create an endpoint**
```
<endpoint name="forward-ep" xmlns="http://ws.apache.org/ns/synapse">
    <address uri="hl7://127.0.0.1:50001"/>
</endpoint>
```

4) **Create sequences**
```
<sequence name="reply-seq" trace="disable" xmlns="http://ws.apache.org/ns/synapse">
    <log level="full">
        <property name="MSG" value="==== reply-seq SEQ  ==="/>
    </log>
</sequence>
```
---
```
<sequence name="fault-seq" trace="disable" xmlns="http://ws.apache.org/ns/synapse">
    <log level="full">
        <property name="MSG" value="==== fault-seq SEQ  ==="/>
    </log>
</sequence>
```

5) **Create an HL7 proxy for storing the messages**
```
<proxy name="to-store" startOnLoad="true" statistics="enable" trace="enable" transports="hl7" xmlns="http://ws.apache.org/ns/synapse">
    <target>
        <inSequence>
            <log level="full">
                <property name="MSG" value="==== to-store INPUT SEQ  ==="/>
            </log>
              
            <store messageStore="jdbcStore"/>
            <drop/>
        </inSequence>
        <outSequence>
            <log level="full">
                <property name="MSG" value="==== to-store OUT SEQ  ==="/>
            </log>
            <drop/>
        </outSequence>
        <faultSequence>
            <log level="full">
                <property name="MSG" value="==== to-store FAULT SEQ  ==="/>
            </log>
            <drop/>
        </faultSequence>
    </target>
    <parameter name="transport.hl7.maxPoolSize">200</parameter>
    <parameter name="transport.hl7.ValidateMessage">false</parameter>
    <parameter name="transport.hl7.Port">9299</parameter>
    <parameter name="transport.hl7.AutoAck">false</parameter>
    <parameter name="transport.hl7.corePoolSize">50</parameter>
    <parameter name="transport.hl7.idleThreadKeepAlive">5000</parameter>
</proxy>
```

6) Activate a hl7 server on 127.0.0.1:50001 with HAPI TestPanel

7) Send hl7 message to proxy with HAPI TestPanel

8) The message is successfull saved in the store 

9) Activate the messageProcessor "ProcessorXYZ" and observing following error. 
**Note**: The HAPI server receive correctly the hl7 message on 127.0.0.1:50001 
The `reply-seq` is not called and the `fault-seq` receive the hl7 ACK message 

```
TID: [-1234] [] [2017-11-16 12:00:45,188] DEBUG {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor} -  Starting Message Processor Scheduler : null {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor}
TID: [-1234] [] [2017-11-16 12:00:45,203]  INFO {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor} -  Successfully re-activated the message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor}
TID: [-1234] [] [2017-11-16 12:00:46,452] DEBUG {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Sending the message to client with message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:00:46,455] DEBUG {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender} -  Send HL7 message using EPR :hl7://127.0.0.1:50001 {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender}
TID: [-1234] [] [2017-11-16 12:00:46,472] DEBUG {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender} -  HL7 message successfully dispatched to URL hl7://127.0.0.1:50001 {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender}
TID: [-1234] [] [2017-11-16 12:00:46,476] DEBUG {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender} -  Response message received from target EP : MSH|^~\&|AAAA|BBBB|CCCC|DDDD|20171116120046.463+0100||ACK^A31|2233|P|2.5
MSA|AA|PIC38d3ef0d632a4c46
 {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender}
TID: [-1234] [] [2017-11-16 12:00:46,478] ERROR {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  BlockingMessageSender of message processor [ProcessorXYZ] failed to send message to the endpoint {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:00:46,480]  INFO {org.apache.synapse.mediators.builtin.LogMediator} -  To: , WSAction: urn:mediate, SOAPAction: urn:mediate, MessageID: urn:uuid:CF17179B3B5AB35B38176238493875437-2114254148, Direction: request, MSG = ==== fault-seq SEQ  ===, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><hl7:message xmlns:hl7="http://wso2.org/hl7"><ACK xmlns="urn:hl7-org:v2xml">
    <MSH>
        <MSH.1>|</MSH.1>
        <MSH.2>^~\&amp;</MSH.2>
        <MSH.3>
            <HD.1>AAAA</HD.1>
        </MSH.3>
        <MSH.4>
            <HD.1>BBBB</HD.1>
        </MSH.4>
        <MSH.5>
            <HD.1>CCCC</HD.1>
        </MSH.5>
        <MSH.6>
            <HD.1>DDDD</HD.1>
        </MSH.6>
        <MSH.7>
            <TS.1>20171116120046.463+0100</TS.1>
        </MSH.7>
        <MSH.9>
            <MSG.1>ACK</MSG.1>
            <MSG.2>A31</MSG.2>
        </MSH.9>
        <MSH.10>2233</MSH.10>
        <MSH.11>
            <PT.1>P</PT.1>
        </MSH.11>
        <MSH.12>
            <VID.1>2.5</VID.1>
        </MSH.12>
    </MSH>
    <SFT/>
    <MSA>
        <MSA.1>AA</MSA.1>
        <MSA.2>PIC38d3ef0d632a4c46</MSA.2>
    </MSA>
    <ERR/>
</ACK></hl7:message></soapenv:Body></soapenv:Envelope> {org.apache.synapse.mediators.builtin.LogMediator}
TID: [-1234] [] [2017-11-16 12:00:46,481] DEBUG {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Successfully terminated job of message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:00:46,482]  WARN {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Failed to send the message through the deactivate sequence. Sequence name does not Exist. {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:00:46,482] DEBUG {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor} -  Deactivating message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor}
TID: [-1234] [] [2017-11-16 12:00:46,502]  INFO {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor} -  Successfully deactivated the message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor}
TID: [-1234] [] [2017-11-16 12:00:46,503] DEBUG {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor} -  Trying to fetch InboundRequestProcessor from classpath..  {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor}
TID: [-1234] [] [2017-11-16 12:00:46,506] DEBUG {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor} -  Message Processor Cleanup Service found  : org.wso2.carbon.mediation.message.processor.cleanup.MessageProcessorCleanupTask {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor}
TID: [-1234] [] [2017-11-16 12:00:46,508] DEBUG {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Message processor [ProcessorXYZ] stopped due to reach of max attempts {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:00:46,508] DEBUG {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Failed to send to client retrying after 10000s with attempt count - 1 {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:00:56,511] DEBUG {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Exiting the iteration of message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:00:56,512] DEBUG {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Exiting service thread of message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:01:18,364] ERROR {ca.uhn.hl7v2.app.Receiver} -  Error while processing message:  {ca.uhn.hl7v2.app.Receiver}
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
	at ca.uhn.hl7v2.llp.MinLLPWriter.writeMessage(MinLLPWriter.java:105)
	at ca.uhn.hl7v2.app.Receiver$Grunt.run(Receiver.java:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

If I add `<property name="OUT_ONLY" scope="default" type="STRING" value="true"/>`
before  `<store messageStore="jdbcStore"/>` in the proxy I observe the following error.
**Note**: The HAPI server receive correctly the hl7 message on 127.0.0.1:50001 
The `reply-seq` is not called and the `fault-seq` receive the hl7 message(request) instead of hl7 ACK message 

```
TID: [-1234] [] [2017-11-16 12:42:00,378] DEBUG {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor} -  Starting Message Processor Scheduler : null {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor}
TID: [-1234] [] [2017-11-16 12:42:00,396]  INFO {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor} -  Successfully re-activated the message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor}
TID: [-1234] [] [2017-11-16 12:42:01,585] DEBUG {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Sending the message to client with message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:42:01,587] DEBUG {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender} -  Send HL7 message using EPR :hl7://127.0.0.1:50001 {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender}
TID: [-1234] [] [2017-11-16 12:42:01,602] DEBUG {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender} -  HL7 message successfully dispatched to URL hl7://127.0.0.1:50001 {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender}
TID: [-1234] [] [2017-11-16 12:42:01,603] DEBUG {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender} -  Response message received from target EP : MSH|^~\&|AAAA|BBBB|CCCC|DDDD|20171116124201.6+0100||ACK^A31|2234|P|2.5
MSA|AA|PIC38d3ef0d632a4c46
 {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender}
TID: [-1234] [] [2017-11-16 12:42:01,605] ERROR {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender} -  Error while processing the response HL7 message {org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender}
java.lang.UnsupportedOperationException: Not yet implemented
	at org.apache.axis2.description.OutOnlyAxisOperation.getMessage(OutOnlyAxisOperation.java:124)
	at org.apache.axis2.transport.base.AbstractTransportSender.createResponseMessageContext(AbstractTransportSender.java:193)
	at org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender.processResponse(HL7TransportSender.java:77)
	at org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender.sendUsingEPR(HL7TransportSender.java:175)
	at org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender.sendMessage(HL7TransportSender.java:67)
	at org.apache.axis2.transport.base.AbstractTransportSender.invoke(AbstractTransportSender.java:112)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:297)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendRobust(BlockingMsgSender.java:282)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:201)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.dispatch(ForwardingService.java:471)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.execute(ForwardingService.java:207)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
TID: [-1234] [] [2017-11-16 12:42:01,608] ERROR {org.apache.synapse.message.senders.blocking.BlockingMsgSender} -  Error sending Message to url : hl7://127.0.0.1:50001 {org.apache.synapse.message.senders.blocking.BlockingMsgSender}
org.apache.axis2.AxisFault: Error while processing the response HL7 message
	at org.apache.axis2.transport.base.AbstractTransportSender.handleException(AbstractTransportSender.java:226)
	at org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender.processResponse(HL7TransportSender.java:82)
	at org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender.sendUsingEPR(HL7TransportSender.java:175)
	at org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender.sendMessage(HL7TransportSender.java:67)
	at org.apache.axis2.transport.base.AbstractTransportSender.invoke(AbstractTransportSender.java:112)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:297)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendRobust(BlockingMsgSender.java:282)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:201)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.dispatch(ForwardingService.java:471)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.execute(ForwardingService.java:207)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: Not yet implemented
	at org.apache.axis2.description.OutOnlyAxisOperation.getMessage(OutOnlyAxisOperation.java:124)
	at org.apache.axis2.transport.base.AbstractTransportSender.createResponseMessageContext(AbstractTransportSender.java:193)
	at org.wso2.carbon.business.messaging.hl7.transport.HL7TransportSender.processResponse(HL7TransportSender.java:77)
	... 18 more
TID: [-1234] [] [2017-11-16 12:42:01,610] ERROR {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  BlockingMessageSender of message processor [ProcessorXYZ] failed to send message to the endpoint {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:42:01,611]  INFO {org.apache.synapse.mediators.builtin.LogMediator} -  To: , WSAction: urn:mediate, SOAPAction: urn:mediate, MessageID: urn:uuid:CF17179B3B5AB35B38178641474412301-1064715702, Direction: request, MSG = ==== fault-seq SEQ  ===, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><hl7:message xmlns:hl7="http://wso2.org/hl7"><ADT_A05 xmlns="urn:hl7-org:v2xml">
    <MSH>
        <MSH.1>|</MSH.1>
        <MSH.2>^~\&amp;</MSH.2>
        <MSH.3>
            <HD.1>CCCC</HD.1>
        </MSH.3>
        <MSH.4>
            <HD.1>DDDD</HD.1>
        </MSH.4>
        <MSH.5>
            <HD.1>AAAA</HD.1>
        </MSH.5>
        <MSH.6>
            <HD.1>BBBB</HD.1>
        </MSH.6>
        <MSH.7>
            <TS.1>20171103173132</TS.1>
        </MSH.7>
        <MSH.9>
            <MSG.1>ADT</MSG.1>
            <MSG.2>A31</MSG.2>
            <MSG.3>ADT_A05</MSG.3>
        </MSH.9>
        <MSH.10>PIC38d3ef0d632a4c46</MSH.10>
        <MSH.11>
            <PT.1>P</PT.1>
        </MSH.11>
        <MSH.12>
            <VID.1>2.5</VID.1>
        </MSH.12>
        <MSH.18>8859/14</MSH.18>
    </MSH>
    <SFT/>
    <EVN>
        <EVN.1>A31</EVN.1>
        <EVN.2>
            <TS.1>20171103173131</TS.1>
        </EVN.2>
        <EVN.4>02</EVN.4>
        <EVN.5>
            <XCN.15>XXXXXX72H12C351I</XCN.15>
        </EVN.5>
        <EVN.6>
            <TS.1>20171103173131</TS.1>
        </EVN.6>
    </EVN>
    <PID>
        <PID.3>
            <CX.1>33</CX.1>
            <CX.4>
                <HD.1>CODCLI</HD.1>
            </CX.4>
            <CX.5>AN</CX.5>...
        
    ...<ACC/>
    <UB1/>
    <UB2/>
</ADT_A05></hl7:message></soapenv:Body></soapenv:Envelope> {org.apache.synapse.mediators.builtin.LogMediator}
TID: [-1234] [] [2017-11-16 12:42:01,613] ERROR {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  BlockingMessageSender of message processor [ProcessorXYZ] failed to send message to the endpoint {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:42:01,613] DEBUG {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Successfully terminated job of message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:42:01,613]  WARN {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Failed to send the message through the deactivate sequence. Sequence name does not Exist. {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:42:01,614] DEBUG {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor} -  Deactivating message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor}
TID: [-1234] [] [2017-11-16 12:42:01,627]  INFO {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor} -  Successfully deactivated the message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor}
TID: [-1234] [] [2017-11-16 12:42:01,627] DEBUG {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor} -  Trying to fetch InboundRequestProcessor from classpath..  {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor}
TID: [-1234] [] [2017-11-16 12:42:01,628] DEBUG {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor} -  Message Processor Cleanup Service found  : org.wso2.carbon.mediation.message.processor.cleanup.MessageProcessorCleanupTask {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor}
TID: [-1234] [] [2017-11-16 12:42:01,628] DEBUG {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Message processor [ProcessorXYZ] stopped due to reach of max attempts {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:42:01,629] DEBUG {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Failed to send to client retrying after 10000s with attempt count - 1 {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:42:11,629] DEBUG {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Exiting the iteration of message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
TID: [-1234] [] [2017-11-16 12:42:11,629] DEBUG {org.apache.synapse.message.processor.impl.forwarder.ForwardingService} -  Exiting service thread of message processor [ProcessorXYZ] {org.apache.synapse.message.processor.impl.forwarder.ForwardingService}
```

**Related Issues:**

**Comment by marcses** [comment]
I tried to add `
<property name="FORCE_SC_ACCEPTED" scope="axis2"
                    type="STRING" value="true"/>
`

before `<store messageStore="jdbcStore"/>` in the proxy and I observe the following value from debugger: HTTP_SC=null...
![debugger_forwardingservice_blockingmessagesender](https://user-images.githubusercontent.com/26251486/32942634-e2f331be-cb89-11e7-90d0-b43297945666.PNG)
