### ISSUE TITLE
Ciphertool is broken in WSO2 EI  and EI as a BPS

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-ei#1345]
**Description:**

- When executing the cipher tool to encrypt passwords, on WSO2 EI from <EI_HOME>/bin directory, got an error as below.
- And also when executing the cipher tool to encrypt passwords, on WSO2 EI as a BPS Profile from <EI_HOME>/wso2/business-process/bin, got an error as below.

```
Exception in thread "main" org.wso2.ciphertool.exception.CipherToolException: File, cipher-standalone-config.properties does not exist.
    at org.wso2.ciphertool.utils.Utils.setSystemProperties(Utils.java:247)
    at org.wso2.ciphertool.CipherTool.initialize(CipherTool.java:93)
    at org.wso2.ciphertool.CipherTool.main(CipherTool.java:52)
```

- This was reproduced with EI 6.0.0 and EI 6.1.1.

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
EI 6.0.0, EI 6.1.1

**Related Issues:**

**Comment by milanperera** [comment]
This error is no longer reproducible in EI-6.1.1-update23 and works as expected.
Seems like the issue is being fixed from [1].

[1] https://github.com/wso2/carbon-kernel/pull/1322
