### ISSUE TITLE
[critical] Analytics server searches for "repository/conf" directory

### ISSUE THREAD

**Issue by aparnawso2** [wso2/product-ei#138]
Analytics server cluster searches for "repository/conf" directory and seems like its hard coded.

/home/cloud-user/das/das_symlink/repository/conf/analytics/analytics-config.xml

`TID: [-1234] [] [2017-02-07 06:34:01,003] ERROR {org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService} -  Error while executing query :         INSERT INTO TABLE esbServiceStatPerHour        SELECT year, month, day, hour, componentId, componentName, componentType,        sum(totalDuration) as totalDuration, min(minDuration) as minDuration, max(maxDuration) as maxDuration,        sum(noOfInvocation) as noOfInvocation, sum(faultCount) as faultCount,        getHourStartingTime(year, month, day, hour) as startTime,        cast(getHourStartingTime(year, month, day, hour) as STRING) as facetStartTime, entryPoint, meta_tenantId,        getHourStartingTime(year, month, day, hour) as _timestamp        FROM esbServiceStatPerMinute        GROUP BY        year, month, day, hour, componentId, componentName, componentType, entryPoint, meta_tenantId {org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService}
org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Error executing analytics query: Error in cluster execute one: org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Exception in executing query INSERT INTO TABLE esbServiceStatPerHour        SELECT year, month, day, hour, componentId, componentName, componentType,        sum(totalDuration) as totalDuration, min(minDuration) as minDuration, max(maxDuration) as maxDuration,        sum(noOfInvocation) as noOfInvocation, sum(faultCount) as faultCount,        getHourStartingTime(year, month, day, hour) as startTime,        cast(getHourStartingTime(year, month, day, hour) as STRING) as facetStartTime, entryPoint, meta_tenantId,        getHourStartingTime(year, month, day, hour) as _timestamp        FROM esbServiceStatPerMinute        GROUP BY        year, month, day, hour, componentId, componentName, componentType, entryPoint, meta_tenantId
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQuery(SparkAnalyticsExecutor.java:726)
	at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeQuery(CarbonAnalyticsProcessorService.java:201)
	at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeScript(CarbonAnalyticsProcessorService.java:151)
	at org.wso2.carbon.analytics.spark.core.AnalyticsTask.execute(AnalyticsTask.java:60)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.analytics.dataservice.core.clustering.AnalyticsClusterException: Error in cluster execute one: org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Exception in executing query INSERT INTO TABLE esbServiceStatPerHour        SELECT year, month, day, hour, componentId, componentName, componentType,        sum(totalDuration) as totalDuration, min(minDuration) as minDuration, max(maxDuration) as maxDuration,        sum(noOfInvocation) as noOfInvocation, sum(faultCount) as faultCount,        getHourStartingTime(year, month, day, hour) as startTime,        cast(getHourStartingTime(year, month, day, hour) as STRING) as facetStartTime, entryPoint, meta_tenantId,        getHourStartingTime(year, month, day, hour) as _timestamp        FROM esbServiceStatPerMinute        GROUP BY        year, month, day, hour, componentId, componentName, componentType, entryPoint, meta_tenantId
	at org.wso2.carbon.analytics.dataservice.core.clustering.AnalyticsClusterManagerImpl.executeOne(AnalyticsClusterManagerImpl.java:264)
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQuery(SparkAnalyticsExecutor.java:723)
	... 10 more
Caused by: java.util.concurrent.ExecutionException: org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Exception in executing query INSERT INTO TABLE esbServiceStatPerHour        SELECT year, month, day, hour, componentId, componentName, componentType,        sum(totalDuration) as totalDuration, min(minDuration) as minDuration, max(maxDuration) as maxDuration,        sum(noOfInvocation) as noOfInvocation, sum(faultCount) as faultCount,        getHourStartingTime(year, month, day, hour) as startTime,        cast(getHourStartingTime(year, month, day, hour) as STRING) as facetStartTime, entryPoint, meta_tenantId,        getHourStartingTime(year, month, day, hour) as _timestamp        FROM esbServiceStatPerMinute        GROUP BY        year, month, day, hour, componentId, componentName, componentType, entryPoint, meta_tenantId
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:204)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Exception in executing query INSERT INTO TABLE esbServiceStatPerHour        SELECT year, month, day, hour, componentId, componentName, componentType,        sum(totalDuration) as totalDuration, min(minDuration) as minDuration, max(maxDuration) as maxDuration,        sum(noOfInvocation) as noOfInvocation, sum(faultCount) as faultCount,        getHourStartingTime(year, month, day, hour) as startTime,        cast(getHourStartingTime(year, month, day, hour) as STRING) as facetStartTime, entryPoint, meta_tenantId,        getHourStartingTime(year, month, day, hour) as _timestamp        FROM esbServiceStatPerMinute        GROUP BY        year, month, day, hour, componentId, componentName, componentType, entryPoint, meta_tenantId
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQueryLocal(SparkAnalyticsExecutor.java:772)
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQuery(SparkAnalyticsExecutor.java:729)
	at org.wso2.carbon.analytics.spark.core.AnalyticsExecutionCall.call(AnalyticsExecutionCall.java:45)
	at org.wso2.carbon.analytics.spark.core.AnalyticsExecutionCall.call(AnalyticsExecutionCall.java:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:202)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:384)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:334)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:225)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:71)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:56)
	at org.wso2.carbon.analytics.dataservice.core.clustering.AnalyticsClusterManagerImpl.executeOne(AnalyticsClusterManagerImpl.java:262)
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQuery(SparkAnalyticsExecutor.java:723)
	at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeQuery(CarbonAnalyticsProcessorService.java:201)
	at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeScript(CarbonAnalyticsProcessorService.java:151)
	at org.wso2.carbon.analytics.spark.core.AnalyticsTask.execute(AnalyticsTask.java:60)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 33.0 failed 4 times, most recent failure: Lost task 0.3 in stage 33.0 (TID 75, ei6s2-analytics1.novalocal): java.lang.RuntimeException: Error in creating analytics data service impl.: Cannot initalize analytics data service, the analytics data service configuration file cannot be found at: /home/cloud-user/das/das_symlink/repository/conf/analytics/analytics-config.xml
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsServiceHolder.checkAndPopulateCustomAnalyticsDS(AnalyticsServiceHolder.java:89)
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsServiceHolder.getAnalyticsDataService(AnalyticsServiceHolder.java:74)
	at org.wso2.carbon.analytics.spark.core.internal.ServiceHolder.getAnalyticsDataService(ServiceHolder.java:95)
	at org.wso2.carbon.analytics.spark.core.rdd.AnalyticsRDD.compute(AnalyticsRDD.java:87)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsException: Cannot initalize analytics data service, the analytics data service configuration file cannot be found at: /home/cloud-user/das/das_symlink/repository/conf/analytics/analytics-config.xml
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.loadAnalyticsDataServiceConfig(AnalyticsDataServiceImpl.java:332)
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.<init>(AnalyticsDataServiceImpl.java:133)
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsServiceHolder.checkAndPopulateCustomAnalyticsDS(AnalyticsServiceHolder.java:87)
	... 24 more

`

**Comment by mpmunasinghe** [comment]
Adding the system parameters mentioned in https://github.com/wso2/product-ei/issues/127
Would fix the above issue. In a symlink based deployment this is required in the startup scripts to properly refer the changed directory structure.

**Comment by aparnawso2** [comment]
I have added the above #127 configurations, but still, issues exists.

**Comment by mpmunasinghe** [comment]
Alongside above parameters mentioned in #127 below line should be replaced
export CARBON_CONFIG_DIR_PATH=$CARBON_HOME/conf
with following in bin/load-spark-env-vars.sh
export CARBON_CONFIG_DIR_PATH=<SYM_LINK_PATH>/conf
