### ISSUE TITLE
java.lang.ClassCastException occurs in a PUT request with empty body and application/octet-stream content type

### ISSUE THREAD

**Issue by VijithaEkanayake** [wso2/product-ei#1404]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Create an API with PUT resource
2. Disable chunking by adding following property to API 's insequence

<property name="DISABLE_CHUNKING" value="true" scope="axis2"/>

3. Send a PUT request to the API

curl -X PUT --header 'Content-Type: application/octet-stream' --header 'Accept: application/octet-stream' --header 'Content-Length:0'  -d '{}' "https://localhost:8243/perform/put" -k

4. ClasscastException will be occurred as [1]

[1] [2017-09-28 07:50:52,152] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "PUT /perform/v1.0.0/put HTTP/1.1[\r][\n]"
[2017-09-28 07:50:52,152] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "Host: localhost:8243[\r][\n]"
[2017-09-28 07:50:52,152] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "User-Agent: curl/7.47.0[\r][\n]"
[2017-09-28 07:50:52,152] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "Content-Type: application/octet-stream[\r][\n]"
[2017-09-28 07:50:52,152] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "Accept: application/octet-stream[\r][\n]"
[2017-09-28 07:50:52,152] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "Content-Length:0[\r][\n]"
[2017-09-28 07:50:52,152] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "Authorization: Bearer 0134bbc7-91f3-3346-85d6-2ff8c12e6cbf[\r][\n]"
[2017-09-28 07:50:52,152] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "[\r][\n]"
[2017-09-28 07:50:52,152] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "{}"
[2017-09-28 07:50:52,152] DEBUG - headers http-incoming-2 >> PUT /perform/v1.0.0/put HTTP/1.1
[2017-09-28 07:50:52,153] DEBUG - headers http-incoming-2 >> Host: localhost:8243
[2017-09-28 07:50:52,153] DEBUG - headers http-incoming-2 >> User-Agent: curl/7.47.0
[2017-09-28 07:50:52,153] DEBUG - headers http-incoming-2 >> Content-Type: application/octet-stream
[2017-09-28 07:50:52,153] DEBUG - headers http-incoming-2 >> Accept: application/octet-stream
[2017-09-28 07:50:52,153] DEBUG - headers http-incoming-2 >> Content-Length:0
[2017-09-28 07:50:52,153] DEBUG - headers http-incoming-2 >> Authorization: Bearer 0134bbc7-91f3-3346-85d6-2ff8c12e6cbf
[2017-09-28 07:50:52,391] ERROR - TargetHandler Unexpected error: org.apache.http.message.BasicHttpRequest cannot be cast to org.apache.http.message.BasicHttpEntityEnclosingRequest
java.lang.ClassCastException: org.apache.http.message.BasicHttpRequest cannot be cast to org.apache.http.message.BasicHttpEntityEnclosingRequest
	at org.apache.synapse.transport.passthru.TargetRequest.processChunking(TargetRequest.java:327)
	at org.apache.synapse.transport.passthru.TargetRequest.start(TargetRequest.java:267)
	at org.apache.synapse.transport.passthru.TargetHandler.requestReady(TargetHandler.java:169)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.produceOutput(DefaultNHttpClientConnection.java:286)
	at org.apache.synapse.transport.http.conn.LoggingNHttpClientConnection.produceOutput(LoggingNHttpClientConnection.java:132)
	at org.apache.synapse.transport.passthru.ClientIODispatch.onOutputReady(ClientIODispatch.java:88)
	at org.apache.synapse.transport.passthru.ClientIODispatch.onOutputReady(ClientIODispatch.java:41)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:143)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:180)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:342)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:748)

**Related Issues:**

**Comment by VijithaEkanayake** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/841
