### ISSUE TITLE
"SQLException: Invalid column name" when creating a OData enabled dataservice with oracle db

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#1409]
**Description:**
This was reproduced with 6.1.1 fresh pack and oracle 12c db.

Steps to reproduce.
SQL queries
```
create or replace TYPE one AS OBJECT (
    fecha_cuota DATE,
    cuantia_cuota NUMBER,
    CONSTRUCTOR FUNCTION one
        RETURN SELF AS RESULT
); 
create table testTable 
(
	someNO NUMBER,
	inData one
);
INSERT INTO testTable VALUES(1, one(TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 100));

INSERT INTO testTable VALUES(2, one(TO_DATE('2003/06/14 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 200));

create or replace PACKAGE newPkg AS
      TYPE refcur IS REF CURSOR;
     
      PROCEDURE newProc
      (
            p_canal IN NUMBER,
            c_cursor OUT refcur
      );
 END;

create or replace PACKAGE BODY newPkg AS
      PROCEDURE newProc
      (
            p_canal IN NUMBER,
            c_cursor OUT refcur
      )
      IS
      BEGIN
	    OPEN c_cursor FOR
 	    SELECT testTable.inData FROM testTable where someNO=p_canal;
       END;
END;
```
dataservice
```
<data name="xyz" transports="http https local">
   <config enableOData="true" id="default">
      <property name="driverClassName">oracle.jdbc.driver.OracleDriver</property>
      <property name="url">jdbc:oracle:thin:@[ip]:[port]/[sid]</property>
      <property name="username">[username]</property>
      <property name="password">[password]</property>
   </config>
   <query id="consultaProcedure" useConfig="default">
      <sql>{call newPkg.newProc(:p_canal,:c_cursor)}</sql>
      <result element="resultado" rowName="resultado">
         <element column="inData[0]" name="dataOutput" xsdType="date"/>
         <element column="inData[1]" name="numOutput" xsdType="float"/>
      </result>
      <param name="p_canal" sqlType="INTEGER"/>
      <param name="c_cursor" sqlType="ORACLE_REF_CURSOR" type="OUT"/>
   </query>
   <operation name="getConsultaProcedure">
      <call-query href="consultaProcedure">
         <with-param name="p_canal" query-param="p_canal"/>
      </call-query>
   </operation>
</data>

```

When we upload the dataservice, we get the following error.
```
[2017-11-24 14:36:23,196] [EI-Core] ERROR - DBDeployer The xyz.dbs service, which is not valid, caused {1}
DS Fault Message: OData Service Fault : Error in reading table meta data in TESTTABLE table. :Invalid column name
DS Code: UNKNOWN_ERROR
Nested Exception:-
java.sql.SQLException: Invalid column name

	at org.wso2.carbon.dataservices.core.odata.RDBMSDataHandler.readTableColumnMetaData(RDBMSDataHandler.java:1056)
	at org.wso2.carbon.dataservices.core.odata.RDBMSDataHandler.initializeMetaData(RDBMSDataHandler.java:1078)
	at org.wso2.carbon.dataservices.core.odata.RDBMSDataHandler.<init>(RDBMSDataHandler.java:114)
	at org.wso2.carbon.dataservices.core.description.config.RDBMSConfig.createODataHandler(RDBMSConfig.java:64)
	at org.wso2.carbon.dataservices.core.DBDeployer.createDBService(DBDeployer.java:805)
	at org.wso2.carbon.dataservices.core.DBDeployer.processService(DBDeployer.java:1152)
	at org.wso2.carbon.dataservices.core.DBDeployer.deploy(DBDeployer.java:201)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Invalid column name
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:147)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:209)
	at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:3325)
	at oracle.jdbc.driver.OracleResultSetImpl.findColumn(OracleResultSetImpl.java:1926)
	at oracle.jdbc.driver.OracleResultSet.getString(OracleResultSet.java:1515)
	at org.wso2.carbon.dataservices.core.odata.RDBMSDataHandler.readTableColumnMetaData(RDBMSDataHandler.java:1028)
	... 23 more
```
Without Odata enabled, it works fine. Also, it works with mysql for both OData enabled/disabled.

request
```
<body>
   <p:getConsultaProcedure xmlns:p="http://ws.wso2.org/dataservice">
      <!--Exactly 1 occurrence-->
      <xs:p_canal xmlns:xs="http://ws.wso2.org/dataservice">1</xs:p_canal>
   </p:getConsultaProcedure>
</body>
```

response
```
<resultado xmlns="http://ws.wso2.org/dataservice">
   <resultado>
      <dataOutput>2003-05-03 21:02:44.0</dataOutput>
      <numOutput>100</numOutput>
   </resultado>
</resultado>
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 6.1.1

**OS, DB, other environment details and versions:**    
oracle 12c db 

**Steps to reproduce:**

**Related Issues:**

**Comment by madhawa-gunasekara** [comment]
I tried to reproduce this issue with the ORACLE 11g. I couldn't able to reproduce this issue. but when I do the debugging with @Thishani, We was able to find that IS_AUTOINCREMENT column is causing the issue. but according JDBC spec [1] It should be supported. Sometime you are not using the correct jdbc driver. 

[1] https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html
[2] https://hub.docker.com/r/alexeiled/docker-oracle-xe-11g/
