### ISSUE TITLE
ClassCastException within cache mediator

### ISSUE THREAD

**Issue by VijithaEkanayake** [wso2/product-ei#1441]
**Description:**
When processing the response message from the cache mediator, implementation tries to cast HTTP status code to a String. Then it throws class cast exception as follows.

INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2017-11-30 14:49:49,156] [EI-Core] ERROR - SequenceMediator java.lang.Integer cannot be cast to java.lang.String
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.mediator.cache.CacheMediator.processResponseMessage(CacheMediator.java:369)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.mediator.cache.CacheMediator.mediate(CacheMediator.java:209)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:100)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:62)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.rest.Resource.process(Resource.java:343)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.rest.API.process(API.java:338)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:123)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:101)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:56)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:574)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:197)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:263)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.lang.Thread.run(Thread.java:748)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2017-11-30 14:49:49,158] [EI-Core] ERROR - caching_enabled_api java.lang.Integer cannot be cast to java.lang.String
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.mediator.cache.CacheMediator.processResponseMessage(CacheMediator.java:369)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.mediator.cache.CacheMediator.mediate(CacheMediator.java:209)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:100)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:62)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.rest.Resource.process(Resource.java:343)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.rest.API.process(API.java:338)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:123)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:101)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:56)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:574)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:197)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:263)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.lang.Thread.run(Thread.java:748)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2017-11-30 14:49:49,194] [EI-Core]  INFO - LogMediator To: http://www.w3.org/2005/08/addressing/anonymous, WSAction: , SOAPAction: , MessageID: urn:uuid:e96e9d3b-bf74-43af-86e9-a449430afb96, Direction: response, MESSAGE = Executing default "fault" sequence, ERROR_CODE = 0, ERROR_MESSAGE = java.lang.Integer cannot be cast to java.lang.String, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><jsonArray><?xml-multiple  jsonElement?><jsonElement><msg>Hello</msg><?xml-multiple  services?><services>elec</services><services>patrol</services><test>World.</test></jsonElement><jsonElement><msg>Hi</msg><?xml-multiple  services?><services>water</services><test>Sri Lanka.</test></jsonElement></jsonArray></soapenv:Body></soapenv:Envelope>

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by VijithaEkanayake** [comment]
Fixed with https://github.com/wso2/carbon-mediation/pull/923
