### ISSUE TITLE
JDBC message processor gives null pointer when the message SOAP body is empty

### ISSUE THREAD

**Issue by vinok88** [wso2/product-ei#1449]
**Description:**
When a message body is empty, JDBC message processor gives following NPE.
`[2017-12-01 14:06:44,127] [EI-Core]  INFO - LogMediator To: /services/Aproxy, MessageID: urn:uuid:3547bae4-64dd-4d15-8280-94dec0601bb0, Direction: request, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body/></soapenv:Envelope>
[2017-12-01 14:06:45,076] [EI-Core] ERROR - MessageConverter Cannot create Message Context. Error:null
java.lang.NullPointerException
	at org.apache.axiom.om.impl.llom.OMElementImpl.addChild(OMElementImpl.java:211)
	at org.apache.axiom.soap.impl.llom.SOAPBodyImpl.addChild(SOAPBodyImpl.java:231)
	at org.apache.synapse.message.store.impl.commons.MessageConverter.getSoapEnvelope(MessageConverter.java:362)
	at org.apache.synapse.message.store.impl.commons.MessageConverter.toMessageContext(MessageConverter.java:98)
	at org.apache.synapse.message.store.impl.jms.JmsConsumer.receive(JmsConsumer.java:107)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.fetch(ForwardingService.java:406)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.execute(ForwardingService.java:196)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 6.1.1
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by vinok88** [comment]
Fixed in https://github.com/wso2/wso2-synapse/pull/973.
