### ISSUE TITLE
Data Service in Carbon Application

### ISSUE THREAD

**Issue by masoudk1990** [wso2/product-ei#1499]
**Description:**
When I create a Data Service it works fine in browser, but in Carbon Application it throws exception.

**Affected Product Version:**
wso2ei-6.1.1

**OS, DB, other environment details and versions:**    
Windows 10, Microsoft SQL Server, jdk1.8.0_144

**Steps to reproduce:**
Here is Data Service:
`<data name="DSTest" transports="http https local">
   <config enableOData="false" id="1">
      <property name="driverClassName">com.microsoft.sqlserver.jdbc.SQLServerDriver</property>
      <property name="url">jdbc:sqlserver://myAddress:1433;databaseName=myDB</property>
      <property name="username">sa</property>
      <property name="password">myPassword</property>
   </config>
   <query id="1" useConfig="1">
      <sql>select F_Id,F_ProvFarsi,F_Prov3Char from T_ProvCity where F_City3Char = ?</sql>
      <result element="myElement" rowName="myRow">
         <element column="F_Id" name="F_Id" xsdType="string"/>
         <element column="F_ProvFarsi" name="F_ProvFarsi" xsdType="string"/>
         <element column="F_Prov3Char" name="F_Prov3Char" xsdType="string"/>
      </result>
      <param name="param0" sqlType="QUERY_STRING"/>
   </query>
   <resource method="GET" path="/getProv">
      <call-query href="1">
         <with-param name="param0" query-param="param0"/>
      </call-query>
   </resource>
</data>`

Here is carbon Application:
`    <resource methods="POST" uri-template="/getprov">
        <inSequence>
            <property expression="json-eval($.city)" name="uri.var.propCity" scope="default" type="STRING"/>
            <log level="custom">
                <property expression="fn:concat('input city: ', get-property('uri.var.propCity'))" name="message"/>
            </log>
            <send>
                <endpoint>
                    <http method="get" uri-template="http://localhost:8280/services/DSTest/getProv?wsdl&amp;param0={uri.var.propCity}"/>
                </endpoint>
            </send>
        </inSequence>
        <outSequence>
            <send/>
        </outSequence>
        <faultSequence/>
    </resource>`

and here is error message:

> [2017-12-09 11:07:01,248] [EI-Core] ERROR - DBInOutMessageReceiver Error in in-out message receiver
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Nested Exception:-
javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:param0
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Source Data Service:-
Name: DSTest
Location: \DSTest.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: _get_getprov
Current Params: {}

	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:75)
	at org.wso2.carbon.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:357)
	at org.wso2.carbon.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:41)
	at org.wso2.carbon.dataservices.core.DBInOutMessageReceiver.invokeBusinessLogic(DBInOutMessageReceiver.java:57)
	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:42)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Related Issues:**

**Comment by madhawa-gunasekara** [comment]
Hi @masoudk1990, 

There is an issue with your esb resource. url is not correct please remove wsdl in the url
