### ISSUE TITLE
Cache mediator not working as expected with binary contents

### ISSUE THREAD

**Issue by VijithaEkanayake** [wso2/product-ei#1602]
**Description:**
When using cache mediator with binary content ESB throws a runtime exception with below stack trace when the cache is hit.

```
[2017-12-23 16:25:20,574] ERROR - PassThroughHttpSender Failed to submit the response
java.lang.RuntimeException: ContentID is null
	at org.apache.axiom.om.impl.llom.OMTextImpl.getDataHandler(OMTextImpl.java:370)
	at org.wso2.carbon.relay.ExpandingMessageFormatter.findAndWrite2OutputStream(ExpandingMessageFormatter.java:182)
	at org.wso2.carbon.relay.ExpandingMessageFormatter.writeTo(ExpandingMessageFormatter.java:100)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:552)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:267)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:212)
	at org.apache.synapse.mediators.builtin.RespondMediator.mediate(RespondMediator.java:28)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:81)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:48)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:149)
	at org.wso2.carbon.mediator.cache.CacheMediator.processRequestMessage(CacheMediator.java:380)
	at org.wso2.carbon.mediator.cache.CacheMediator.mediate(CacheMediator.java:211)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:81)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:48)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:149)
	at org.apache.synapse.rest.Resource.process(Resource.java:297)
	at org.apache.synapse.rest.API.process(API.java:378)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:97)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:65)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:266)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:83)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:317)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:149)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
ESB 4.9.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
 1). Create an API with below configs where backend service returns binary content.
 ```
<api xmlns="http://ws.apache.org/ns/synapse" name="TestAttachmentAPI" context="/attachmentAPI">
   <resource methods="GET" uri-template="*" protocol="http">
      <inSequence>
         <log>
            <property name="in" value="===== IN ====="/>
         </log>
         <cache scope="per-host" collector="false" hashGenerator="org.wso2.carbon.mediator.cache.digest.REQUESTHASHGenerator" timeout="960">
            <onCacheHit>
               <log>
                  <property name="cachehit" value="Cache is hit"/>
               </log>
               <respond/>
            </onCacheHit>
            <implementation type="memory" maxSize="20000"/>
         </cache>
         <send>
            <endpoint>
               <address uri="http://192.168.8.100:8000/conf.zip"/>
            </endpoint>
         </send>
      </inSequence>
      <outSequence>
         <log>
            <property name="out" value="=== OUT ===="/>
         </log>
         <cache scope="per-host" collector="true"/>
         <send/>
      </outSequence>
   </resource>
</api>
```

2). Invoke the API twice to see the mentioned exception.

**Related Issues:**

**Comment by VijithaEkanayake** [comment]
Fixed with https://github.com/wso2/carbon-mediation/commit/dbfb25b01c915319d034801709465ac8a6679140#diff-27b6b1e0d16b94fd7174706f75b33a7e
