### ISSUE TITLE
Error while deploying Message Processor Config in an EI Cluster

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#1607]
**Description:**
Error while sending cluster messages when scheduling a message processor in clustered mode

**Affected Product Version:**
WSO2 EI 6.1.1 Update - <>

**OS, DB, other environment details and versions:**   
Mac OS with ActiveMQ broker 5.1.3.3 

**Steps to reproduce:**
1. Create a EI cluster of 2 nodes
2. Deploy a CAR file with a message processor to EI node 1
3. You will see following stack trace

```
[2018-01-02 16:07:31,918] [EI-Core] ERROR - NTaskTaskManager Scheduling task [[NTask::-1234::MSMP_MBMessageProcessor0]::synapse.message.processor.quartz] FAILED. Error: Error in cluster message send-receive: org.wso2.carbon.ntask.common.TaskException: The task 'MSMP_MBMessageProcessor0' does not exist
org.wso2.carbon.ntask.common.TaskException: Error in cluster message send-receive: org.wso2.carbon.ntask.common.TaskException: The task 'MSMP_MBMessageProcessor0' does not exist
	at org.wso2.carbon.ntask.core.impl.clustered.ClusterGroupCommunicator.sendReceive(ClusterGroupCommunicator.java:208)
	at org.wso2.carbon.ntask.core.impl.clustered.ClusteredTaskManager.sendReceive(ClusteredTaskManager.java:263)
	at org.wso2.carbon.ntask.core.impl.clustered.ClusteredTaskManager.scheduleTask(ClusteredTaskManager.java:309)
	at org.wso2.carbon.ntask.core.impl.clustered.ClusteredTaskManager.scheduleTask(ClusteredTaskManager.java:93)
	at org.wso2.carbon.mediation.ntask.NTaskTaskManager.schedule(NTaskTaskManager.java:106)
	at org.apache.synapse.message.processor.impl.ScheduledMessageProcessor.start(ScheduledMessageProcessor.java:186)
	at org.apache.synapse.message.processor.impl.ScheduledMessageProcessor.init(ScheduledMessageProcessor.java:122)
	at org.apache.synapse.message.processor.impl.forwarder.ScheduledMessageForwardingProcessor.init(ScheduledMessageForwardingProcessor.java:52)
	at org.apache.synapse.deployers.MessageProcessorDeployer.deploySynapseArtifact(MessageProcessorDeployer.java:58)
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:194)
	at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifacts(SynapseAppDeployer.java:131)
	at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:272)
	at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:72)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: org.wso2.carbon.ntask.common.TaskException: The task 'MSMP_MBMessageProcessor0' does not exist
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:204)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: org.wso2.carbon.ntask.common.TaskException: The task 'MSMP_MBMessageProcessor0' does not exist
	at org.wso2.carbon.ntask.core.impl.RegistryBasedTaskRepository.getTask(RegistryBasedTaskRepository.java:148)
	at org.wso2.carbon.ntask.core.impl.AbstractQuartzTaskManager.scheduleLocalTask(AbstractQuartzTaskManager.java:193)
	at org.wso2.carbon.ntask.core.impl.AbstractQuartzTaskManager.scheduleLocalTask(AbstractQuartzTaskManager.java:188)
	at org.wso2.carbon.ntask.core.impl.clustered.ClusteredTaskManager.finalScheduleTask(ClusteredTaskManager.java:313)
	at org.wso2.carbon.ntask.core.impl.clustered.rpc.ScheduleTaskCall.doWork(ScheduleTaskCall.java:39)
	at org.wso2.carbon.ntask.core.impl.clustered.rpc.ScheduleTaskCall.doWork(ScheduleTaskCall.java:23)
	at org.wso2.carbon.ntask.core.impl.clustered.rpc.TaskCall.call(TaskCall.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:202)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:384)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:334)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:225)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:71)
	at com.hazelcast.util.executor.DelegatingFuture.get(DelegatingFuture.java:56)
	at org.wso2.carbon.ntask.core.impl.clustered.ClusterGroupCommunicator.sendReceive(ClusterGroupCommunicator.java:206)
	at org.wso2.carbon.ntask.core.impl.clustered.ClusteredTaskManager.sendReceive(ClusteredTaskManager.java:263)
	at org.wso2.carbon.ntask.core.impl.clustered.ClusteredTaskManager.scheduleTask(ClusteredTaskManager.java:309)
	at org.wso2.carbon.ntask.core.impl.clustered.ClusteredTaskManager.scheduleTask(ClusteredTaskManager.java:93)
	at org.wso2.carbon.mediation.ntask.NTaskTaskManager.schedule(NTaskTaskManager.java:106)
	at org.apache.synapse.message.processor.impl.ScheduledMessageProcessor.start(ScheduledMessageProcessor.java:186)
	at org.apache.synapse.message.processor.impl.ScheduledMessageProcessor.init(ScheduledMessageProcessor.java:122)
	at org.apache.synapse.message.processor.impl.forwarder.ScheduledMessageForwardingProcessor.init(ScheduledMessageForwardingProcessor.java:52)
	at org.apache.synapse.deployers.MessageProcessorDeployer.deploySynapseArtifact(MessageProcessorDeployer.java:58)
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:194)
	at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifacts(SynapseAppDeployer.java:131)
	at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:272)
	at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:72)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2018-01-02 16:07:31,925] [EI-Core]  INFO - ScheduledMessageProcessor Started message processor. [MBMessageProcessor].
```

**Related Issues:**
N/A

**Comment by sdkottegoda** [comment]
This happenes when the registry is not mounted correctly. To be specific, if the governance registry is not shared among the nodes in the cluster.
