### ISSUE TITLE
Exception thrown continuously when subscription connection is abruptly removed

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/product-ei#1613]
**Description:**
Following error gets logged endlessly when a subscription connection is suddenly removed while there are other subscriptions for the same queue.
TID: [-1] [] [2017-12-18 07:20:31,604] ERROR {org.wso2.andes.kernel.disruptor.LogExceptionHandler} -  [ Sequence: 1468537 ] Exception occurred while processing inbound events.Event type: SAFE_ZONE_DECLARE_EVENT {org.wso2.andes.kernel.disruptor.LogExceptionHandler}
java.lang.NullPointerException
	at org.wso2.andes.kernel.AndesAckEvent.addTraceLog(AndesAckEvent.java:134)
	at org.wso2.andes.kernel.AndesAckEvent.setMetadataReference(AndesAckEvent.java:80)
	at org.wso2.andes.kernel.disruptor.inbound.AckHandler.ackReceived(AckHandler.java:109)
	at org.wso2.andes.kernel.disruptor.inbound.AckHandler.processAcknowledgements(AckHandler.java:91)
	at org.wso2.andes.kernel.disruptor.inbound.AckEventBatchHandler.onEvent(AckEventBatchHandler.java:99)
	at org.wso2.andes.kernel.disruptor.inbound.AckEventBatchHandler.onEvent(AckEventBatchHandler.java:32)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Steps to reproduce:**
1. Add 2 subscriptions to the broker for the same queue.
2. Publish some number of messages to the queue.
3. Mock a scenario where the subscription is closed while a message is being written to the subscription.
4. Observe the continuous NullPointerException.

**Comment by wggihan** [comment]
This issue is fixed now and available from 6.1.1-update-16
