### ISSUE TITLE
Fault sequence not executed when malformed payload causes RelayUtils build failure

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/product-ei#1662]
**Description:**
A Runtime exception is thrown and the message flow get interrupted when a malformed payload is sent from the back end.
java.lang.RuntimeException: org.apache.synapse.SynapseException: Error while building message
	at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:108)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:565)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:194)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:260)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.synapse.SynapseException: Error while building message
	at org.apache.synapse.mediators.AbstractMediator.handleException(AbstractMediator.java:367)
	at org.apache.synapse.mediators.AbstractListMediator.buildMessage(AbstractListMediator.java:142)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:83)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.mediators.MediatorFaultHandler.onFault(MediatorFaultHandler.java:93)
	at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:101)
	... 8 more

**Affected Product Version:**
WSO2ESB-5.0.0

**Steps to reproduce:**
1. Create and API with the following configuration
```xml
<resource methods="GET">
      <inSequence>
         <call>
            <endpoint>
               <address uri="http://www.mocky.io/v2/5a51ccf82e0000b116c03a22"/>
            </endpoint>
         </call>
         <log level="full"/>
         <respond/>
      </inSequence>
      <faultSequence>
         <log level="full">
            <property name="something" value="faultSeq"/>
         </log>
         <send/>
      </faultSequence>
   </resource>
```
2. Set the content type of the back-end to text-html and the response to a malformed payload.
e.g. ```<a>something</b>```
3. Invoke the API and observe the stack trace.

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-4799

**Comment by milindaperera** [comment]
Fixed in https://github.com/wso2/wso2-synapse/commit/bf638703b38cf3260ff94311b728bce45c2a9026

**Comment by himasha** [comment]
Closing issue since the fix is merged.
