### ISSUE TITLE
[EI] When clicking the Generate Axis2 Client link, backend gives an error

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#170]
**Enviornment**
JAVA- jdk 1.7.0_51
OS-ubuntu 14.10
Browser-Firefox 47.0
            -Chrome 51.02
EI alpha pack

**Steps**

1. Start the integrator server and access the echo service under services list
2. Click on the **Generate Axis2 Client**  link

**Error**

1. Frontend couldn't load axis2client related window
2. Backend throws the following error

`[2017-02-14 10:11:43,056] [EI-Core] ERROR - AxisEngine The endpoint reference (EPR) for the Operation not found is /carbon/wsdl2code/index.jsp?generateClient=http://chalitha-Latitude-E6540:8280/services/echo?wsdl&toppage=false&endpoints=echoHttpEndpoint,echoHttpsSoap12Endpoint,echoHttpSoap12Endpoint,echoHttpsSoap11Endpoint,echoHttpsEndpoint,echoHttpSoap11Endpoint and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.
org.apache.axis2.AxisFault: The endpoint reference (EPR) for the Operation not found is /carbon/wsdl2code/index.jsp?generateClient=http://chalitha-Latitude-E6540:8280/services/echo?wsdl&toppage=false&endpoints=echoHttpEndpoint,echoHttpsSoap12Endpoint,echoHttpSoap12Endpoint,echoHttpsSoap11Endpoint,echoHttpsEndpoint,echoHttpSoap11Endpoint and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.
	at org.apache.axis2.engine.DispatchPhase.checkPostConditions(DispatchPhase.java:102)
	at org.apache.axis2.engine.Phase.invoke(Phase.java:329)
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:325)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
[2017-02-14 10:11:43,057] [EI-Core] ERROR - ServerWorker Error processing GET request for : /carbon/wsdl2code/index.jsp?generateClient=http://chalitha-Latitude-E6540:8280/services/echo?wsdl&toppage=false&endpoints=echoHttpEndpoint,echoHttpsSoap12Endpoint,echoHttpSoap12Endpoint,echoHttpsSoap11Endpoint,echoHttpsEndpoint,echoHttpSoap11Endpoint
org.apache.axis2.AxisFault: The endpoint reference (EPR) for the Operation not found is /carbon/wsdl2code/index.jsp?generateClient=http://chalitha-Latitude-E6540:8280/services/echo?wsdl&toppage=false&endpoints=echoHttpEndpoint,echoHttpsSoap12Endpoint,echoHttpSoap12Endpoint,echoHttpsSoap11Endpoint,echoHttpsEndpoint,echoHttpSoap11Endpoint and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.
	at org.apache.axis2.engine.DispatchPhase.checkPostConditions(DispatchPhase.java:102)
	at org.apache.axis2.engine.Phase.invoke(Phase.java:329)
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:325)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

`

**Comment by madhawa-gunasekara** [comment]
Fixed with https://github.com/wso2/product-ei/pull/172
