### ISSUE TITLE
Unable to use WSDL endpoint with Basic auth, with a username having special characters

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#1764]
**Description:**
Issues observed while fetching the relevant WSDL when using the WSDL endpoint 
Since the username has special characters they should be URL encoded in the WSDL URL.
e.g. https://user%40foo.com:password@abc.com
But it is not URL decoded before Base64 encoding.
And gves following error:
Caused by: java.lang.IllegalArgumentException: Illegal character(s) in message header value: Basic xxxxxxxxxxxxxxxxxxxx
at sun.net.www.protocol.http.HttpURLConnection.checkMessageHeader(HttpURLConnection.java:482)
at sun.net.www.protocol.http.HttpURLConnection.isExternalMessageHeaderAllowed(HttpURLConnection.java:434)
at sun.net.www.protocol.http.HttpURLConnection.setRequestProperty(HttpURLConnection.java:2753)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.setRequestProperty(HttpsURLConnectionImpl.java:316)
at org.apache.synapse.config.SynapseConfigUtils.getOMElementFromURL(SynapseConfigUtils.java:297)

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-4368
https://github.com/wso2/product-ei/issues/1605

**Comment by malakaganga** [comment]
Related to : https://github.com/wso2/product-ei/issues/1605
