### ISSUE TITLE
File inbound endpoint MoveAfterProcess and MoveAfterFailure on windows gives error

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-ei#1783]
**Description:**
When using File inbound endpoint errors given for move after process and move after failure actions. This occurs only on windows. Please find the error below.

`TID: [-1] [] [2016-03-30 22:41:30,800] ERROR {org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer} -  Error moving file : file:///D:/in/appxml.xml to D:\processed {org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer}^M
org.apache.commons.vfs2.FileSystemException: Could not rename "file:///D:/in/appxml.xml" to "file:///D:/processed/appxml.xml".^M
    at org.apache.commons.vfs2.provider.AbstractFileObject.moveTo(AbstractFileObject.java:1117)^M
    at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.moveOrDeleteAfterProcessing(FilePollingConsumer.java:846)^M
    at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.directoryHandler(FilePollingConsumer.java:572)^M
    at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.poll(FilePollingConsumer.java:214)^M
    at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.execute(FilePollingConsumer.java:134)^M
    at org.wso2.carbon.inbound.endpoint.protocol.file.FileTask.taskExecute(FileTask.java:47)^M
    at org.wso2.carbon.inbound.endpoint.common.InboundRunner.run(InboundRunner.java:111)^M
    at java.lang.Thread.run(Thread.java:745)^M
Caused by: org.apache.commons.vfs2.FileSystemException: Could not rename file "D:\in\appxml.xml" to "file:///D:/processed/appxml.xml".^M
    at org.apache.commons.vfs2.provider.local.LocalFile.doRename(LocalFile.java:141)^M
    at org.apache.commons.vfs2.provider.AbstractFileObject.moveTo(AbstractFileObject.java:1103)^M
    ... 7 more^M`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by himasha** [comment]
This could happen due to permission issues where the user does not have append/write permission  to the locations, since in [1] a file is first created and then the content is written.

[1] https://github.com/wso2/wso2-synapse/blob/master/modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java#L292
