### ISSUE TITLE
Error thrown when using analytics

### ISSUE THREAD

**Issue by gilliandass** [wso2/product-ei#179]
Configure analytics in EI. Start the analytics runtime. Start EI server. When accessing the management console the following error is thrown:

[2017-02-14 16:24:57,181] [EI-Core] ERROR - MessageFlowReporterThread Error in mediation flow statistic data consumer while consuming data
java.lang.NullPointerException
	at org.wso2.carbon.das.messageflow.data.publisher.services.MessageFlowReporterThread.processAndPublishEventList(MessageFlowReporterThread.java:143)
	at org.wso2.carbon.das.messageflow.data.publisher.services.MessageFlowReporterThread.run(MessageFlowReporterThread.java:95)

**Comment by mpmunasinghe** [comment]
Fixed with https://github.com/wso2/carbon-mediation/commit/2563366f4a5da97b5bacb1671d185afc30eca8d1
