### ISSUE TITLE
Cannot run EI7 sample JMS Synchronous Invocations - Dual Channel using MB4

### ISSUE THREAD

**Issue by Asitha** [wso2/product-ei#1795]
**Description:**
When trying to run the sample https://github.com/wso2/product-ei/tree/7.0.x/samples/jms-synchronous-invocation using MB getting the following exception in MB on the first invocation of the sample:
```
ERROR {org.wso2.broker.amqp.codec.frames.QueueBind} -  Error while binding to amq.direct with queue ResponseQueue with routing key ResponseQueue 
org.wso2.broker.core.BrokerException: Error occurred while storing binding Binding{queue=Queue{name='ResponseQueue', durable=true, autoDelete=false}, routingKey='ResponseQueue'}
	at org.wso2.broker.core.store.dao.impl.BindingDaoImpl.persist(BindingDaoImpl.java:64)
	at org.wso2.broker.core.BindingsRegistry.bind(BindingsRegistry.java:52)
	at org.wso2.broker.core.Exchange.bind(Exchange.java:91)
	at org.wso2.broker.core.MessagingEngine.bind(MessagingEngine.java:128)
	at org.wso2.broker.core.Broker.bind(Broker.java:114)
	at org.wso2.broker.amqp.codec.AmqpChannel.bind(AmqpChannel.java:126)
	at org.wso2.broker.amqp.codec.frames.QueueBind.lambda$handle$0(QueueBind.java:86)
	at org.wso2.broker.amqp.codec.handlers.BlockingTaskHandler.channelRead(BlockingTaskHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL180118063918810' defined on 'MB_BINDING'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.wso2.broker.core.store.dao.impl.BindingDaoImpl.persist(BindingDaoImpl.java:61)
	... 14 more
Caused by: ERROR 23505: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL180118063918810' defined on 'MB_BINDING'.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.IndexChanger.insertAndCheckDups(Unknown Source)
	at org.apache.derby.impl.sql.execute.IndexChanger.doInsert(Unknown Source)
	at org.apache.derby.impl.sql.execute.IndexChanger.insert(Unknown Source)
	at org.apache.derby.impl.sql.execute.IndexSetChanger.insert(Unknown Source)
	at org.apache.derby.impl.sql.execute.RowChangerImpl.insertRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 21 more
```

The wireshark dump for the issue is here: 
[wireshar.dump.zip](https://github.com/wso2/message-broker/files/1642260/wireshar.dump.zip)

**Affected Product Version:**
MB 4, EI 7

**Comment by Asitha** [comment]
MB4 Doesn't support selectors for queues. Need to use topic based solution on a temporary queues based solution for this.
