### ISSUE TITLE
Server fails to start when a subscription registry resource is not available 

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#1830]
**Description:**
When a subscription registry resource is not available at the pack, ESB server fails to start since it was unable to resolve all the required OSGI components. Further noticed, even if we miss only one resource (there are some subscription resources available) it fails to initialize the EventBroker at https://github.com/wso2/carbon-commons/blob/master/components/event/org.wso2.carbon.event.core/src/main/java/org/wso2/carbon/event/core/internal/builder/EventBrokerHandler.java#L58 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
ESB 4.9.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Start ESB 4.9.0
2. Create a topic called true from the left menu
3. Browse the topic and create a subscription for that topic
4. Browse the path /_system/governance/event/topics/true/ws.subscriptions/ and delete the registry resource existing this path.
5. Restart the server. We get the following error and the server is not starting properly.

org.wso2.carbon.event.core.exception.EventBrokerConfigurationException: Cannot get the subscriptions 
	at org.wso2.carbon.event.core.internal.CarbonEventBroker.loadExistingSubscriptions(CarbonEventBroker.java:94)
	at org.wso2.carbon.event.core.internal.CarbonEventBroker.init(CarbonEventBroker.java:68)
	at org.wso2.carbon.event.core.internal.CarbonEventBrokerFactory.getEventBroker........

**Related Issues:**

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/carbon-commons/pull/294/commits/afc5b069e3d24ac9c5d0d706a9dc7295cc62dba8
