### ISSUE TITLE
[Windows][Analatics] Backend throws an error when trying to access the Analatics server

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#185]
**Environment**
JDK-1.8.0_21
OS- windows 2012 rc1
Firefox 47.0

**Steps**
**Start the EI alpha pack with start_all script.
Access the management console** following error could be seen the backend

**Error**
`[2017-02-14 22:26:00,203] [EI-Analytics] ERROR {org.wso2.carbon.analytics.spark.
core.CarbonAnalyticsProcessorService} -  Error while executing query :         C
REATE TEMPORARY TABLE esbServiceStatPerMinute USING CarbonAnalytics        OPTIO
NS (tableName "org_wso2_esb_analytics_stream_StatPerMinute",        schema "year
 INT -i, month INT -i, day INT -i, hour INT -i, minute INT -i, componentId FACET
 -i,        componentName FACET -i, componentType FACET -i, totalDuration LONG,
minDuration LONG,        maxDuration LONG, noOfInvocation LONG -sp, faultCount L
ONG, startTime LONG -i, facetStartTime FACET -i,        entryPoint FACET -i, met
a_tenantId INT -i, _timestamp LONG -i",        primaryKeys "meta_tenantId, year,
 month, day, hour, minute, componentId, componentType, componentName",        in
crementalParams "esbServiceStatPerMinute, HOUR",        mergeSchema "false")
org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Exce
ption in executing query CREATE TEMPORARY TABLE esbServiceStatPerMinute USING Ca
rbonAnalytics        OPTIONS (tableName "org_wso2_esb_analytics_stream_StatPerMi
nute",        schema "year INT -i, month INT -i, day INT -i, hour INT -i, minute
 INT -i, componentId FACET -i,        componentName FACET -i, componentType FACE
T -i, totalDuration LONG, minDuration LONG,        maxDuration LONG, noOfInvocat
ion LONG -sp, faultCount LONG, startTime LONG -i, facetStartTime FACET -i,
  entryPoint FACET -i, meta_tenantId INT -i, _timestamp LONG -i",        primary
Keys "meta_tenantId, year, month, day, hour, minute, componentId, componentType,
 componentName",        incrementalParams "esbServiceStatPerMinute, HOUR",
  mergeSchema "false")
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.
executeQueryLocal(SparkAnalyticsExecutor.java:772)
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.
executeQuery(SparkAnalyticsExecutor.java:729)
        at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.
executeQuery(CarbonAnalyticsProcessorService.java:201)
        at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.
executeScript(CarbonAnalyticsProcessorService.java:151)
        at org.wso2.carbon.analytics.spark.core.AnalyticsTask.execute(AnalyticsT
ask.java:60)
        at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuar
tzJobAdapter.java:67)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionExce
ption: Spark SQL Context is not available. Check if the cluster has instantiated
 properly.
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.
executeQueryLocal(SparkAnalyticsExecutor.java:763)
        ... 11 more
[2017-02-14 22:26:00,266] [EI-Analytics] ERROR {org.wso2.carbon.analytics.spark.
core.AnalyticsTask} -  Error while executing the scheduled task for the script:
EsbAnalytics-SparkScript-Realtime-Statistic
org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Exce
ption in executing query CREATE TEMPORARY TABLE esbServiceStatPerMinute USING Ca
rbonAnalytics        OPTIONS (tableName "org_wso2_esb_analytics_stream_StatPerMi
nute",        schema "year INT -i, month INT -i, day INT -i, hour INT -i, minute
 INT -i, componentId FACET -i,        componentName FACET -i, componentType FACE
T -i, totalDuration LONG, minDuration LONG,        maxDuration LONG, noOfInvocat
ion LONG -sp, faultCount LONG, startTime LONG -i, facetStartTime FACET -i,
  entryPoint FACET -i, meta_tenantId INT -i, _timestamp LONG -i",        primary
Keys "meta_tenantId, year, month, day, hour, minute, componentId, componentType,
 componentName",        incrementalParams "esbServiceStatPerMinute, HOUR",
  mergeSchema "false")
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.
executeQueryLocal(SparkAnalyticsExecutor.java:772)
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.
executeQuery(SparkAnalyticsExecutor.java:729)
        at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.
executeQuery(CarbonAnalyticsProcessorService.java:201)
        at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.
executeScript(CarbonAnalyticsProcessorService.java:151)
        at org.wso2.carbon.analytics.spark.core.AnalyticsTask.execute(AnalyticsT
ask.java:60)
        at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuar
tzJobAdapter.java:67)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionExce
ption: Spark SQL Context is not available. Check if the cluster has instantiated
 properly.
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.
executeQueryLocal(SparkAnalyticsExecutor.java:763)
        ... 11 more
[2017-02-14 22:28:00,028] [EI-Analytics] ERROR {org.wso2.carbon.analytics.spark.
core.CarbonAnalyticsProcessorService} -  Error while executing query :         C
REATE TEMPORARY TABLE esbServiceStatPerMinute USING CarbonAnalytics        OPTIO
NS (tableName "org_wso2_esb_analytics_stream_StatPerMinute",        schema "year
 INT -i, month INT -i, day INT -i, hour INT -i, minute INT -i, componentId FACET
 -i,        componentName FACET -i, componentType FACET -i, totalDuration LONG,
minDuration LONG,        maxDuration LONG, noOfInvocation LONG -sp, faultCount L
ONG, startTime LONG -i, facetStartTime FACET -i,        entryPoint FACET -i, met
a_tenantId INT -i, _timestamp LONG -i",        primaryKeys "meta_tenantId, year,
 month, day, hour, minute, componentId, componentType, componentName",        in
crementalParams "esbServiceStatPerMinute, HOUR",        mergeSchema "false")
org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Exce
ption in executing query CREATE TEMPORARY TABLE esbServiceStatPerMinute USING Ca
rbonAnalytics        OPTIONS (tableName "org_wso2_esb_analytics_stream_StatPerMi
nute",        schema "year INT -i, month INT -i, day INT -i, hour INT -i, minute
 INT -i, componentId FACET -i,        componentName FACET -i, componentType FACE
T -i, totalDuration LONG, minDuration LONG,        maxDuration LONG, noOfInvocat
ion LONG -sp, faultCount LONG, startTime LONG -i, facetStartTime FACET -i,
  entryPoint FACET -i, meta_tenantId INT -i, _timestamp LONG -i",        primary
Keys "meta_tenantId, year, month, day, hour, minute, componentId, componentType,
 componentName",        incrementalParams "esbServiceStatPerMinute, HOUR",
  mergeSchema "false")
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.
executeQueryLocal(SparkAnalyticsExecutor.java:772)
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.
executeQuery(SparkAnalyticsExecutor.java:729)
        at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.
executeQuery(CarbonAnalyticsProcessorService.java:201)
        at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.
executeScript(CarbonAnalyticsProcessorService.java:151)
        at org.wso2.carbon.analytics.spark.core.AnalyticsTask.execute(AnalyticsT
ask.java:60)
        at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuar
tzJobAdapter.java:67)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionExce
ption: Spark SQL Context is not available. Check if the cluster has instantiated
 properly.
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.
executeQueryLocal(SparkAnalyticsExecutor.java:763)
        ... 11 more
[2017-02-14 22:28:00,028] [EI-Analytics] ERROR {org.wso2.carbon.analytics.spark.
core.AnalyticsTask} -  Error while executing the scheduled task for the script:
EsbAnalytics-SparkScript-Realtime-Statistic
org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Exce
ption in executing query CREATE TEMPORARY TABLE esbServiceStatPerMinute USING Ca
rbonAnalytics        OPTIONS (tableName "org_wso2_esb_analytics_stream_StatPerMi
nute",        schema "year INT -i, month INT -i, day INT -i, hour INT -i, minute
 INT -i, componentId FACET -i,        componentName FACET -i, componentType FACE
T -i, totalDuration LONG, minDuration LONG,        maxDuration LONG, noOfInvocat
ion LONG -sp, faultCount LONG, startTime LONG -i, facetStartTime FACET -i,
  entryPoint FACET -i, meta_tenantId INT -i, _timestamp LONG -i",        primary
Keys "meta_tenantId, year, month, day, hour, minute, componentId, componentType,
 componentName",        incrementalParams "esbServiceStatPerMinute, HOUR",
  mergeSchema "false")
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.
executeQueryLocal(SparkAnalyticsExecutor.java:772)
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.
executeQuery(SparkAnalyticsExecutor.java:729)
        at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.
executeQuery(CarbonAnalyticsProcessorService.java:201)
        at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.
executeScript(CarbonAnalyticsProcessorService.java:151)
        at org.wso2.carbon.analytics.spark.core.AnalyticsTask.execute(AnalyticsT
ask.java:60)
        at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuar
tzJobAdapter.java:67)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionExce
ption: Spark SQL Context is not available. Check if the cluster has instantiated
 properly.
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.
executeQueryLocal(SparkAnalyticsExecutor.java:763)
        ... 11 more
`

**Comment by chalitha87** [comment]
Verified 15th of Feb pack. Issue no longer reproducible.
