### ISSUE TITLE
Analytics-backup script with -deleteTables not work on Windows

### ISSUE THREAD

**Issue by marcses** [wso2/product-ei#1851]
**Description:**
Referring to [documentation](https://docs.wso2.com/display/DAS3xx/Backing+Up+or+Restoring+Analytics+Data) , the script analytics-backup.bat with option -deleteTables search in wrong config dir path **..\repository\conf**\analytics\analytics-config.xml instead of **..\conf**\analytics\analytics-config.xml

`JAVA_HOME environment variable is set to C:\Program Files\Java\jdk1.8.0_112
CARBON_HOME environment variable is set to C:\WSO2EI~2.0\wso2\ANALYT~1\bin\..
Exception in thread "main" java.lang.RuntimeException: Error in creating analytics data service impl.: Cannot initalize analytics data service, the analytics da
ta service configuration file cannot be found at: C:\WSO2EI~2.0\wso2\ANALYT~1\bin\..\repository\conf\analytics\analytics-config.xml
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsServiceHolder.checkAndPopulateCustomAnalyticsDS(AnalyticsServiceHolder.java:89)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsServiceHolder.getAnalyticsDataService(AnalyticsServiceHolder.java:74)
        at org.wso2.carbon.analytics.tools.backup.AnalyticsDataBackupTool.main(AnalyticsDataBackupTool.java:128)
Caused by: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsException: Cannot initalize analytics data service, the analytics data service config
uration file cannot be found at: C:\WSO2EI~2.0\wso2\ANALYT~1\bin\..\repository\conf\analytics\analytics-config.xml
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.loadAnalyticsDataServiceConfig(AnalyticsDataServiceImpl.java:332)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.<init>(AnalyticsDataServiceImpl.java:133)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsServiceHolder.checkAndPopulateCustomAnalyticsDS(AnalyticsServiceHolder.java:87)
        ... 2 more
C:\wso2ei-6.1.0\wso2\analytics\bin>
`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 6.1.0 - Analytics

**OS, DB, other environment details and versions:**    
Windows Seven pro, Java(TM) SE Runtime Environment 1.8.0_131, Oracle 11g EE
**Steps to reproduce:**
execute: EI_HOME\wso2\analytics\binanalytics-backup.bat -deleteTables -tables "MyTableToDelete" -tenantId -1234

**Related Issues:**

**Comment by marcses** [comment]
I have resolved adding the following parameters in the script analytics-backup.bat

In the section :runServer
- set CARBON_CONFIG_DIR_PATH=%CARBON_HOME%\conf

In the section :updateClasspath
- set CARBON_CLASSPATH="%CARBON_HOME%\..\lib\*";%CARBON_CLASSPATH%;
- set CARBON_CLASSPATH="%CARBON_HOME%\..\..\lib\*";%CARBON_CLASSPATH%;
