### ISSUE TITLE
Executing the identity-anonymization-tool with default configs results in table not found error

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1910]
**Description:**
Executing the default "./forget-me.sh" resulted in sql execution issue due to a missing table. If a user, who uses the Integrator profile, should be able to execute the anonymization script to remove the information that is not required to maintain in the logs.

Therefore the default configuration defined in the config.json should be possible to execute with out any issue.

**Affected Product Version:**
EI 6.1.1 update 23

**OS, DB, other environment details and versions:**    
DB - Mysql
OS - Ubuntu 15.10
DB - H2

**Steps to reproduce:**
1. Configure EI server to use integrator profile
2. Run the './forget-me.sh' from <EI_HOME>/bin location

Observations
Script executed and the following error message appeared.

```
sashika@sashika:~/.wum-wso2/products/wso2esb/EI/wso2ei-6.1.1-update23/bin$ ./forget-me.sh -U peter
2018-03-06 14:46:57 INFO  ForgetMeTool:167 - Generating pseudonym as pseudo name is not provided : a490d656-0a68-4189-a92f-bbb39996f0d4
2018-03-06 14:46:57 INFO  HikariDataSource:72 - HikariPool-0 - is starting.
2018-03-06 14:46:57 INFO  ForgetMeExecutionEngine:219 - Processor execution completed. Processor : log-file
2018-03-06 14:46:57 ERROR ForgetMeExecutionEngine:112 - Interrupted while executing the processor thread : java.util.concurrent.FutureTask@433d61fb
java.util.concurrent.ExecutionException: org.wso2.carbon.privacy.forgetme.api.runtime.InstructionExecutionException: Error occurred while executing sql from : /home/sashika/.wum-wso2/products/wso2esb/EI/wso2ei-6.1.1-update23/wso2/tools/identity-anonymization-tool/conf/sql/bpmn
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.waitForCompletion(ForgetMeExecutionEngine.java:109)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.execute(ForgetMeExecutionEngine.java:91)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:188)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:128)
Caused by: org.wso2.carbon.privacy.forgetme.api.runtime.InstructionExecutionException: Error occurred while executing sql from : /home/sashika/.wum-wso2/products/wso2esb/EI/wso2ei-6.1.1-update23/wso2/tools/identity-anonymization-tool/conf/sql/bpmn
	at org.wso2.carbon.privacy.forgetme.sql.instructions.RdbmsForgetMeInstruction.execute(RdbmsForgetMeInstruction.java:111)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:217)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:188)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.privacy.forgetme.sql.exception.SQLModuleException: org.h2.jdbc.JdbcSQLException: Table "ACT_HI_ATTACHMENT" not found; SQL statement:
UPDATE ACT_HI_ATTACHMENT
SET USER_ID_ =  ? 
WHERE USER_ID_ =  ? 
 [42102-140]
	at org.wso2.carbon.privacy.forgetme.sql.module.DomainSeparatedSQLExecutionModule.execute(DomainSeparatedSQLExecutionModule.java:96)
	at org.wso2.carbon.privacy.forgetme.sql.module.DomainSeparatedSQLExecutionModule.execute(DomainSeparatedSQLExecutionModule.java:36)
	at org.wso2.carbon.privacy.forgetme.sql.instructions.RdbmsForgetMeInstruction.execute(RdbmsForgetMeInstruction.java:107)
	... 6 more
Caused by: org.h2.jdbc.JdbcSQLException: Table "ACT_HI_ATTACHMENT" not found; SQL statement:
UPDATE ACT_HI_ATTACHMENT
SET USER_ID_ =  ? 
WHERE USER_ID_ =  ? 
 [42102-140]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.Parser.readTableOrView(Parser.java:4498)
	at org.h2.command.Parser.readTableOrView(Parser.java:4478)
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:683)
	at org.h2.command.Parser.parseUpdate(Parser.java:641)
	at org.h2.command.Parser.parsePrepared(Parser.java:414)
	at org.h2.command.Parser.parse(Parser.java:275)
	at org.h2.command.Parser.parse(Parser.java:247)
	at org.h2.command.Parser.prepare(Parser.java:201)
	at org.h2.command.Parser.prepareCommand(Parser.java:214)
	at org.h2.engine.Session.prepareLocal(Session.java:434)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1071)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:234)
	at com.zaxxer.hikari.proxy.ConnectionProxy.prepareStatement(ConnectionProxy.java:265)
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.prepareStatement(HikariConnectionProxy.java)
	at org.wso2.carbon.privacy.forgetme.sql.util.NamedPreparedStatement.<init>(NamedPreparedStatement.java:72)
	at org.wso2.carbon.privacy.forgetme.sql.util.NamedPreparedStatement.<init>(NamedPreparedStatement.java:83)
	at org.wso2.carbon.privacy.forgetme.sql.module.DomainSeparatedSQLExecutionModule.execute(DomainSeparatedSQLExecutionModule.java:71)
	... 8 more
2018-03-06 14:46:57 INFO  ForgetMeExecutionEngine:115 - All processors have been properly shut-down

```

**Expected Results**
The default configuration should support to execute the tool to anonymize the user PII information. According to the current config.json file it is configured to execute the sql file that contains the PII identification anonymization process for business-process server as well.

Issue can be resolved if we configure the config.json without "sql" dir.

**Comment by milanperera** [comment]
This is fixed in [1].

[1] https://github.com/wso2/identity-anonymization-tool/pull/63
