### ISSUE TITLE
[Migration ESB500 to EI 600] Unable to log in to tenant domain after the migration

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#194]
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
EI M1 Jenkins Build (15/02/2017)
DB - mysql 5.6.31

**Steps**
1. Tenant domain is created in the ESB500 pack and few service available
2. Migrate the ESB500 pack to EI600 pack with artifacts
3. Log in to the tenant domain 

**Observation**
1. Unable to log into the tenant domain 
2. Following exception observed in the terminal

[2017-02-16 11:11:54,284] [EI-Core]  WARN - SourceHandler Connection time out after request is read: http-incoming-3 Socket Timeout : 180000 Remote Address : 10.100.11.26/10.100.11.26:33122
[2017-02-16 11:14:01,410] [EI-Core]  INFO - SourceHandler Writer null when calling informWriterError
[2017-02-16 11:14:01,410] [EI-Core]  WARN - SourceHandler Connection time out after request is read: http-incoming-31 Socket Timeout : 180000 Remote Address : as.wso2.org/127.0.0.1:50560
[2017-02-16 11:14:01,452] [EI-Core] ERROR - RelayUtils Error while building Passthrough stream
org.apache.axiom.om.OMException: javax.xml.stream.XMLStreamException: DOCTYPE is not allowed
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
	at org.apache.axiom.om.impl.llom.OMDocumentImpl.getOMDocumentElement(OMDocumentImpl.java:109)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:570)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:566)
	at org.apache.synapse.transport.passthru.util.DeferredMessageBuilder.getDocument(DeferredMessageBuilder.java:160)
	at org.apache.synapse.transport.passthru.util.RelayUtils.builldMessage(RelayUtils.java:136)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:99)
	at org.apache.synapse.mediators.AbstractListMediator.buildMessage(AbstractListMediator.java:140)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:83)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:314)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:554)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:188)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processResponse(MultitenantMessageReceiver.java:170)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:82)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:262)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: DOCTYPE is not allowed
	at org.apache.axiom.util.stax.dialect.DisallowDoctypeDeclStreamReaderWrapper.next(DisallowDoctypeDeclStreamReaderWrapper.java:36)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
	... 22 more
[2017-02-16 11:14:01,454] [EI-Core] ERROR - SequenceMediator Error while building message
org.apache.axis2.AxisFault: Error while building Passthrough stream
	at org.apache.synapse.transport.passthru.util.RelayUtils.handleException(RelayUtils.java:283)
	at org.apache.synapse.transport.passthru.util.RelayUtils.builldMessage(RelayUtils.java:142)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:99)
	at org.apache.synapse.mediators.AbstractListMediator.buildMessage(AbstractListMediator.java:140)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:83)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:314)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:554)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:188)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processResponse(MultitenantMessageReceiver.java:170)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:82)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:262)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.axiom.om.OMException: javax.xml.stream.XMLStreamException: DOCTYPE is not allowed
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
	at org.apache.axiom.om.impl.llom.OMDocumentImpl.getOMDocumentElement(OMDocumentImpl.java:109)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:570)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:566)
	at org.apache.synapse.transport.passthru.util.DeferredMessageBuilder.getDocument(DeferredMessageBuilder.java:160)
	at org.apache.synapse.transport.passthru.util.RelayUtils.builldMessage(RelayUtils.java:136)
	... 17 more
Caused by: javax.xml.stream.XMLStreamException: DOCTYPE is not allowed
	at org.apache.axiom.util.stax.dialect.DisallowDoctypeDeclStreamReaderWrapper.next(DisallowDoctypeDeclStreamReaderWrapper.java:36)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
	... 22 more
[2017-02-16 11:14:01,462] [EI-Core]  INFO - LogMediator To: http://www.w3.org/2005/08/addressing/anonymous, WSAction: , SOAPAction: , MessageID: urn:uuid:1b72a205-96b2-4a73-9cb2-7083b55a9219, Direction: response, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body/></soapenv:Envelope>

**Comment by madhawa-gunasekara** [comment]
Hi @sashikamw ,

What are the steps did you follow, there was an issue in ESB 5.0 tenan'ts main.xml. That's issue you are facing

**Comment by madhawa-gunasekara** [comment]
main sequence

**Comment by sashikamw** [comment]
Thanks Madahawa. Issue solved after correcting the main.xml file as below. We should include this to the migration documentation

<?xml version="1.0" encoding="UTF-8"?>
<sequence xmlns="http://ws.apache.org/ns/synapse" name="main">
   <in>
      <log/>
   </in>
   <out>
      <send/>
   </out>
</sequence>

**Comment by gilliandass** [comment]
Added into migration docs for migrating tenant artifacts.
https://docs.wso2.com/display/EI600/Upgrading+from+WSO2+Enterprise+Service+Bus
