### ISSUE TITLE
[Migration ESB500 to EI600] Authentication failure when invoking the secured proxy service

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#195]
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
EI M1 Jenkins Build (15/02/2017)
DB - mysql 5.6.31

Steps
1 TSecured proxy service exists in the  ESB500 pack 
2. Migrate the ESB500 pack to EI600 pack with artifacts
3. Invoke the secured proxy

Observations
1. Invocation failed due to authentication failure
2. Following error observed

[2017-02-16 11:20:23,048] [EI-Core] ERROR - ServerWorker Error processing POST request for : /services/enrichSample6
org.apache.axis2.AxisFault: The security token could not be authenticated or authorized
	at org.apache.rampart.handler.RampartReceiver.setFaultCodeAndThrowAxisFault(RampartReceiver.java:195)
	at org.apache.rampart.handler.RampartReceiver.invoke(RampartReceiver.java:96)
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:403)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.ws.security.WSSecurityException: The security token could not be authenticated or authorized; nested exception is: 
	javax.security.auth.callback.UnsupportedCallbackException: Check failed : System error
	at org.apache.ws.security.processor.UsernameTokenProcessor.handleUsernameToken(UsernameTokenProcessor.java:181)
	at org.apache.ws.security.processor.UsernameTokenProcessor.handleToken(UsernameTokenProcessor.java:61)
	at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:332)
	at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:249)
	at org.apache.rampart.RampartEngine.process(RampartEngine.java:217)
	at org.apache.rampart.handler.RampartReceiver.invoke(RampartReceiver.java:93)
	... 10 more
Caused by: javax.security.auth.callback.UnsupportedCallbackException: Check failed : System error
	at org.wso2.carbon.security.util.ServicePasswordCallbackHandler.handle(ServicePasswordCallbackHandler.java:120)
	at org.apache.rampart.TokenCallbackHandler.handle(TokenCallbackHandler.java:116)
	at org.apache.ws.security.processor.UsernameTokenProcessor.handleUsernameToken(UsernameTokenProcessor.java:168)
	... 15 more
[2017-02-16 11:22:35,238] [EI-Core]  INFO - SourceHandler Writer null when calling informWriterError

**Comment by sashikamw** [comment]
[artifacts.tar.gz](https://github.com/wso2/product-ei/files/779860/artifacts.tar.gz)

**Comment by nandika** [comment]
This scenario worked fine after creating the testrole1 role and adding a user to that role and using that users username, password in the request.
