### ISSUE TITLE
Failed to run the anonymization tool for BPMN related tables

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1960]
**Description:**
Failed to execute the identity-anonymization-tool tool for BPMN processes due to a table doesn't exists error

**Affected Product Version**:
EI 6.1.1 update 23

**OS, DB, other environment details and versions**:
OS - ubuntu 15.10
DB - mysql 5.6
JDK - 1.8

**Steps to reproduce:**
1. Configure BPS profile
2. Implement BPMN sample (LoanApprovalProcess.bar)
3. Execute the sample
4. Run the anonymization tool (ex: ./forget-me.sh -U Sashika )

**Observations**
Configured the data source and the config.json as documented in [1]

Failed to run the anonymization tool due to the following exception
```
sashika@sashika:~/.wum-wso2/products/wso2esb/EI/wso2ei-6.1.1-update23/wso2/business-process/bin$ ./forget-me.sh -U Sashika
2018-03-09 16:09:36 INFO  ForgetMeTool:167 - Generating pseudonym as pseudo name is not provided : 57105b1d-4875-467e-a247-cac2eeb756e3
2018-03-09 16:09:37 INFO  HikariDataSource:72 - HikariPool-0 - is starting.
2018-03-09 16:09:37 ERROR ForgetMeExecutionEngine:112 - Interrupted while executing the processor thread : java.util.concurrent.FutureTask@16aa0a0a
java.util.concurrent.ExecutionException: org.wso2.carbon.privacy.forgetme.api.runtime.InstructionExecutionException: Error occurred while executing sql from : /home/sashika/.wum-wso2/products/wso2esb/EI/wso2ei-6.1.1-update23/wso2/tools/identity-anonymization-tool/conf/sql/bpmn
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.waitForCompletion(ForgetMeExecutionEngine.java:109)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.execute(ForgetMeExecutionEngine.java:91)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:188)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:128)
Caused by: org.wso2.carbon.privacy.forgetme.api.runtime.InstructionExecutionException: Error occurred while executing sql from : /home/sashika/.wum-wso2/products/wso2esb/EI/wso2ei-6.1.1-update23/wso2/tools/identity-anonymization-tool/conf/sql/bpmn
	at org.wso2.carbon.privacy.forgetme.sql.instructions.RdbmsForgetMeInstruction.execute(RdbmsForgetMeInstruction.java:111)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:217)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:188)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.privacy.forgetme.sql.exception.SQLModuleException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'EI611update23Acitiviti.ACT_BPS_SUBSTITUTES' doesn't exist
	at org.wso2.carbon.privacy.forgetme.sql.module.DomainSeparatedSQLExecutionModule.execute(DomainSeparatedSQLExecutionModule.java:96)
	at org.wso2.carbon.privacy.forgetme.sql.module.DomainSeparatedSQLExecutionModule.execute(DomainSeparatedSQLExecutionModule.java:36)
	at org.wso2.carbon.privacy.forgetme.sql.instructions.RdbmsForgetMeInstruction.execute(RdbmsForgetMeInstruction.java:107)
	... 6 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'EI611update23Acitiviti.ACT_BPS_SUBSTITUTES' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)
	at com.mysql.jdbc.Util.getInstance(Util.java:383)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1193)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.execute(PreparedStatementProxy.java:44)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.execute(HikariPreparedStatementProxy.java)
	at org.wso2.carbon.privacy.forgetme.sql.module.DomainSeparatedSQLExecutionModule.execute(DomainSeparatedSQLExecutionModule.java:90)
	... 8 more
2018-03-09 16:09:47 INFO  ForgetMeExecutionEngine:219 - Processor execution completed. Processor : log-file
2018-03-09 16:09:47 INFO  ForgetMeExecutionEngine:115 - All processors have been properly shut-down
sashika@sashika:~/.wum-wso2/products/wso2esb/EI/wso2ei-6.1.1-update23/wso2/business-process/bin$ 

```
Note - The above-mentioned table (ACT_BPS_SUBSTITUTES) does not exists in the activiti database by default

[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information

**Comment by milanperera** [comment]
Please refer [1] for creating tables for BPMN.

[1] https://docs.wso2.com/display/EI611/Changing+the+Default+Databases+for+BPMN+and+BPEL#ChangingtheDefaultDatabasesforBPMNandBPEL-CreatingdatabasetablesintheBPMNdatabase
