### ISSUE TITLE
ClassNotFoundException when executing the identity-anonymization-tool for analytics

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#2002]
**Description:**
ClassNotFoundException when executing the identity-anonymization-tool for analytics profile

**Affected Product Version:**
EI 6.2.0 snapshot ( 13/03/2018)

**OS, DB, other environment details and versions:**    
DB - mysql 5.6
JDK 1.8
OS - Ubuntu 15.10

**Steps to reproduce:**
1. Configure the analytics as documented

config.json
```
{
    "processors": [
        "analytics-streams"
    ],
    "directories": [
        {
            "dir": "streams",
            "type": "analytics-streams",
            "processor": "analytics-streams"
        }
    ]
}
```
stream.json
```
{
    "streams": [
	{
            "streamName": "BPMN_Process_Instance_Data_Publish",
            "attributes": ["startUserId"],
            "id": "username"
        },
	{
            "streamName": "BPMN_Task_Instance_Data_Publish",
            "attributes": ["assignee"],
            "id": "username"
        },
        {
            "streamName": "BPMN_Service_Task_Instance_Data_Publish",
            "attributes": ["assignee"],
            "id": "username"
        }
    ]
}
```
2. Execute the tool
```
./forgetme.sh -U manager -carbon /home/sashika/.wum-wso2/products/wso2esb/EI/wso2ei-6.2.0-SNAPSHOT/wso2/analytics
```

**Observations**
Observed a ClassNotFound exception when executing the tool

```
sashika@sashika:~/.wum-wso2/products/wso2esb/EI/wso2ei-6.2.0-SNAPSHOT/bin$ ./forgetme.sh -U manager -carbon /home/sashika/.wum-wso2/products/wso2esb/EI/wso2ei-6.2.0-SNAPSHOT/wso2/analytics2018-03-14 15:25:03 INFO  ForgetMeTool:168 - Generating pseudonym as pseudo name is not provided : 6bd10239-1cd4-4c6d-9195-e023e8bd14ab
Exception in thread "main" java.lang.NoClassDefFoundError: org/wso2/carbon/analytics/dataservice/core/clustering/AnalyticsClusterManager
	at org.wso2.carbon.privacy.forgetme.analytics.streams.instructions.AnalyticsStreamsInstructionReader.read(AnalyticsStreamsInstructionReader.java:73)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.getInstructions(ForgetMeExecutionEngine.java:143)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.startExecutors(ForgetMeExecutionEngine.java:121)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.execute(ForgetMeExecutionEngine.java:90)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:189)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:129)
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.analytics.dataservice.core.clustering.AnalyticsClusterManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

```

[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information#RemovingPersonallyIdentifiableInformation-RemovingPIIfromtheAnalyticsprofile
 

**Related Issues:**

**Comment by sashikamw** [comment]
Verified the issue in latest EI 6.2.0 Snapshot (15/03/2018) and the issue still exists

**Comment by nandika** [comment]
This is due to a classpath problem in the forgetme script. The script should be updated to add plugins directory to the classpath while excluding the slf4j jars as done in [1] 

[1] https://raw.githubusercontent.com/wso2/product-das/master/modules/distribution/src/scripts/overrides/forget-me

**Comment by ShanikaWickramasinghe** [comment]
@nandika 
Observed the same exception as below in wso2-ei-6.2.0-rc1 pack

Exception in thread "main" java.lang.NoClassDefFoundError: org/wso2/carbon/analytics/dataservice/core/clustering/AnalyticsClusterManager
	at org.wso2.carbon.privacy.forgetme.analytics.streams.instructions.AnalyticsStreamsInstructionReader.read(AnalyticsStreamsInstructionReader.java:73)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.getInstructions(ForgetMeExecutionEngine.java:143)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.startExecutors(ForgetMeExecutionEngine.java:121)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.execute(ForgetMeExecutionEngine.java:90)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:198)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:138)
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.analytics.dataservice.core.clustering.AnalyticsClusterManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

**Comment by sajithshn** [comment]
This is not applicable anymore as we have moved to SP based analytics. This issue is reported on DAS based analytiscs
