### ISSUE TITLE
HTTP service requests fail if a Hazelcast runtime exception is thrown

### ISSUE THREAD

**Issue by kasunbg** [wso2/product-ei#2026]
**Description:**
Time to time, we see classic Hazelcast OperationTimeoutException stack traces in the log. This has been overlooked as a intermittent state which'll ultimately recover. But, if this exception occurred in the request path, then the request fails and goes to the fault sequence for error handling.

{code}
com.hazelcast.core.OperationTimeoutException: No response for 120000 ms. Aborting invocation!
{code}

When the operation timout occurred, ESB service requests returns faults until Hazelcast recovers from this state.

**The [OperationTimeoutException](https://github.com/hazelcast/hazelcast/blob/v3.5.3/hazelcast/src/main/java/com/hazelcast/core/OperationTimeoutException.java#L29) is a [runtime exception](https://github.com/hazelcast/hazelcast/blob/v3.5.3/hazelcast/src/main/java/com/hazelcast/core/HazelcastException.java#L22). But, we have not handled the OperationTimeoutException anywhere in our code. The EI service requests fails because of this.**

#### How to fix this?

I think the fix is straight-forward. We need to wrap the methods in `org.wso2.carbon.core.clustering.hazelcast.HazelcastDistributedMapProvider` with a try-catch block, and catch HazelcastException. It should be handled there itself since the client code won't know how to handle this exception.

```
TID: [-1234] [] [2018-02-01 01:13:31,182] ERROR {org.wso2.carbon.security.util.ServicePasswordCallbackHandler} -  Error in authenticating user. {org.wso2.carbon.security.util.ServicePasswordCallbackHandler}
  com.hazelcast.core.OperationTimeoutException: No response for 120000 ms. Aborting invocation! 
Invocation{ serviceName='hz:impl:mapService', op=SetOperation{$cache.$domain[carbon.super]USER_ROLES_CACHE_MANAGER#USER_ROLES_CACHE}, 
partitionId=71, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, 
target=Address[localhost]:4000, backupsExpected=0, backupsCompleted=0} No response has been received!  
backups-expected:0 backups-completed: 0
  at com.hazelcast.spi.impl.operationservice.impl.Invocation.newOperationTimeoutException(Invocation.java:491)
  at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:277)
  at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:224)
  at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:204)
  at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:456)
  at com.hazelcast.map.impl.proxy.MapProxySupport.setInternal(MapProxySupport.java:508)
  at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:171)
  at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:161)
  at org.wso2.carbon.core.clustering.hazelcast.HazelcastDistributedMapProvider$DistMap.put(HazelcastDistributedMapProvider.java:149)
  at org.wso2.carbon.caching.impl.CacheImpl.internalPut(CacheImpl.java:352)
  at org.wso2.carbon.caching.impl.CacheImpl.put(CacheImpl.java:368)
  at org.wso2.carbon.user.core.common.UserRolesCache.addToCache(UserRolesCache.java:96)
  at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addToUserRolesCache(AbstractUserStoreManager.java:2927)
  at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addToIsUserHasRole(AbstractUserStoreManager.java:1917)
  at org.wso2.carbon.user.core.common.AbstractUserStoreManager.isUserInRole(AbstractUserStoreManager.java:1889)
  at org.wso2.carbon.user.core.common.AbstractUserStoreManager.isUserInRole(AbstractUserStoreManager.java:1850)
  at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.isUserAuthorized(JDBCAuthorizationManager.java:242)
  at org.wso2.carbon.security.util.ServicePasswordCallbackHandler.authenticateUser(ServicePasswordCallbackHandler.java:255)
  at org.wso2.carbon.security.util.ServicePasswordCallbackHandler.handle(ServicePasswordCallbackHandler.java:105)
  at org.apache.rampart.TokenCallbackHandler.handle(TokenCallbackHandler.java:116)
  at org.apache.ws.security.processor.UsernameTokenProcessor.handleUsernameToken(UsernameTokenProcessor.java:168)
  at org.apache.ws.security.processor.UsernameTokenProcessor.handleToken(UsernameTokenProcessor.java:61)
  at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:332)
  at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:249)
  at org.apache.rampart.RampartEngine.process(RampartEngine.java:214)
  at org.apache.rampart.handler.RampartReceiver.invoke(RampartReceiver.java:92)
  at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
  at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
  at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
  at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
  at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:317)
  at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:149)
  at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  at ------ End remote and begin local stack-trace ------.(Unknown Source)
  at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:384)
  at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:334)
  at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:225)
  at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:204)
  at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:456)
  at com.hazelcast.map.impl.proxy.MapProxySupport.setInternal(MapProxySupport.java:508)
  at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:171)
  at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:161)
  at org.wso2.carbon.core.clustering.hazelcast.HazelcastDistributedMapProvider$DistMap.put(HazelcastDistributedMapProvider.java:149)
  at org.wso2.carbon.caching.impl.CacheImpl.internalPut(CacheImpl.java:352)
  at org.wso2.carbon.caching.impl.CacheImpl.put(CacheImpl.java:368)
  at org.wso2.carbon.user.core.common.UserRolesCache.addToCache(UserRolesCache.java:96)
  at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addToUserRolesCache(AbstractUserStoreManager.java:2927)
  at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addToIsUserHasRole(AbstractUserStoreManager.java:1917)
  at org.wso2.carbon.user.core.common.AbstractUserStoreManager.isUserInRole(AbstractUserStoreManager.java:1889)
  at org.wso2.carbon.user.core.common.AbstractUserStoreManager.isUserInRole(AbstractUserStoreManager.java:1850)
  at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.isUserAuthorized(JDBCAuthorizationManager.java:242)
  at org.wso2.carbon.security.util.ServicePasswordCallbackHandler.authenticateUser(ServicePasswordCallbackHandler.java:255)
  at org.wso2.carbon.security.util.ServicePasswordCallbackHandler.handle(ServicePasswordCallbackHandler.java:105)
  at org.apache.rampart.TokenCallbackHandler.handle(TokenCallbackHandler.java:116)
  at org.apache.ws.security.processor.UsernameTokenProcessor.handleUsernameToken(UsernameTokenProcessor.java:168)
  at org.apache.ws.security.processor.UsernameTokenProcessor.handleToken(UsernameTokenProcessor.java:61)
  at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:332)
  at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:249)
  at org.apache.rampart.RampartEngine.process(RampartEngine.java:214)
  at org.apache.rampart.handler.RampartReceiver.invoke(RampartReceiver.java:92)
  at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
  at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
  at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
  at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
  at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:317)
  at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:149)
  at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

```

**Affected Product Version:**
Can be seen in ESB 4.9.0
This is there in the latest version as well as I see.

**OS, DB, other environment details and versions:**    
Two node cluster with Hazelcast. 

**Steps to reproduce:**
* Make sure registry caching is enabled
* Add a proxy service that reads a registry resource via `get-property()`
* Overloaded one node N1 by sending requests. Now, other node N2 will start throwing operation timeout exceptions.
* Send a request to your proxy service in N2.

**Related Issues:**
N/A

**Comment by sdkottegoda** [comment]
Addressed in https://github.com/wso2/carbon-kernel/pull/1734
