### ISSUE TITLE
ClassCastException when adding custom SOAPHeader to message in secured proxy

### ISSUE THREAD

**Issue by nuwanw** [wso2/product-ei#2042]
The below error can be observed when trying to add custom SOAPHeader to a message in secured proxy service. This error occurs when ESB try to send the message out. 

Adding header using enrich or header mediator 
`<enrich>

      <source clone="true" type="inline">
         <customHeaderResp xmlns="">
               <test1>ABC</test1>
               <test2>XYZ</test2>
         </customHeaderResp>
       </source>
       <target xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                    action="child"
                    xpath="//soapenv:Header"/>
</enrich>`

at org.apache.synapse.core.axis2.Axis2Sender.handleException(Axis2Sender.java:270)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:238)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:531)
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:118)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:337)
	at org.apache.synapse.mediators.builtin.LoopBackMediator.mediate(LoopBackMediator.java:63)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:213)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:404)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.axis2.AxisFault: Error in extracting message properties
	at org.apache.rampart.handler.RampartSender.invoke(RampartSender.java:76)
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:426)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:235)
	... 18 more
Caused by: org.apache.rampart.RampartException: Error in extracting message properties
	at org.apache.rampart.RampartMessageData.<init>(RampartMessageData.java:414)
	at org.apache.rampart.MessageBuilder.build(MessageBuilder.java:61)
	at org.apache.rampart.handler.RampartSender.invoke(RampartSender.java:65)
	... 23 more
Caused by: org.apache.ws.security.WSSecurityException: Error in converting SOAP Envelope to Document; nested exception is: 
	java.lang.ClassCastException: org.apache.axiom.om.impl.llom.OMElementImpl cannot be cast to org.apache.axiom.soap.SOAPHeaderBlock
	at org.apache.rampart.util.Axis2Util.getDocumentFromSOAPEnvelope(Axis2Util.java:156)
	at org.apache.rampart.RampartMessageData.<init>(RampartMessageData.java:268)
	... 25 more
Caused by: java.lang.ClassCastException: org.apache.axiom.om.impl.llom.OMElementImpl cannot be cast to org.apache.axiom.soap.SOAPHeaderBlock
	at org.apache.rampart.util.Axis2Util.getDocumentFromSOAPEnvelope(Axis2Util.java:107

**Comment by harshana05** [comment]
Hi @malakaganga @prabushi @nuwanw 

Has this been merged to ESB 5.0.0 branch as well?
