### ISSUE TITLE
The analytics-backup.sh script under wso2/analytics/bin throw errors

### ISSUE THREAD

**Issue by kasunbg** [wso2/product-ei#2066]
**Description:**
The `$EI_HOME/wso2/analytics/bin/analytics-backup.sh` can be used to [backup and restore](https://docs.wso2.com/display/DAS310/Backing+Up+or+Restoring+Analytics+Data) DAS eventstore data.

When I run it using the following command, it threw an error:
```
./analytics-backup.sh -purge -table "ORG_WSO2_ESB_ANALYTICS_STREAM_EVENT" -tenantId -1234 -timeFrom 18-03-24-00:00:00 -timeTo 18-03-27-00:00:00
```
The error:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.<init>(AnalyticsDataServiceImpl.java:152)
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsServiceHolder.checkAndPopulateCustomAnalyticsDS(AnalyticsServiceHolder.java:87)
	at org.wso2.carbon.analytics.dataservice.core.AnalyticsServiceHolder.getAnalyticsDataService(AnalyticsServiceHolder.java:74)
	at org.wso2.carbon.analytics.tools.backup.AnalyticsDataBackupTool.main(AnalyticsDataBackupTool.java:128)
Caused by: java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at java.util.Properties.setProperty(Properties.java:166)
	at java.lang.System.setProperty(System.java:796)
	at org.wso2.carbon.utils.CarbonUtils.getCarbonHome(CarbonUtils.java:252)
	at org.wso2.carbon.utils.CarbonUtils.getCarbonConfigDirPath(CarbonUtils.java:299)
	at org.wso2.carbon.analytics.dataservice.core.Constants.<clinit>(Constants.java:81)
	... 4 more
```

Seems the cause is that CARBON_HOME is not set properly. I was able to execute it successfully by setting the CARBON_HOME as an environment variable before running the above command. I used the below command for that purpose:

```
CARBON_HOME=</path/to/WSO2_EI>/wso2/analytics ./analytics-backup.sh -purge -table "ORG_WSO2_ESB_ANALYTICS_STREAM_EVENT" -tenantId -1234 -timeFrom 18-03-24-00:00:00 -timeTo 18-03-27-00:00:00
```

While we need to fix this in the next version, we should also update our documentation about the above workaround.

**Affected Product Version:**
EI-Analytics 6.1.1

**OS, DB, other environment details and versions:**    
Ubuntu 16.04
JDK 8

**Steps to reproduce:**
See above.

**Related Issues:**
N/A

**Comment by nandika** [comment]
Verified with EI 6.3.0 version and it is working fine

**Comment by shavidissa** [comment]
Thank you Kasun and Nandika!

Updated the docs for 6xx and 630.
[1]https://docs.wso2.com/display/EI6xx/Backing+Up+or+Restoring+Analytics+Data
[2] https://docs.wso2.com/display/EI630/Backing+Up+or+Restoring+Analytics+Data

P.S: The tested OS mentions EI-Analytics 6.1.1. I tested this on 6.1.1 and 6.2.0 and it gave me the following error [3]. Therefore, I didn't add this page to the respective docs.

[3] `Error: Could not find or load main class org.wso2.carbon.analytics.tools.backup.AnalyticsDataBackupTool`
