### ISSUE TITLE
Fix ForceMessageValidationTestCase test cases.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2071]
**Description:**
Test testInvalidJSONMessage() and testInvalidXMLMessage() are failing due to recent carbon-mediation upgrades.

Need to fix them properly.

Ref :- https://wso2.org/jenkins/view/products/job/products/job/product-ei/lastBuild/testReport/

Errors :- 

Error Message

Test fails for forcing JSON validation with force.json.message.validation passthru-http property. expected:<true> but was:<false>
Stacktrace

java.lang.AssertionError: Test fails for forcing JSON validation with force.json.message.validation passthru-http property. expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at org.wso2.carbon.esb.passthru.transport.test.ForceMessageValidationTestCase.testInvalidJSONMessage(ForceMessageValidationTestCase.java:90)

Test fails for forcing XML validation with force.xml.message.validation passthru-http property. expected:<true> but was:<false>
Stacktrace

java.lang.AssertionError: Test fails for forcing XML validation with force.xml.message.validation passthru-http property. expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at org.wso2.carbon.esb.passthru.transport.test.ForceMessageValidationTestCase.testInvalidXMLMessage(ForceMessageValidationTestCase.java:111)

**Suggested Labels:**

**Suggested Assignees:**

**Comment by prabushi** [comment]
Related fix added in https://github.com/wso2/wso2-synapse/pull/1074 Failing due to mediation version is degraded. Will enable after testing after the milestone release.

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/product-ei/pull/2077
