### ISSUE TITLE
Solution and Config projects cannot be created in EI 6.2.0 RC2 Tooling 

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#2089]
**Description:**
When we try to create a config or solution project via Dashboard in EI tooling, It doesn't load the project creation UI

**Suggested Labels:**
Type/Bug
Severity/Blocker
Priority/Highest
Affected/EI 6.2.0 RC2

**Affected Product Version:**
EI 6.2.0 RC2 tooling pack

**OS, DB, other environment details and versions:**    
OS- macOS High Sierra
JDK- java version "1.8.0_152
EI 6.2.0 RC2 tooling  fresh pack

**Steps to reproduce:**
Start the EI 6.2.0 RC2 tooling pack
Pack got started but backend throws the below error
Try to create a solution or config project from the Dashboard
Try to create both project even from File-> new ->Other

**Results:**

1. Starting throws the below error

`Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.osgi.storage.FrameworkExtensionInstaller (file:/Users/chalitha/Documents/RD/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.osgi_3.10.102.v20160118-1700.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.eclipse.osgi.storage.FrameworkExtensionInstaller
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
org.eclipse.m2e.logback.configuration: Logback config file: /Users/chalitha/Documents/workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.6.2.20150902-0002.xml
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://913.fwk415758005:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://913.fwk415758005:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
org.eclipse.m2e.logback.configuration: Initializing logback
Exception in thread "ServerConnection STARTING" java.lang.NoClassDefFoundError: java/sql/Time
	at com.google.gson.Gson.<init>(Gson.java:230)
	at com.google.gson.GsonBuilder.create(GsonBuilder.java:545)
	at org.eclipse.epp.internal.logging.aeri.ide.server.json.Json.getInstance(Json.java:59)
	at org.eclipse.epp.internal.logging.aeri.ide.server.json.Json.deserialize(Json.java:88)
	at org.eclipse.epp.internal.logging.aeri.ide.server.mars.IO.refreshConfiguration(IO.java:70)
	at org.eclipse.epp.internal.logging.aeri.ide.server.mars.ServerConnection.startUp(ServerConnection.java:101)
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: java.sql.Time
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:709)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:351)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 9 more
`

2. Config or solution projects cannot be created either way in above steps.

**Comment by prabushi** [comment]
It seems this issue is coming from eclipse side. 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=498728
https://github.com/eclipse/leshan/issues/58
Apparently it is fixed in Eclipse Oxygen. https://github.com/eclipse/buildship/issues/282

**Comment by prabushi** [comment]
As a workaround we can add `--add-modules=ALL-SYSTEM` in eclipse.ini file.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=530401

**Comment by dakshika** [comment]
closing this since it has a workaround and fixed in latest version
