### ISSUE TITLE
Timeout after facing an AxisFault error “Caused by: org.apache.rampart.RampartException: Error in extracting message properties”

### ISSUE THREAD

**Issue by Shakila** [wso2/product-ei#2104]
**Description:**
Randomly, requests time out after facing the following AxisFault in WSO2 ESB 4.8.1 for SOAP calls via services: 

[2018/03/07 09:35:53.876] [] [ZUTB0] [] [org.apache.synapse.core.axis2.Axis2Sender] [emetteur:B2B] [nomApi:] [nomRessource::] [service:SRVX_DetailAssurancePredica_vs:] [nomOperation:restituerContrat] [consommateur::] [consommateurOrigine::] [acteur:OX20002] [CR:87800] [canalID:] [distribCanalID:] - [PassThroughMessageProcessor-2] ERROR o.a.synapse.core.axis2.Axis2Sender - Unexpected error during sending message out
org.apache.axis2.AxisFault: Error in extracting message properties
at org.apache.rampart.handler.RampartSender.invoke(RampartSender.java:76) ~[rampart-core_1.6.1.wso2v12.jar:na]
…
Caused by: org.apache.rampart.RampartException: Error in extracting message properties
at org.apache.rampart.RampartMessageData.<init>(RampartMessageData.java:410) ~[rampart-core_1.6.1.wso2v12.jar:na]
…

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Shakila** [comment]
It's fixed in the svn revision r57865
Repo: https://svn.wso2.com/wso2/custom/projects/projects/carbon/turing/platform/trunk/dependencies/rampart/1.6.1-wso2v12/
