### ISSUE TITLE
VFS SMB not working in E.I 6.2.0

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2150]
**Description:**
VFS SMB is not Working as expected. It throws following error

```
[2018-04-27 15:06:24,060] [EI-Core] ERROR - VFSTransportListener Repeatedly failed to resolve the file URI: 
----------------------------------------------------------
org.apache.commons.vfs2.FileSystemException: Badly formed URI 
----------------------------------------------------------.
        at org.apache.commons.vfs2.provider.url.UrlFileProvider.findFile(UrlFileProvider.java:75)
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:793)
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:658)
        at org.apache.synapse.transport.vfs.VFSTransportListener.scanFileOrDirectory(VFSTransportListener.java:261)
        at org.apache.synapse.transport.vfs.VFSTransportListener.poll(VFSTransportListener.java:188)
        at org.apache.synapse.transport.vfs.VFSTransportListener.poll(VFSTransportListener.java:134)
        at org.apache.axis2.transport.base.AbstractPollingTransportListener$1$1.run(AbstractPollingTransportListener.java:67)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.MalformedURLException: unknown protocol: smb
        at java.net.URL.<init>(URL.java:600)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at org.apache.commons.vfs2.provider.url.UrlFileProvider.findFile(UrlFileProvider.java:60)
        ... 10 more
```

**Steps to reproduce:**

Please deploy the follwoing proxy configs

```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="VFSSMB"
       transports="vfs"
       startOnLoad="true"
       trace="disable">
   <description/>
   <target>
      <endpoint>
         <address uri="http://localhost:9000/services/SimpleStockQuoteService"
                  format="soap12"/>
      </endpoint>
      <outSequence>
         <property name="transport.vfs.ReplyFileName"
                   expression="fn:concat(fn:substring-after(get-property('MessageID'), 'urn:uuid:'), '.xml')"
                   scope="transport"/>
         <property name="OUT_ONLY" value="true"/>
         <send>
            <endpoint>
               <address uri="vfs:smb://Nirothipan:smb@localhost/SambaShareOut/reply.xml"/>
            </endpoint>
         </send>
      </outSequence>
   </target>
   <parameter name="transport.vfs.ActionAfterProcess">MOVE</parameter>
   <parameter name="transport.PollInterval">5</parameter>
   <parameter name="transport.vfs.MoveAfterProcess">vfs:smb://Nirothipan:smb@localhost/SambaShareOut</parameter>
   <parameter name="transport.vfs.FileURI">vfs:smb://Nirothipan:smb@localhost/SambaShareIn</parameter>
   <parameter name="transport.vfs.MoveAfterFailure">vfs:smb://Nirothipan:smb@localhost/SambaShareOut</parameter>
   <parameter name="transport.vfs.FileNamePattern">.*\.xml</parameter>
   <parameter name="transport.vfs.ContentType">text/xml</parameter>
   <parameter name="transport.vfs.ActionAfterFailure">MOVE</parameter>
</proxy>
```

or follow sample https://docs.wso2.com/display/EI620/Sample+265%3A+Accessing+a+Windows+Share+Using+the+VFS+Transport

you can refer https://risenfall.wordpress.com/2014/11/03/how-to-setup-vfs-transport-in-wso2-esb-with-samba/ also.

Please note that, the same is working properly in ESB 4.8.1 , EBS 5.0.0 and EI 6.1.1.

**Comment by fede-rodriguez** [comment]
I am having this problem also... is there any solution to this that does not involve waiting for the new package? Thanks!

**Comment by Nirothipan** [comment]
This fix will be available with this weekly release.
