### ISSUE TITLE
ESB continuously failover to same node due to javax.jms.IllegalStateException

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#2154]
**Description:**

When MB Client throws a  javax.jms.IllegalStateException ESB continuously failover to same node. 

Caused by: javax.jms.IllegalStateException: Object AMQConnection:
Host: mb-2.prod1.midw.prod10.aws.travisperkins.com
Port: 5672
Virtual Host: carbon
Client ID: clientID
Active session count: 0 has been closed
	at org.wso2.andes.client.Closeable.checkNotClosed(Closeable.java:70)
	at org.wso2.andes.client.AMQConnection.createSession(AMQConnection.java:705)
	at org.wso2.andes.client.AMQConnection.createSession(AMQConnection.java:697)
	at org.wso2.andes.client.AMQConnection.createSession(AMQConnection.java:691)
	at org.wso2.andes.client.AMQConnection.createTopicSession(AMQConnection.java:779)
	at org.apache.axis2.transport.jms.JMSOutTransportInfo.createJMSSender(JMSOutTransportInfo.java:380)
	at org.apache.axis2.transport.jms.JMSSender.sendMessage(JMSSender.java:127)
	... 43 more

**Affected Product Version:**

ESB 4.9.0
MB 3.0.0

**OS, DB, other environment details and versions:** 

Java 7/8   

**Steps to reproduce:**

1. Setup MB1 single node with cluster enabled, and configure broker.xml to have minimum node count =2. Setup another MB2 single node with cluster enabled with default configs.

2. Setup ESB node to have failover connection as MB1,MB2. 

3. When a message is sent javax.jms.IllegalStateException is thrown and continuously failover to same node. 

These steps are jest to create javax.jms.IllegalStateException. 
Another situation this can be thrown is when trying to create a session on a closed connection. 
Need to fix server side to handle it properly so that Andes client will not throw  an IllegalStateException. 

**Related Issues:**
N/A

**Comment by abeykoon** [comment]
Fixed with https://github.com/wso2/andes/pull/971
