### ISSUE TITLE
Issues with quick start guide EI 6.2.0

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2156]
**Description:**
1. Getting 401 Unauthorized for the wso2eidemo@gmail.com which is defined in "PaymentRequestProcessingSequence" of [1]. Therefore, cannot test the reservation request and continue further, since the reservation request is not sent to the defined email address.

It seems we should correct the accessToken, clientId, clientSecret, etc.

[1] - https://github.com/wso2-docs/WSO2_EI/blob/master/Quick_Start_Guide_Artifacts/SampleServicesCompositeApplication_1.0.0.car

2. email defined at activiti.xml is not working. It throws the following error [2].

`<property name="mailServerDefaultFrom" value="wso2eidemo@gmail.com"/><property name="mailServerUsername" value="wso2eidemo@gmail.com"/><property name="mailServerPassword" value="wso2carbon@ei"/>`

```
[2018-05-08 12:20:02,522] [EI-Business-Process] ERROR {org.wso2.carbon.bpmn.rest.common.provider.ExceptionMapper.BPMNExceptionHandler} -  Activiti Exception Occured 
org.activiti.engine.ActivitiException: Could not send e-mail in execution 5
	at org.activiti.engine.impl.bpmn.behavior.MailActivityBehavior.handleException(MailActivityBehavior.java:411)
	at org.activiti.engine.impl.bpmn.behavior.MailActivityBehavior.execute(MailActivityBehavior.java:107)
	at org.activiti.engine.impl.pvm.runtime.AtomicOperationActivityExecute.execute(AtomicOperationActivityExecute.java:60)
	at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:644)
..................
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:587
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1398)
	at org.apache.commons.mail.Email.send(Email.java:1423)
	at org.activiti.engine.impl.bpmn.behavior.MailActivityBehavior.execute(MailActivityBehavior.java:102)
	... 192 more
Caused by: javax.mail.AuthenticationFailedException
	at javax.mail.Service.connect(Service.java:306)
	at javax.mail.Service.connect(Service.java:156)
	at javax.mail.Service.connect(Service.java:105)
	at javax.mail.Transport.send0(Transport.java:168)
	at javax.mail.Transport.send(Transport.java:98)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1388)
	... 194 more
```
[2] - https://docs.wso2.com/display/EI620/Quick+Start+Guide#QuickStartGuide-Cancelthereservation

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
We can point to [2], to generate tokens and define another email at the gmail connector to test the quick start.
[2] - https://docs.wso2.com/display/EI6xx/Using+the+Gmail+Connector#UsingtheGmailConnector-CreatingthecredentialsforusingtheGmailConnector

**Comment by shavidissa** [comment]
Hi Prabushi,

We revamped the QSG. So moving forward you won't get this issue. Thank you, for raising this concern.

[1] https://docs.wso2.com/display/EI6xx/Quick+Start+Guide
