### ISSUE TITLE
Unable to locate Smooks digest configuration

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#2180]
**Description:**

Apply fix [1] to smooks orbit bundle of WSO2

Error: 
TID: [-1234] [] [2018-02-15 09:54:27,025] ERROR {org.apache.synapse.mediators.base.SequenceMediator} -  Unable to locate Smooks digest configuration '/META-INF/xsd/smooks/csv-1.2.xsd-smooks.xml' for extended resource configuration namespace 'http://www.milyn.org/xsd/smooks/csv-1.2.xsd'.  This resource must be available on the classpath. {org.apache.synapse.mediators.base.SequenceMediator}
org.milyn.cdr.SmooksConfigurationException: Unable to locate Smooks digest configuration '/META-INF/xsd/smooks/csv-1.2.xsd-smooks.xml' for extended resource configuration namespace 'http://www.milyn.org/xsd/smooks/csv-1.2.xsd'.  This resource must be available on the classpath.
	at org.milyn.cdr.XMLConfigDigester.assertExtendedConfigOK(XMLConfigDigester.java:616)
	at org.milyn.cdr.XMLConfigDigester.getExtenededConfigDigester(XMLConfigDigester.java:581)
	at org.milyn.cdr.XMLConfigDigester.digestExtendedResourceConfig(XMLConfigDigester.java:539)
	at org.milyn.cdr.XMLConfigDigester.digestV11XSDValidatedConfig(XMLConfigDigester.java:340)
	at org.milyn.cdr.XMLConfigDigester.digestConfigRecursively(XMLConfigDigester.java:226)
	at org.milyn.cdr.XMLConfigDigester.digestConfig(XMLConfigDigester.java:184)
	at org.milyn.cdr.SmooksResourceConfigurationStore.registerResources(SmooksResourceConfigurationStore.java:229)
	at org.milyn.Smooks.addConfigurations(Smooks.java:340)
	at org.milyn.Smooks.addConfigurations(Smooks.java:358)
	at org.milyn.Smooks.<init>(Smooks.java:172)
	at org.wso2.carbon.mediator.transform.SmooksMediator.createSmooksConfig(SmooksMediator.java:220)
	at org.wso2.carbon.mediator.transform.SmooksMediator.mediate(SmooksMediator.java:104)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:37)
	at org.apache.synapse.config.xml.SwitchCase.mediate(SwitchCase.java:69)
	at org.apache.synapse.mediators.filters.SwitchMediator.mediate(SwitchMediator.java:134)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectInbound(Axis2SynapseEnvironment.java:446)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FileInjectHandler.invoke(FileInjectHandler.java:163)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.processFile(FilePollingConsumer.java:763)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.directoryHandler(FilePollingConsumer.java:543)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.poll(FilePollingConsumer.java:214)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.execute(FilePollingConsumer.java:134)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FileTask.taskExecute(FileTask.java:47)
	at org.wso2.carbon.inbound.endpoint.common.InboundTask.execute(InboundTask.java:45)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[1]. https://github.com/smooks/smooks/issues/94

**Affected Product Version:**

ESB 5.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

Unknown 

**Related Issues:**
N/A

**Comment by Nirothipan** [comment]
Fix modified with 
https://github.com/wso2-support/orbit/pull/72
https://github.com/wso2/orbit/pull/325
