### ISSUE TITLE
Message-Broker profile clustering, Second node shows errors

### ISSUE THREAD

**Issue by etalaq** [wso2/product-ei#2187]
**Description:**
Clustering Message Broker profile fails with the second node joining the cluster

**Suggested Labels:**
wso2ei,message-broker

**Affected Product Version:**
WSO2EI-6.2.0

**OS, DB, other environment details and versions:**    
CentOS 7.4 / MariaDB 10

**Steps to reproduce:**
Follow the steps in clustering:
https://docs.wso2.com/display/EI620/Clustering+the+Message+Broker+Profile

From the logs, the below messages occur on the second message-broker profile node (even if running the nodes in any order, the later gets the below messages):

`[2018-05-19 21:15:30,347] [EI-Broker] ERROR {org.wso2.andes.thrift.MBThriftClient} -  Attempt 0 failed updating slot delete safe zone
org.apache.thrift.TApplicationException: Internal error processing updateCurrentMessageIdForSafeZone
	at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
	at org.wso2.andes.thrift.slot.gen.SlotManagementService$Client.recv_updateCurrentMessageIdForSafeZone(SlotManagementService.java:221)
	at org.wso2.andes.thrift.slot.gen.SlotManagementService$Client.updateCurrentMessageIdForSafeZone(SlotManagementService.java:207)
	at org.wso2.andes.thrift.MBThriftClient.updateSlotDeletionSafeZone(MBThriftClient.java:303)
	at org.wso2.andes.kernel.slot.SlotCoordinatorCluster$ThriftSlotCoordinator.updateSlotDeletionSafeZone(SlotCoordinatorCluster.java:156)
	at org.wso2.andes.kernel.slot.SlotCoordinatorCluster.updateSlotDeletionSafeZone(SlotCoordinatorCluster.java:66)
	at org.wso2.andes.kernel.slot.SlotMessageCounter.submitCurrentSafeZone(SlotMessageCounter.java:153)
	at org.wso2.andes.kernel.slot.SlotMessageCounter.access$700(SlotMessageCounter.java:51)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.updateCoordinatorWithCurrentSafezone(SlotMessageCounter.java:380)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.run(SlotMessageCounter.java:326)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-19 21:15:30,348] [EI-Broker]  WARN {org.wso2.andes.thrift.MBThriftClient} -  Error returning thrift client back to the pool. Coordinator might have changed.
java.lang.IllegalStateException: Returned object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:541)
	at org.wso2.andes.thrift.MBThriftClient.returnServiceClient(MBThriftClient.java:473)
	at org.wso2.andes.thrift.MBThriftClient.updateSlotDeletionSafeZone(MBThriftClient.java:309)
	at org.wso2.andes.kernel.slot.SlotCoordinatorCluster$ThriftSlotCoordinator.updateSlotDeletionSafeZone(SlotCoordinatorCluster.java:156)
	at org.wso2.andes.kernel.slot.SlotCoordinatorCluster.updateSlotDeletionSafeZone(SlotCoordinatorCluster.java:66)
	at org.wso2.andes.kernel.slot.SlotMessageCounter.submitCurrentSafeZone(SlotMessageCounter.java:153)
	at org.wso2.andes.kernel.slot.SlotMessageCounter.access$700(SlotMessageCounter.java:51)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.updateCoordinatorWithCurrentSafezone(SlotMessageCounter.java:380)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.run(SlotMessageCounter.java:326)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-19 21:15:30,361] [EI-Broker] ERROR {org.wso2.andes.thrift.MBThriftClient} -  Attempt 1 failed updating slot delete safe zone
org.apache.thrift.TApplicationException: Internal error processing updateCurrentMessageIdForSafeZone
	at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
	at org.wso2.andes.thrift.slot.gen.SlotManagementService$Client.recv_updateCurrentMessageIdForSafeZone(SlotManagementService.java:221)
	at org.wso2.andes.thrift.slot.gen.SlotManagementService$Client.updateCurrentMessageIdForSafeZone(SlotManagementService.java:207)
	at org.wso2.andes.thrift.MBThriftClient.updateSlotDeletionSafeZone(MBThriftClient.java:303)
	at org.wso2.andes.kernel.slot.SlotCoordinatorCluster$ThriftSlotCoordinator.updateSlotDeletionSafeZone(SlotCoordinatorCluster.java:156)
	at org.wso2.andes.kernel.slot.SlotCoordinatorCluster.updateSlotDeletionSafeZone(SlotCoordinatorCluster.java:66)
	at org.wso2.andes.kernel.slot.SlotMessageCounter.submitCurrentSafeZone(SlotMessageCounter.java:153)
	at org.wso2.andes.kernel.slot.SlotMessageCounter.access$700(SlotMessageCounter.java:51)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.updateCoordinatorWithCurrentSafezone(SlotMessageCounter.java:380)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.run(SlotMessageCounter.java:326)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-19 21:15:30,362] [EI-Broker]  WARN {org.wso2.andes.thrift.MBThriftClient} -  Error returning thrift client back to the pool. Coordinator might have changed.
java.lang.IllegalStateException: Returned object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:541)
	at org.wso2.andes.thrift.MBThriftClient.returnServiceClient(MBThriftClient.java:473)
	at org.wso2.andes.thrift.MBThriftClient.updateSlotDeletionSafeZone(MBThriftClient.java:309)
	at org.wso2.andes.kernel.slot.SlotCoordinatorCluster$ThriftSlotCoordinator.updateSlotDeletionSafeZone(SlotCoordinatorCluster.java:156)
	at org.wso2.andes.kernel.slot.SlotCoordinatorCluster.updateSlotDeletionSafeZone(SlotCoordinatorCluster.java:66)
	at org.wso2.andes.kernel.slot.SlotMessageCounter.submitCurrentSafeZone(SlotMessageCounter.java:153)
	at org.wso2.andes.kernel.slot.SlotMessageCounter.access$700(SlotMessageCounter.java:51)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.updateCoordinatorWithCurrentSafezone(SlotMessageCounter.java:380)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.run(SlotMessageCounter.java:326)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by etalaq** [comment]
after reading the documents again from the following links:
https://docs.wso2.com/display/EI620/Clustering+the+Message+Broker+Profile
https://docs.wso2.com/display/MB320/Clustered+Deployment#6af0855168524ac7a3488e7e239e3e7a
https://docs.wso2.com/display/MB310/Default+Ports+of+WSO2+Products

you have to enable the ports on the system firewall. For example i have CentOS:
note that i'm using different ports for each profile clustering.
`#!/bin/sh

#### Firewall Configuration
#### BEGIN
# Integration runtime ports 
sudo firewall-cmd --permanent --add-port=9443/tcp
sudo firewall-cmd --permanent --add-port=8243/tcp
sudo firewall-cmd --permanent --add-port=8280/tcp

# EI-Analytics runtime ports
sudo firewall-cmd --permanent --add-port=9444/tcp
sudo firewall-cmd --permanent --add-port=9161/tcp
sudo firewall-cmd --permanent --add-port=7712/tcp
sudo firewall-cmd --permanent --add-port=7612/tcp
sudo firewall-cmd --permanent --add-port=7078/tcp
sudo firewall-cmd --permanent --add-port=11225/tcp


# EI-Business Process runtime ports
sudo firewall-cmd --permanent --add-port=9445/tcp
sudo firewall-cmd --permanent --add-port=9765/tcp
sudo firewall-cmd --permanent --add-port=9443/tcp
sudo firewall-cmd --permanent --add-port=9443/tcp

# EI-Broker runtime ports
sudo firewall-cmd --permanent --add-port=9446/tcp
sudo firewall-cmd --permanent --add-port=9766/tcp
sudo firewall-cmd --permanent --add-port=5675/tcp
sudo firewall-cmd --permanent --add-port=8675/tcp
sudo firewall-cmd --permanent --add-port=1886/tcp
sudo firewall-cmd --permanent --add-port=8836/tcp
sudo firewall-cmd --permanent --add-port=7614/tcp
sudo firewall-cmd --permanent --add-port=4000/tcp
sudo firewall-cmd --permanent --add-port=1883/tcp
sudo firewall-cmd --permanent --add-port=8833/tcp
sudo firewall-cmd --permanent --add-port=7611/tcp

# EI-MSF4J runtime ports
sudo firewall-cmd --permanent --add-port=9090/tcp

# Thrift Ports
sudo firewall-cmd --permanent --add-port=4100/tcp
sudo firewall-cmd --permanent --add-port=4200/tcp
sudo firewall-cmd --permanent --add-port=4300/tcp
sudo firewall-cmd --permanent --add-port=4400/tcp


sudo firewall-cmd --permanent --add-port=9763/tcp
sudo firewall-cmd --permanent --add-port=10389/tcp
sudo firewall-cmd --permanent --add-port=8000/tcp
sudo firewall-cmd --permanent --add-port=11111/tcp
sudo firewall-cmd --permanent --add-port=9999/tcp
sudo firewall-cmd --permanent --add-port=45564/tcp


sudo firewall-cmd --reload
#### END`

Now the nodes doesn't show the problem anymore.
