### ISSUE TITLE
BPMN Rest task throws Class cast exception upon an error response

### ISSUE THREAD

**Issue by vinok88** [wso2/product-ei#2199]
**Description:**
Upon an error response from the backend when invoked from the rest task when the response content is not xml or json, following exception is thrown.

`java.lang.ClassCastException: java.lang.String cannot be cast to org.wso2.carbon.bpmn.core.types.datatypes.xml.api.XMLDocument
	at org.wso2.carbon.bpmn.extensions.rest.RESTTask.execute(RESTTask.java:254)
	at org.activiti.engine.impl.delegate.JavaDelegateInvocation.invoke(JavaDelegateInvocation.java:34)
	at org.activiti.engine.impl.delegate.DelegateInvocation.proceed(DelegateInvocation.java:37)
	at org.activiti.engine.impl.delegate.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:25)
	at org.activiti.engine.impl.bpmn.behavior.ServiceTaskJavaDelegateActivityBehavior.execute(ServiceTaskJavaDelegateActivityBehavior.java:51)
	at org.activiti.engine.impl.bpmn.behavior.ServiceTaskJavaDelegateActivityBehavior.execute(ServiceTaskJavaDelegateActivityBehavior.java:40)
	at org.activiti.engine.impl.bpmn.helper.ClassDelegate.execute(ClassDelegate.java:158)
	at org.activiti.engine.impl.pvm.runtime.AtomicOperationActivityExecute.execute(AtomicOperationActivityExecute.java:60)
	at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:644)`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by vinok88** [comment]
fixed in https://github.com/wso2/carbon-business-process/pull/528
