### ISSUE TITLE
[EI600 DSS] Unable to invoke the dss services deployed in the tenant domain

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#230]
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
EI 600 RC1
DB - mysql 5.6.31

**Steps**
1. Create a tenant domain
2. Deploy a dss service in tenant domain (ex: CSVSampleService, ExcelSampleService)
3. Invoke the service
4. Access the wsdl of the service

**Observation**
1. Following error observed when invoking the service

[2017-02-19 17:08:20,413] [EI-Core] ERROR - SourceHandler Unexpected I/O error: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:265)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:474)
	at org.apache.http.impl.nio.reactor.SessionOutputBufferImpl.flush(SessionOutputBufferImpl.java:167)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.produceOutput(DefaultNHttpServerConnection.java:319)
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.produceOutput(LoggingNHttpServerConnection.java:127)
	at org.apache.synapse.transport.passthru.ServerIODispatch.onOutputReady(ServerIODispatch.java:87)
	at org.apache.synapse.transport.passthru.ServerIODispatch.onOutputReady(ServerIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:143)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:180)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:342)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:745)

2. Following error when accessing the wsdl and tryit tool

[2017-02-19 17:08:42,888] [EI-Core] ERROR - NativeWorkerPool Uncaught exception
java.lang.RuntimeException: Error while getting tenant activation status.
	at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.getTenantConfigurationContext(TenantAxisUtils.java:126)
	at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.getTenantAxisConfiguration(TenantAxisUtils.java:104)
	at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.getAxisService(TenantAxisUtils.java:208)
	at org.wso2.carbon.mediation.transport.handlers.PassThroughNHttpGetProcessor.process(PassThroughNHttpGetProcessor.java:311)
	at org.apache.synapse.transport.passthru.ServerWorker.processHttpRequestUri(ServerWorker.java:696)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:138)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Tenant domain has not been set in CarbonContext
	at org.wso2.carbon.caching.impl.CacheManagerFactoryImpl.getCacheManager(CacheManagerFactoryImpl.java:79)
	at org.wso2.carbon.user.core.tenant.TenantCache.getTenantCache(TenantCache.java:38)
	at org.wso2.carbon.user.core.tenant.TenantCache.getValueFromCache(TenantCache.java:73)
	at org.wso2.carbon.user.core.tenant.JDBCTenantManager.getTenant(JDBCTenantManager.java:295)
	at org.wso2.carbon.user.core.tenant.JDBCTenantManager.isTenantActive(JDBCTenantManager.java:600)
	at org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils.getTenantConfigurationContext(TenantAxisUtils.java:123)
	... 9 more

**Comment by sashikamw** [comment]
The issue with tenant dss service invocation solved with the fix given in 20/02/2017 latest build pack. However unable to access the WSDL or tryit tool due to above-mentioned error.
