### ISSUE TITLE
Exception occurred while testing Dual Channel scenario

### ISSUE THREAD

**Issue by a5anka** [wso2/product-ei#2333]
**Description:**

Following exception was observered in the integrator node when the dual channel scenario was tested.

```
[2018-06-14 19:17:25,185] [EI-Core] ERROR - JMSSender Did not receive a JMS response within 30000 ms to destination : direct://amq.direct/TempQueue668539b0-7aa3-464b-9252-0182fc5771a5/TempQueue668539b0-7aa3-464b-9252-0182fc5771a5?routingkey='TempQueue668539b0-7aa3-464b-9252-0182fc5771a5'&exclusive='true'&autodelete='true' with JMS correlation ID : ID:e5b0933a-8cf4-3ee5-84f6-bd76c2c12a75
[2018-06-14 19:17:25,313] [EI-Core] ERROR - Axis2Sender Connection:Keep-Alive,Content-Type:text/xml; charset=UTF-8,Date:Thu, 14 Jun 2018 13:45:10 GMT,Transfer-Encoding:chunked, Unexpected error sending message back
org.apache.axis2.AxisFault: Did not receive a JMS response within 30000 ms to destination : direct://amq.direct/TempQueue668539b0-7aa3-464b-9252-0182fc5771a5/TempQueue668539b0-7aa3-464b-9252-0182fc5771a5?routingkey='TempQueue668539b0-7aa3-464b-9252-0182fc5771a5'&exclusive='true'&autodelete='true' with JMS correlation ID : ID:e5b0933a-8cf4-3ee5-84f6-bd76c2c12a75
	at org.apache.axis2.transport.base.AbstractTransportSender.handleException(AbstractTransportSender.java:234)
	at org.apache.axis2.transport.jms.JMSSender.waitForResponseAndProcess(JMSSender.java:434)
	at org.apache.axis2.transport.jms.JMSSender.sendOverJMS(JMSSender.java:368)
	at org.apache.axis2.transport.jms.JMSSender.sendMessage(JMSSender.java:192)
	at org.apache.axis2.transport.base.AbstractTransportSender.invoke(AbstractTransportSender.java:119)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:217)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:530)
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:120)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:336)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:570)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:193)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:263)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### Affected Product Version
wso2ei-6.3.0-rc1

### Steps to reproduce
Follow the instructions in https://docs.wso2.com/display/EI620/JMS+Synchronous+Invocations+%3A+Dual+Channel+HTTP-to-JMS

### Related Issues
https://github.com/wso2/product-ei/issues/1036

**Comment by Sewmi** [comment]
The same issue can be seen with wso2ei-6.1.1 as well.

Furthermore, When the above error is observed in the Integrator console, log similar to below was observed in the wso2 message broker side

[2018-07-19 10:21:03,150] [EI-Broker]  INFO {org.wso2.andes.server.handler.ChannelCloseHandler} -  Received channel close for id 1 citing class 0 and method 0
[2018-07-19 10:21:03,150] [EI-Broker]  INFO {org.wso2.andes.server.AMQChannel} -  Unsubscribing all consumers on channel [/127.0.0.1:50289(admin):1]
[2018-07-19 10:21:03,151] [EI-Broker]  INFO {org.wso2.andes.server.AMQChannel} -  Unsubscribing consumer '1' on channel [/127.0.0.1:50289(admin):1]
[2018-07-19 10:21:03,152] [EI-Broker]  INFO {org.wso2.andes.kernel.subscription.StorageQueue} -  Purging messages of queue tempqueue262f02dd-a3ba-4052-8324-18f908cb6500
[2018-07-19 10:21:03,153] [EI-Broker]  INFO {org.wso2.andes.kernel.AndesContextInformationManager} -  Queue Deleted: tempqueue262f02dd-a3ba-4052-8324-18f908cb6500
[2018-07-19 10:21:03,153] [EI-Broker]  INFO {org.wso2.andes.kernel.subscription.AndesSubscriptionManager} -  Remove Local Subscription AMQP subscriptionId=b7f1e637-28c9-4364-8fa2-3ba80486e1e9,storageQueue=tempqueue262f02dd-a3ba-4052-8324-18f908cb6500,protocolType=AMQP,isActive=true,connection= [ connectedIP=/127.0.0.1:50289/1,connectedNode=NODE:Sewminis-MacBook-Pro-2.local/10.100.5.3,protocolChannelID=091b2d11-a999-4b3c-adbc-159753ecf5c3 ]
[2018-07-19 10:21:03,157] [EI-Broker]  INFO {org.wso2.andes.kernel.FlowControlManager} -  Channel removed (ID: 127.0.0.1:50289)

**Comment by a5anka** [comment]
@stelapo According to our analysis, this is a regression issue from the fix done in https://github.com/wso2/wso2-axis2/pull/127/files. We need to properly fix this.

**Comment by stelapo** [comment]
@a5anka thank you for the information
