### ISSUE TITLE
Staging build for WUM-4.9.0 fails consistently for 2 test cases

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/product-ei#2370]
**Description:**
IterateSequentialPropertySavingTestCase.testSavingSequentialTrueProperty and EditPassThroughProxyServiceTestCase.editProxyService fail with the following stacktrace.

org.apache.axis2.AxisFault: org.apache.axis2.databinding.ADBException: Unexpected subelement {http://proxyadmin.carbon.wso2.org/xsd}preservePolicy
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.wso2.carbon.proxyadmin.stub.ProxyServiceAdminStub.fromOM(ProxyServiceAdminStub.java:6655)
	at org.wso2.carbon.proxyadmin.stub.ProxyServiceAdminStub.getProxy(ProxyServiceAdminStub.java:2382)
	at org.wso2.esb.integration.common.clients.proxy.admin.ProxyServiceAdminClient.getProxyDetails(ProxyServiceAdminClient.java:231)
	at org.wso2.carbon.esb.mediator.test.iterate.IterateSequentialPropertySavingTestCase.testSavingSequentialTrueProperty(IterateSequentialPropertySavingTestCase.java:52)
Caused by: java.lang.Exception: org.apache.axis2.databinding.ADBException: Unexpected subelement {http://proxyadmin.carbon.wso2.org/xsd}preservePolicy
	at org.wso2.carbon.proxyadmin.stub.types.carbon.ProxyData$Factory.parse(ProxyData.java:3456)
	at org.wso2.carbon.proxyadmin.stub.types.synapse.GetProxyResponse$Factory.parse(GetProxyResponse.java:417)
	at org.wso2.carbon.proxyadmin.stub.ProxyServiceAdminStub.fromOM(ProxyServiceAdminStub.java:6453)
	... 37 more
Caused by: org.apache.axis2.databinding.ADBException: Unexpected subelement {http://proxyadmin.carbon.wso2.org/xsd}preservePolicy
	at org.wso2.carbon.proxyadmin.stub.types.carbon.ProxyData$Factory.parse(ProxyData.java:3450)
	... 39 more

However, these 2 do not fail either locally or in the support release jenkins.

**Affected Product Version:**
WUM ESB 4.9.0

**Comment by prabushi** [comment]
Now, these two tests are failing in both UAT, Staging, and even locally. This is due to proxy admin stub with the fix, [1], is not available via WUM.

[1] -https://github.com/wso2/carbon-mediation/commit/0aef626bab50a806b6703496dd7a977fad811d9a#diff-41f2d05de3e87d0915e20d7c59492c8aR44
