### ISSUE TITLE
Product MB 3.1.0 MQTT test failures with NullPointerException

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2373]
**Description:**
Product MB 3.1.0 branch MQTT test failures due to the fix added at https://github.com/wso2/product-ei/issues/1845

Tests fails with the following error.
```
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-07-03 16:37:31,891] ERROR {org.wso2.andes.kernel.disruptor.LogExceptionHandler} -  [ Sequence: 391 ] Exception occurred while processing inbound events.
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - java.lang.NullPointerException
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.andes.kernel.AndesSubscriptionManager.addSubscription(AndesSubscriptionManager.java:186)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.andes.kernel.disruptor.inbound.InboundSubscriptionEvent.handleOpenSubscriptionEvent(InboundSubscriptionEvent.java:126)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.andes.kernel.disruptor.inbound.InboundSubscriptionEvent.updateState(InboundSubscriptionEvent.java:97)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.andes.kernel.disruptor.inbound.InboundEventContainer.updateState(InboundEventContainer.java:190)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:71)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:40)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.lang.Thread.run(Thread.java:748)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
MB 3.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Fixed for support MB 3.1.0 branch.
