### ISSUE TITLE
NullPointerException while executing SlotTimeoutTask

### ISSUE THREAD

**Issue by Asitha** [wso2/product-ei#2404]
**Description:**

Following error occurs intermittently when trying to start the server. Once the issue occur server needs to be restarted 

It seems like there is a race condition when initializing the `slotCoordinator` variable within `SlotMessageCounter`. There is a possibility that the Slot Coordinator is not initialized when the slot coordinator is assigned to the `SlotMessageCounter`, hence the NPE issue [1].

We might need to patch this soon since this error is not recoverable and the server needs to be restarted until this race condition is not hit.

There are two options as far as I understood to fix this. 
1. One would be to use a double checked locking for the getInstance method and get rid of the static slotMessageCounter variable.
2. Another would be to initialize the slotMessageCounter variable through a different method which will be called after the SlotCooridnator is initialized.

I prefer 1st method. Do we have any other option to fix this? WDYT?
```
TID: [-1] [] [2018-07-11 11:35:35,896] ERROR {org.wso2.andes.kernel.slot.SlotMessageCounter} -  Error occurred while executing SlotTimeoutTask {org.wso2.andes.kernel.slot.SlotMessageCounter}
java.lang.NullPointerException
        at org.wso2.andes.kernel.slot.SlotMessageCounter.submitCurrentSafeZone(SlotMessageCounter.java:153)
        at org.wso2.andes.kernel.slot.SlotMessageCounter.access$700(SlotMessageCounter.java:51)
        at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.updateCoordinatorWithCurrentSafezone(SlotMessageCounter.java:380)
        at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.run(SlotMessageCounter.java:326)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
[1] https://github.com/wso2-support/andes/blob/support-3.2.19/modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java#L99

**Comment by Nirothipan** [comment]
Fix https://github.com/wso2/andes/pull/989
