### ISSUE TITLE
[Tooling] java.lang.NullPointerException on diagram redraw

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#2528]
**Description:**
check with this Synapse-config : https://docs.wso2.com/display/EI630/Exposing+Several+Services+as+a+Single+Service

```xml
<?xml version="1.0" encoding="UTF-8"?>
<api context="/healthcare" name="HealthcareAPI" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="GET" uri-template="/querydoctor/{category}">
        <inSequence>
            <log description="Request Log" level="custom">
                <property name="message" value="&quot;Welcome to Healthcare&quot;"/>
            </log>
            <send>
                <endpoint key="QueryDoctorEP"/>
            </send>
        </inSequence>
        <outSequence>
            <send/>
        </outSequence>
        <faultSequence/>
    </resource>
    <resource methods="POST" uri-template="/categories/{category}/reserve">
        <inSequence>
            <property description="Get Hospital" expression="json-eval($.hospital)" name="Hospital" scope="default" type="STRING"/>
            <property description="Get Card Number" expression="json-eval($.cardNo)" name="card_number" scope="default" type="STRING"/>
            <datamapper config="gov:datamapper/RequestMapping.dmc" inputSchema="gov:datamapper/RequestMapping_inputSchema.json" inputType="JSON" outputSchema="gov:datamapper/RequestMapping_outputSchema.json" outputType="JSON"/>
            <switch source="get-property('Hospital')">
                <case regex="grand oak community hospital">
                    <log description="Grand Oak Log" level="custom">
                        <property expression="fn:concat('Routing to ', get-property('Hospital'))" name="message"/>
                    </log>
                    <property description="Set Hospital VARIABLE" name="uri.var.hospital" scope="default" type="STRING" value="grandoaks"/>
                    <call>
                        <endpoint key="GrandOakEP"/>
                    </call>
                </case>
                <case regex="clemency medical center">
                    <log description="Clemency Log" level="custom">
                        <property expression="fn:concat('Routing to ', get-property('Hospital'))" name="message"/>
                    </log>
                    <property description="Set Hospital Varible" name="uri.var.hospital" scope="default" type="STRING" value="clemency"/>
                    <call>
                        <endpoint key="ClemencyEP"/>
                    </call>
                </case>
                <case regex="pine valley community hospital">
                    <log description="" level="custom">
                        <property expression="fn:concat('Routing to ', get-property('Hospital'))" name="message"/>
                    </log>
                    <property description="Set Hospital Variable" name="uri.var.hospital" scope="default" type="STRING" value="pinevalley"/>
                    <call>
                        <endpoint key="PineValleyEP"/>
                    </call>
                </case>
                <default>
                    <log description="Fault Log" level="custom">
                        <property expression="fn:concat('Invalid hospital - ', get-property('Hospital'))" name="message"/>
                    </log>
                    <respond/>
                </default>
            </switch>
            <property description="Get Appointment NUmber" expression="json-eval($.appointmentNumber)" name="uri.var.appointment_id " scope="default" type="STRING"/>
            <property description="Get Doctor Details" expression="/default/expression" name="doctor_details" scope="default" type="STRING"/>
            <property description="Get Patient Details" expression="json-eval($.patient)" name="patient_details" scope="default" type="STRING"/>
            <call>
                <endpoint key="ChannelingFeeEP"/>
            </call>
            <property description="Get Actual Fee" expression="json-eval($.actualFee)" name="actual_fee" scope="default" type="STRING"/>
            <payloadFactory description="Payload" media-type="json">
                <format>{
"appointmentNumber":$1,
"doctor":$2,
"patient":$3,
"fee":$4,
"confirmed":"false",
"card_number":"$5"
}</format>
                <args>
                    <arg evaluator="xml" expression="$ctx:uri.var.appointment_id"/>
                    <arg evaluator="xml" expression="$ctx:doctor_details"/>
                    <arg evaluator="xml" expression="$ctx:patient_details"/>
                    <arg evaluator="xml" expression="$ctx:actual_fee"/>
                    <arg evaluator="xml" expression="$ctx:card_number"/>
                </args>
            </payloadFactory>
            <call>
                <endpoint key="SettlePaymentEP"/>
            </call>
            <respond/>
        </inSequence>
        <outSequence>
            <send/>
        </outSequence>
        <faultSequence/>
    </resource>
</api>
```

Just Try to open the API
===================
ERROR
====================
java.lang.NullPointerException
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.custom.connections.ConnectionCalculator.getNearestLinkEditPart(ConnectionCalculator.java:47)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.custom.AbstractMediator.connectToMostSuitableElement(AbstractMediator.java:529)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.edit.parts.LogMediatorEditPart.access$1(LogMediatorEditPart.java:1)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.edit.parts.LogMediatorEditPart$2.setBounds(LogMediatorEditPart.java:135)
	at org.eclipse.draw2d.ToolbarLayout.layout(ToolbarLayout.java:385)
	at org.eclipse.draw2d.Figure.layout(Figure.java:1096)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1899)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1901)
	at org.eclipse.gmf.runtime.diagram.ui.figures.BorderedNodeFigure.validate(BorderedNodeFigure.java:262)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1901)
	at org.eclipse.gmf.runtime.diagram.ui.figures.BorderItemsAwareFreeFormLayer.validate(BorderItemsAwareFreeFormLayer.java:183)
	at org.eclipse.draw2d.FreeformViewport$FreeformViewportLayout.calculatePreferredSize(FreeformViewport.java:25)
	at org.eclipse.draw2d.AbstractLayout.getPreferredSize(AbstractLayout.java:110)
	at org.eclipse.draw2d.AbstractHintLayout.getPreferredSize(AbstractHintLayout.java:90)
	at org.eclipse.draw2d.Figure.getPreferredSize(Figure.java:810)
	at org.eclipse.gmf.runtime.draw2d.ui.internal.figures.OverlayScrollPaneLayout.calculatePreferredSize(OverlayScrollPaneLayout.java:45)
	at org.eclipse.draw2d.AbstractLayout.getPreferredSize(AbstractLayout.java:110)
	at org.eclipse.draw2d.AbstractHintLayout.getPreferredSize(AbstractHintLayout.java:90)
	at org.eclipse.draw2d.Figure.getPreferredSize(Figure.java:810)
	at org.eclipse.gmf.runtime.draw2d.ui.internal.figures.AnimatableScrollPane.getPreferredSize(AnimatableScrollPane.java:106)
	at org.eclipse.gmf.runtime.draw2d.ui.figures.ConstrainedToolbarLayout.calculateChildrenSize(ConstrainedToolbarLayout.java:388)
	at org.eclipse.gmf.runtime.draw2d.ui.figures.ConstrainedToolbarLayout.calculatePreferredSize(ConstrainedToolbarLayout.java:96)
	at org.eclipse.draw2d.AbstractLayout.getPreferredSize(AbstractLayout.java:110)
	at org.eclipse.draw2d.AbstractHintLayout.getPreferredSize(AbstractHintLayout.java:90)
	at org.eclipse.draw2d.Figure.getPreferredSize(Figure.java:810)
	at org.eclipse.gmf.runtime.diagram.ui.figures.ResizableCompartmentFigure.getPreferredSize(ResizableCompartmentFigure.java:368)
	at org.eclipse.gmf.runtime.diagram.ui.figures.BorderedNodeFigure.getPreferredSize(BorderedNodeFigure.java:182)
	at org.eclipse.draw2d.GridData.computeSize(GridData.java:393)
	at org.eclipse.draw2d.GridLayout.layout(GridLayout.java:245)
	at org.eclipse.draw2d.GridLayout.calculatePreferredSize(GridLayout.java:202)
	at org.eclipse.draw2d.AbstractLayout.getPreferredSize(AbstractLayout.java:110)
	at org.eclipse.draw2d.AbstractHintLayout.getPreferredSize(AbstractHintLayout.java:90)
	at org.eclipse.draw2d.AbstractHintLayout.calculateMinimumSize(AbstractHintLayout.java:56)
	at org.eclipse.draw2d.AbstractHintLayout.getMinimumSize(AbstractHintLayout.java:73)
	at org.eclipse.draw2d.Figure.getMinimumSize(Figure.java:782)
	at org.eclipse.draw2d.StackLayout.calculateMinimumSize(StackLayout.java:44)
	at org.eclipse.draw2d.AbstractHintLayout.getMinimumSize(AbstractHintLayout.java:73)
	at org.eclipse.draw2d.Figure.getMinimumSize(Figure.java:782)
	at org.eclipse.draw2d.ToolbarLayout.getChildMinimumSize(ToolbarLayout.java:210)
	at org.eclipse.draw2d.ToolbarLayout.calculateChildrenSize(ToolbarLayout.java:94)
	at org.eclipse.draw2d.ToolbarLayout.calculateMinimumSize(ToolbarLayout.java:134)
	at org.eclipse.draw2d.AbstractHintLayout.getMinimumSize(AbstractHintLayout.java:73)
	at org.eclipse.draw2d.Figure.getMinimumSize(Figure.java:782)
	at org.eclipse.draw2d.StackLayout.calculateMinimumSize(StackLayout.java:44)
	at org.eclipse.draw2d.AbstractHintLayout.getMinimumSize(AbstractHintLayout.java:73)
	at org.eclipse.draw2d.Figure.getMinimumSize(Figure.java:782)
	at org.eclipse.draw2d.ToolbarLayout.getChildMinimumSize(ToolbarLayout.java:210)
	at org.eclipse.draw2d.ToolbarLayout.calculateChildrenSize(ToolbarLayout.java:94)
	at org.eclipse.draw2d.ToolbarLayout.calculateMinimumSize(ToolbarLayout.java:134)
	at org.eclipse.draw2d.AbstractHintLayout.getMinimumSize(AbstractHintLayout.java:73)
	at org.eclipse.draw2d.Figure.getMinimumSize(Figure.java:782)
	at org.eclipse.draw2d.StackLayout.calculateMinimumSize(StackLayout.java:44)
	at org.eclipse.draw2d.AbstractHintLayout.getMinimumSize(AbstractHintLayout.java:73)
	at org.eclipse.draw2d.Figure.getMinimumSize(Figure.java:782)
	at org.eclipse.draw2d.ToolbarLayout.getChildMinimumSize(ToolbarLayout.java:210)
	at org.eclipse.draw2d.ToolbarLayout.calculateChildrenSize(ToolbarLayout.java:94)
	at org.eclipse.draw2d.ToolbarLayout.calculateMinimumSize(ToolbarLayout.java:134)
	at org.eclipse.draw2d.AbstractHintLayout.getMinimumSize(AbstractHintLayout.java:73)
	at org.eclipse.draw2d.Figure.getMinimumSize(Figure.java:782)
	at org.eclipse.draw2d.StackLayout.calculateMinimumSize(StackLayout.java:44)
	at org.eclipse.draw2d.AbstractHintLayout.getMinimumSize(AbstractHintLayout.java:73)
	at org.eclipse.draw2d.Figure.getMinimumSize(Figure.java:782)
	at org.eclipse.gmf.runtime.diagram.ui.figures.BorderedNodeFigure.getMinimumSize(BorderedNodeFigure.java:178)
	at org.eclipse.gmf.runtime.diagram.ui.layout.FreeFormLayoutEx.layout(FreeFormLayoutEx.java:51)
	at org.eclipse.draw2d.Figure$LayoutNotifier.layout(Figure.java:1979)
	at org.eclipse.draw2d.Figure.layout(Figure.java:1096)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1899)
	at org.eclipse.gmf.runtime.diagram.ui.figures.BorderItemsAwareFreeFormLayer.validate(BorderItemsAwareFreeFormLayer.java:183)
	at org.eclipse.draw2d.FreeformViewport$FreeformViewportLayout.calculatePreferredSize(FreeformViewport.java:25)
	at org.eclipse.draw2d.AbstractLayout.getPreferredSize(AbstractLayout.java:110)
	at org.eclipse.draw2d.AbstractHintLayout.getPreferredSize(AbstractHintLayout.java:90)
	at org.eclipse.draw2d.Figure.getPreferredSize(Figure.java:810)
	at org.eclipse.gmf.runtime.draw2d.ui.internal.figures.OverlayScrollPaneLayout.calculatePreferredSize(OverlayScrollPaneLayout.java:45)
	at org.eclipse.draw2d.AbstractLayout.getPreferredSize(AbstractLayout.java:110)
	at org.eclipse.draw2d.AbstractHintLayout.getPreferredSize(AbstractHintLayout.java:90)
	at org.eclipse.draw2d.Figure.getPreferredSize(Figure.java:810)
	at org.eclipse.gmf.runtime.draw2d.ui.internal.figures.AnimatableScrollPane.getPreferredSize(AnimatableScrollPane.java:106)
	at org.eclipse.gmf.runtime.draw2d.ui.figures.ConstrainedToolbarLayout.calculateChildrenSize(ConstrainedToolbarLayout.java:388)
	at org.eclipse.gmf.runtime.draw2d.ui.figures.ConstrainedToolbarLayout.calculatePreferredSize(ConstrainedToolbarLayout.java:96)
	at org.eclipse.draw2d.AbstractLayout.getPreferredSize(AbstractLayout.java:110)
	at org.eclipse.draw2d.AbstractHintLayout.getPreferredSize(AbstractHintLayout.java:90)
	at org.eclipse.draw2d.Figure.getPreferredSize(Figure.java:810)
	at org.eclipse.gmf.runtime.diagram.ui.figures.ResizableCompartmentFigure.getPreferredSize(ResizableCompartmentFigure.java:368)
	at org.eclipse.gmf.runtime.draw2d.ui.figures.ConstrainedToolbarLayout.layout(ConstrainedToolbarLayout.java:203)
	at org.eclipse.draw2d.Figure.layout(Figure.java:1096)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1899)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1901)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1901)
	at org.eclipse.gmf.runtime.diagram.ui.figures.BorderItemsAwareFreeFormLayer.validate(BorderItemsAwareFreeFormLayer.java:183)
	at org.eclipse.draw2d.FreeformViewport$FreeformViewportLayout.calculatePreferredSize(FreeformViewport.java:25)
	at org.eclipse.draw2d.AbstractLayout.getPreferredSize(AbstractLayout.java:110)
	at org.eclipse.draw2d.AbstractHintLayout.getPreferredSize(AbstractHintLayout.java:90)
	at org.eclipse.draw2d.Figure.getPreferredSize(Figure.java:810)
	at org.eclipse.gmf.runtime.draw2d.ui.internal.figures.OverlayScrollPaneLayout.calculatePreferredSize(OverlayScrollPaneLayout.java:45)
	at org.eclipse.draw2d.AbstractLayout.getPreferredSize(AbstractLayout.java:110)
	at org.eclipse.draw2d.AbstractHintLayout.getPreferredSize(AbstractHintLayout.java:90)
	at org.eclipse.draw2d.Figure.getPreferredSize(Figure.java:810)
	at org.eclipse.gmf.runtime.draw2d.ui.internal.figures.AnimatableScrollPane.getPreferredSize(AnimatableScrollPane.java:106)
	at org.eclipse.gmf.runtime.draw2d.ui.figures.ConstrainedToolbarLayout.calculateChildrenSize(ConstrainedToolbarLayout.java:388)
	at org.eclipse.gmf.runtime.draw2d.ui.figures.ConstrainedToolbarLayout.calculatePreferredSize(ConstrainedToolbarLayout.java:96)
	at org.eclipse.draw2d.AbstractLayout.getPreferredSize(AbstractLayout.java:110)
	at org.eclipse.draw2d.AbstractHintLayout.getPreferredSize(AbstractHintLayout.java:90)
	at org.eclipse.draw2d.Figure.getPreferredSize(Figure.java:810)
	at org.eclipse.gmf.runtime.diagram.ui.figures.ResizableCompartmentFigure.getPreferredSize(ResizableCompartmentFigure.java:368)
	at org.eclipse.draw2d.GridData.computeSize(GridData.java:393)
	at org.eclipse.draw2d.GridLayout.layout(GridLayout.java:245)
	at org.eclipse.draw2d.GridLayout.calculatePreferredSize(GridLayout.java:202)
	at org.eclipse.draw2d.AbstractLayout.getPreferredSize(AbstractLayout.java:110)
	at org.eclipse.draw2d.AbstractHintLayout.getPreferredSize(AbstractHintLayout.java:90)
	at org.eclipse.draw2d.AbstractHintLayout.calculateMinimumSize(AbstractHintLayout.java:56)
	at org.eclipse.draw2d.AbstractHintLayout.getMinimumSize(AbstractHintLayout.java:73)
	at org.eclipse.draw2d.Figure.getMinimumSize(Figure.java:782)
	at org.eclipse.draw2d.StackLayout.calculateMinimumSize(StackLayout.java:44)
	at org.eclipse.draw2d.AbstractHintLayout.getMinimumSize(AbstractHintLayout.java:73)
	at org.eclipse.draw2d.Figure.getMinimumSize(Figure.java:782)
	at org.eclipse.gmf.runtime.diagram.ui.figures.BorderedNodeFigure.getMinimumSize(BorderedNodeFigure.java:178)
	at org.eclipse.gmf.runtime.diagram.ui.layout.FreeFormLayoutEx.layout(FreeFormLayoutEx.java:51)
	at org.eclipse.draw2d.Figure$LayoutNotifier.layout(Figure.java:1979)
	at org.eclipse.draw2d.Figure.layout(Figure.java:1096)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1899)
	at org.eclipse.gmf.runtime.diagram.ui.figures.BorderItemsAwareFreeFormLayer.validate(BorderItemsAwareFreeFormLayer.java:183)
	at org.eclipse.gmf.runtime.diagram.ui.editparts.DiagramEditPart$1.validate(DiagramEditPart.java:157)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1901)
	at org.eclipse.gmf.runtime.diagram.ui.figures.BorderItemsAwareFreeFormLayer.validate(BorderItemsAwareFreeFormLayer.java:183)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1901)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1901)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1901)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1901)
	at org.eclipse.draw2d.Viewport.validate(Viewport.java:380)
	at org.eclipse.gmf.runtime.diagram.ui.parts.DiagramEditor.initializeContents(DiagramEditor.java:1373)
	at org.eclipse.gmf.runtime.diagram.ui.parts.DiagramEditor.initializeGraphicalViewerContents(DiagramEditor.java:873)
	at org.eclipse.gmf.runtime.diagram.ui.parts.DiagramEditor.initializeGraphicalViewer(DiagramEditor.java:865)
	at org.eclipse.gmf.runtime.diagram.ui.parts.DiagramEditorWithFlyOutPalette.initializeGraphicalViewer(DiagramEditorWithFlyOutPalette.java:116)
	at org.eclipse.gmf.runtime.diagram.ui.resources.editor.parts.DiagramDocumentEditor.initializeGraphicalViewer(DiagramDocumentEditor.java:174)
	at org.eclipse.gmf.runtime.diagram.ui.parts.DiagramEditor.createGraphicalViewer(DiagramEditor.java:807)
	at org.eclipse.gef.ui.parts.GraphicalEditor.createPartControl(GraphicalEditor.java:171)
	at org.eclipse.gmf.runtime.diagram.ui.parts.DiagramEditor.createPartControl(DiagramEditor.java:1580)
	at org.eclipse.gmf.runtime.diagram.ui.parts.DiagramEditorWithFlyOutPalette.createPartControl(DiagramEditorWithFlyOutPalette.java:328)
	at org.eclipse.gmf.runtime.diagram.ui.resources.editor.parts.DiagramDocumentEditor.createPartControl(DiagramDocumentEditor.java:1514)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:241)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.part.EsbMultiPageEditor.createPage0(EsbMultiPageEditor.java:287)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.part.EsbMultiPageEditor.createPages(EsbMultiPageEditor.java:606)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:348)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:151)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:99)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:355)
	at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:990)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:955)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:105)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:74)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:56)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:992)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:661)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:767)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:738)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:732)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:716)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1293)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.lambda$0(LazyStackRenderer.java:68)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4871)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:173)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:620)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:584)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:769)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:401)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1188)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3261)
	at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3176)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3158)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3153)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3117)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3107)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:563)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:518)
	at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:360)
	at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:167)
	at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:279)
	at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:244)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:271)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:249)
	at org.eclipse.jdt.internal.ui.navigator.OpenAndExpand.run(OpenAndExpand.java:50)
	at org.eclipse.ui.actions.RetargetAction.run(RetargetAction.java:216)
	at org.eclipse.ui.navigator.CommonNavigatorManager$2.open(CommonNavigatorManager.java:191)
	at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:46)
	at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:851)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:848)
	at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1163)
	at org.eclipse.ui.navigator.CommonViewer.handleOpen(CommonViewer.java:451)
	at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:273)
	at org.eclipse.jface.util.OpenStrategy.access$2(OpenStrategy.java:268)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:308)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4082)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3699)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Suggested Labels:**
tooling

**Suggested Assignees:**

**Affected Product Version:**
6.3.0

**OS, DB, other environment details and versions:**    
MacOs HighS

**Steps to reproduce:**

**Comment by Shakila** [comment]
I tried to reproduce this on same MacOs High Sierra but couldn't achieve it. These are the steps that I did for reproducing the issue.

1. Created the API by importing the artifact.
2. Opened the API
3. Clicked the source view and again changed to design view.
Then created an API and changed the config from the source view and did 2 & 3.

**Comment by rosensilva** [comment]
The following JSONPATH causes this error
            <property description="Get Actual Fee" expression="json-eval($.actualFee)" name="actual_fee" scope="default" type="STRING"/>

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-platform/pull/142
