### ISSUE TITLE
NullPointerException when creating the proxy service in Developer Studio

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2552]
**Description:**
Getting the following error when creating the proxy service with the latest fixes.

```
java.lang.NullPointerException
	at org.wso2.developerstudio.eclipse.project.extensions.templates.ArtifactTemplate.getTemplateDataStream(ArtifactTemplate.java:75)
	at org.wso2.developerstudio.eclipse.artifact.proxyservice.ui.wizard.ProxyServiceProjectCreationWizard.performFinish(ProxyServiceProjectCreationWizard.java:126)
```
**Suggested Labels:**

**Suggested Assignees:**
rosens@wso2.com

**Affected Product Version:**
6.4.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-platform/pull/65
