### ISSUE TITLE
Class cast exception happens when RabbitMQ message contains boolean / numeric and list type headers

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#2585]
**Description:**
When EI proxy is using as a listener proxy to a RabbitMQ queue, it gives a Class cast exception when the message contains not String headers (Ex:- Numeric, Boolean, List). 
`java.lang.ClassCastException: java.lang.String cannot be cast to com.rabbitmq.client.LongString
at org.apache.axis2.transport.rabbitmq.utils.RabbitMQUtils.getTransportHeaders(RabbitMQUtils.java:126)
at org.apache.axis2.transport.rabbitmq.RabbitMQMessageReceiver.processThroughAxisEngine(RabbitMQMessageReceiver.java:112)
at org.apache.axis2.transport.rabbitmq.RabbitMQMessageReceiver.onMessage(RabbitMQMessageReceiver.java:61)
at org.apache.axis2.transport.rabbitmq.ServiceTaskManager$MessageListenerTask.startConsumer(ServiceTaskManager.java:608)
at org.apache.axis2.transport.rabbitmq.ServiceTaskManager$MessageListenerTask.run(ServiceTaskManager.java:336)
at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)`

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
EI 6.1.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Create a JMS listener proxy pointing to RabbitMQ queue.
Publish a message with not string header

**Related Issues:**

**Comment by GDLMadushanka** [comment]
fixed

**Comment by dulanjalidilmi** [comment]
This should be fixed in ESB-5.0.0 as well
