### ISSUE TITLE
java.lang.RuntimeException: ContentID is null in Cache Mediator for application/octet-stream response

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#2601]
**Description:**
Due to a fix given for https://wso2.org/jira/browse/ESBJAVA-4318 there is a regression issue found, where for binary responses it gives following exception,

Caused by: java.lang.RuntimeException: ContentID is null
	at org.apache.axiom.om.impl.llom.OMTextImpl.getDataHandler(OMTextImpl.java:370)
	at org.wso2.carbon.relay.ExpandingMessageFormatter.findAndWrite2OutputStream(ExpandingMessageFormatter.java:182)
	at org.wso2.carbon.relay.ExpandingMessageFormatter.writeTo(ExpandingMessageFormatter.java:100)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:580)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:265)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
ESB-4.9.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2-support/carbon-mediation/pull/171

**Comment by Nirothipan** [comment]
Fixed in ESB 4.9.0 with https://github.com/wso2-support/carbon-mediation/pull/171.

The public commit is not needed as the implementation is different in the master branch.

**Comment by liyanamaisarah00** [comment]
hi, i also faced the same issue. may i know the solution. github link given cannot be accessed.
