### ISSUE TITLE
The datasources cannot be added from tooling

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#2629]
**Description:**
The datasources cannot be added via dev studio tooling.
When the dataservice added to use that datasource  as
<config id="default">
        <property name="carbon_datasource_name">mysql</property>
    </config>

It gives the following error,

[2018-09-10 11:14:29,268] [EI-Core] ERROR - DBDeployer The TestDataService-1.0.0.dbs service, which is not valid, caused {1}
DS Fault Message: The Carbon data source 'mysql' cannot be found
DS Code: UNKNOWN_ERROR
Source Data Service:-
Name: TestDataService
Location: /media/chanika/data/support/pinkroccade/wso2ei-6.1.1/wso2/tmp/carbonapps/-1234/1536558269263mysqlDataSourceCar_1.0.0.car/TestDataService_1.0.0/TestDataService-1.0.0.dbs
Description: 
Default Namespace: http://ws.wso2.org/dataservice

	at org.wso2.carbon.dataservices.core.description.config.ConfigFactory.getCarbonDataSourceConfig(ConfigFactory.java:169)
	at org.wso2.carbon.dataservices.core.description.config.ConfigFactory.createConfig(ConfigFactory.java:76)
	at org.wso2.carbon.dataservices.core.DataServiceFactory.createDataService(DataServiceFactory.java:159)
	at org.wso2.carbon.dataservices.core.DBDeployer.createDBService(DBDeployer.java:797)
	at org.wso2.carbon.dataservices.core.DBDeployer.processService(DBDeployer.java:1152)
	at org.wso2.carbon.dataservices.core.DBDeployer.deploy(DBDeployer.java:201)
	at org.wso2.carbon.application.deployer.handler.DefaultAppDeployer.deployRecursively(DefaultAppDeployer.java:173)
	at org.wso2.carbon.application.deployer.handler.DefaultAppDeployer.deployArtifacts(DefaultAppDeployer.java:69)
	at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:272)
	at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:72)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2018-09-10 11:14:29,272] [EI-Core] ERROR - ApplicationManager Error occurred while deploying Carbon Application
org.apache.axis2.deployment.DeploymentException: The TestDataService-1.0.0.dbs service, which is not valid, caused {1}
	at org.wso2.carbon.dataservices.core.DBDeployer.deploy(DBDeployer.java:249)
	at org.wso2.carbon.application.deployer.handler.DefaultAppDeployer.deployRecursively(DefaultAppDeployer.java:173)
	at org.wso2.carbon.application.deployer.handler.DefaultAppDeployer.deployArtifacts(DefaultAppDeployer.java:69)
	at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:272)
	at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:72)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: DS Fault Message: The Carbon data source 'mysql' cannot be found
DS Code: UNKNOWN_ERROR
Source Data Service:-
Name: TestDataService
Location: /media/chanika/data/support/pinkroccade/wso2ei-6.1.1/wso2/tmp/carbonapps/-1234/1536558269263mysqlDataSourceCar_1.0.0.car/TestDataService_1.0.0/TestDataService-1.0.0.dbs
Description: 
Default Namespace: http://ws.wso2.org/dataservice

	at org.wso2.carbon.dataservices.core.description.config.ConfigFactory.getCarbonDataSourceConfig(ConfigFactory.java:169)
	at org.wso2.carbon.dataservices.core.description.config.ConfigFactory.createConfig(ConfigFactory.java:76)
	at org.wso2.carbon.dataservices.core.DataServiceFactory.createDataService(DataServiceFactory.java:159)
	at org.wso2.carbon.dataservices.core.DBDeployer.createDBService(DBDeployer.java:797)
	at org.wso2.carbon.dataservices.core.DBDeployer.processService(DBDeployer.java:1152)
	at org.wso2.carbon.dataservices.core.DBDeployer.deploy(DBDeployer.java:201)
	... 21 more

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI6.3.0 tooling
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by indikasampath2000** [comment]
Fixed with https://github.com/wso2/product-ei/issues/2939
