### ISSUE TITLE
Message loss in multinode queue scenario

### ISSUE THREAD

**Issue by a5anka** [wso2/product-ei#2672]
### Description

When the testSingleQueueMultiNodeSendReceive(org.wso2.mb.platform.tests.clustering.QueueClusterTestCase) cluster test was run following errors were observed.

```
[2018-09-16 11:23:43,216] [EI-Broker] ERROR {org.wso2.andes.kernel.disruptor.delivery.ContentCacheCreator} -  message content not found for message ids : 63989670899892245,

[2018-09-16 11:23:43,224] [EI-Broker] ERROR {com.lmax.disruptor.IgnoreExceptionHandler} -  Exception processing: 3671 Message ID: 63989670899892245, Error occurred : true
org.wso2.andes.kernel.AndesException: Empty message received while retrieving message content for message id 63989670899892245
	at org.wso2.andes.kernel.disruptor.delivery.ContentDecompressionHandler.onEvent(ContentDecompressionHandler.java:118)
	at org.wso2.andes.kernel.disruptor.delivery.ContentDecompressionHandler.onEvent(ContentDecompressionHandler.java:37)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2018-09-16 11:23:43,609] [EI-Broker]  WARN {org.wso2.andes.kernel.disruptor.delivery.DeliveryEventHandler} -  Moving message to Dead Letter Channel Due to Send Error. Message ID 63989670899892245
```

### Affected Product Version

EI-6.4.0-m8

### Steps to reproduce

1. Create a 2 node message broker cluster.
2. Run  testSingleQueueMultiNodeSendReceive(org.wso2.mb.platform.tests.clustering.QueueClusterTestCase)  
cluster test. This will create a single consumer and producer to multiple nodes. The test failed due to messages not receiving.

**Comment by a5anka** [comment]
I'll post the results after running with [log4jdbc](http://movingaheadblog.blogspot.com/2016/07/how-to-use-log4jdbc-with-wso2-products_28.html).

**Comment by a5anka** [comment]
Following is the logs extracts related to a lost message.


#### Node 1
##### Trace logs
```
[2018-09-16 12:03:43,942] TRACE {org.wso2.andes.tools.utils.MessageTracer} -  Message { destination: clustersinglequeue3 , id: 63990300394651648 } mapped to andes message 
[2018-09-16 12:03:43,942] TRACE {org.wso2.andes.tools.utils.MessageTracer} -  Message { destination: clustersinglequeue3 , id: 63990300394651648 } messaging event submitted to inbound disruptor 
[2018-09-16 12:03:43,948] TRACE {org.wso2.andes.tools.utils.MessageTracer} -  Message { destination: clustersinglequeue3 , id: 63990300394651648 } content written to database 
[2018-09-16 12:03:43,949] TRACE {org.wso2.andes.tools.utils.MessageTracer} -  Message { destination: clustersinglequeue3 , id: 63990300394651648 } slot information updated 
```
#### Carbon logs
```
TID: [-1] [] [2018-09-16 12:03:43,944]  INFO {jdbc.sqlonly} -  batching 1 statements: 1: INSERT INTO MB_METADATA (MESSAGE_ID,QUEUE_ID,DLC_QUEUE_ID,MESSAGE_METADATA) 
VALUES ( 63990300394651648,2,-1,'<byte[]>' ) 
 
TID: [-1] [] [2018-09-16 12:03:43,945]  INFO {jdbc.sqlonly} -  batching 1 statements: 1: INSERT INTO MB_CONTENT(MESSAGE_ID,CONTENT_OFFSET,MESSAGE_CONTENT) 
VALUES (63990300394651648, 0, '<byte[]>') 
```

#### Node 2
##### Trace logs
```
[2018-09-16 12:03:45,235] TRACE {org.wso2.andes.tools.utils.MessageTracer} -  Message { destination: clustersinglequeue3 , id: 63990300394651648 , slotId: clustersinglequeue3|0-63990300641329155 } metadata read from database
[2018-09-16 12:03:45,348] TRACE {org.wso2.andes.tools.utils.MessageTracer} -  Message { destination: clustersinglequeue3 , id: 63990300394651648 } metadata buffered for delivery 
[2018-09-16 12:03:45,367] TRACE {org.wso2.andes.tools.utils.MessageTracer} -  Message { destination: clustersinglequeue3 , id: 63990300394651648 } submitted to outbound disruptor 
[2018-09-16 12:03:45,550] TRACE {org.wso2.andes.tools.utils.MessageTracer} -  Message { destination: clustersinglequeue3 , id: 63990300394651648 } content read from database 
[2018-09-16 12:03:45,737] TRACE {org.wso2.andes.tools.utils.MessageTracer} -  Message { destination: clustersinglequeue3 , id: 63990300394651648 } message moved to DLC 
```

#### Carbon logs
```
TID: [-1] [] [2018-09-16 12:03:45,524]  INFO {jdbc.sqlonly} -  SELECT MESSAGE_CONTENT, MESSAGE_ID, CONTENT_OFFSET FROM MB_CONTENT WHERE MESSAGE_ID IN (63990300439740418,63990300458876928,63990300433973248,63990300423487488,63990300406448128,63990300442099713,63990300420866048,63990300456255488,63990300436594688,63990300441837568,63990300435283968,63990300419555328,63990300428730368,63990300394651648,63990300431613953,63990300451274753,63990300431351808) 
TID: [-1] [] [2018-09-16 12:03:45,551] ERROR {org.wso2.andes.kernel.disruptor.delivery.ContentCacheCreator} -  message content not found for message ids : 63990300394651648, 
TID: [-1] [] [2018-09-16 12:03:45,626] ERROR {com.lmax.disruptor.IgnoreExceptionHandler} -  Exception processing: 1 Message ID: 63990300394651648, Error occurred : true 
org.wso2.andes.kernel.AndesException: Empty message received while retrieving message content for message id 63990300394651648
        at org.wso2.andes.kernel.disruptor.delivery.ContentDecompressionHandler.onEvent(ContentDecompressionHandler.java:118)
        at org.wso2.andes.kernel.disruptor.delivery.ContentDecompressionHandler.onEvent(ContentDecompressionHandler.java:37)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
TID: [-1] [] [2018-09-16 12:03:45,714]  WARN {org.wso2.andes.kernel.disruptor.delivery.DeliveryEventHandler} -  Moving message to Dead Letter Channel Due to Send Error. Message ID 63990300394651648 
TID: [-1] [] [2018-09-16 12:03:45,729]  INFO {jdbc.sqlonly} -  UPDATE MB_METADATA SET DLC_QUEUE_ID=1 WHERE MESSAGE_ID=63990300394651648 
TID: [-1] [] [2018-09-16 12:03:45,730]  INFO {jdbc.sqlonly} -  UPDATE MB_EXPIRATION_DATA SET DLC_QUEUE_ID=1 WHERE MESSAGE_ID=63990300394651648
```

**Comment by sdkottegoda** [comment]
Ran the following test with jmeter,
1. Connect queue consumer to node 1.
2. publish 1000 messages to the same queue to node2.

All messages were received without any problem.

But when I ran the aboove test, it failed.

**Comment by sdkottegoda** [comment]
The issue got resolved when the org.wso2.carbon.ndatasource jars were downgraded to the version 4.4.32. Looking at the git history we could find the following PR that could have an impact on the behaviour.  https://github.com/wso2/carbon-kernel/pull/1805

**Comment by mikroco** [comment]
I installed wso2iot-3.2.0 under centos 7
but when i run broker.sh,
I have the same error
sorry, help me
thanks!




[root@localhost bin]# ./broker.sh
JAVA_HOME environment variable is set to /usr/java/jdk1.8.0_201-amd64
CARBON_HOME environment variable is set to /home/wso2iot-3.2.0/wso2/broker
Using Java memory options: -Xms256m -Xmx1024m
[2019-07-02 16:41:33,981] [IoT-Broker]  WARN {org.apache.axiom.util.stax.dialect.                                                                                       StAXDialectDetector} -  Unable to determine dialect of the StAX implementation at                                                                                        bundleresource://13.fwk1715998167/
[2019-07-02 16:41:33,981] [IoT-Broker]  WARN {org.apache.axiom.util.stax.dialect.                                                                                       StAXDialectDetector} -  Unable to determine dialect of the StAX implementation at                                                                                        bundleresource://13.fwk1715998167/
 INFO {org.wso2.andes.wso2.internal.QpidBundleActivator} -  Setting BundleContext                                                                                        in PluginManager
[2019-07-02 16:41:34,827] [IoT-Broker]  INFO {org.wso2.carbon.core.internal.Carbo                                                                                       nCoreActivator} -  Starting WSO2 Carbon...
[2019-07-02 16:41:34,828] [IoT-Broker]  INFO {org.wso2.carbon.core.internal.Carbo                                                                                       nCoreActivator} -  Operating System : Linux 3.10.0-957.el7.x86_64, amd64
[2019-07-02 16:41:34,828] [IoT-Broker]  INFO {org.wso2.carbon.core.internal.Carbo                                                                                       nCoreActivator} -  Java Home        : /usr/java/jdk1.8.0_201-amd64/jre
[2019-07-02 16:41:34,828] [IoT-Broker]  INFO {org.wso2.carbon.core.internal.Carbo                                                                                       nCoreActivator} -  Java Version     : 1.8.0_201
[2019-07-02 16:41:34,829] [IoT-Broker]  INFO {org.wso2.carbon.core.internal.Carbo                                                                                       nCoreActivator} -  Java VM          : Java HotSpot(TM) 64-Bit Server VM 25.201-b0                                                                                       9,Oracle Corporation
[2019-07-02 16:41:34,829] [IoT-Broker]  INFO {org.wso2.carbon.core.internal.Carbo                                                                                       nCoreActivator} -  Carbon Home      : /home/wso2iot-3.2.0/wso2/broker
[2019-07-02 16:41:34,829] [IoT-Broker]  INFO {org.wso2.carbon.core.internal.Carbo                                                                                       nCoreActivator} -  Java Temp Dir    : /home/wso2iot-3.2.0/wso2/broker/tmp
[2019-07-02 16:41:34,829] [IoT-Broker]  INFO {org.wso2.carbon.core.internal.Carbo                                                                                       nCoreActivator} -  User             : root, fr-FR, Africa/Douala
[2019-07-02 16:41:37,448] [IoT-Broker]  INFO {org.wso2.carbon.registry.core.jdbc.                                                                                       EmbeddedRegistryService} -  Configured Registry in 104ms
[2019-07-02 16:41:37,566] [IoT-Broker]  INFO {org.wso2.carbon.registry.core.inter                                                                                       nal.RegistryCoreServiceComponent} -  Registry Mode    : READ-WRITE
[2019-07-02 16:41:37,576] [IoT-Broker]  INFO {org.wso2.andes.configuration.AndesC                                                                                       onfigurationManager} -  Main andes configuration located at : /home/wso2iot-3.2.0                                                                                       /wso2/broker/conf/broker.xml
[2019-07-02 16:41:37,646] [IoT-Broker]  INFO {org.wso2.andes.configuration.AndesC                                                                                       onfigurationManager} -  Main andes configuration located at : /home/wso2iot-3.2.0                                                                                       /wso2/broker/conf/broker.xml
[2019-07-02 16:41:37,787] [IoT-Broker]  INFO {org.wso2.carbon.metrics.impl.util.J                                                                                       DBCReporterBuilder} -  Creating JDBC reporter for Metrics with source 'localhost'                                                                                       , data source 'jdbc/WSO2MetricsDB' and 60 seconds polling period
[2019-07-02 16:41:37,788] [IoT-Broker]  INFO {org.wso2.carbon.metrics.impl.util.J                                                                                       mxReporterBuilder} -  Creating JMX reporter for Metrics with domain 'org.wso2.car                                                                                       bon.metrics'
[2019-07-02 16:41:37,799] [IoT-Broker]  INFO {org.wso2.carbon.metrics.impl.report                                                                                       er.AbstractReporter} -  Started JDBC reporter for Metrics
[2019-07-02 16:41:37,800] [IoT-Broker]  INFO {org.wso2.carbon.metrics.impl.report                                                                                       er.AbstractReporter} -  Started JMX reporter for Metrics
[2019-07-02 16:41:41,475] [IoT-Broker]  INFO {org.wso2.carbon.registry.indexing.s                                                                                       olr.SolrClient} -  Default Embedded Solr Server Initialized
[2019-07-02 16:41:41,963] [IoT-Broker]  INFO {org.wso2.carbon.user.core.internal.                                                                                       UserStoreMgtDSComponent} -  Carbon UserStoreMgtDSComponent activated successfully                                                                                       .
[2019-07-02 16:41:57,194] [IoT-Broker]  INFO {org.apache.axis2.deployment.Cluster                                                                                       Builder} -  Clustering has been disabled
[2019-07-02 16:41:57,428] [IoT-Broker]  INFO {org.wso2.carbon.identity.user.store                                                                                       .configuration.deployer.UserStoreConfigurationDeployer} -  User Store Configurati                                                                                       on Deployer initiated.
[2019-07-02 16:41:57,429] [IoT-Broker]  INFO {org.wso2.carbon.identity.user.store                                                                                       .configuration.deployer.UserStoreConfigurationDeployer} -  User Store Configurati                                                                                       on Deployer initiated.
[2019-07-02 16:41:58,661] [IoT-Broker]  INFO {org.apache.axis2.deployment.ModuleD                                                                                       eployer} -  Deploying module: addressing-1.6.1-wso2v22 - file:/home/wso2iot-3.2.0                                                                                       /wso2/broker/repository/deployment/client/modules/addressing-1.6.1-wso2v22.mar
[2019-07-02 16:41:58,995] [IoT-Broker]  INFO {org.apache.axis2.deployment.Deploym                                                                                       entEngine} -  Deploying Web service: org.wso2.carbon.andes.admin-3.2.16 -
[2019-07-02 16:41:59,015] [IoT-Broker]  INFO {org.apache.axis2.deployment.Deploym                                                                                       entEngine} -  Deploying Web service: org.wso2.carbon.andes.admin.mqtt-3.2.16 -
[2019-07-02 16:41:59,046] [IoT-Broker]  INFO {org.apache.axis2.deployment.Deploym                                                                                       entEngine} -  Deploying Web service: org.wso2.carbon.andes.event.admin-3.2.16 -
[2019-07-02 16:42:00,136] [IoT-Broker]  INFO {org.apache.axis2.deployment.Deploym                                                                                       entEngine} -  Deploying Web service: org.wso2.carbon.tryit-4.5.8 -
[2019-07-02 16:42:00,367] [IoT-Broker]  INFO {org.wso2.carbon.core.init.CarbonSer                                                                                       verManager} -  Repository       : /home/wso2iot-3.2.0/wso2/broker/repository/depl                                                                                       oyment/server/
[2019-07-02 16:42:00,380] [IoT-Broker]  INFO {org.wso2.carbon.andes.core.internal                                                                                       .ds.QueueManagerServiceDS} -  Successfully created the queue manager service
[2019-07-02 16:42:00,385] [IoT-Broker]  INFO {org.wso2.carbon.andes.core.internal                                                                                       .ds.SubscriptionManagerServiceDS} -  Successfully created the subscription manage                                                                                       r service
[2019-07-02 16:42:00,433] [IoT-Broker]  INFO {org.wso2.carbon.core.multitenancy.e                                                                                       ager.TenantLoadingConfig} -  Using tenant lazy loading policy...
[2019-07-02 16:42:00,445] [IoT-Broker]  INFO {org.wso2.carbon.core.internal.permi                                                                                       ssion.update.PermissionUpdater} -  Permission cache updated for tenant -1234
[2019-07-02 16:42:00,742] [IoT-Broker]  INFO {org.wso2.andes.configuration.AndesC                                                                                       onfigurationManager} -  Main andes configuration located at : /home/wso2iot-3.2.0                                                                                       /wso2/broker/conf/broker.xml
[2019-07-02 16:42:00,776] [IoT-Broker]  INFO {org.wso2.carbon.andes.internal.Qpid                                                                                       ServiceComponent} -  Activating Andes Message Broker Engine...
[2019-07-02 16:42:00,789] [IoT-Broker]  INFO {org.wso2.andes.server.Broker} -  St                                                                                       arting Qpid using configuration : /home/wso2iot-3.2.0/wso2/broker/conf/advanced/q                                                                                       pid-config.xml
[2019-07-02 16:42:00,823] [IoT-Broker]  INFO {org.wso2.andes.server.registry.Appl                                                                                       icationRegistry} -  Initialising Application Registry(org.wso2.andes.server.regis                                                                                       try.ConfigurationFileApplicationRegistry@6e3bde62)
[2019-07-02 16:42:00,847] [IoT-Broker]  INFO {org.wso2.andes.server.plugins.Plugi                                                                                       nManager} -  Opened service trackers
[Broker] BRK-1001 : Startup : Version: 0.11 Build: 90784:90849
[2019-07-02 16:42:00,952] [IoT-Broker]  INFO {org.wso2.andes.server.management.JM                                                                                       XManagedObjectRegistry} -  Initialising managed object registry using jplatform M                                                                                       Bean server
[2019-07-02 16:42:00,957] [IoT-Broker]  INFO {org.wso2.andes.server.security.auth                                                                                       .manager.PrincipalDatabaseAuthenticationManager} -  PrincipalDatabase concrete im                                                                                       plementation : org.wso2.carbon.andes.authentication.andes.CarbonBasedPrincipalDat                                                                                       abase
[2019-07-02 16:42:00,961] [IoT-Broker]  INFO {org.wso2.andes.server.security.auth                                                                                       .manager.PrincipalDatabaseAuthenticationManager} -  Initialised PLAIN SASL provid                                                                                       er successfully
[2019-07-02 16:42:00,962] [IoT-Broker]  INFO {org.wso2.andes.server.security.auth                                                                                       .manager.PrincipalDatabaseAuthenticationManager} -  Additional SASL providers suc                                                                                       cessfully registered.
[2019-07-02 16:42:00,962] [IoT-Broker]  INFO {org.wso2.andes.server.security.auth                                                                                       .manager.PrincipalDatabaseAuthenticationManager} -  Registering UserManagementMBe                                                                                       an
[Broker] MNG-1001 : Startup
[Broker] MNG-1004 : Ready : Using the platform JMX Agent
[2019-07-02 16:42:01,076] [IoT-Broker]  INFO {org.wso2.andes.store.rdbms.RDBMSCon                                                                                       nection} -  JDBC connection established with jndi config WSO2MBStoreDB
[2019-07-02 16:42:01,089] [IoT-Broker]  INFO {org.wso2.andes.store.rdbms.RDBMSAnd                                                                                       esContextStoreImpl} -  Andes Context Store initialised
[2019-07-02 16:42:01,089] [IoT-Broker]  INFO {org.wso2.andes.kernel.AndesKernelBo                                                                                       ot} -  AndesContextStore initialised with org.wso2.andes.store.rdbms.RDBMSAndesCo                                                                                       ntextStoreImpl
[2019-07-02 16:42:01,100] [IoT-Broker]  INFO {org.wso2.andes.store.rdbms.RDBMSCon                                                                                       nection} -  JDBC connection established with jndi config WSO2MBStoreDB
[2019-07-02 16:42:01,117] [IoT-Broker]  WARN {org.wso2.andes.configuration.AndesC                                                                                       onfigurationManager} -  Error when trying to read property : transaction/maxWaitT                                                                                       imeout. Switching to default value : 30
[2019-07-02 16:42:01,119] [IoT-Broker]  INFO {org.wso2.andes.store.rdbms.RDBMSMes                                                                                       sageStoreImpl} -  Message Store initialised
[2019-07-02 16:42:01,120] [IoT-Broker]  INFO {org.wso2.andes.kernel.AndesKernelBo                                                                                       ot} -  Andes MessageStore initialised with org.wso2.andes.store.rdbms.RDBMSMessag                                                                                       eStoreImpl
[2019-07-02 16:42:01,163] [IoT-Broker]  INFO {org.wso2.andes.server.cluster.Clust                                                                                       erManager} -  Initializing Standalone Mode. Current Node ID:NODE:localhost/127.0.                                                                                       0.1 127.0.0.1
[2019-07-02 16:42:01,166] [IoT-Broker]  WARN {org.wso2.andes.configuration.AndesC                                                                                       onfigurationManager} -  Error when trying to read property : coordination/RDBMSBa                                                                                       sedClusterEventSynchronization/@enabled. Switching to default value : true
[2019-07-02 16:42:01,172] [IoT-Broker]  WARN {org.wso2.andes.configuration.AndesC                                                                                       onfigurationManager} -  Error when trying to read property : coordination/RDBMSBa                                                                                       sedClusterEventSynchronization/@enabled. Switching to default value : true
[2019-07-02 16:42:01,230] [IoT-Broker]  WARN {org.wso2.andes.configuration.AndesC                                                                                       onfigurationManager} -  Error when trying to read property : coordination/RDBMSBa                                                                                       sedClusterEventSynchronization/@enabled. Switching to default value : true
[2019-07-02 16:42:01,280] [IoT-Broker]  INFO {org.wso2.andes.kernel.Andes} -  And                                                                                       es API initialised.
[2019-07-02 16:42:01,323] [IoT-Broker]  INFO {org.wso2.andes.kernel.AndesChannel}                                                                                        -  Channel created (ID: Internel_channel)
[2019-07-02 16:42:01,335] [IoT-Broker]  INFO {org.wso2.andes.kernel.AndesKernelBo                                                                                       ot} -  Syncing exchanges, queues, bindings and subscriptions
[2019-07-02 16:42:01,343] [IoT-Broker]  INFO {org.wso2.andes.kernel.disruptor.inb                                                                                       ound.InboundDBSyncRequestEvent} -  Running DB sync task.
[2019-07-02 16:42:01,347] [IoT-Broker]  INFO {org.wso2.andes.kernel.Andes} -  Sta                                                                                       rting Safe Zone Calculator for slots.
[2019-07-02 16:42:01,347] [IoT-Broker]  WARN {org.wso2.andes.kernel.disruptor.inb                                                                                       ound.InboundDBSyncRequestEvent} -  Recovering node. Adding exchange messageRouter                                                                                       Name=amq.dlc,type=DLC,autoDelete=false
[2019-07-02 16:42:01,358] [IoT-Broker]  INFO {org.wso2.andes.kernel.AndesContextI                                                                                       nformationManager} -  Message Router Sync [create]: amq.dlc
[2019-07-02 16:42:01,359] [IoT-Broker]  WARN {org.wso2.andes.kernel.disruptor.inb                                                                                       ound.InboundDBSyncRequestEvent} -  Recovering node. Adding queue to queue registr                                                                                       y queueName=deadletterchannel,queueOwner=admin,isExclusive=false,isDurable=true,i                                                                                       sShared=false,lastPurgedTimestamp=0
[2019-07-02 16:42:01,417] [IoT-Broker]  INFO {org.wso2.andes.kernel.AndesContextI                                                                                       nformationManager} -  Queue Sync [create]: deadletterchannel
[2019-07-02 16:42:01,420] [IoT-Broker]  WARN {org.wso2.andes.kernel.disruptor.inb                                                                                       ound.InboundDBSyncRequestEvent} -  Recovering node. Adding binding [Binding]E=amq                                                                                       .dlc/Q=deadletterchannel/RK=deadletterchannel/D=true/EX=false
[2019-07-02 16:42:01,421] [IoT-Broker]  INFO {org.wso2.andes.kernel.AndesContextI                                                                                       nformationManager} -  Binding Sync [create]: [Binding]E=amq.dlc/Q=deadletterchann                                                                                       el/RK=deadletterchannel/D=true/EX=false
