### ISSUE TITLE
[Tooling] Cannot delete created multiple projects on windows

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#2691]
**Description:**
$subject. 

**Suggested Labels:**
Windows, bug

**Suggested Assignees:**

**Affected Product Version:**
6.4.0

**OS, DB, other environment details and versions:**    
Windows 10

**Steps to reproduce:**
1. Create ESB solution project with C-app Project, the Connector exporter
2. Select multiple projects from Project Explorer
3. Click Delete

Will get below error
```
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
        at org.eclipse.core.internal.resources.Resource.delete(Resource.java:773)
        at org.eclipse.core.internal.resources.Project.delete(Project.java:318)
        at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:155)
        at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
        at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
        at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
        at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Contains: Could not delete '/Rest/src'.
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
        at org.eclipse.core.internal.localstore.FileSystemResourceManager.delete(FileSystemResourceManager.java:366)
        at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFolder(ResourceTree.java:358)
        at org.eclipse.core.internal.resources.ResourceTree.internalDeleteProject(ResourceTree.java:393)
        at org.eclipse.core.internal.resources.ResourceTree.standardDeleteProject(ResourceTree.java:850)
        at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1785)
        at org.eclipse.core.internal.resources.Resource.delete(Resource.java:760)
        at org.eclipse.core.internal.resources.Project.delete(Project.java:318)
        at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:155)
        at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
        at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
        at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
        at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Contains: Problems encountered while deleting files.
Contains: Could not delete: C:\Users\dakshika\eclipse-workspace2\Rest\src\main\synapse-config\api\UserInfoRestAPI.xml.
java.nio.file.FileSystemException: C:\Users\dakshika\eclipse-workspace2\Rest\src\main\synapse-config\api\UserInfoRestAPI.xml: The process cannot access the file because it is being used by another process.

        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
        at java.nio.file.Files.deleteIfExists(Unknown Source)
        at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:220)
        at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:248)
        at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:248)
        at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:248)
        at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:248)
        at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:137)
        at org.eclipse.core.internal.localstore.DeleteVisitor.delete(DeleteVisitor.java:63)
        at org.eclipse.core.internal.localstore.DeleteVisitor.visit(DeleteVisitor.java:151)
        at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:111)
        at org.eclipse.core.internal.localstore.FileSystemResourceManager.delete(FileSystemResourceManager.java:363)
        at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFolder(ResourceTree.java:358)
        at org.eclipse.core.internal.resources.ResourceTree.internalDeleteProject(ResourceTree.java:393)
        at org.eclipse.core.internal.resources.ResourceTree.standardDeleteProject(ResourceTree.java:850)
        at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1785)
        at org.eclipse.core.internal.resources.Resource.delete(Resource.java:760)
        at org.eclipse.core.internal.resources.Project.delete(Project.java:318)
        at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:155)
        at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
        at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
        at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
        at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Contains: Could not delete: C:\Users\dakshika\eclipse-workspace2\Rest\src\main\synapse-config\api.
Contains: Could not delete: C:\Users\dakshika\eclipse-workspace2\Rest\src\main\synapse-config\endpoints\UsersHttpEP.xml.
java.nio.file.FileSystemException: C:\Users\dakshika\eclipse-workspace2\Rest\src\main\synapse-config\endpoints\UsersHttpEP.xml: The process cannot access the file because it is being used by another process.

        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
        at java.nio.file.Files.deleteIfExists(Unknown Source)
        at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:220)
        at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:248)
        at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:248)
        at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:248)
        at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:248)
        at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:137)
        at org.eclipse.core.internal.localstore.DeleteVisitor.delete(DeleteVisitor.java:63)
        at org.eclipse.core.internal.localstore.DeleteVisitor.visit(DeleteVisitor.java:151)
        at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:111)
        at org.eclipse.core.internal.localstore.FileSystemResourceManager.delete(FileSystemResourceManager.java:363)
        at org.eclipse.core.internal.resources.ResourceTree.internalDeleteFolder(ResourceTree.java:358)
        at org.eclipse.core.internal.resources.ResourceTree.internalDeleteProject(ResourceTree.java:393)
        at org.eclipse.core.internal.resources.ResourceTree.standardDeleteProject(ResourceTree.java:850)
        at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1785)
        at org.eclipse.core.internal.resources.Resource.delete(Resource.java:760)
        at org.eclipse.core.internal.resources.Project.delete(Project.java:318)
        at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:155)
        at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
        at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
        at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
        at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Contains: Could not delete: C:\Users\dakshika\eclipse-workspace2\Rest\src\main\synapse-config\endpoints.
Contains: Could not delete: C:\Users\dakshika\eclipse-workspace2\Rest\src\main\synapse-config.
Contains: Could not delete: C:\Users\dakshika\eclipse-workspace2\Rest\src\main.
Contains: Could not delete: C:\Users\dakshika\eclipse-workspace2\Rest\src.
Contains: Could not delete 'C:\Users\dakshika\eclipse-workspace2\Rest'.
!SUBENTRY 1 org.eclipse.core.resources 4 273 2018-09-19 07:39:30.743
!MESSAGE Problems encountered while deleting resources.
!SUBENTRY 2 org.eclipse.core.resources 4 273 2018-09-19 07:39:30.744
!MESSAGE Could not delete '/Rest/src'.
!STACK 1
```

**Related Issues:**

**Comment by rosensilva** [comment]
Cannot reproduce in the latest master branch
