### ISSUE TITLE
Durable subscriber connection not properly closed when undeploying inbound endpoint

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/product-ei#2699]
**Description:**
The following exception occurred when undeploying and redeploying carbon application that has JMS inbound endpoint. The similar issue could be found in https://github.com/wso2/product-ei/issues/1135

```
TID: [-1] [] [2018-09-21 14:42:38,966] ERROR {org.wso2.andes.client.AMQConnection} -  Throwable Received but no listener set. {org.wso2.andes.client.AMQConnection}
org.wso2.andes.AMQChannelClosedException: Error: Cannot subscribe to queue carbon:xxxxxxxxxx as it already has an existing exclusive consumer [error code 403: access refused]
	at org.wso2.andes.client.handler.ChannelCloseMethodHandler.methodReceived(ChannelCloseMethodHandler.java:100)
	at org.wso2.andes.client.handler.ClientMethodDispatcherImpl.dispatchChannelClose(ClientMethodDispatcherImpl.java:163)
	at org.wso2.andes.framing.amqp_0_91.ChannelCloseBodyImpl.execute(ChannelCloseBodyImpl.java:140)
	at org.wso2.andes.client.state.AMQStateManager.methodReceived(AMQStateManager.java:111)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.methodBodyReceived(AMQProtocolHandler.java:546)
	at org.wso2.andes.client.protocol.AMQProtocolSession.methodFrameReceived(AMQProtocolSession.java:467)
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:92)
	at org.wso2.andes.client.protocol.AMQProtocolHandler$2.run(AMQProtocolHandler.java:479)
	at org.wso2.andes.pool.Job.processAll(Job.java:111)
	at org.wso2.andes.pool.Job.run(Job.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Related issue https://github.com/wso2/product-ei/issues/1135
Fixes https://github.com/wso2/carbon-mediation/pull/895 & https://github.com/wso2/carbon-commons/pull/283
