### ISSUE TITLE
Issue in publishing analytics stats via SSL

### ISSUE THREAD

**Issue by nishadi** [wso2/product-ei#2700]
**Description:**
When publishing analytics stats via SSL, an error occurs as below while starting the integrator server.
```
ERROR {org.wso2.carbon.databridge.agent.endpoint.DataEndpoint} -  Unable to send events to the endpoint. 
org.wso2.carbon.databridge.agent.exception.DataEndpointException: Cannot send Events
	at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftDataEndpoint.send(ThriftDataEndpoint.java:88)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpoint$EventPublisher.publish(DataEndpoint.java:314)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpoint$EventPublisher.run(DataEndpoint.java:272)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$Client.recv_publish(ThriftSecureEventTransmissionService.java:223)
	at org.wso2.carbon.databridge.commons.thrift.service.secure.ThriftSecureEventTransmissionService$Client.publish(ThriftSecureEventTransmissionService.java:210)
	at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftDataEndpoint.send(ThriftDataEndpoint.java:79)
```
This happens due to an error in the analytics server side, while waiting for the ack from publishing. 
The flow gets interrupted in analytics server because it tries to end a tenant flow even though it is not created.

**Suggested Labels:**
Type/Bug Fix

**Suggested Assignees:**

**Affected Product Version:**
EI 6.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Enable analytics via SSL. 

**Related Issues:**

**Comment by AnuGayan** [comment]
This was fixed by https://github.com/wso2/carbon-analytics-common/pull/566
