### ISSUE TITLE
Error : Read timed out 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-ei#2719]
**Description:**
Getting error -> Read timed out in  "RestPostFixUrlTest#testRESTURITemplateWithAdditionalParam"
[java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
  at org.wso2.carbon.automation.test.utils.http.client.HttpRequestUtil.sendGetRequest(HttpRequestUtil.java:62)
        at org.wso2.carbon.esb.rest.test.api.RestPostFixUrlTest.testRESTURITemplateWithAdditionalParam(RestPostFixUrlTest.java:61)]

**Affected Product Version:**
WSO2ei -6.5.0

**OS, DB, other environment details and versions:**    
Windows - 2016

**Comment by prabushi** [comment]
@NilukaSripalim Could you please explain the scenario where you have encountered the above error? Used artifacts are most preferable.

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/product-ei/pull/2760
