### ISSUE TITLE
[DSS] NPE when using ARRAY SQLType

### ISSUE THREAD

**Issue by nuwandiw** [wso2/product-ei#2771]
**Description:**
Following error is thrown when trying to create operation for a query which accepts ARRAY SQLType parameter.
```
[2018-10-20 00:01:12,604] [EI-Core] ERROR - DBDeployer The OrderDetailService.dbs service, which is not valid, caused {1}

java.lang.NullPointerException

	at org.wso2.carbon.dataservices.core.DBUtils.getSimpleSchemaTypeName(DBUtils.java:914)

	at org.wso2.carbon.dataservices.core.DataServiceDocLitWrappedSchemaGenerator.createInputEntryElement(DataServiceDocLitWrappedSchemaGenerator.java:292)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
6.4.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Create a SQL query, adding an input with SQLType "ARRAY".
Go to Next and add new operation.
Select the previously created query from drop down.
Finish creating the data service.
NPE can be seen in the back end.

**Related Issues:**

**Comment by chanikag** [comment]
Related issue: https://wso2.org/jira/browse/DS-1168
