### ISSUE TITLE
Intermittent test failure BpelRetireDeploymentTest.

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/product-ei#2829]
**Description:**
BpelRetireDeploymentTest test failed intermittently for 6.1.0 in jenkins building.

**Error Message**
Condition returned by method "isServiceDeployed" in class org.wso2.ei.businessprocess.integration.tests.bpel.upload.BpelRetireDeploymentTest was not fulfilled within 60 seconds.

**Stacktrace**
org.awaitility.core.ConditionTimeoutException: Condition returned by method "isServiceDeployed" in class org.wso2.ei.businessprocess.integration.tests.bpel.upload.BpelRetireDeploymentTest was not fulfilled within 60 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:145)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:79)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:27)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:902)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:860)
	at org.wso2.ei.businessprocess.integration.tests.bpel.upload.BpelRetireDeploymentTest.testRetireClient(BpelRetireDeploymentTest.java:75)

**Affected Product Version:**
WSO2 EI 6.1.0

**Comment by madushadhanushka** [comment]
[BpelRetireDeploymentTest.log](https://github.com/wso2/product-ei/files/2551659/BpelRetireDeploymentTest.log)
