### ISSUE TITLE
Intermittent test failure InboundTransportTest

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/product-ei#2837]
**Description:**
InboundTransportTest fail intermittently on EI 6.1.1 Jenkins build.

**Error Message**
expected:<true> but was:<false>

**Stacktrace**
java.lang.AssertionError: expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at org.testng.Assert.assertTrue(Assert.java:47)
	at org.wso2.carbon.esb.file.inbound.transport.test.InboundTransportTest.testInboundEndpointFileName_SpecialChars(InboundTransportTest.java:172)

**Affected Product Version:**
EI 6.1.1

**Comment by madushadhanushka** [comment]
Full log
[InboundTest.log](https://github.com/wso2/product-ei/files/2557849/InboundTest.log)
