### ISSUE TITLE
Error messages occur during the starting up ESB 4.8.1

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/product-ei#2863]
**Description:**
Following error message occur while starting up the ESB 4.8.1 server due to newly added Synpase cache handler.

```
TID: [0] [ESB] [2018-11-12 15:44:32,686] ERROR {org.wso2.carbon.mediation.library.RegistryCachingHandler} -  Error while loading synapse configurations for clear cache in /_system/esbConfig/repository/carbonapps/path_mapping/ISS_ServicioTransformacion_Recursos_CAP_1.0.0 {org.wso2.carbon.mediation.library.RegistryCachingHandler}
org.apache.synapse.SynapseException: Given entry key is empty or null.
	at org.apache.synapse.config.SynapseConfiguration.handleException(SynapseConfiguration.java:1536)
	at org.apache.synapse.config.SynapseConfiguration.assertAlreadyExists(SynapseConfiguration.java:1845)
	at org.apache.synapse.config.SynapseConfiguration.addEntry(SynapseConfiguration.java:638)
	at org.apache.synapse.config.SynapseConfiguration.getEntryDefinition(SynapseConfiguration.java:800)
	at org.wso2.carbon.mediation.library.RegistryCachingHandler.clearCache(RegistryCachingHandler.java:109)
	at org.wso2.carbon.mediation.library.RegistryCachingHandler.put(RegistryCachingHandler.java:51)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2503)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:1005)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:697)
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:657)
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:289)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2503)
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:205)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:997)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:697)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:465)
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:657)
	at org.wso2.carbon.application.deployer.persistence.CarbonAppPersistenceManager.createResourcePathMappingFile(CarbonAppPersistenceManager.java:400)
	at org.wso2.carbon.application.deployer.handler.RegistryResourceDeployer.deployArtifacts(RegistryResourceDeployer.java:67)
	at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:251)
	at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:114)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:79)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:124)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Affected Product Version:**
ESB 4.8.1

**Related Issues**
https://github.com/wso2/product-ei/issues/2361

**Comment by madushadhanushka** [comment]
Fixed in https://github.com/wso2/carbon-mediation/pull/1114
