### ISSUE TITLE
Intermittent test failure in InboundTransportTest

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/product-ei#2873]
**Description**
Intermittent test failure in InboundTransportTest in for EI 6.1.1/ ESB 5.0.0 in jenkins support build.

**Error message**
expected: but was:

**Stacktrace**
java.lang.AssertionError: expected: but was:
at org.testng.Assert.fail(Assert.java:89)
at org.testng.Assert.failNotEquals(Assert.java:489)
at org.testng.Assert.assertTrue(Assert.java:37)
at org.testng.Assert.assertTrue(Assert.java:47)
at org.wso2.carbon.esb.file.inbound.transport.test.InboundTransportTest.testInboundEndpointFileName_SpecialChars(InboundTransportTest.java:172)

**Affected Product Version**
WSO2 EI 6.1.1

[inboundTransportTest_Full_Log](https://github.com/wso2-support/product-ei/files/2560557/inboundTransportTestFullLog.log)

**Comment by madushadhanushka** [comment]
Fix for EI 6.1.0
https://github.com/wso2-support/product-ei/pull/103/
