### ISSUE TITLE
Cannot start EI 6.1.0 in JDK 1.7 in Fedora 23

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#291]
JDK 1.7, Fedora 23

It does not go to login page. javax.net.ssl.SSLException: bad record MAC error is thrown. Not work for IP and localhost both in a standalone pack.

ERROR - SourceHandler I/O error: bad record MAC
javax.net.ssl.SSLException: bad record MAC
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1605)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1573)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:971)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:876)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:750)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doUnwrap(SSLIOSession.java:245)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.decryptData(SSLIOSession.java:378)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:413)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:119)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:722)
[2017-03-15 14:04:04,331] [EI-Core] ERROR - SourceHandler I/O error: bad record MAC
javax.net.ssl.SSLException: bad record MAC
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1605)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1573)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:971)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:876)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:750)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doUnwrap(SSLIOSession.java:245)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.decryptData(SSLIOSession.java:378)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:413)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:119)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:722)

**Comment by nandika** [comment]
We have switched to 9443 port. Please check this with the new build.

**Comment by ushanib** [comment]
This is fixed in 16-3-2017 pack
