### ISSUE TITLE
Intermittent test failure in RetrieveBackendWsdlTestCase

### ISSUE THREAD

**Issue by Nipunich** [wso2/product-ei#2913]
### Description
Intermittent test failure in RetrieveBackendWsdlTestCase for 6.1.0 in jenkins build.
 
### Error message
Error while adding proxy

### Stacktrace
java.lang.Exception: Error while adding proxy 
	at org.wso2.esb.integration.common.clients.proxy.admin.ProxyServiceAdminClient.addProxyService(ProxyServiceAdminClient.java:154)
	at org.wso2.esb.integration.common.utils.ESBTestCaseUtils.updateESBConfiguration(ESBTestCaseUtils.java:283)
	at org.wso2.esb.integration.common.utils.ESBIntegrationTest.updateESBConfiguration(ESBIntegrationTest.java:231)
	at org.wso2.esb.integration.common.utils.ESBIntegrationTest.loadSampleESBConfiguration(ESBIntegrationTest.java:199)
	at org.wso2.carbon.esb.nhttp.transport.test.RetrieveBackendWsdlTestCase.testRetrieveBackendServiceWsdl(RetrieveBackendWsdlTestCase.java:65)
Caused by: org.apache.axis2.AxisFault: A service named StockQuoteProxy2 already exists
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:370)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:445)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.proxyadmin.stub.ProxyServiceAdminStub.addProxy(ProxyServiceAdminStub.java:1272)
	at org.wso2.esb.integration.common.clients.proxy.admin.ProxyServiceAdminClient.addProxyService(ProxyServiceAdminClient.java:152)

### Affected Product Version
WSO2 EI 6.1.0

[retrieveBackendWsdlTestCaseFullLog.log](https://github.com/wso2-support/product-ei/files/2560513/retrieveBackendWsdlTestCaseFullLog.log)

**Comment by Nipunich** [comment]
Issue fixed in https://github.com/wso2-support/product-ei/pull/139
