### ISSUE TITLE
transformjson proxy gives an exception

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#2947]
**Description:**
Document: https://docs.wso2.com/display/EI6xx/Working+with+JSON+Message+Payloads#WorkingwithJSONMessagePayloads-ConstructingandtransformingJSONpayloads

When it is trying to add the following proxy 'transformjson', it cannot be added. 
```
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="transformjson"
       transports="https,http"
       statistics="disable"
       trace="disable"
       startOnLoad="true">
   <target>
      <inSequence>
         <script language="js"><![CDATA[
           payload = mc.getPayloadJSON();
           for (i = 0; i &lt; payload.length; ++i) {
               payload[i].id_str = payload[i].id;
               delete payload[i].id;
               payload[i].tags[payload[i].tags.length] = "pub";
           }
           mc.setPayloadJSON(payload);
         ]]></script>
         <log>
            <property name="JSON-Payload" expression="json-eval($.)"/>
         </log>
         <respond/>
      </inSequence>
   </target>
   <description/>
</proxy>
```

Exception: 
```
Caused by: org.apache.synapse.SynapseException: Exception initializing inline script
	at org.apache.synapse.mediators.bsf.ScriptMediator.initInlineScript(ScriptMediator.java:461)
	at org.apache.synapse.mediators.bsf.ScriptMediator.<init>(ScriptMediator.java:192)
	at org.apache.synapse.mediators.bsf.ScriptMediatorFactory.createSpecificMediator(ScriptMediatorFactory.java:105)
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:94)
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:223)
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:46)
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createAnonymousSequence(SequenceMediatorFactory.java:70)
	at org.apache.synapse.config.xml.ProxyServiceFactory.createProxy(ProxyServiceFactory.java:166)
	at org.wso2.carbon.proxyadmin.service.ProxyServiceAdmin.addProxyService(ProxyServiceAdmin.java:257)
	at org.wso2.carbon.proxyadmin.service.ProxyServiceAdmin.addProxy(ProxyServiceAdmin.java:710)
	... 143 more
Caused by: javax.script.ScriptException: org.mozilla.javascript.EvaluatorException: missing ) after for-loop control (<Unknown Source>#2)
	at com.sun.phobos.script.javascript.RhinoScriptEngine.compile(RhinoScriptEngine.java:341)
	at com.sun.phobos.script.javascript.RhinoScriptEngine.compile(RhinoScriptEngine.java:323)
	at org.apache.synapse.mediators.bsf.ScriptMediator.initInlineScript(ScriptMediator.java:450)
	... 152 more
Caused by: org.mozilla.javascript.EvaluatorException: missing ) after for-loop control (<Unknown Source>#2)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:64)
	at org.mozilla.javascript.Parser.addError(Parser.java:188)
	at org.mozilla.javascript.Parser.addError(Parser.java:166)
	at org.mozilla.javascript.Parser.reportError(Parser.java:223)
	at org.mozilla.javascript.Parser.reportError(Parser.java:217)
	at org.mozilla.javascript.Parser.mustMatchToken(Parser.java:388)
	at org.mozilla.javascript.Parser.mustMatchToken(Parser.java:378)
	at org.mozilla.javascript.Parser.forLoop(Parser.java:1280)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:959)
	at org.mozilla.javascript.Parser.statement(Parser.java:901)
	at org.mozilla.javascript.Parser.parse(Parser.java:540)
	at org.mozilla.javascript.Parser.parse(Parser.java:502)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2350)
	at org.mozilla.javascript.Context.compileReader(Context.java:1296)
	at org.mozilla.javascript.Context.compileReader(Context.java:1268)
	at com.sun.phobos.script.javascript.RhinoScriptEngine.compile(RhinoScriptEngine.java:337)
```

**Suggested Labels:**
Doc[Product-excellance]
Priority/Highest
Severity/Major

**Affected Product Version:**
EI6xx

**OS, DB, other environment details and versions:**    
Tested in OSX
product: wso2ei-6.4.0+1541412472334.full

**Steps to reproduce:**
1. Copy the above proxy and save it. 
2. Above mentioned exception is occurred. 
<img width="1440" alt="screen shot 2018-12-05 at 10 34 12 pm" src="https://user-images.githubusercontent.com/31693103/49530395-24e1b500-f8de-11e8-9b6c-d85758681d4d.png">

**Comment by Nirothipan** [comment]
Here the issue occurs when the source is directly pasted which is not the correct way.

Please go to design view and add the following script in Source Script which works.

```

payload = mc.getPayloadJSON();
           for (i = 0; i < payload.length; ++i) {
               payload[i].id_str = payload[i].id;
               delete payload[i].id;
               payload[i].tags[payload[i].tags.length] = "pub";
           }
           mc.setPayloadJSON(payload);
```


======================================

![scripmediator](https://user-images.githubusercontent.com/24619763/53726219-8db3db80-3e93-11e9-92c5-1d168b3d0c27.png)


======================================

Please update the docs

**Comment by nilminiwso2** [comment]
I changed the 'transformjson' given in the doc [1] to the following, and I am able to save. This is the same code that was referred in the answer that @Nirothipan has give above. @Nirothipan - Could you please confirm.

```
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="transformjson"
       transports="https,http"
       statistics="disable"
       trace="disable"
       startOnLoad="true">
   <target>
      <inSequence>
         <script language="js">
           payload = mc.getPayloadJSON();
           for (i = 0; i &lt; payload.length; ++i) {
               payload[i].id_str = payload[i].id;
               delete payload[i].id;
               payload[i].tags[payload[i].tags.length] = "pub";
           }
           mc.setPayloadJSON(payload);
         </script>
         <log>
            <property name="JSON-Payload" expression="json-eval($.)"/>
         </log>
         <respond/>
      </inSequence>
   </target>
   <description/>
</proxy>
```

[1] https://docs.wso2.com/display/EI6xx/Working+with+JSON+Message+Payloads#WorkingwithJSONMessagePayloads-ConstructingandtransformingJSONpayloads
