### ISSUE TITLE
[EI610][Oracle12c] Unable to start intergrator using -Dsetup

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#296]
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
EI610 Jenkins build pack - 15/03/2014
DB - Oracle 12c

**Steps**
1. Configure the data source with oracle
2. Start the integrator with -Dsetup (./integrator.sh -Dsetup)

**Observations**
2017-03-15 17:36:34,774] [EI-Core]  INFO - ManagementModeConfigurationLoader CEP started in Single node mode
[2017-03-15 17:36:37,734] [EI-Core] ERROR - Activator Cannot start User Manager Core bundle
java.lang.Exception: Error in creating the database
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeDatabase(DefaultRealmService.java:354)
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:91)
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:115)
	at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.java:68)
	at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleCheckActivator.java:61)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.Exception: Error occurred while executing :  CREATE INDEX INDEX_UM_PERMISSION ON UM_PERMISSION (UM_RESOURCE_ID, UM_ACTION, UM_TENANT_ID) 
	at org.wso2.carbon.utils.dbcreator.DatabaseCreator.executeSQL(DatabaseCreator.java:177)
	at org.wso2.carbon.utils.dbcreator.DatabaseCreator.executeSQLScript(DatabaseCreator.java:333)
	at org.wso2.carbon.utils.dbcreator.DatabaseCreator.createRegistryDatabase(DatabaseCreator.java:61)
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeDatabase(DefaultRealmService.java:344)
	... 19 more
Caused by: java.sql.SQLException: ORA-01408: such column list already indexed

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:202)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:45)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:933)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1718)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1678)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:332)
	at org.wso2.carbon.utils.dbcreator.DatabaseCreator.executeSQL(DatabaseCreator.java:147)
	... 22 more

**Comment by sashikamw** [comment]
Created a JIRA - https://wso2.org/jira/browse/CARBON-16110

**Comment by Dilshani** [comment]
Identified same error with analytics cluster. As oracle scripts in every product within EI contains index, this issue can be reproduced by them too.

**Comment by nandika** [comment]
This should be fixed with the new kernel.

**Comment by nandika** [comment]
Please test with new pack.

**Comment by nandika** [comment]
This is fixed with kernel version update
