### ISSUE TITLE
The "Schema definition cannot be found for connector operations" error due to schema operation missing for the file connector - EI Tooling

### ISSUE THREAD

**Issue by Methma** [wso2/product-ei#2983]
**Description:**
The "Schema definition cannot be found for connector operations" error is occurring while using the file Connector as the 'input' file for the Data Mapper in EI Tooling.

The below error is logged in the console.

> java.io.FileNotFoundException: File '/home/methma/workspace/SAINSBURYSSUB-15/.metadata/.Connectors/fileconnector-connector-2.0.12/null/output_schema/move.json' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:196)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1326)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1344)
	at org.wso2.developerstudio.datamapper.diagram.schemagen.util.AbstractSchemaGenerator.getSchemaResourcePath(AbstractSchemaGenerator.java:33)
	at org.wso2.developerstudio.datamapper.diagram.schemagen.util.SchemaGeneratorHelper.getSchemaContent(SchemaGeneratorHelper.java:56)
	at org.wso2.developerstudio.datamapper.diagram.custom.util.SchemaKeyEditorDialog.loadSchemaFromConnectorOperation(SchemaKeyEditorDialog.java:611)
	at org.wso2.developerstudio.datamapper.diagram.custom.util.SchemaKeyEditorDialog.okPressed(SchemaKeyEditorDialog.java:591)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:466)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.wso2.developerstudio.datamapper.diagram.custom.action.LoadInputSchemaAction.doRun(LoadInputSchemaAction.java:76)
	at org.eclipse.gmf.runtime.common.ui.action.AbstractActionHandler.run(AbstractActionHandler.java:359)
	at org.eclipse.gmf.runtime.common.ui.action.ActionManager$1.run(ActionManager.java:225)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.gmf.runtime.common.ui.action.ActionManager.run(ActionManager.java:223)
	at org.eclipse.gmf.runtime.common.ui.action.AbstractActionHandler.runWithEvent(AbstractActionHandler.java:377)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

Identified cause for the error:

When adding a connector to devStudio, connector zip will be added to workspace/.metadata/.Connectors and extracted there. DevStudio will load these schema related to each connector referring the workspace location (input_schema and output_schema within each connector component). 
In this case, we are getting the above mentioned error when the connector zip is not included with the schema for a particular operation. If the schema is not available within the connector, devStudio will not be able to load the schema into data mapper.

**Suggested Labels:**
EI Tooling

**Affected Product Version:**
Tooling 6.4.0

**Steps to reproduce:**
1. Add file-connector to the Dev Studio.
2. Add that connector to the datamapper as the input.

**Comment by dinuish94** [comment]
No changes to be done from the DevStudio end. Schema generation should be done to the 'File connector'. This is in progress.

**Comment by keerthu** [comment]
Fixed in https://github.com/wso2-extensions/esb-connector-file/pull/59
