### ISSUE TITLE
 Error occurs in payload factory when using a JSON payload with the "$" character 

### ISSUE THREAD

**Issue by SavithriNandadasa** [wso2/product-ei#3043]
**Description:**
The following error occurs when using a JSON payload with the "$" character

2019-01-03 10:25:26,271] [EI-Core] ERROR - SequenceMediator No group 2java.lang.IndexOutOfBoundsException: No group 2 at java.util.regex.Matcher.start(Matcher.java:375) at java.util.regex.Matcher.appendReplacement(Matcher.java:880) at org.apache.synapse.mediators.transform.PayloadFactoryMediator.replaceCTX(PayloadFactoryMediator.java:281) at org.apache.synapse.mediators.transform.PayloadFactoryMediator.regexTransformCTX(PayloadFactoryMediator.java:218) at org.apache.synapse.mediators.transform.PayloadFactoryMediator.mediate(PayloadFactoryMediator.java:160) at org.apache.synapse.mediators.transform.PayloadFactoryMediator.mediate(PayloadFactoryMediator.java:109) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:99) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:61) at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) at org.apache.synapse.rest.Resource.process(Resource.java:343) at org.apache.synapse.rest.API.process(API.java:418) at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:123) at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:101) at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69) at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304) at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:78) at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326) at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:372) at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151) at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
 
**Affected Product Version:**
EI 6.1.1
  
**Steps to reproduce:**
- Create a sample API as follows.
```
<api xmlns="http://ws.apache.org/ns/synapse" name="Test1" context="/test1">
   <resource methods="POST" uri-template="/" protocol="http">
      <inSequence>
         <enrich>
            <source clone="true" xpath="json-eval($)"/>
            <target type="property" property="STAYS_RESPONSE"/>
         </enrich>
         <payloadFactory media-type="json">
            <format>{"stays":$ctx:STAYS_RESPONSE}</format>
            <args/>
         </payloadFactory>
         <respond/>
      </inSequence>
   </resource>
</api>
```
-  Invoke the API with the following payload.
```
{
  "aaa": [
    {
      "message": "sdsf $44"
    }
  ]
}
```

**Comment by arunans23** [comment]
This issues seems to be there in the wum updated pack too. We need to fix it ASAP.

A simple workaround would be the following.
```
<api xmlns="http://ws.apache.org/ns/synapse" name="Test1" context="/test1">
   <resource methods="POST" uri-template="/" protocol="http">
      <inSequence>
         <enrich>
            <source clone="true" xpath="json-eval($)"/>
            <target type="property" property="STAYS_RESPONSE"/>
         </enrich>
         <payloadFactory media-type="json">
            <format>{"stays":$1}</format>
            <args>
               <arg evaluator="xml" expression="get-property('STAYS_RESPONSE')"/>
            </args>
         </payloadFactory>
         <respond/>
      </inSequence>
   </resource>
</api>
```

**Comment by arunans23** [comment]
Further to add, we have officially removed inline expressions from PayloadFactory Mediators in EI 6.4.0. But the EI docs are not updated yet. I have created a [JIRA issue](https://wso2.org/jira/browse/DOCUMENTATION-8449) to track this.

**Comment by GDLMadushanka** [comment]
Closing the issue since inline expression support is removed and docs are updated
