### ISSUE TITLE
Cache mediator inside an iterate mediator throws NPE

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/product-ei#3077]
**Description:**
When a cache mediator is inside an iterate mediator and when the iterate mediator executes parallely, the following NPE is thrown.

```
[EI-Core] ERROR - TemplateMediator Tenant domain has not been set in CarbonContext
java.lang.NullPointerException: Tenant domain has not been set in CarbonContext
	at org.wso2.carbon.caching.impl.CacheManagerFactoryImpl.getCacheManager(CacheManagerFactoryImpl.java:79)
	at org.wso2.carbon.mediator.cache.CacheMediator.getMediatorCache(CacheMediator.java:517)
	at org.wso2.carbon.mediator.cache.CacheMediator.processRequestMessage(CacheMediator.java:331)
	at org.wso2.carbon.mediator.cache.CacheMediator.mediate(CacheMediator.java:227)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:99)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:61)
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:104)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:148)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:84)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:99)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:61)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.mediators.MediatorWorker.run(MediatorWorker.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
The reason for this is that when the iterate mediator is in parallel mode, a different thread executes the mediation and that thread loses the tenant information. Tenant information in stored in a threadlocal variable and that is needed by the cache mediator.

**Affected Product Version:**
EI 6.1.1

**Comment by ThishaniLucas** [comment]
Closing this issue since the cache mediator implementation is totally different in the newer product versions.
