### ISSUE TITLE
[EI610][Tenant] Exception when invoking dataservice with select operation

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#322]
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
EI610 PreAlpha Pack
DB - postgresSQL

**Steps**
1. Create a tenant in EI
2. create a data service with select query
3. Invoke the select query

[queueDetails.dbs.zip](https://github.com/wso2/product-ei/files/857426/queueDetails.dbs.zip)

**Observation**
1. Other operations (insert,update, delete works fine)
2.  Following error observed after invoking 'select all' operation
```
[2017-03-21 13:46:57,403] [EI-Core]  INFO - SourceHandler Writer null when calling informWriterError
[2017-03-21 13:46:57,403] [EI-Core] ERROR - SourceHandler Unexpected I/O error: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:265)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:474)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.sendEncryptedData(SSLIOSession.java:362)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.outboundTransport(SSLIOSession.java:450)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:152)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:180)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:342)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sashikamw** [comment]
Same exception observed in tenant mode when invoking the data service that works in the super tenant mode.

Observed the below exception when mongodb sample is invoked in the tenant mode

```
[2017-03-21 16:43:07,719] [EI-Core]  WARN - SourceHandler Illegal incoming connection state: REQUEST_READY . Possibly two send backs are happening for the same request
[2017-03-21 16:43:07,719] [EI-Core]  WARN - SourceHandler Trying to write response body while the handler is in an inconsistent state REQUEST_READY
[2017-03-21 16:43:07,720] [EI-Core] ERROR - SourceHandler Unexpected I/O error: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:265)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:474)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.sendEncryptedData(SSLIOSession.java:362)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.outboundTransport(SSLIOSession.java:450)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:152)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:180)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:342)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sashikamw** [comment]
This issue is reproducible in the Alpha pack (with the patch 9999 shared on 31/03/2017). Observed when invoking eventing sample, getProductByCode method.

**Comment by milindaperera** [comment]
Reproducible in snapshot for tenants with mysql 5.6 in Java8
Noticed for low load no response received, but for continuous high load exception reproduced

**Comment by sashikamw** [comment]
Verified this issue with the snapshot shared on 03/04/2017 with the patch contains 'org.wso2.carbon.core_4.4.15.jar'
