### ISSUE TITLE
Message building error when the json message key contains the colon ":" and it getting converted to xml.

### ISSUE THREAD

**Issue by PrabhashDilhan** [wso2/product-ei#3237]
**Description:**
**We can observe below error using a JSON message which has a key that contains the colon ":"  and a content-aware mediator in ESB 4.8.1.**

[2019-02-18 10:04:11,762] ERROR -  javax.xml.stream.XMLStreamException: Unbound prefix: urn {org.apache.synapse.mediators.base.SequenceMediator}
org.apache.axiom.om.OMException: javax.xml.stream.XMLStreamException: Unbound prefix: urn
        at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
        at org.apache.axiom.om.impl.llom.OMElementImpl.buildNext(OMElementImpl.java:653)
        at org.apache.axiom.om.impl.llom.OMNodeImpl.getNextOMSibling(OMNodeImpl.java:122)
        at org.apache.axiom.om.impl.llom.OMElementImpl.getNextOMSibling(OMElementImpl.java:343)
        at org.apache.axiom.om.impl.traverse.OMChildrenIterator.getNextNode(OMChildrenIterator.java:36)
        at org.apache.axiom.om.impl.traverse.OMAbstractIterator.hasNext(OMAbstractIterator.java:58)
        at org.apache.synapse.commons.json.JsonUtil.removeIndentations(JsonUtil.java:379)
        at org.apache.synapse.commons.json.JsonUtil.removeIndentations(JsonUtil.java:386)
        at org.apache.synapse.commons.json.JsonUtil.removeIndentations(JsonUtil.java:386)
        at org.apache.synapse.commons.json.JsonUtil.newJsonPayload(JsonUtil.java:492)
        at org.apache.synapse.commons.json.JsonUtil.newJsonPayload(JsonUtil.java:534)
        at org.apache.synapse.mediators.transform.PayloadFactoryMediator.mediate(PayloadFactoryMediator.java:141)
        at org.apache.synapse.mediators.transform.PayloadFactoryMediator.mediate(PayloadFactoryMediator.java:85)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:89)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:135)
        at org.apache.synapse.rest.Resource.process(Resource.java:305)
        at org.apache.synapse.rest.API.process(API.java:298)
        at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:76)
        at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:50)
        at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:248)
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:516)
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:170)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
        at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:242)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
ESB-4.8.1
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

- Deploy the below proxy service

`<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="XSLTProxy"
       transports="https,http"
       statistics="disable"
       trace="disable"
       startOnLoad="true">
   <target>
      <inSequence>
         <xslt key="gov:/custom/transform.xslt"/>
         <respond/>
      </inSequence>
   </target>
   <description/>
</proxy>`

- Add below xslt configuration into the registry(gov:/custom/transform.xslt-)

`<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:template match="ISOMessage/data">
        <ISOMessage>
            <data>
                <xsl:apply-templates/>
            </data>
        </ISOMessage>
    </xsl:template>
    <xsl:template match="field">
        <field>
            <xsl:for-each select="*">
                <xsl:choose>
                    <xsl:when test="name()='id'">
                        <xsl:attribute name="{name()}">
                            <xsl:value-of select="text()"/>
                        </xsl:attribute>
                    </xsl:when>
                    <xsl:otherwise>
                        <xsl:value-of select="."/>
                    </xsl:otherwise>
                </xsl:choose>
            </xsl:for-each>
        </field>
    </xsl:template>
</xsl:stylesheet>`

- Invoke the proxy service using below json payload.

`{ "ISOMessage": { "data": { "field": [ { "i:d": "0", "teext": "0200" }, { "id": "6", "text": "sd" }, { "id": "4", "text": "000000500000" }, { "id": "7", "text": "0111522180" }, { "id": "11", "text": "123489" }, { "id": "32", "text": "100009" }, { "id": "44", "text": "XYRTUI5269TYUI" }, { "id": "111", "text": "ABCDEFGHIJ 23125436754" } ] } } }`

**Related Issues:**

**Comment by nandika** [comment]
Need to verify this against the latest EI

**Comment by arunans23** [comment]
Our main target for XSLT mediator is to work with XML. But currently XSLT mediator supports JSON as well, but breaks with special characters in the key. But others mediators like Payload Factory mediator, log mediators would work with JSON payloads with special characters (for eg ':'). 

All the above tests are done against EI 6.4.0 and verified that the outputs are in order.
