### ISSUE TITLE
Analytics Worker does not support MySQL DB Engines with utf-8 charsets

### ISSUE THREAD

**Issue by Savidude** [wso2/product-ei#3249]
**Description:**
The following error is obtained when trying to run a worker node connected to a MySQL database with utf-8 charset.

> [2019-02-26 10:02:15,222] ERROR {org.wso2.siddhi.core.table.Table} - Error on 'EI_Analytics_StatApp'. Failed to initialize store for table name 'MediatorStatAgg_DAYS': Unable to initialize table 'MediatorStatAgg_DAYS': Specified key was too long; max key length is 3072 bytes Error while connecting to Table 'MediatorStatAgg_DAYS', will retry in '5 sec'. org.wso2.siddhi.core.exception.ConnectionUnavailableException: Failed to initialize store for table name 'MediatorStatAgg_DAYS': Unable to initialize table 'MediatorStatAgg_DAYS': Specified key was too long; max key length is 3072 bytes
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.connect(RDBMSEventTable.java:882)
	at org.wso2.siddhi.core.table.Table.connectWithRetry(Table.java:364)
	at org.wso2.siddhi.core.SiddhiAppRuntime.startWithoutSources(SiddhiAppRuntime.java:400)
	at org.wso2.siddhi.core.SiddhiAppRuntime.start(SiddhiAppRuntime.java:375)
	at org.wso2.carbon.stream.processor.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:224)
	at org.wso2.carbon.stream.processor.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:93)
	at org.wso2.carbon.stream.processor.core.internal.StreamProcessorDeployer.deploy(StreamProcessorDeployer.java:306)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.wso2.extension.siddhi.store.rdbms.exception.RDBMSTableException: Unable to initialize table 'MediatorStatAgg_DAYS': Specified key was too long; max key length is 3072 bytes
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.createTable(RDBMSEventTable.java:1125)
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.connect(RDBMSEventTable.java:874)
	... 19 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 3072 bytes
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.execute(PreparedStatementProxy.java:44)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.execute(HikariPreparedStatementProxy.java)
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.executeDDQueries(RDBMSEventTable.java:1159)
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.createTable(RDBMSEventTable.java:1120)
	... 20 more

**Suggested Labels:**
Analytics, Type/Bug, Priority/High 

**Suggested Assignees:**

**Affected Product Version:**
WSO2 EI 6.4.0

**OS, DB, other environment details and versions:**    
MySQL 5.7.23-23

**Steps to reproduce:**
1. Create MySQL database with a utf-8 charset
2. Point worker to the database by changing the database details of the configurations at EI_ANALYTICS in wso2.datasources of `<PRODUCT_EI>/wso2/analytics/conf/worker/deployment.yaml`.
3. Start worker node

**Related Issues:**

**Comment by dilee** [comment]
**Possible Cause**
The possible cause for this particular error is because the fields we are using in '_group by_' operations [1] are exceeding the maximum character limit when the DB engine charset is set to UTF-8. 

**Solution**
We need to revisit [1] and refactor the keys in a way which would not exceed the maximum byte length (3072).

**Workaround**
As a temporary solution, we can set the DB charset to _latin1_ and proceed.

[1] - https://github.com/wso2/analytics-solutions/blob/18b0349b472a89e8769050e67f9d5456a8b1059e/features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/siddhi-files/ei_analytics_statapp_0.siddhi#L81

**Comment by AnuGayan** [comment]
**Cause**
MediatorStatAgg__* tables are getting created from the [1] aggregation as @dilee mentioned and when getting created all the group by columns and AGG_TIMESTAMP, AGG_EVENT_TIMESTAMP will be considered as a composite primary key. The length of the composite key is longer than the maximum character length of utf-8.   

**Solution**
Since we cannot drop any group by columns because they are critical columns for the analytics, The best solution that can be done is to change the charset type to _latin1_

[1] https://github.com/wso2/analytics-solutions/blob/master/features/ei-analytics-feature/org.wso2.analytics.solutions.ei.analytics.feature/src/main/resources/siddhi-files/EI_Analytics_StatApp.siddhi#L81
