### ISSUE TITLE
REST_URL_POSTFIX get appended to JMS endpoints

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#3283]
**Description:**
In the call mediator blocking mode. Additional URL path parameters get appended to JMS enspoints. Which results in the following exception.
`[2019-03-05 10:15:02,228] ERROR - JMSOutTransportInfo Couldn't locate the JMS destination jmslistner of type queue/additional extracted from the URL jms:/jmslistner?transport.jms.ConnectionFactoryJNDIName=QueueConnectionFactory&java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory&java.naming.provider.url=repository/conf/jndi.properties&transport.jms.DestinationType=queue/additional
javax.naming.NameNotFoundException: dynamicQueues/jmslistner
	at org.wso2.andes.jndi.ReadOnlyContext.lookup(ReadOnlyContext.java:271)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at org.apache.axis2.transport.jms.JMSUtils.lookup(JMSUtils.java:667)
	at org.apache.axis2.transport.jms.JMSUtils.lookupDestination(JMSUtils.java:920)
	at org.apache.axis2.transport.jms.JMSOutTransportInfo.getDestination(JMSOutTransportInfo.java:197)
	at org.apache.axis2.transport.jms.JMSOutTransportInfo.loadConnectionFactoryFromProperties(JMSOutTransportInfo.java:145)
	at org.apache.axis2.transport.jms.JMSOutTransportInfo.createJMSSender(JMSOutTransportInfo.java:343)
	at org.apache.axis2.transport.jms.JMSSender.sendMessage(JMSSender.java:135)
	at org.apache.axis2.transport.base.AbstractTransportSender.invoke(AbstractTransportSender.java:112)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:297)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendRobust(BlockingMsgSender.java:444)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:343)
	at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:88)
	at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:78)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:547)
	at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:382)
	at org.apache.synapse.endpoints.AddressEndpoint.send(AddressEndpoint.java:65)
	at org.apache.synapse.endpoints.IndirectEndpoint.send(IndirectEndpoint.java:55)
	at org.apache.synapse.mediators.builtin.CallMediator.handleBlockingCall(CallMediator.java:139)
	at org.apache.synapse.mediators.builtin.CallMediator.mediate(CallMediator.java:98)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:100)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:62)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:343)
	at org.apache.synapse.rest.API.process(API.java:399)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:123)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:101)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:77)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:325)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:371)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`
**Suggested Labels:**
Bug

**Affected Product Version:**
EI 6.4.0

**Steps to reproduce:**
Configure EI 6.4.0 with wso2 MB and call the following API
```
<api xmlns="http://ws.apache.org/ns/synapse" name="testpostFix2" context="/testpostfix">
   <resource methods="POST GET">
      <inSequence>
         <property name="OUT_ONLY" value="true"/>
         <property name="FORCE_SC_ACCEPTED" value="true" scope="axis2"/>
         <log level="custom">
            <property name="hello" value="here I am"/>
         </log>
         <property name="ContentType" value="application/json" scope="axis2"/>
         <property name="messageType" value="application/json" scope="axis2"/>
         <call blocking="true">
            <endpoint key="conf:/testJMS"/>
         </call>
      </inSequence>
   </resource>
</api>
```

**Comment by prabushi** [comment]
**testJMS** endpoint is as follows.
```
<?xml version="1.0" encoding="UTF-8"?>
<endpoint xmlns="http://ws.apache.org/ns/synapse" name="conf//testJMS">
   <address uri="jms:/jmslistner?transport.jms.ConnectionFactoryJNDIName=QueueConnectionFactory&amp;java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory&amp;java.naming.provider.url=conf/jndi.properties&amp;transport.jms.DestinationType=queue">
      <suspendOnFailure>
         <progressionFactor>1.0</progressionFactor>
      </suspendOnFailure>
      <markForSuspension>
         <retriesBeforeSuspension>0</retriesBeforeSuspension>
         <retryDelay>0</retryDelay>
      </markForSuspension>
   </address>
</endpoint>
```
