### ISSUE TITLE
[EI61][DSS][Tenant] Failed to execute resources with path parameter

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#329]
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
EI610 PreAlpha Pack
DB - postgresSQL

**Steps**
1. Log in to tenant user
2. Create a query
3. Create a resource with a path parameter (ex: person/{PersonID} )
4. Invoke the service
[persondetails.dbs.zip](https://github.com/wso2/product-ei/files/861406/persondetails.dbs.zip)

**Observations**
1. Failed with Incompatible parameter exception

```
curl -X GET  http://sashika:8280/services/t/tenant.com/persondetails/person/9
<axis2ns74:DataServiceFault xmlns:axis2ns74="http://ws.wso2.org/dataservice"><axis2ns74:current_params>{}</axis2ns74:current_params><axis2ns74:current_request_name>_getperson_personid</axis2ns74:current_request_name><axis2ns74:source_data_service><axis2ns74:location>/persondetails.dbs</axis2ns74:location><axis2ns74:default_namespace>http://ws.wso2.org/dataservice</axis2ns74:default_namespace><axis2ns74:description>N/A</axis2ns74:description><axis2ns74:data_service_name>persondetails</axis2ns74:data_service_name></axis2ns74:source_data_service><axis2ns74:ds_code>INCOMPATIBLE_PARAMETERS_ERROR</axis2ns74:ds_code></axis2ns74:DataServiceFault>
```

```
[2017-03-22 17:29:33,057] [EI-Core] ERROR - ServerWorker Error processing GET request for : /services/t/tenant.com/persondetails/person/9
org.apache.axis2.AxisFault: DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Nested Exception:-
javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:PersonID
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Source Data Service:-
Name: persondetails
Location: /persondetails.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: _getperson_personid
Current Params: {}


	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doNhttpREST(MultitenantMessageReceiver.java:591)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doREST(MultitenantMessageReceiver.java:370)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRequest(MultitenantMessageReceiver.java:228)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:78)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sashikamw** [comment]
Could reproduce this issue in the SNAPSHOT pack shared on 03/04/2017. Verified in the cluster setup.

**Comment by sashikamw** [comment]
This issue still exists in the latest pack shared on 07/07/2017 with the patch consists following jars

- org.wso2.carbon.core_4.4.15.jar
- org.wso2.carbon.dataservices.core_4.4.5.jar
- org.wso2.carbon.integrator.core_6.1.0-SNAPSHOT.jar


<axis2ns16:DataServiceFault xmlns:axis2ns16="http://ws.wso2.org/dataservice"><axis2ns16:current_params>{}</axis2ns16:current_params><axis2ns16:source_data_service><axis2ns16:data_service_name>mysqltest</axis2ns16:data_service_name><axis2ns16:description>N/A</axis2ns16:description><axis2ns16:location>/mysqltest.dbs</axis2ns16:location><axis2ns16:default_namespace>http://ws.wso2.org/dataservice</axis2ns16:default_namespace></axis2ns16:source_data_service><axis2ns16:ds_code>INCOMPATIBLE_PARAMETERS_ERROR</axis2ns16:ds_code><axis2ns16:current_request_name>_getperson_personid</axis2ns16:current_request_name></axis2ns16:DataServiceFault

**Comment by diptesh-patil** [comment]
Any update on this issue? We are also stuck with this issue.

**Comment by sashikamw** [comment]
Observed the issue in EI 6.2.0 M1 Pack

**Comment by SITRE** [comment]
i am using wso2 ei 4.0 and i have this issues. Any work around ?
