### ISSUE TITLE
json path with predicates is not working in Enrich mediator

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/product-ei#3331]
**Description:**
create an enrich mediator with the following configuration:
```
<enrich>
    <source type="inline" clone="false">{}</source>
    <target xpath="json-eval($.store.book[?(@.category=='fiction')].price)"/>
</enrich>
```
request payload:
```
{
    "store": {
        "book": [
            {
                "category": "reference",
                "author": "Nigel Rees",
                "title": "Sayings of the Century",
                "price": 8.95
            },
            {
                "category": "fiction",
                "author": "J. R. R. Tolkien",
                "title": "The Lord of the Rings",
                "isbn": "0-395-19395-8",
                "price": 22.99
            }
        ]
    }
}
```
The request fails with the following excpetion in the server:
```
[2019-03-12 11:11:27,226] [EI-Core] ERROR - enrichApi Not enough predicates supplied for filter [?] at position 18
com.jayway.jsonpath.InvalidPathException: Not enough predicates supplied for filter [?] at position 18
	at com.jayway.jsonpath.internal.path.PathCompiler.readPlaceholderToken(PathCompiler.java:413)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:142)
	at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:612)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
	at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:612)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
	at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:124)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:58)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:75)
	at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101)
	at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467)
	at com.jayway.jsonpath.internal.JsonContext.set(JsonContext.java:139)
	at org.apache.synapse.mediators.elementary.Target.setEnrichResultToBody(Target.java:425)
	at org.apache.synapse.mediators.elementary.Target.insertJson(Target.java:368)
	at org.apache.synapse.mediators.elementary.EnrichMediator.mediate(EnrichMediator.java:102)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:351)
	at org.apache.synapse.rest.API.process(API.java:417)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:383)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by yasirjanjua** [comment]
@sdkottegoda I'm getting a similar error on EI 6.6.0 for the following 

```xml
             <enrich>
                  <source clone="true" type="custom" xpath="json-eval($.data.PaymentRows[?(@.Account=='2900')])"/>
                  <target action="replace" property="payment" type="property"/>
               </enrich>
```

Error:
Caused by: com.jayway.jsonpath.InvalidPathException: Not enough predicates supplied for filter [?] at position 24

Is there a workaround for it?
