### ISSUE TITLE
NullPointerException is thrown when JDBC message store tries to process invalid message from the database

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-ei#3333]
Steps to reproduce:

1. Insert a record with a string message into the database table configured to the message store

1. Add a message processor pointing to the same message store

The following exception will be thrown. 

```
java.lang.NullPointerException
	at org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore.closeStream(JDBCMessageStore.java:239)
	at org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore.deserializeMessage(JDBCMessageStore.java:224)
	at org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore.messageContentResultSet(JDBCMessageStore.java:629)
	at org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore$3.getResult(JDBCMessageStore.java:437)
	at org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore.getProcessedRows(JDBCMessageStore.java:189)
	at org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore.getResultMessageContextFromDatabase(JDBCMessageStore.java:148)
	at org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore.peek(JDBCMessageStore.java:440)
	at org.apache.synapse.message.store.impl.jdbc.JDBCConsumer.receive(JDBCConsumer.java:70)
	at org.apache.synapse.message.processor.impl.sampler.SamplingService.fetch(SamplingService.java:199)
	at org.apache.synapse.message.processor.impl.sampler.SamplingService.execute(SamplingService.java:131)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
This has happened due to the message couldn't be converted into ObjectInputStream at [1]

[1] https://github.com/Abilashini/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/message/store/impl/jdbc/JDBCMessageStore.java#L211

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1272
