### ISSUE TITLE
Error observing when deployed CAPP by change version for the same CAPP and redeploy

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-ei#3344]
**Description:**
Error observed when changing the already deployed CAPP with different version and redeploy. Also its not shown in Management console.  Below is the error messages observed. 

```
[2019-03-11 11:34:29,985] [EI-Core]  INFO - ApplicationManager Deploying Carbon Application : TestEICompositeApplication_2.0.0.car...
[2019-03-11 11:34:29,989] [EI-Core] ERROR - ApplicationManager Carbon Application : TestEICompositeApplication_1.0.0 already exists. Two applications can't have the same Id. Deployment aborted.
[2019-03-11 11:34:29,990] [EI-Core] ERROR - ApplicationManager Error occurred while deploying Carbon Application
org.wso2.carbon.CarbonException: Carbon Application : TestEICompositeApplication_1.0.0 already exists. Two applications can't have the same Id. Deployment aborted.
        at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:246)
        at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:72)
        at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
        at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
        at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
        at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
        at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
        at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
        at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
        at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
        at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
        at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2019-03-11 11:34:29,991] [EI-Core]  INFO - ApplicationManager Reverting successfully deployed artifcats in this CApp : TestEICompositeApplication_1.0.0
```

**Suggested Labels:**
EI Tooling
6.5.0

**Steps to reproduce:**
- Create a CAPP and deploy
- Redeploy the same CAPP by only change the version of the CAPP

**Comment by Drifftr** [comment]
The version field in platform distribution wizard is for changing the car file name only. If we need to change the capp application version we need to change the version from the pom.xml in capp project. This will let you deploy two capps with same names but different versions. However we are not supporting proxy versioning. So though we changed the capp versions, if we have the same proxy names, proxy artifacts will not be deployed since versioning is not supported.

**Comment by prabushi** [comment]
At the moment, deploying the same artifact with different versions is not supported from the server end.
