### ISSUE TITLE
[EI61][DSS] Error when invoking odata service using the primary key reference when the primary key is a string value

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#350]
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
EI610 PreAlpha Pack
DB - postgresSQL

**Steps**
1. Create a table in oracle or mysql with a string value as primary key
CREATE TABLE StringPersons (
    ID varchar(255) NOT NULL,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int,
    PRIMARY KEY (ID)
);

metadata file
```
<EntityType Name="StringPersons">
<Key>
<PropertyRef Name="ID" />
</Key>
<Property Name="Age" Type="Edm.Int32" MaxLength="10" />
<Property Name="ID" Type="Edm.String" Nullable="false" MaxLength="255" />
<Property Name="FirstName" Type="Edm.String" MaxLength="255" />
<Property Name="LastName" Type="Edm.String" Nullable="false" MaxLength="255" />
 </EntityType>
```

2. Create a data service for above data source
3. Invoke the datasource to retrieve data for a given id (Tried for DELETE, PUT methods as well)
Ex: GET http://localhost:8280/odata/supertenantpersondetails/persondb/StringPersons(abc)

```
{
"error": {
"code": null,
"message": "Error occurred. :Unknown key property abc"
}
}
```
```

[2017-03-23 23:21:31,163] [EI-Core] ERROR - ODataAdapter Error occurred. :Unknown key property abc
Unknown key property abc
	at org.apache.olingo.server.core.uri.parser.ParserHelper.compoundKey(ParserHelper.java:397)
	at org.apache.olingo.server.core.uri.parser.ParserHelper.parseKeyPredicate(ParserHelper.java:324)
	at org.apache.olingo.server.core.uri.parser.ResourcePathParser.leadingResourcePathSegment(ResourcePathParser.java:207)
	at org.apache.olingo.server.core.uri.parser.ResourcePathParser.parsePathSegment(ResourcePathParser.java:88)
	at org.apache.olingo.server.core.uri.parser.Parser.parseUri(Parser.java:179)
	at org.apache.olingo.server.core.ServiceDispatcher.execute(ServiceDispatcher.java:93)
	at org.apache.olingo.server.core.OData4HttpHandler.process(OData4HttpHandler.java:67)
	at org.wso2.carbon.dataservices.core.odata.ODataServiceHandler.process(ODataServiceHandler.java:80)
	at org.wso2.carbon.dataservices.odata.endpoint.ODataEndpoint.process(ODataEndpoint.java:71)
	at org.wso2.carbon.dataservices.odata.ODataServlet.service(ODataServlet.java:31)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:615)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745
```

**Comment by madhawa-gunasekara** [comment]
try with GET http://localhost:8280/odata/supertenantpersondetails/persondb/StringPersons("abc")

**Comment by sashikamw** [comment]
This works when we invoke as http://localhost:8280/odata/supertenantpersondetails/persondb/StringPersons('abc').
