### ISSUE TITLE
[Docs] Error on executing command - Sample 252: Pure Text (Binary) and POX Message Support with JMS.

### ISSUE THREAD

**Issue by menuka94** [wso2/product-ei#3553]
**Description:**
Regarding doc page: [Sample 252: Pure Text (Binary) and POX Message Support with JMS](https://docs.wso2.com/display/EI6xx/Sample+252%3A+Pure+Text+%28Binary%29+and+POX+Message+Support+with+JMS).

I get the following error in the Axis2Server's console when the command `ant jmsclient -Djms_type=binary -Djms_dest=dynamicQueues/JMSFileUploadProxy -Djms_payload=./../../samples/service-bus/resources/mtom/asf-logo.gif` is executed from `<EI_HOME>/samples/axis2Client`.

```
ERROR {org.apache.synapse.transport.nhttp.ServerWorker} -  Error processing POST request
org.apache.axiom.om.OMException: com.ctc.wstx.exc.WstxIOException: Invalid UTF-8 start byte 0x83 (at char #7, byte #-1)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
	at org.apache.axiom.om.impl.llom.OMDocumentImpl.getOMDocumentElement(OMDocumentImpl.java:109)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:570)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:566)
	at org.apache.axis2.transport.TransportUtils.createDocumentElement(TransportUtils.java:197)
	at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:146)
	at org.apache.axis2.transport.http.util.RESTUtil.processXMLRequest(RESTUtil.java:65)
	at org.apache.synapse.transport.nhttp.util.RESTUtil.processPOSTRequest(RESTUtil.java:240)
	at org.apache.synapse.transport.nhttp.ServerWorker.processEntityEnclosingMethod(ServerWorker.java:468)
	at org.apache.synapse.transport.nhttp.ServerWorker.run(ServerWorker.java:291)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ctc.wstx.exc.WstxIOException: Invalid UTF-8 start byte 0x83 (at char #7, byte #-1)
	at com.ctc.wstx.sr.StreamScanner.constructFromIOE(StreamScanner.java:633)
	at com.ctc.wstx.sr.StreamScanner.loadMore(StreamScanner.java:1007)
	at com.ctc.wstx.sr.StreamScanner.getNext(StreamScanner.java:762)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2002)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1131)
	at org.apache.axiom.util.stax.wrapper.XMLStreamReaderWrapper.next(XMLStreamReaderWrapper.java:225)
	at org.apache.axiom.util.stax.dialect.DisallowDoctypeDeclStreamReaderWrapper.next(DisallowDoctypeDeclStreamReaderWrapper.java:34)
	at org.apache.axiom.util.stax.wrapper.XMLStreamReaderWrapper.next(XMLStreamReaderWrapper.java:225)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
	... 13 more
Caused by: java.io.CharConversionException: Invalid UTF-8 start byte 0x83 (at char #7, byte #-1)
	at com.ctc.wstx.io.UTF8Reader.reportInvalidInitial(UTF8Reader.java:303)
	at com.ctc.wstx.io.UTF8Reader.read(UTF8Reader.java:189)
	at com.ctc.wstx.io.ReaderSource.readInto(ReaderSource.java:86)
	at com.ctc.wstx.io.BranchingReaderSource.readInto(BranchingReaderSource.java:56)
	at com.ctc.wstx.sr.StreamScanner.loadMore(StreamScanner.java:1001)
	... 21 more

```

**Comment by GDLMadushanka** [comment]
We have removed wso2ei-samples.sh from EI 6.5.0 onwards. Which means we are no longer supporting to start the server in sample modes. Given that, I think this will not be an issue. However, if we can reproduce the issue in runtime we must fix that.

**Comment by KasunAratthanage** [comment]
@samgnaniah This issue can be closed.
