### ISSUE TITLE
[Windows] Backend gives several errors when starting BPS,MB and Analatics wso2server scritps.

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#37]
**Environment**
OS-Windows 2008
JAVA-jdk 1.8.0_121
Default IE M1 pack

**Steps**

1. Start the wso2server.bat file of BPS, Analytics and MB inside wso2ei-6.0.0-m1\wso2\$product\bin folder
2. Then following errors can be seen in the backend of each  product

**BPS**
` FATAL {org.wso2.carbon.mediation.initializer.ServiceBu
sInitializer} -  Couldn't initialize the ESB...
org.apache.synapse.SynapseException: The synapse.xml location .\.\
        ./repository/deployment/server/synapse-configs
    \default doesn't exist
        at org.apache.synapse.SynapseControllerFactory.handleFatal(SynapseContro
llerFactory.java:121)
        at org.apache.synapse.SynapseControllerFactory.validatePath(SynapseContr
ollerFactory.java:113)
        at org.apache.synapse.SynapseControllerFactory.validate(SynapseControlle
rFactory.java:88)
        at org.apache.synapse.SynapseControllerFactory.createSynapseController(S
ynapseControllerFactory.java:44)
        at org.apache.synapse.ServerManager.init(ServerManager.java:103)
        at org.wso2.carbon.mediation.initializer.ServiceBusInitializer.initESB(S
erviceBusInitializer.java:451)
        at org.wso2.carbon.mediation.initializer.ServiceBusInitializer.activate(
ServiceBusInitializer.java:196)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(Servi
ceComponent.java:260)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(S
erviceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(Serv
iceComponentProp.java:345)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(Instan
ceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(Insta
nceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:34
3)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.
java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.ser
viceChanged(FilteredServiceListener.java:107)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEv
ent(BundleContextImpl.java:861)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventM
anager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchr
onous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServ
iceEventPrivileged(ServiceRegistry.java:819)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServ
iceEvent(ServiceRegistry.java:771)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.reg
ister(ServiceRegistrationImpl.java:130)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerSer
vice(ServiceRegistry.java:214)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerSe
rvice(BundleContextImpl.java:433)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerSe
rvice(BundleContextImpl.java:451)
        at org.wso2.carbon.inbound.endpoint.persistence.service.InboundEndpointP
ersistenceServiceDSComponent.activate(InboundEndpointPersistenceServiceDSCompone
nt.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(Servi
ceComponent.java:260)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(S
erviceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(Serv
iceComponentProp.java:345)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(Instan
ceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(Insta
nceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:34
3)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.
java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.ser
viceChanged(FilteredServiceListener.java:107)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEv
ent(BundleContextImpl.java:861)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventM
anager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchr
onous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServ
iceEventPrivileged(ServiceRegistry.java:819)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServ
iceEvent(ServiceRegistry.java:771)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.reg
ister(ServiceRegistrationImpl.java:130)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerSer
vice(ServiceRegistry.java:214)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerSe
rvice(BundleContextImpl.java:433)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerSe
rvice(BundleContextImpl.java:451)
        at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(Carbon
ServerManager.java:514)
        at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManag
er.java:219)
        at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(Car
bonCoreServiceComponent.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(Servi
ceComponent.java:260)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(S
erviceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(Serv
iceComponentProp.java:345)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(Instan
ceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(Insta
nceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:34
3)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.
java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.ser
viceChanged(FilteredServiceListener.java:107)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEv
ent(BundleContextImpl.java:861)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventM
anager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchr
onous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServ
iceEventPrivileged(ServiceRegistry.java:819)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServ
iceEvent(ServiceRegistry.java:771)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.reg
ister(ServiceRegistrationImpl.java:130)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerSer
vice(ServiceRegistry.java:214)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerSe
rvice(BundleContextImpl.java:433)
        at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpServi
ce(Activator.java:81)
        at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(A
ctivator.java:60)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServ
let.java:40)
        at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationS
ervlet.java:38)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.
java:1269)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.
java:1182)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:10
72)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContex
t.java:5368)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContex
t.java:5660)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.
java:1571)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.
java:1561)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[2017-01-25 00:02:08,471]  INFO {org.wso2.carbon.integrator.core.internal.Inte`

**Analytics**

FATAL {org.wso2.carbon.mediation.initializer.ServiceBusInitializer} -  Couldn't initialize the ESB... {org.wso2.carbon.mediation.initializer.ServiceBusInitializer}
org.apache.synapse.SynapseException: The synapse.xml location .\.\
        ./repository/deployment/server/synapse-configs
    \default doesn't exist
	at org.apache.synapse.SynapseControllerFactory.handleFatal(SynapseControllerFactory.java:121)
	at org.apache.synapse.SynapseControllerFactory.validatePath(SynapseControllerFactory.java:113)
	at org.apache.synapse.SynapseControllerFactory.validate(SynapseControllerFactory.java:88)
	at org.apache.synapse.SynapseControllerFactory.createSynapseController(SynapseControllerFactory.java:44)
	at org.apache.synapse.ServerManager.init(ServerManager.java:103)
	at org.wso2.carbon.mediation.initializer.ServiceBusInitializer.initESB(ServiceBusInitializer.java:451)
	at org.wso2.carbon.mediation.initializer.ServiceBusInitializer.activate(ServiceBusInitializer.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
	at org.wso2.carbon.inbound.endpoint.persistence.service.InboundEndpointPersistenceServiceDSComponent.activate(InboundEndpointPersistenceServiceDSComponent.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:514)
	at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManager.java:219)
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(CarbonCoreServiceComponent.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)
	at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1269)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1182)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1072)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5368)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5660)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1571)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1561)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**MB**

`Error: Could not find or load main class Files\Java\jre1.8.0_101\bin\java -Djava
.opts=" -Djava.io.tmpdir=C:\Users\ADMINI~1\Desktop\WSO2EI~1.0-M\wso2\BUSINE~1\bi
n\..\wso2\tmp -Dcatalina.base=C:\Users\ADMINI~1\Desktop\WSO2EI~1.0-M\wso2\BUSINE
~1\bin\..\..\lib\tomcat -Dwso2.carbon.xml=C:\Users\ADMINI~1\Desktop\WSO2EI~1.0-M
\wso2\BUSINE~1\bin\..\conf\carbon.xml -Dwso2.registry.xml=C:\Users\ADMINI~1\Desk
top\WSO2EI~1.0-M\wso2\BUSINE~1\bin\..\conf\registry.xml -Dwso2.user.mgt.xml=C:\U
sers\ADMINI~1\Desktop\WSO2EI~1.0-M\wso2\BUSINE~1\bin\..\conf\user-mgt.xml -Djava
.util.logging.config.file=C:\Users\ADMINI~1\Desktop\WSO2EI~1.0-M\wso2\BUSINE~1\b
in\..\conf\etc\logging-bridge.properties -Djava.util.logging.manager=org.apache.
juli.ClassLoaderLogManager -Dcarbon.config.dir.path=C:\Users\ADMINI~1\Desktop\WS
O2EI~1.0-M\wso2\BUSINE~1\bin\..\conf  -Dcomponents.repo=C:\Users\ADMINI~1\Deskto
p\WSO2EI~1.0-M\wso2\BUSINE~1\bin\..\..\components\plugins -Dcarbon.config.dir.pa
th=C:\Users\ADMINI~1\Desktop\WSO2EI~1.0-M\wso2\BUSINE~1\bin\..\conf -Dcarbon.com
ponents.dir.path=C:\Users\ADMINI~1\Desktop\WSO2EI~1.0-M\wso2\BUSINE~1\bin\..\..\
components -Dcarbon.extensions.dir.path=C:\Users\ADMINI~1\Desktop\WSO2EI~1.0-M\w
so2\BUSINE~1\bin\..\..\..\extensions -Dcarbon.dropins.dir.path=C:\Users\ADMINI~1
\Desktop\WSO2EI~1.0-M\wso2\BUSINE~1\bin\..\..\components\dropins -Dcarbon.extern
al.lib.dir.path=C:\Users\ADMINI~1\Desktop\WSO2EI~1.0-M\wso2\BUSINE~1\bin\..\..\.
.\lib -Dcarbon.patches.dir.path=C:\Users\ADMINI~1\Desktop\WSO2EI~1.0-M\wso2\BUSI
NE~1\bin\..\..\..\patches -Dcarbon.servicepacks.dir.path=C:\Users\ADMINI~1\Deskt
op\WSO2EI~1.0-M\wso2\BUSINE~1\bin\..\..\..\servicepacks -Dcarbon.internal.lib.di
r.path=C:\Users\ADMINI~1\Desktop\WSO2EI~1.0-M\wso2\BUSINE~1\bin\..\..\lib -Dconf
.location=C:\Users\ADMINI~1\Desktop\WSO2EI~1.0-M\wso2\BUSINE~1\bin\..\conf -Dcom
.atomikos.icatch.file=C:\Users\ADMINI~1\Desktop\WSO2EI~1.0-M\wso2\BUSINE~1\bin\.
.\..\lib\transactions.properties -Dcom.atomikos.icatch.hide_init_file_path=true
-Dorg.apache.jasper.compiler.Parser.STRICT_QUOTE_ESCAPING=false -Dorg.apache.jas
per.runtime.BodyContentImpl.LIMIT_BUFFER=true -Dcom.sun.jndi.ldap.connect.pool.a
uthentication=simple -Dcom.sun.jndi.ldap.connect.pool.timeout=3000 -Dorg.terraco
tta.quartz.skipUpdateCheck=true -Dcarbon.classpath=.\lib;C:\Program
C:\Users\Administrator\Desktop\wso2ei-6.0.0-m1\wso2\broker\bin>`

**Comment by mpmunasinghe** [comment]
Fixed with https://github.com/wso2/product-ei/pull/84/commits/fa4c4a004808689da5c83af81bdd10c8700c07c0
