### ISSUE TITLE
./wsdl2java.sh script doesn't work as intended and gives errors

### ISSUE THREAD

**Issue by gvasanka** [wso2/product-ei#376]
Getting following when running ./wsdl2java.sh available on EI_HOME\bin folder
Using IBM JDK 1.8

```
asankav@asankav-ThinkPad-T540p:~/servers/releasetest/ei/23/profile/ana/wso2ei-6.1.0-SNAPSHOT/bin$ ./wsdl2java.sh -uri http://localhost:9000/services/SimpleStockQuoteService?wsdl
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.

BUILD SUCCESSFUL
Total time: 0 seconds
log4j:WARN Error during default initialization
java.lang.NoClassDefFoundError: org.wso2.carbon.bootstrap.logging.LoggingBridge
	at java.lang.ClassLoader.defineClass(ClassLoader.java:346)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:154)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:727)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:95)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1182)
	at java.security.AccessController.doPrivileged(AccessController.java:686)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:602)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:846)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:825)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:325)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:805)
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at org.apache.log4j.helpers.Loader.loadClass(Loader.java:198)
	at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:327)
	at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:124)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:785)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.apache.log4j.Logger.getLogger(Logger.java:104)
	at org.apache.commons.logging.impl.Log4JLogger.getLogger(Log4JLogger.java:262)
	at org.apache.commons.logging.impl.Log4JLogger.<init>(Log4JLogger.java:108)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:88)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:437)
	at org.apache.commons.logging.impl.LogFactoryImpl.createLogFromClass(LogFactoryImpl.java:1025)
	at org.apache.commons.logging.impl.LogFactoryImpl.discoverLogImplementation(LogFactoryImpl.java:844)
	at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:541)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:292)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:269)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
	at org.apache.axis2.wsdl.codegen.CodeGenerationEngine.<clinit>(CodeGenerationEngine.java:59)
	at org.apache.axis2.wsdl.WSDL2Code.main(WSDL2Code.java:35)
	at org.apache.axis2.wsdl.WSDL2Java.main(WSDL2Java.java:24)
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.bootstrap.logging.LoggingBridge
	at java.net.URLClassLoader.findClass(URLClassLoader.java:607)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:846)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:825)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:325)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:805)
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	... 39 more
Retrieving document at 'http://localhost:9000/services/SimpleStockQuoteService?wsdl'.
```

**Comment by nandika** [comment]
Fixed with https://github.com/wso2/product-ei/pull/425

**Comment by nandika** [comment]
https://github.com/wso2/product-ei/pull/425 fixes this issue

**Comment by nandika** [comment]
https://github.com/wso2/product-ei/pull/434

Fixed
