### ISSUE TITLE
[Analytics] Exception when trying to log into dashboard 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3773]
**Description:**

Affected version : 6.5.0 - M7

Steps to reproduce: 

1. Start analytics profile dashboard ./analytics-dashboard.sh
2. Try to log in at https://192.168.8.100:9643/portal
3. You will get below exception a few times on the log

```
[2019-04-23 11:55:55,069]  WARN {io.netty.channel.DefaultChannelPipeline} - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1615)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1781)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1070)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:896)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:766)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:292)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1248)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1194)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	... 16 more
```

**Comment by abeykoon** [comment]
This is because in the certificate we pack by default has not contain ` Subject Alternative Name Field s`.  Please refer below. It is enforced by chrome browser, but not by firefox as of 16 th OCT 2019. 

[1]. https://www.digicert.com/subject-alternative-name.htm
[2]. https://knowledge.digicert.com/solution/SO9440.html

**Comment by abeykoon** [comment]
At production, customer should include certificates with SAN fields. Hence, lowing the priority.

**Comment by sameeragunarathne** [comment]
Let's update the docs on these to update the certificates with SANs provided

**Comment by praveennadarajah** [comment]
The relevant information about certificates with SAN fields is included in[1] and [2]. Hence closing the issue.
[1] https://docs.wso2.com/display/EI6xx/Using+the+Analytics+Dashboard
[2] https://docs.wso2.com/display/EI650/Using+the+Analytics+Dashboard
