### ISSUE TITLE
fn:replace() function (XPath 2.0) does not support $ctx XPath functions with the child elements as input arguments for OM properties 

### ISSUE THREAD

**Issue by VirajHasitha** [wso2/product-ei#3798]
**Description:**
It is unable to write a single expression for fn:replace() using $ctx XPath functions with the child elements as an input argument for OM properties.

**Affected Product Version:**
EI 6.2.0  

**Steps to reproduce:**
Create a proxy service which has an OM property as below

```
<property name="vars" scope="default">
   <root xmlns="http://wso2.example/vars">
     <item>name</item>
   </root>
</property>
```

Write a property with an expression using the fn:replace() function to replace the item value as below. 

`<property expression="fn:replace($ctx:vars//v:item, 'n', 'N')" name="item2" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:v="http://wso2.example/vars"/>`

Execute this proxy service will result in an Error as below

```
ERROR - SynapseXPath Evaluation of the XPath expression fn:replace($ctx:vars//v:item, 'n', 'N') resulted in an error
; Line#: 1; Column#: -1
net.sf.saxon.trans.XPathException: Required item type of first operand of '/' is node(); supplied value has item type javatype:org.apache.axiom.om.impl.llom.OMElementImpl
	at net.sf.saxon.expr.ItemTypeCheckingFunction.testConformance(ItemTypeCheckingFunction.java:65)
	at net.sf.saxon.expr.ItemTypeCheckingFunction.mapItem(ItemTypeCheckingFunction.java:41)
	at net.sf.saxon.expr.ItemMappingIterator.next(ItemMappingIterator.java:90)
	at net.sf.saxon.expr.ContextMappingIterator.next(ContextMappingIterator.java:52)
	at net.sf.saxon.value.SequenceExtent.<init>(SequenceExtent.java:105)
	at net.sf.saxon.expr.sort.DocumentOrderIterator.<init>(DocumentOrderIterator.java:31)
	at net.sf.saxon.expr.sort.DocumentSorter.iterate(DocumentSorter.java:101)
	at net.sf.saxon.expr.Atomizer.iterate(Atomizer.java:230)
	at net.sf.saxon.expr.AtomicSequenceConverter.iterate(AtomicSequenceConverter.java:281)
	at net.sf.saxon.expr.CardinalityChecker.evaluateItem(CardinalityChecker.java:249)
	at net.sf.saxon.functions.Replace.evaluateItem(Replace.java:119)
	at net.sf.saxon.expr.Expression.iterate(Expression.java:429)
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:326)
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:389)
	at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:642)
	at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:475)
	at org.apache.synapse.mediators.builtin.PropertyMediator.getResultValue(PropertyMediator.java:366)
	at org.apache.synapse.mediators.builtin.PropertyMediator.mediate(PropertyMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:224)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:415)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by GDLMadushanka** [comment]
I tried with the following configs but couldn't get it done.
```
<property name="vars" scope="default">
                <root xmlns="http://wso2.example/vars">
                    <item>name</item>
                </root>
            </property>
            <property name="apos" scope="default" type="STRING" value="'"/>
            <property expression="fn:concat('fn:replace(',get-property('apos'),$ctx:vars,get-property('apos'),',',get-property('apos'),'n',get-property('apos'),',',get-property('apos'),'N',get-property('apos'),')')" name="d" scope="default" type="STRING"/>
            <log>
                <property expression="$ctx:d" name="xpathexspr"/>
                <property expression="evaluate($ctx:d)" name="xpathexpr"/>
            </log>
            <respond/>
```
Seems like not achievable using only Xpath expressions

**Comment by IvenYan** [comment]
I have a related issue, (I use micro integration). Here is my issue:
{SynapseXPath} Evaluation of the XPath expression replace(//@user_varchar2,'CARBON','') resulted in an error
org.jaxen.UnresolvableException: No Such Function replace
	at org.jaxen.SimpleFunctionContext.getFunction(SimpleFunctionContext.java:127) ~[axiom_1.2.11.wso2v16.jar:?]
	at org.apache.synapse.util.xpath.SynapseXPathFunctionContext.getFunction(SynapseXPathFunctionContext.java:101) ~[?:?]
	at org.jaxen.ContextSupport.getFunction(ContextSupport.java:242) ~[axiom_1.2.11.wso2v16.jar:?]
	at org.jaxen.Context.getFunction(Context.java:216) ~[axiom_1.2.11.wso2v16.jar:?]
	at org.jaxen.expr.DefaultFunctionCallExpr.evaluate(DefaultFunctionCallExpr.java:176) ~[axiom_1.2.11.wso2v16.jar:?]
	at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:102) ~[axiom_1.2.11.wso2v16.jar:?]
	at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:675) ~[axiom_1.2.11.wso2v16.jar:?]
	at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:215) ~[axiom_1.2.11.wso2v16.jar:?]
	at org.jaxen.BaseXPath.evaluate(BaseXPath.java:175) ~[axiom_1.2.11.wso2v16.jar:?]

The source code:  <property expression="fn:replace(//@user_varchar2,'CARBON','')" name="ls.var.user_varchar2" scope="default" type="STRING"/>

**Comment by GDLMadushanka** [comment]
Hi @IvenYan,

Did you enable the xpath 2.0 

You can enable xpath 2.0 by adding the following configuration to <MI_HOME>/conf/deployment.toml file
```
[mediation] 
synapse.enable_xpath_dom_failover=true
```

Thanks,
Lahiru
