### ISSUE TITLE
Cannot create google spreadsheet datasource in query mode

### ISSUE THREAD

**Issue by Vathsan** [wso2/product-ei#3803]
**Description:**
When creating a google spreadsheet datasource in query mode CONNECTION_UNAVAILABLE_ERROR occurs. It shows the artifact as faulty artifact in management console. 

Note: When creating the datasource using the management console, at edit datasource wizard 'Test Connection' option says connection successful for the same spreadsheet URL. 

`DS Fault Message: Error in retrieving Feed data Not Found DS Code: CONNECTION_UNAVAILABLE_ERROR Source Data Service:- Name: sampleService2 Location: /sampleService2.dbs Description: N/A Default Namespace: http://ws.wso2.org/dataservice Nested Exception:- java.sql.SQLException: Error in retrieving Feed data Not Found at org.wso2.carbon.dataservices.core.description.config.RDBMSConfig.<init>(RDBMSConfig.java:45) at org.wso2.carbon.dataservices.core.description.config.ConfigFactory.getRDBMSConfig(ConfigFactory.java:92) at org.wso2.carbon.dataservices.core.description.config.ConfigFactory.createConfig(ConfigFactory.java:60) at org.wso2.carbon.dataservices.core.DataServiceFactory.createDataService(DataServiceFactory.java:160) at org.wso2.carbon.dataservices.core.DBDeployer.createDBService(DBDeployer.java:811) at org.wso2.carbon.dataservices.core.DBDeployer.processService(DBDeployer.java:1169) at org.wso2.carbon.dataservices.core.DBDeployer.deploy(DBDeployer.java:202) at org.wso2.carbon.dataservices.core.FaultyServiceRectifier.run(FaultyServiceRectifier.java:110) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: java.sql.SQLException: Error in retrieving Feed data Not Found at org.wso2.carbon.dataservices.sql.driver.util.GSpreadFeedProcessor.getFeed(GSpreadFeedProcessor.java:237) at org.wso2.carbon.dataservices.sql.driver.TGSpreadConnection.extractSpreadSheetFeed(TGSpreadConnection.java:201) at org.wso2.carbon.dataservices.sql.driver.TGSpreadConnection.<init>(TGSpreadConnection.java:81) at org.wso2.carbon.dataservices.sql.driver.TConnectionFactory.createConnection(TConnectionFactory.java:34) at org.wso2.carbon.dataservices.sql.driver.TDriver.connect(TDriver.java:51) at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:278) at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182) at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:730) at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:664) at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:200) at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:127) at org.wso2.carbon.dataservices.core.description.config.SQLConfig.createConnection(SQLConfig.java:187) at org.wso2.carbon.dataservices.core.description.config.SQLConfig.createConnection(SQLConfig.java:173) at org.wso2.carbon.dataservices.core.description.config.SQLConfig.initSQLDataSource(SQLConfig.java:151) at org.wso2.carbon.dataservices.core.description.config.RDBMSConfig.<init>(RDBMSConfig.java:43) ... 14 more Caused by: com.google.gdata.util.ResourceNotFoundException: Not Found <!DOCTYPE html><html lang="si"><head><meta name="description" content="වෙබ් පද සැකසුම, ඉදිරිපත්කිරීම් සහ පැතිරුම්පත්"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0"><link rel="shortcut icon" href="//ssl.gstatic.com/docs/common/drive_favicon1.ico"><title>පිටුව හමු නොවීය</title><link href="//fonts.googleapis.com/css?family=Product+Sans" rel="stylesheet" type="text/css"><style>/* Copyright 2019 Google Inc. All Rights Reserved. */ .goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}#drive-logo{margin:18px 0;position:absolute;white-space:nowrap}.docs-drivelogo-img{background-image:url('//ssl.gstatic.com/images/branding/googlelogo/1x/googlelogo_color_116x41dp.png');background-size:116px 41px;display:inline-block;height:41px;vertical-align:bottom;width:116px}.docs-drivelogo-text{color:#000;display:inline-block;opacity:0.54;text-decoration:none;font-family:'Product Sans',Arial,Helvetica,sans-serif;font-size:32px;text-rendering:optimizeLegibility;position:relative;top:-6px;left:-7px;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}@media (-webkit-min-device-pixel-ratio:1.5),(min-resolution:144dpi){.docs-drivelogo-img{background-image:url('//ssl.gstatic.com/images/branding/googlelogo/2x/googlelogo_color_116x41dp.png')}}</style><style type="text/css">body {background-color: #fff; font-family: Arial,sans-serif; font-size: 13px; margin: 0; padding: 0;}a, a:link, a:visited {color: #112ABB;}</style><style type="text/css">.errorMessage {font-size: 12pt; font-weight: bold; line-height: 150%;}</style></head><body><div id="outerContainer"><div id="innerContainer"><div style="position: absolute; top: -80px;"><div style="margin: 18px 0; position: absolute; white-space: nowrap;"><a href="//support.google.com/docs/"><img height="35px" src="//ssl.gstatic.com/docs/common/product/spreadsheets_lockup1.png" alt="Google ලාංජනය"/></a></div></div><div align="center"><p class="errorMessage" style="padding-top: 50px">කනගාටුයි, මේ අවස්ථාවේදී ගොනුව විවෘත කළ නොහැකිය.</p><p> කරුණාකර ලිපිනය පරික්ෂා කර නැවත උත්සාහ කරන්න. </p><div style="background: #F0F6FF; border: 1px solid black; margin-top: 35px; padding: 10px 125px; width: 300px;"><p><strong>Google Drive සමඟ දේවල් කරගන්න</strong></p><p>Google Drive හි යෙදුම් මඟින් සබැඳි ලේඛන , පැතිරුම්පත්, ඉදිරිපත් කිරීම් සහ තවත් දේ නිර්මාණය කිරීමට, සුරැකීමට සහ බෙදා ගැනීමට වඩාත් පහසු වේ.</p><p><a href="https://drive.google.com/start/apps">drive.google.com/start/apps</a> හි සිට තවත් දැනගන්න.</p></div></div></div></div></body><style>#outerContainer {margin: auto; max-width: 750px;}#innerContainer {margin-bottom: 20px; margin-left: 40px; margin-right: 40px; margin-top: 80px; position: relative;}</style></html> at com.google.gdata.client.http.HttpGDataRequest.handleErrorResponse(HttpGDataRequest.java:599) at com.google.gdata.client.http.GoogleGDataRequest.handleErrorResponse(GoogleGDataRequest.java:564) at com.google.gdata.client.http.HttpGDataRequest.checkResponse(HttpGDataRequest.java:560) at com.google.gdata.client.http.HttpGDataRequest.execute(HttpGDataRequest.java:538) at com.google.gdata.client.http.GoogleGDataRequest.execute(GoogleGDataRequest.java:536) at com.google.gdata.client.Service.getFeed(Service.java:1135) at com.google.gdata.client.Service.getFeed(Service.java:1077) at com.google.gdata.client.GoogleService.getFeed(GoogleService.java:676) at com.google.gdata.client.Service.getFeed(Service.java:1034) at org.wso2.carbon.dataservices.sql.driver.util.GSpreadFeedProcessor.getFeed(GSpreadFeedProcessor.java:235) ... 28 more`

**Suggested Labels:**
EI 6.5.0
DSS

**Affected Product Version:**
EI 6.5.0-m7
   
**Steps to reproduce:**
1. Create a google spreadsheet datasource (select public visibility, refer: [1])
2. Make sure to test connection after providing the spreadsheet URL
3. Add a query to the datasource
4. Define an operation to invoke the query

[1]https://docs.google.com/spreadsheets/d/1pi7xz8fPaOUFiCX_3vkcdEfIJJwE_wId0K3Iqvmiw74/edit?usp=sharing

**Comment by Vathsan** [comment]
Query mode works fine with spreadsheets which have private visibility(we send a request with authorization parameters). It is not working for spreadsheet with public visibility eventhough spreadsheet is published to the web.
