### ISSUE TITLE
[Tooling] Exception when exporting artifacts as a CAR application

### ISSUE THREAD

**Issue by dilee** [wso2/product-ei#3817]
**Description:**
The following exception is thrown when exporting artifacts as a CAR application.

```
2019-04-30 10:44:22.925
!MESSAGE Error while cleaning the target directory
!STACK 0
java.lang.IllegalArgumentException: /Users/dileesha/Documents/runtime-EclipseApplication/TestProxyCompositeApplication/target does not exist
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1252)
	at org.wso2.developerstudio.eclipse.platform.core.project.export.ProjectArtifactHandler.clearTarget(ProjectArtifactHandler.java:92)
	at org.wso2.developerstudio.eclipse.distribution.project.export.CarExportHandler.exportArtifact(CarExportHandler.java:73)
```

**Steps to reproduce:**
1. Create a ESB project.
2. Try to export artifacts as a CAR file.

**Related Issues:**
https://github.com/wso2/product-ei/issues/3801

**Comment by dilee** [comment]
Fixed in https://github.com/wso2/developer-studio/pull/182
