### ISSUE TITLE
Unable to deploy a car file having registry sequence

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#3868]
**Description:**
Error thrown in console while deploying following artifact.

```
<?xml version="1.0" encoding="UTF-8"?>
<proxy name="testSeqTooling" startOnLoad="true" transports="http https" xmlns="http://ws.apache.org/ns/synapse">
    <target>
        <inSequence>
            <log level="custom">
                <property name="== Proxy ===" value="===== Invoked ======"/>
            </log>
            <call>
                <endpoint key="gov:/regSeq"/>
            </call>
            <payloadFactory media-type="xml">
                <format>
                    <niro xmlns="">ram</niro>
                </format>
                <args/>
            </payloadFactory>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </target>
</proxy>
```

**Steps to reproduce:**

Deploy the attached car file ( after renaming to .car )
[TestTemplateCompositeApplication_1.0.0.zip](https://github.com/wso2/product-ei/files/3141623/TestTemplateCompositeApplication_1.0.0.zip)

Following error thrown in console
```
[2019-05-03 16:46:09,639] [EI-Core] ERROR - IndirectEndpointFactory Invalid endpoint configuration.
[2019-05-03 16:46:09,647] [EI-Core] ERROR - ProxyServiceDeployer ProxyService Deployment from the file : /home/nirothipan/Desktop/trash/wso2ei-6.5.0-m7-SNAPSHOT/wso2/tmp/carbonapps/-1234/1556881938325TestTemplateCompositeApplication_1.0.0.car/testSeqTooling_1.0.0/testSeqTooling-1.0.0.xml : Failed.
org.apache.synapse.SynapseException: Invalid endpoint configuration.
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.handleException(EndpointFactory.java:330)
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.getEndpointFactory(EndpointFactory.java:260)
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.getEndpointFromElement(EndpointFactory.java:80)
	at org.apache.synapse.config.xml.endpoints.XMLToEndpointMapper.getObjectFromOMNode(XMLToEndpointMapper.java:55)
	at org.apache.synapse.registry.AbstractRegistry.getResource(AbstractRegistry.java:142)
	at org.apache.synapse.config.SynapseConfiguration.getEndpoint(SynapseConfiguration.java:1054)
	at org.apache.synapse.endpoints.IndirectEndpoint.reLoadAndInitEndpoint(IndirectEndpoint.java:173)
	at org.apache.synapse.endpoints.IndirectEndpoint.init(IndirectEndpoint.java:114)
	at org.apache.synapse.mediators.builtin.CallMediator.init(CallMediator.java:311)
	at org.apache.synapse.mediators.AbstractListMediator.init(AbstractListMediator.java:194)
	at org.apache.synapse.mediators.base.SequenceMediator.init(SequenceMediator.java:315)
	at org.apache.synapse.deployers.ProxyServiceDeployer.initializeProxy(ProxyServiceDeployer.java:260)
	at org.apache.synapse.deployers.ProxyServiceDeployer.deploySynapseArtifact(ProxyServiceDeployer.java:77)
	at org.wso2.carbon.proxyadmin.ProxyServiceDeployer.deploySynapseArtifact(ProxyServiceDeployer.java:46)
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:197)
	at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifactType(SynapseAppDeployer.java:1099)
	at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifacts(SynapseAppDeployer.java:114)
	at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:272)
	at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:72)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2019-05-03 16:46:09,651] [EI-Core] ERROR - AbstractSynapseArtifactDeployer Deployment of the Synapse Artifact from file : /home/nirothipan/Desktop/trash/wso2ei-6.5.0-m7-SNAPSHOT/wso2/tmp/carbonapps/-1234/1556881938325TestTemplateCompositeApplication_1.0.0.car/testSeqTooling_1.0.0/testSeqTooling-1.0.0.xml : Failed!
org.apache.synapse.deployers.SynapseArtifactDeploymentException: ProxyService Deployment from the file : /home/nirothipan/Desktop/trash/wso2ei-6.5.0-m7-SNAPSHOT/wso2/tmp/carbonapps/-1234/1556881938325TestTemplateCompositeApplication_1.0.0.car/testSeqTooling_1.0.0/testSeqTooling-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.handleSynapseArtifactDeploymentError(AbstractSynapseArtifactDeployer.java:480)
	at org.apache.synapse.deployers.ProxyServiceDeployer.deploySynapseArtifact(ProxyServiceDeployer.java:124)
	at org.wso2.carbon.proxyadmin.ProxyServiceDeployer.deploySynapseArtifact(ProxyServiceDeployer.java:46)
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:197)
	at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifactType(SynapseAppDeployer.java:1099)
	at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifacts(SynapseAppDeployer.java:114)
	at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:272)
	at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:72)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.synapse.SynapseException: Invalid endpoint configuration.
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.handleException(EndpointFactory.java:330)
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.getEndpointFactory(EndpointFactory.java:260)
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.getEndpointFromElement(EndpointFactory.java:80)
	at org.apache.synapse.config.xml.endpoints.XMLToEndpointMapper.getObjectFromOMNode(XMLToEndpointMapper.java:55)
	at org.apache.synapse.registry.AbstractRegistry.getResource(AbstractRegistry.java:142)
	at org.apache.synapse.config.SynapseConfiguration.getEndpoint(SynapseConfiguration.java:1054)
	at org.apache.synapse.endpoints.IndirectEndpoint.reLoadAndInitEndpoint(IndirectEndpoint.java:173)
	at org.apache.synapse.endpoints.IndirectEndpoint.init(IndirectEndpoint.java:114)
	at org.apache.synapse.mediators.builtin.CallMediator.init(CallMediator.java:311)
	at org.apache.synapse.mediators.AbstractListMediator.init(AbstractListMediator.java:194)
	at org.apache.synapse.mediators.base.SequenceMediator.init(SequenceMediator.java:315)
	at org.apache.synapse.deployers.ProxyServiceDeployer.initializeProxy(ProxyServiceDeployer.java:260)
	at org.apache.synapse.deployers.ProxyServiceDeployer.deploySynapseArtifact(ProxyServiceDeployer.java:77)
	... 23 more
[2019-05-03 16:46:09,655] [EI-Core]  INFO - AbstractSynapseArtifactDeployer The file has been backed up into : NO_BACKUP_ON_WORKER.INFO
[2019-05-03 16:46:09,656] [EI-Core] ERROR - AbstractSynapseArtifactDeployer Deployment of synapse artifact failed. Error reading /home/nirothipan/Desktop/trash/wso2ei-6.5.0-m7-SNAPSHOT/wso2/tmp/carbonapps/-1234/1556881938325TestTemplateCompositeApplication_1.0.0.car/testSeqTooling_1.0.0/testSeqTooling-1.0.0.xml : ProxyService Deployment from the file : /home/nirothipan/Desktop/trash/wso2ei-6.5.0-m7-SNAPSHOT/wso2/tmp/carbonapps/-1234/1556881938325TestTemplateCompositeApplication_1.0.0.car/testSeqTooling_1.0.0/testSeqTooling-1.0.0.xml : Failed.
org.apache.axis2.deployment.DeploymentException: ProxyService Deployment from the file : /home/nirothipan/Desktop/trash/wso2ei-6.5.0-m7-SNAPSHOT/wso2/tmp/carbonapps/-1234/1556881938325TestTemplateCompositeApplication_1.0.0.car/testSeqTooling_1.0.0/testSeqTooling-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:207)
	at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifactType(SynapseAppDeployer.java:1099)
	at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifacts(SynapseAppDeployer.java:114)
	at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:272)
	at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:72)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.synapse.deployers.SynapseArtifactDeploymentException: ProxyService Deployment from the file : /home/nirothipan/Desktop/trash/wso2ei-6.5.0-m7-SNAPSHOT/wso2/tmp/carbonapps/-1234/1556881938325TestTemplateCompositeApplication_1.0.0.car/testSeqTooling_1.0.0/testSeqTooling-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.handleSynapseArtifactDeploymentError(AbstractSynapseArtifactDeployer.java:480)
	at org.apache.synapse.deployers.ProxyServiceDeployer.deploySynapseArtifact(ProxyServiceDeployer.java:124)
	at org.wso2.carbon.proxyadmin.ProxyServiceDeployer.deploySynapseArtifact(ProxyServiceDeployer.java:46)
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:197)
	... 21 more
Caused by: org.apache.synapse.SynapseException: Invalid endpoint configuration.
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.handleException(EndpointFactory.java:330)
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.getEndpointFactory(EndpointFactory.java:260)
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.getEndpointFromElement(EndpointFactory.java:80)
	at org.apache.synapse.config.xml.endpoints.XMLToEndpointMapper.getObjectFromOMNode(XMLToEndpointMapper.java:55)
	at org.apache.synapse.registry.AbstractRegistry.getResource(AbstractRegistry.java:142)
	at org.apache.synapse.config.SynapseConfiguration.getEndpoint(SynapseConfiguration.java:1054)
	at org.apache.synapse.endpoints.IndirectEndpoint.reLoadAndInitEndpoint(IndirectEndpoint.java:173)
	at org.apache.synapse.endpoints.IndirectEndpoint.init(IndirectEndpoint.java:114)
	at org.apache.synapse.mediators.builtin.CallMediator.init(CallMediator.java:311)
	at org.apache.synapse.mediators.AbstractListMediator.init(AbstractListMediator.java:194)
	at org.apache.synapse.mediators.base.SequenceMediator.init(SequenceMediator.java:315)
	at org.apache.synapse.deployers.ProxyServiceDeployer.initializeProxy(ProxyServiceDeployer.java:260)
	at org.apache.synapse.deployers.ProxyServiceDeployer.deploySynapseArtifact(ProxyServiceDeployer.java:77)
	... 23 more
[2019-05-03 16:46:09,659] [EI-Core] ERROR - ApplicationManager Error occurred while deploying Carbon Application
org.apache.axis2.deployment.DeploymentException: ProxyService Deployment from the file : /home/nirothipan/Desktop/trash/wso2ei-6.5.0-m7-SNAPSHOT/wso2/tmp/carbonapps/-1234/1556881938325TestTemplateCompositeApplication_1.0.0.car/testSeqTooling_1.0.0/testSeqTooling-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:219)
	at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifactType(SynapseAppDeployer.java:1099)
	at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifacts(SynapseAppDeployer.java:114)
	at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:272)
	at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:72)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.deployment.DeploymentException: ProxyService Deployment from the file : /home/nirothipan/Desktop/trash/wso2ei-6.5.0-m7-SNAPSHOT/wso2/tmp/carbonapps/-1234/1556881938325TestTemplateCompositeApplication_1.0.0.car/testSeqTooling_1.0.0/testSeqTooling-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:207)
	... 21 more
Caused by: org.apache.synapse.deployers.SynapseArtifactDeploymentException: ProxyService Deployment from the file : /home/nirothipan/Desktop/trash/wso2ei-6.5.0-m7-SNAPSHOT/wso2/tmp/carbonapps/-1234/1556881938325TestTemplateCompositeApplication_1.0.0.car/testSeqTooling_1.0.0/testSeqTooling-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.handleSynapseArtifactDeploymentError(AbstractSynapseArtifactDeployer.java:480)
	at org.apache.synapse.deployers.ProxyServiceDeployer.deploySynapseArtifact(ProxyServiceDeployer.java:124)
	at org.wso2.carbon.proxyadmin.ProxyServiceDeployer.deploySynapseArtifact(ProxyServiceDeployer.java:46)
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:197)
	... 21 more
Caused by: org.apache.synapse.SynapseException: Invalid endpoint configuration.
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.handleException(EndpointFactory.java:330)
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.getEndpointFactory(EndpointFactory.java:260)
	at org.apache.synapse.config.xml.endpoints.EndpointFactory.getEndpointFromElement(EndpointFactory.java:80)
	at org.apache.synapse.config.xml.endpoints.XMLToEndpointMapper.getObjectFromOMNode(XMLToEndpointMapper.java:55)
	at org.apache.synapse.registry.AbstractRegistry.getResource(AbstractRegistry.java:142)
	at org.apache.synapse.config.SynapseConfiguration.getEndpoint(SynapseConfiguration.java:1054)
	at org.apache.synapse.endpoints.IndirectEndpoint.reLoadAndInitEndpoint(IndirectEndpoint.java:173)
	at org.apache.synapse.endpoints.IndirectEndpoint.init(IndirectEndpoint.java:114)
	at org.apache.synapse.mediators.builtin.CallMediator.init(CallMediator.java:311)
	at org.apache.synapse.mediators.AbstractListMediator.init(AbstractListMediator.java:194)
	at org.apache.synapse.mediators.base.SequenceMediator.init(SequenceMediator.java:315)
	at org.apache.synapse.deployers.ProxyServiceDeployer.initializeProxy(ProxyServiceDeployer.java:260)
	at org.apache.synapse.deployers.ProxyServiceDeployer.deploySynapseArtifact(ProxyServiceDeployer.java:77)
	... 23 more

```

**Comment by Nirothipan** [comment]
Tested with 6.5.0 m7 pack

**Comment by Nirothipan** [comment]
This is happening since sequence is selected instead of Endpoint. Hence closing
