### ISSUE TITLE
Default RESTBasicAuthHandler is not working properly.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#4063]
**Description:**
$subject

**Steps to reproduce:**

- Follow https://docs.wso2.com/display/EI6xx/Applying+Security+to+an+API#ea063f428dad42c39f33c679501bf320
- Invoke the api with basic auth header. ( Authorization : YWRtaW46YWRtaW4= )
- Following error is thrown

```
[2019-05-21 20:32:08,062] [EI-Core] ERROR - ServerWorker Error processing GET request for : /stockquote/view/IBM. 
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.wso2.carbon.integrator.core.handler.RESTBasicAuthHandler.processSecurity(RESTBasicAuthHandler.java:104)
	at org.wso2.carbon.integrator.core.handler.RESTBasicAuthHandler.handleRequest(RESTBasicAuthHandler.java:65)
	at org.apache.synapse.rest.API.process(API.java:357)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:135)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:113)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:338)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:159)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mbouchar** [comment]
When adding authorization to the basic auth handler, I found that there's no checks before parsing the authorization header. Common errors that are not checked :
- No check about a missing Authorization header value
- Invalid Base64 value
- Invalid formatting of "username:password" value (ex: missing ":")

**Comment by mathieubouchard** [comment]
I created https://github.com/wso2/carbon-mediation/pull/1264, which add the parsing checks. But that pull request has more changes, including adding authorization handling for the basic http handler.
