### ISSUE TITLE
Runtime error is thrown when inserting null headers into the header mediator that is defined inside the onCacheHit segment in the cache mediator 

### ISSUE THREAD

**Issue by PrabhashDilhan** [wso2/product-ei#4073]
**Description:**
Below run time exception is thrown when inserting null headers into the header mediator that is defined inside the **onCacheHit** segment in the cache mediator.

Runtime error occurred while mediating the message {org.apache.synapse.config.xml.AnonymousListMediator}
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at org.apache.synapse.mediators.transform.HeaderMediator.mediate(HeaderMediator.java:188)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
        at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:37)
        at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:203)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
        at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:37)
        at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:203)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
        at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:169)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.wso2.carbon.mediator.cache.CacheMediator.replaceEnvelopeWithCachedResponse(CacheMediator.java:359)
        at org.wso2.carbon.mediator.cache.CacheMediator.processRequestMessage(CacheMediator.java:295)
        at org.wso2.carbon.mediator.cache.CacheMediator.mediate(CacheMediator.java:222)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.rest.Resource.process(Resource.java:364)
        at org.apache.synapse.rest.API.process(API.java:417)
        at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:135)
        at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:113)
        at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
        at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
        at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
        at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
        at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:383)
        at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 6.4.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

- Deploy the proxy service shared below
```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="MyProxy"
       startOnLoad="true"
       statistics="enable"
       trace="enable"
       transports="http,https">
   <target>
      <inSequence>
         <log/>
         <property expression="$trp:X-SE-IFW-ApplicationName"
                   name="stockprop"
                   scope="operation"
                   type="STRING"/>
         <cache collector="false" timeout="120">
            <onCacheHit>
               <log/>
               <log level="custom">
                  <property expression="get-property('operation','stockprop')"
                            name="OnCache********************"/>
               </log>
               <header expression="get-property('operation','stockprop')"
                       name="MMY"
                       scope="transport"/>
               <header expression="get-property('operation','stockprop')"
                       name="MMY2"
                       scope="transport"/>
               <log level="custom">
                  <property expression="$trp:MMY" name="****header is set"/>
               </log>
               <respond/>
            </onCacheHit>
            <protocol type="HTTP">
               <methods>*</methods>
               <headersToExcludeInHash/>
               <responseCodes>.*</responseCodes>
               <enableCacheControl>false</enableCacheControl>
               <includeAgeHeader>false</includeAgeHeader>
               <hashGenerator>org.wso2.carbon.mediator.cache.digest.DOMHASHGenerator</hashGenerator>
            </protocol>
            <implementation maxSize="1000"/>
         </cache>
         <send>
            <endpoint>
               <http uri-template="http://www.mocky.io/v2/5ce28f9a340000a30c77354d"/>
            </endpoint>
         </send>
      </inSequence>
      <outSequence>
         <cache collector="true"/>
         <send/>
      </outSequence>
   </target>
   <description/>
</proxy>
````

- invoke it without the **X-SE-IFW-ApplicationName** header.

**Related Issues:**

**Comment by abeykoon** [comment]
If we send a HTTP header via HTTP/HTTPs transport without a value, it will be set to empty by default. The question only is with internally evaluated property is set as a header and it evaluates to null. 

So the solution is to set a empty string as the header when evaluated value becomes null.

**Comment by abeykoon** [comment]
In case, this goes unnoticed, following warning will get printed upon setting a empty string as the value of the header. 

`[2019-05-23 13:44:02,022] [EI-Core]  WARN - HeaderMediator Setting HTTP header : MMY to empty as evaluated value is null`
