### ISSUE TITLE
Escape special characters for xml payloads in payload factory mediator 

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/product-ei#4077]
**Description:**
Payload factory mediator produces following stack trace when building an XML payload with a special character in the incoming payload. 

`` [EI-Core] ERROR - SequenceMediator com.ctc.wstx.exc.WstxParsingException: Illegal character entity: expansion character (code 0xd85d
 at [row,col {unknown-source}]: [1,65]
org.apache.axiom.om.OMException: com.ctc.wstx.exc.WstxParsingException: Illegal character entity: expansion character (code 0xd85d
 at [row,col {unknown-source}]: [1,65]
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.build(OMSerializableImpl.java:78)
	at org.apache.axiom.om.impl.llom.OMElementImpl.build(OMElementImpl.java:722)
	at org.apache.axiom.om.impl.llom.OMElementImpl.detach(OMElementImpl.java:700)
	at org.apache.axiom.om.impl.llom.OMNodeImpl.setParent(OMNodeImpl.java:105)
	at org.apache.axiom.om.impl.llom.OMElementImpl.addChild(OMElementImpl.java:296)
	at org.apache.axiom.om.impl.llom.OMElementImpl.addChild(OMElementImpl.java:212)
	at org.apache.axiom.soap.impl.llom.SOAPBodyImpl.addChild(SOAPBodyImpl.java:231)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.mediate(PayloadFactoryMediator.java:172)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.mediate(PayloadFactoryMediator.java:112)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:260)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.mediateFromContinuationStateStack(Axis2SynapseEnvironment.java:783)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:281)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:574)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:193)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:263)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.ctc.wstx.exc.WstxParsingException: Illegal character entity: expansion character (code 0xd85d
 at [row,col {unknown-source}]: [1,65]
	at com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:606)
	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:479)
	at com.ctc.wstx.sr.StreamScanner.reportIllegalChar(StreamScanner.java:2448)
	at com.ctc.wstx.sr.StreamScanner.validateChar(StreamScanner.java:2377)
	at com.ctc.wstx.sr.StreamScanner.resolveCharEnt(StreamScanner.java:2361)
	at com.ctc.wstx.sr.StreamScanner.fullyResolveEntity(StreamScanner.java:1507)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2746)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1072)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
	... 21 more ``

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
EI-6.4.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

- create a payload with special characters
sample payload: ``{"test":"𧙗"}``

- evaluate the value from payload factory mediator to create an XML payload

**Related Issues:**

**Comment by sameeragunarathne** [comment]
This is fixed in the master with https://github.com/wso2/wso2-synapse/pull/1201/
