### ISSUE TITLE
NPE when using MS/MP in EI

### ISSUE THREAD

**Issue by keerthu** [wso2/product-ei#410]
Getting intermittent NPE as mentioned in https://wso2.org/jira/browse/INTESERVER-2 when they used MS/MP.

[2017-03-21 12:05:49,942] [] ERROR - SamplingService Error occurred while executing the message
org.apache.synapse.SynapseException: Runtime error occurred while mediating the message
        at org.apache.synapse.mediators.AbstractMediator.handleException(AbstractMediator.java:367)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:127)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.message.processor.impl.sampler.SamplingService$1.run(SamplingService.java:211)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.apache.synapse.mediators.store.MessageStoreMediator.getAxis2ParameterValue(MessageStoreMediator.java:226)
        at org.apache.synapse.mediators.store.MessageStoreMediator.mediate(MessageStoreMediator.java:108) 
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)

**Comment by nandika** [comment]
This is same as https://github.com/wso2/product-ei/issues/427
