### ISSUE TITLE
Class cast exception when parsing a json-eval expression to sequence template

### ISSUE THREAD

**Issue by nuwanw** [wso2/product-ei#4127]
Bellow exception occurred when json-eval expression is used in sequence template. This was working fine in previous releases(ESB 5.0.0) and this issue was introduced by an improvement done on evaluating expression path.  

Steps to recreate the issue in EI 6.4.0

```
<template name="LogTemplate" xmlns="http://ws.apache.org/ns/synapse">
    <parameter name="payload"/>
    <sequence>
        <log level="custom">
            <property expression="$func:payload" name="template"
                xmlns:ns="http://org.apache.synapse/xsd" xmlns:ns2="http://org.apache.synapse/xsd"/>
        </log>
      <drop/>
    </sequence>
</template>
```

Sample API

```
<api xmlns="http://ws.apache.org/ns/synapse" name="Test" context="/test">
   <resource methods="POST">
      <inSequence>
         <call-template target="LogTemplate">
            <with-param name="payload" value="{json-eval($.name)}"/>
         </call-template>
         <drop/>
      </inSequence>
   </resource>
</api>
```

curl -v  -X POST -H "Content-Type:application/json" -d '{"person" : {"name" : "abc" }}' http://localhost:8280/test

Once you invoke the service, you will be getting bellow exception.
```[2019-06-11 16:40:36,173] [EI-Core] ERROR - SequenceMediator org.apache.synapse.core.axis2.Axis2MessageContext cannot be cast to org.apache.axiom.om.OMNode
java.lang.ClassCastException: org.apache.synapse.core.axis2.Axis2MessageContext cannot be cast to org.apache.axiom.om.OMNode
	at org.apache.axiom.om.xpath.DocumentNavigator.getDocumentNode(DocumentNavigator.java:602)
	at org.jaxen.expr.DefaultAbsoluteLocationPath.evaluate(DefaultAbsoluteLocationPath.java:102)
	at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:102)
	at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:677)
	at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:216)
	at org.jaxen.BaseXPath.selectSingleNode(BaseXPath.java:237)
	at org.apache.synapse.mediators.Value.resolveObject(Value.java:165)
	at org.apache.synapse.mediators.template.TemplateContext.resolveExpressionValue(TemplateContext.java:111)
	at org.apache.synapse.mediators.template.TemplateContext.getEvaluatedParamValue(Unknown Source)
	at org.apache.synapse.mediators.template.TemplateContext.setupParams(Unknown Source)
	at org.apache.synapse.mediators.template.TemplateMediator.pushFuncContextTo(TemplateMediator.java:121)
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:101)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:148)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:84)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:351)
	at org.apache.synapse.rest.API.process(API.java:417)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:135)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:113)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:383)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by nuwanw** [comment]
Fix https://github.com/wso2/wso2-synapse/pull/1366

**Comment by isudana** [comment]
https://github.com/wso2/wso2-synapse/pull/1366 fixes the issue, but let's keep this issue open to tracking the progress of refactoring template parameter evaluation logic as discussed in the PR.
