### ISSUE TITLE
[ DSS ] Path params not getting populated for DELETE requests in PTT.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#4128]
**Description:**
$subject.

Invoking the following data service

```
<data enableBatchRequests="true" name="DELETEWithBatchTest" serviceNamespace="http://ws.wso2.org/dataservice" transports="http https">
   <config id="default">
      <property name="org.wso2.ws.dataservice.driver">org.h2.Driver</property>
      <property name="org.wso2.ws.dataservice.protocol">jdbc:h2:file:./../../h2DataBase/testdb267563828</property>
      <property name="org.wso2.ws.dataservice.user">wso2carbon</property>
      <property name="org.wso2.ws.dataservice.password">wso2carbon</property>
      <property name="org.wso2.ws.dataservice.minpoolsize">1</property>
      <property name="org.wso2.ws.dataservice.maxpoolsize">10</property>
      <property name="org.wso2.ws.dataservice.autocommit">false</property>
      <property name="org.wso2.ws.dataservice.validation_query">SELECT 1</property>
   </config>
   <query id="deleteFilter" useConfig="default">
      <sql>DELETE FROM FILTER WHERE REC_ID = :id</sql>
      <param name="id" sqlType="INTEGER"/>
   </query>
   <resource method="DELETE" path="filter/{id}">
      <call-query href="deleteFilter">
         <with-param name="id" query-param="id"/>
      </call-query>
   </resource>
</data>
```

with url **http://localhost:8280/services/DELETEWithBatchTest/filter/2** ( HTTP DELETE )

ends up in following error.

```DS Fault Message: Error in DS non result invoke.
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Nested Exception:-
javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:id
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Source Data Service:-
Name: DELETEWithBatchTest
Location: /DELETEWithBatchTest.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: _deletefilter_id
Current Params: {}


	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processSingleRequest(SingleDataServiceRequest.java:118)
	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:67)
	at org.wso2.carbon.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:359)
	at org.wso2.carbon.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:41)
	at org.wso2.carbon.dataservices.core.DBInOnlyMessageReceiver.invokeBusinessLogic(DBInOnlyMessageReceiver.java:53)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:338)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:383)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:id
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Source Data Service:-
Name: DELETEWithBatchTest
Location: /DELETEWithBatchTest.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: _deletefilter_id
Current Params: {}

	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.execute(DSOMDataSource.java:102)
	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.serialize(DSOMDataSource.java:107)
	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.executeInOnly(DSOMDataSource.java:80)
	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processSingleRequest(SingleDataServiceRequest.java:116)
	... 13 more
[2019-06-11 15:22:54,905] [EI-Core] ERROR - ServerWorker Error processing DELETE request for : /services/DELETEWithBatchTest/filter/2
org.apache.axis2.AxisFault: DS Fault Message: Error in DS non result invoke.
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Nested Exception:-
javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:id
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Source Data Service:-
Name: DELETEWithBatchTest
Location: /DELETEWithBatchTest.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: _deletefilter_id
Current Params: {}


	at org.wso2.carbon.dataservices.core.DBUtils.createAxisFault(DBUtils.java:801)
	at org.wso2.carbon.dataservices.core.DBInOnlyMessageReceiver.invokeBusinessLogic(DBInOnlyMessageReceiver.java:58)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:338)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:383)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:id
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Source Data Service:-
Name: DELETEWithBatchTest
Location: /DELETEWithBatchTest.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: _deletefilter_id
Current Params: {}

	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.execute(DSOMDataSource.java:102)
	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.serialize(DSOMDataSource.java:107)
	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.executeInOnly(DSOMDataSource.java:80)
	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processSingleRequest(SingleDataServiceRequest.java:116)
	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:67)
	at org.wso2.carbon.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:359)
	at org.wso2.carbon.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:41)
	at org.wso2.carbon.dataservices.core.DBInOnlyMessageReceiver.invokeBusinessLogic(DBInOnlyMessageReceiver.java:53)
	... 9 more
```

> We can achieve the same with serve let transport. Port ( 9773 ).

**Affected Product Version:**
All EI

**Related Issues:**
https://github.com/wso2/product-ei/issues/484
https://github.com/wso2/product-ei/issues/1788

**Comment by Nirothipan** [comment]
**DS1201DeleteWithBatchReqTest** is failing in Mi because of this issue.
