### ISSUE TITLE
Class cast exception when overriding FIX SessionEventHandler

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4134]
**Description:**

- A class cast exception is thrown when overriding the FIX sessionEven Handler

`Error while initializing the session event handler class: com.experimental.LogonExtension
java.lang.ClassCastException:com.experimental.LogonExtension cannot be cast to org.apache.synapse.transport.fix.SessionEventHandler
at org.apache.synapse.transport.fix.FIXIncomingMessageHandler.<init>(FIXIncomingMessageHandler.java:107)
at org.apache.synapse.transport.fix.FIXApplicationFactory.getFIXApplication(FIXApplicationFactory.java:36)
at org.apache.synapse.transport.fix.FIXSessionFactory.createFIXInitiator(FIXSessionFactory.java:254)
at org.apache.synapse.transport.fix.FIXTransportListener.startListeningForService(FIXTransportListener.java:77)
at org.apache.axis2.transport.base.AbstractTransportListener.internalStartListeningForService(AbstractTransportListener.java:213)
at org.apache.axis2.transport.base.AbstractTransportListener$2.serviceAdded(AbstractTransportListener.java:126)
at org.apache.axis2.transport.base.tracker.AxisServiceTracker.serviceAdded(AxisServiceTracker.java:212)
at org.apache.axis2.transport.base.tracker.AxisServiceTracker$1.serviceUpdate(AxisServiceTracker.java:98)
at org.apache.axis2.engine.AxisConfiguration.notifyObservers(AxisConfiguration.java:666)
at org.apache.axis2.engine.AxisConfiguration.addServiceGroup(AxisConfiguration.java:420)
at org.apache.axis2.engine.AxisConfiguration.addService(AxisConfiguration.java:350)
at org.apache.synapse.core.axis2.ProxyService.buildAxisService(ProxyService.java:761)
at org.apache.synapse.deployers.ProxyServiceDeployer.deploySynapseArtifact(ProxyServiceDeployer.java:82)
at org.wso2.carbon.proxyadmin.ProxyServiceDeployer.deploySynapseArtifact(ProxyServiceDeployer.java:46)
at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:197)
at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifactType(SynapseAppDeployer.java:1065)
at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifacts(SynapseAppDeployer.java:106)
at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:272)
at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:72)
at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
`

- Class causing the exception is as follows.

`import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.synapse.transport.fix.FIXIncomingMessageHandler;
import org.apache.synapse.transport.fix.SessionEventHandler;

import quickfix.FieldNotFound;
import quickfix.Message;
import quickfix.SessionID;
import quickfix.StringField;

public class LogonExtension implements SessionEventHandler {
	
	private static final Log log = LogFactory.getLog(LogonExtension.class);
	private static final String username = "wso2_fix_rfq_username";
	private static final String password = "wso2_fix_password";
	
	public LogonExtension() {
		log.info("LogonExtension initialized");
	}
	
	@Override
	public void onCreate(FIXIncomingMessageHandler fixIncomingMessageHandler, SessionID sessionID) {
		
	}
	
	@Override
	public void onLogon(FIXIncomingMessageHandler fixIncomingMessageHandler, SessionID sessionID) {
		
	}
	
	@Override
	public void onLogout(FIXIncomingMessageHandler fixIncomingMessageHandler, SessionID sessionID) {
		
	}
	
	@Override
	public void toAdmin(FIXIncomingMessageHandler fixIncomingMessageHandler, Message msg, SessionID sessionID) {
		log.info("Detected admin-level message, checking if logon details need to be added");
		try {
            StringField field = msg.getHeader().getField(new StringField(35));
            String value = field.getValue();
            
            if (value.equals("A")) {
            	log.info("Attaching username " + System.getenv(username) + " to 35=A logon message.");
            	msg.setField(553, new StringField(553, System.getenv(username)));
                msg.setField(554, new StringField(554, System.getenv(password)));
            	log.info("FIX message is now: " + msg);
            }
        } catch (FieldNotFound ex) {
        	ex.printStackTrace();
        	log.error("FieldNotFound error in FIX", ex);
        }
		
	}
	
	@Override
	public void fromAdmin(FIXIncomingMessageHandler fixIncomingMessageHandler, Message message, SessionID sessionID) {
		
	}
	
	@Override
	public void toApp(FIXIncomingMessageHandler fixIncomingMessageHandler, Message message, SessionID sessionID) {
		
	}
}`

- compile group: 'org.apache.synapse'

- name: 'synapse-fix-transport'

- version: '2.1.7-wso2v84'

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-5319

**Comment by PetteriPertola** [comment]
Hi, pls let me know if you need any further info about this. Would love to solve as the current work-around is a major hack.
