### ISSUE TITLE
SOAP to JSON Integration broken with JSONStreamBuilder/Formatter

### ISSUE THREAD

**Issue by dushansachinda** [wso2/product-ei#414]
**Just test with simple scenario with the following proxy, The Back End must be JSON, and client should be SOAP**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="WorkflowCallbackService"
       transports="https http"
       startOnLoad="true"
       trace="disable">
   <description/>
   <target>
      <inSequence>
         <property name="messageType"
                   value="application/x-www-form-urlencoded"
                   scope="axis2"
                   type="STRING"/>
         <send>
            <endpoint>
               <address uri="https://localhost:9443/store/site/blocks/workflow/workflow-listener/ajax/workflow-listener.jag"
                        format="rest"/>
            </endpoint>
         </send>
      </inSequence>
      <outSequence>
         <property name="messageType" value="text/xml" scope="axis2" type="STRING"/>
         <send/>
      </outSequence>
   </target>
</proxy>
```

```
[19:46:51,245{GMT}] DEBUG - headers http-outgoing-2 >> Connection: Keep-Alive
[19:46:51,245{GMT}] DEBUG - headers http-outgoing-2 >> User-Agent: Synapse-PT-HttpComponents-NIO
[19:46:51,245{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "POST /foo HTTP/1.1[\r][\n]"
[19:46:51,245{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "Content-Type: application/x-www-form-urlencoded[\r][\n]"
[19:46:51,245{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "SOAPAction: urn:getFullQuote[\r][\n]"
[19:46:51,245{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "Transfer-Encoding: chunked[\r][\n]"
[19:46:51,246{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "Host: localhost:8080[\r][\n]"
[19:46:51,246{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "Connection: Keep-Alive[\r][\n]"
[19:46:51,246{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "User-Agent: Synapse-PT-HttpComponents-NIO[\r][\n]"
[19:46:51,246{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "[\r][\n]"
[19:46:51,246{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "74[\r][\n]"
[19:46:51,246{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "request=%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20[\r][\n]"
[19:46:51,247{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "0[\r][\n]"
[19:46:51,247{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "[\r][\n]"
[19:46:51,254{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "HTTP/1.1 200 OK[\r][\n]"
[19:46:51,254{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "Content-Type: application/json[\r][\n]"
[19:46:51,254{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "Transfer-Encoding: chunked[\r][\n]"
[19:46:51,254{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "Server: Jetty(6.1.26)[\r][\n]"
[19:46:51,254{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "[\r][\n]"
[19:46:51,254{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "35[\r][\n]"
[19:46:51,254{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "{"workflowCallbackResponse" : {"error" : "false"}}   [\r][\n]"
[19:46:51,254{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "0[\r][\n]"
[19:46:51,254{GMT}] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "[\r][\n]"
[19:46:51,254{GMT}] DEBUG - headers http-outgoing-2 << HTTP/1.1 200 OK
[19:46:51,255{GMT}] DEBUG - headers http-outgoing-2 << Content-Type: application/json
[19:46:51,255{GMT}] DEBUG - headers http-outgoing-2 << Transfer-Encoding: chunked
[19:46:51,255{GMT}] DEBUG - headers http-outgoing-2 << Server: Jetty(6.1.26)
[19:46:51,256{GMT}]  INFO - LogMediator To: http://www.w3.org/2005/08/addressing/anonymous, WSAction: , SOAPAction: , MessageID: urn:uuid:c9265bc9-1993-47c4-a93f-e16d86bf9e77, Direction: response, sss = ssss222222, Payload: {"workflowCallbackResponse" : {"error" : "false"}}
[19:46:51,257{GMT}] ERROR - PassThroughHttpSender Failed to submit the response
org.apache.axis2.AxisFault: Can not output XML declaration, after other output has already been done.
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:555)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:264)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:222)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:531)
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:118)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator
```

**Comment by milindaperera** [comment]
We have tried above-mentioned scenario using provided proxy replacing EP with soap mock service. Unfortunately, it is not reproducible.

Tested on EI v6.1.0-ALPHA (also with 6.1.0) in both Java8 (recommended) and Java7 with both `org.wso2.carbon.integrator.core.json.JsonStreamFormatter/"org.wso2.carbon.integrator.core.json.JsonStreamBuilder` and `org.apache.synapse.commons.json.JsonStreamFormatter/org.apache.synapse.commons.json.JsonStreamBuilder` 

Let us know if we missed something.

Here is the wire log:
```
[2017-03-30 10:52:43,919] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 >> "POST /services/WorkflowCallbackService HTTP/1.1[\r][\n]"
[2017-03-30 10:52:43,919] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 >> "Host: localhost:8280[\r][\n]"
[2017-03-30 10:52:43,920] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 >> "User-Agent: curl/7.47.0[\r][\n]"
[2017-03-30 10:52:43,920] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 >> "Accept: */*[\r][\n]"
[2017-03-30 10:52:43,920] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 >> "Content-Length: 27[\r][\n]"
[2017-03-30 10:52:43,920] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 >> "Content-Type: application/x-www-form-urlencoded[\r][\n]"
[2017-03-30 10:52:43,920] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 >> "[\r][\n]"
[2017-03-30 10:52:43,920] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 >> "param1=value1&param2=value2"
[2017-03-30 10:52:43,972] [EI-Core]  INFO - TimeoutHandler This engine will expire all callbacks after GLOBAL_TIMEOUT: 120 seconds, irrespective of the timeout action, after the specified or optional timeout
[2017-03-30 10:52:43,991] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "POST /mockEP HTTP/1.1[\r][\n]"
[2017-03-30 10:52:43,992] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "Accept: */*[\r][\n]"
[2017-03-30 10:52:43,992] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "Content-Type: application/x-www-form-urlencoded[\r][\n]"
[2017-03-30 10:52:43,992] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "Transfer-Encoding: chunked[\r][\n]"
[2017-03-30 10:52:43,992] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "Host: localhost:8080[\r][\n]"
[2017-03-30 10:52:43,992] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "Connection: Keep-Alive[\r][\n]"
[2017-03-30 10:52:43,992] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "User-Agent: Synapse-PT-HttpComponents-NIO[\r][\n]"
[2017-03-30 10:52:43,992] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "[\r][\n]"
[2017-03-30 10:52:43,992] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "1b[\r][\n]"
[2017-03-30 10:52:43,993] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "param2=value2&param1=value1[\r][\n]"
[2017-03-30 10:52:43,993] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "0[\r][\n]"
[2017-03-30 10:52:43,993] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 << "[\r][\n]"
[2017-03-30 10:52:43,993] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "HTTP/1.1 200 OK[\r][\n]"
[2017-03-30 10:52:43,993] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "Content-Type: application/json[\r][\n]"
[2017-03-30 10:52:43,993] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "Transfer-Encoding: chunked[\r][\n]"
[2017-03-30 10:52:43,994] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "Server: Jetty(6.1.26)[\r][\n]"
[2017-03-30 10:52:43,994] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "[\r][\n]"
[2017-03-30 10:52:43,994] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "32[\r][\n]"
[2017-03-30 10:52:43,994] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "{"workflowCallbackResponse" : {"error" : "false"}}[\r][\n]"
[2017-03-30 10:52:43,994] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "0[\r][\n]"
[2017-03-30 10:52:43,994] [EI-Core] DEBUG - wire HTTP-Sender I/O dispatcher-1 >> "[\r][\n]"
[2017-03-30 10:52:44,037] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 << "HTTP/1.1 200 OK[\r][\n]"
[2017-03-30 10:52:44,037] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 << "Content-Type: text/xml; charset=UTF-8[\r][\n]"
[2017-03-30 10:52:44,038] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 << "Date: Thu, 30 Mar 2017 05:22:44 GMT[\r][\n]"
[2017-03-30 10:52:44,038] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 << "Transfer-Encoding: chunked[\r][\n]"
[2017-03-30 10:52:44,038] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 << "[\r][\n]"
[2017-03-30 10:52:44,038] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 << "62[\r][\n]"
[2017-03-30 10:52:44,038] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 << "<jsonObject><workflowCallbackResponse><error>false</error></workflowCallbackResponse></jsonObject>[\r][\n]"
[2017-03-30 10:52:44,038] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 << "0[\r][\n]"
[2017-03-30 10:52:44,038] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-1 << "[\r][\n]"
```

**Comment by milindaperera** [comment]
Abale to reproduce with following proxy configuration in both EI 6.1.0 and ESB 5.0.0
```
<?xml version="1.0" encoding="UTF-8"?><proxy xmlns="http://ws.apache.org/ns/synapse" name="WorkflowCallbackService" transports="http https" startOnLoad="true">
    <description/>
    <target>
        <inSequence>
            <property name="messageType" value="application/x-www-form-urlencoded" scope="axis2" type="STRING"/>
            <send>
                <endpoint>
                    <address uri="http://localhost:8080/mockEP" format="rest"/>
                </endpoint>
            </send>
        </inSequence>
        <outSequence>
            <property name="messageType" value="application/soap+xml" scope="axis2"/>
            <header name="Action" scope="default" value="urn:getQuote"/>
            <send/>
        </outSequence>
    </target>
</proxy>
```

**Comment by nandika** [comment]
this can be accomplished with data mapper also.

**Comment by Nirothipan** [comment]
This scenario throws same exception other way also

JSON -> SOAP conversion

**Comment by Nirothipan** [comment]
I've tried with the following artifacts.

SOAP to JSON Conversion
```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="soapTojson"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http,https">
   <target>
      <inSequence>
         <property name="messageType"
                   scope="axis2"
                   type="STRING"
                   value="application/json"/>
         <log level="full"/>
         <call>
            <endpoint>
               <address format="rest" uri="http://www.mocky.io/v2/56f84ee5240000d1127866c8"/>
            </endpoint>
         </call>
         <property name="messageType"
                   scope="axis2"
                   type="STRING"
                   value="application/soap+xml"/>
         <respond/>
      </inSequence>
   </target>
   <description/>
</proxy>
```

JSON to SOAP Conversion

```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="jsonToSoap"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http,https">
   <target>
      <inSequence>
         <property name="messageType"
                   scope="axis2"
                   type="STRING"
                   value="application/soap+xml"/>
         <call>
            <endpoint>
               <address format="soap12" uri="http://localhost:8280/services/soapRespond"/>
            </endpoint>
         </call>
         <property name="messageType"
                   scope="axis2"
                   type="STRING"
                   value="application/json"/>
         <respond/>
      </inSequence>
   </target>
   <description/>
</proxy>
```

This is reproducible only when format is not defined in the endpoint and otherwise not.

**Comment by Nirothipan** [comment]
Following Conversions works properly

SOAP 12 > JSON
JSON > SOAP12

Following gives the above error
SOAP11 > JSON
JSON - >SOAP11

**Comment by Nirothipan** [comment]
The issue was reproducible with following artifacts.

SOAP12 > JSON Conversion
```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="soapTojson"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http,https">
   <target>
      <inSequence>
         <property name="messageType"
                   scope="axis2"
                   type="STRING"
                   value="application/json"/>
         <call>
            <endpoint>
               <address format="rest" uri="http://www.mocky.io/v2/56f84ee5240000d1127866c8"/>
            </endpoint>
         </call>
         <property name="messageType" scope="axis2" type="STRING" value="text/xml"/>
         <respond/>
      </inSequence>
   </target>
   <description/>
</proxy>                                
```

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1317

**Comment by Nirothipan** [comment]
Fix added with https://github.com/wso2/wso2-synapse/pull/1317/commits/f85281d3c94078d02b0030dfdd71c2e63af06b75
