### ISSUE TITLE
Error when processing a JSON string which only containing "key":" " withing a PayloadFactory mediator.

### ISSUE THREAD

**Issue by VirajHasitha** [wso2/product-ei#4158]
**Description:**
Error is thrown as below for the JSON payload which contains JSON string with space only follows.
```
{
"key": " " 
}
```

Error: 
```
ERROR {org.apache.synapse.config.xml.AnonymousListMediator} -  String index out of range: 0 {org.apache.synapse.config.xml.AnonymousListMediator}
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.isJson(PayloadFactoryMediator.java:477)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.inferReplacementType(PayloadFactoryMediator.java:428)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.replace(PayloadFactoryMediator.java:299)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.mediate(PayloadFactoryMediator.java:149)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.mediate(PayloadFactoryMediator.java:98)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:89)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:56)
	at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:30)
	at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:197)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:89)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:56)
	at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:30)
	at org.apache.synapse.config.xml.SwitchCase.mediate(SwitchCase.java:66)
	at org.apache.synapse.mediators.filters.SwitchMediator.mediate(SwitchMediator.java:123)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:89)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:56)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:149)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:221)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:89)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:56)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:149)
	at org.apache.synapse.rest.Resource.process(Resource.java:297)
	at org.apache.synapse.rest.API.process(API.java:378)
```

**Suggested Labels:**

**Affected Product Version:**
ESB 4.9.0

**Steps to reproduce:**
Create a proxy service with the following payload factory mediator and respond. 

```
<payloadFactory media-type="json">
   <format>
   	{
		"key0":"$1",
		"key1":"$2"
	}
	</format>
   <args>
      <arg evaluator="json" expression="$.key0" />
      <arg evaluator="json" expression="$.key1" />
   </args>
</payloadFactory>
```

Send a request payload as follows,

```
 {
       "key0":"12345678",
       "key1":" "
 }
```

**Comment by malakaganga** [comment]
Fixed with
https://github.com/wso2/wso2-synapse/commit/a8bb7420c70dc92c3aca858a3c5bd66b3710610d
