### ISSUE TITLE
[RC1 Pack] File Inbound EPs with FTPS endpoint not functioning.

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4189]
**Description:**
**NOTE: Reported in 4.9.0 RC1 pack**
1.  By following [1] try to add URL parameters to an FTPS endpoint. (transport.vfs.FileURI) as shown below.
`ftps://wso2qar:qapass@192.168.XX.XX/VFS/IN?vfs.ssl.keystore=/home/esb49/wso2esb-4.9.0-RC1-SNAPSHOT/repository/resources/security/wso2carbon.jks&amp;vfs.ssl.truststore=/home/esb49/wso2esb-4.9.0-RC1-SNAPSHOT/repository/resources/security/client-truststore.jks&amp;vfs.ssl.kspassword=wso2carbon&amp;vfs.ssl.tspassword=wso2carbon&amp;vfs.ssl.keypassword=wso2carbon`

**Issue** : When connecticting to the EP the server gives following error.
```
ERROR - FtpsClientFactory Error occurred while retrieving the keystore paths
java.io.FileNotFoundException:  (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at org.apache.commons.vfs2.provider.ftps.FtpsClientFactory.addSSLParameters(FtpsClientFactory.java:277)
	at org.apache.commons.vfs2.provider.ftps.FtpsClientFactory.createConnection(FtpsClientFactory.java:187)
	at org.apache.commons.vfs2.provider.ftps.FtpsClientWrapper.createClient(FtpsClientWrapper.java:89)
	at org.apache.commons.vfs2.provider.ftps.FtpsClientWrapper.getFtpsClient(FtpsClientWrapper.java:102)
	at org.apache.commons.vfs2.provider.ftps.FtpsClientWrapper.<init>(FtpsClientWrapper.java:56)
	at org.apache.commons.vfs2.provider.ftps.FtpsFileProvider.doCreateFileSystem(FtpsFileProvider.java:130)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.getFileSystem(AbstractOriginatingFileProvider.java:157)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:121)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:90)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:738)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:626)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.initFileCheck(FilePollingConsumer.java:653)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.poll(FilePollingConsumer.java:164)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.execute(FilePollingConsumer.java:134)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FileTask.taskExecute(FileTask.java:45)
	at org.wso2.carbon.inbound.endpoint.common.InboundTask.execute(InboundTask.java:44)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:88)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
**Suggested Labels:**

**Suggested Assignees:**

[1] - https://docs.wso2.com/display/ESB481/VFS+Transport#VFSTransport-URLparams

**Affected Product Version:**

**OS, DB, other environment details and versions:** 
Pack : wso2esb-4.9.0-RC1.zip
Java Version : Java 1.8
Setup : Standalone
Browser : Chrome Version 43.0.2357.130 (64-bit) | FireFox 38.0
DB : H2  

**Steps to reproduce:**

**Related Issues:**

**Comment by sameeragunarathne** [comment]
not reproduced in latest.
