### ISSUE TITLE
DS service does not accept parameters in case it is deployed as part of Carbon Application

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4213]
**Description:**

- Data service is as follows.

```
<data name="testDSS" transports="http https local">
   <config enableOData="false" id="toolkit_db">
      <property name="driverClassName">com.mysql.jdbc.Driver</property>
      <property name="url">jdbc:mysql://127.0.0.1:3306/toolkit_db</property>
      <property name="username">root</property>
      <property name="password">pwd</property>
   </config>
   <query id="select_names" useConfig="toolkit_db">
      <sql>SELECT name FROM names WHERE sample_id = :sampleId and name_type = 'cn'</sql>
      <result element="Entities" rowName="Entity">
         <element column="name" name="name" xsdType="string"/>
      </result>
      <param name="sampleId" sqlType="STRING"/>
   </query>
   <operation name="FindNames">
      <call-query href="select_names">
         <with-param name="sampleId" query-param="sampleId"/>
      </call-query>
   </operation>
</data>
```
- When this service is deployed using the admin console, no issues are observed.

- When deployed using CAPP, following error is thrown.

> [2017-03-30 23:30:39,038] [EI-Core] ERROR - DBInOutMessageReceiver Error in in-out message receiver
> DS Code: INCOMPATIBLE_PARAMETERS_ERROR
> Nested Exception:-
> javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:sampleId
> DS Code: INCOMPATIBLE_PARAMETERS_ERROR
> Source Data Service:-
> Name: testDSS
> Location: /Volumes/disk/work/wso2/wso2ei-6.0.0/wso2/tmp/carbonapps/-1234/1490904885620glis-toolkit-dss-cap_1.0.0.car/testDSS_1.0.0/testDSS-1.0.0.dbs
> Description: N/A
> Default Namespace: http://ws.wso2.org/dataservice
> Current Request Name: FindNames
> Current Params: {}
> 
> at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:75)
> at org.wso2.carbon.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:354)
> at org.wso2.carbon.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:41)
> at org.wso2.carbon.dataservices.core.DBInOutMessageReceiver.invokeBusinessLogic(DBInOutMessageReceiver.java:57)
> at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:42)
> at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:403)
> at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
> at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at java.lang.Thread.run(Thread.java:745)
> Caused by: javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:sampleId
> DS Code: INCOMPATIBLE_PARAMETERS_ERROR
> Source Data Service:-
> Name: testDSS
> Location: /Volumes/disk/work/wso2/wso2ei-6.0.0/wso2/tmp/carbonapps/-1234/1490904885620glis-toolkit-dss-cap_1.0.0.car/testDSS_1.0.0/testDSS-1.0.0.dbs
> Description: N/A
> Default Namespace: http://ws.wso2.org/dataservice
> Current Request Name: FindNames
> Current Params: {}
> 
> at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.execute(DSOMDataSource.java:102)
> at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:73)
> ... 12 more
> [2017-03-30 23:30:39,469] [EI-Core] ERROR - ServerWorker Error processing POST request for : /services/testDSS.SOAP12Endpoint/FindNames
> org.apache.axis2.AxisFault: DS Code: INCOMPATIBLE_PARAMETERS_ERROR
> Nested Exception:-
> javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:sampleId
> DS Code: INCOMPATIBLE_PARAMETERS_ERROR
> Source Data Service:-
> Name: testDSS
> Location: /Volumes/disk/work/wso2/wso2ei-6.0.0/wso2/tmp/carbonapps/-1234/1490904885620glis-toolkit-dss-cap_1.0.0.car/testDSS_1.0.0/testDSS-1.0.0.dbs
> Description: N/A
> Default Namespace: http://ws.wso2.org/dataservice
> Current Request Name: FindNames
> Current Params: {}
> 
> at org.wso2.carbon.dataservices.core.DBUtils.createAxisFault(DBUtils.java:740)
> at org.wso2.carbon.dataservices.core.DBInOutMessageReceiver.invokeBusinessLogic(DBInOutMessageReceiver.java:67)
> at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:42)
> at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:403)
> at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
> at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at java.lang.Thread.run(Thread.java:745)
> Caused by: javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:sampleId
> DS Code: INCOMPATIBLE_PARAMETERS_ERROR
> Source Data Service:-
> Name: testDSS
> Location: /Volumes/disk/work/wso2/wso2ei-6.0.0/wso2/tmp/carbonapps/-1234/1490904885620glis-toolkit-dss-cap_1.0.0.car/testDSS_1.0.0/testDSS-1.0.0.dbs
> Description: N/A
> Default Namespace: http://ws.wso2.org/dataservice
> Current Request Name: FindNames
> Current Params: {}
> 
> at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.execute(DSOMDataSource.java:102)
> at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:73)
> at org.wso2.carbon.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:354)
> at org.wso2.carbon.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:41)
> at org.wso2.carbon.dataservices.core.DBInOutMessageReceiver.invokeBusinessLogic(DBInOutMessageReceiver.java:57)
> ... 9 more

- Further investigation has shown the following

Two identical DSS services, one created "by hand" via admin panel, another deployed as part of car file.
First service working fine in all cases, second doesn't work in TryIt tool, as well as problem reproduced if call it in inSequence of API, but it is working via then I call it from external SOAP UI tool or in same API - but inside "iterate" mediator

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

- wso2ei-6.0.0, OS
- CentOS or MacOS
- Oracle Java 8

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-5255
ESBJAVA-3326
ESBJAVA-4052
DS-1021

**Comment by sachithKay** [comment]
DSS 3.5.1 axis2.xml hadsfollowed configuration:

```
<transportReceiver name="http" class="org.wso2.carbon.core.transports.http.HttpTransportListener">
        <!--
           Uncomment the following if you are deploying this within an application server. You
           need to specify the HTTP port of the application server
        -->
        <parameter name="port">9763</parameter>

        <!--
       Uncomment the following to enable any proxy like Apache2 mod_proxy or any load balancer. The port on the proxy server like Apache is 80
       in this case.
        -->
        <!--<parameter name="proxyPort">80</parameter>-->
    </transportReceiver>
```

EI has the following:

     ```
<transportReceiver name="http" class="org.apache.synapse.transport.passthru.PassThroughHttpListener">
        <parameter name="port" locked="false">8280</parameter>
        <parameter name="non-blocking" locked="false">true</parameter>
        <!--parameter name="bind-address" locked="false">hostname or IP address</parameter-->
        <!--parameter name="WSDLEPRPrefix" locked="false">https://apachehost:port/somepath</parameter-->
        <parameter name="httpGetProcessor" locked="false">org.wso2.carbon.mediation.transport.handlers.PassThroughNHttpGetProcessor</parameter>
        <!--<parameter name="priorityConfigFile" locked="false">location of priority configuration file</parameter>-->
    </transportReceiver>
```
Investigated a little bit. DSS 3.5.1 axis2.xml had followed configuration:

<transportReceiver name="http" class="org.wso2.carbon.core.transports.http.HttpTransportListener">
        
        <parameter name="port">9763</parameter>

        
        
    </transportReceiver>
EI has another:

     <transportReceiver name="http" class="org.apache.synapse.transport.passthru.PassThroughHttpListener">
        <parameter name="port" locked="false">8280</parameter>
        <parameter name="non-blocking" locked="false">true</parameter>
        
        
        <parameter name="httpGetProcessor" locked="false">org.wso2.carbon.mediation.transport.handlers.PassThroughNHttpGetProcessor</parameter>
        
    </transportReceiver>
Check for DSS compatibility with  **org.apache.synapse.transport.passthru.PassThroughHttpListener**
