### ISSUE TITLE
[ESB 4.9.0] MP tries to resend the message even after setting "Non retry http status codes" parameter

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#4258]
**Description:**
Steps to reproduce
1. Create a Backend that send HTTP 304 status code.
2. Now create the following message processor. (Note the "Non retry http status codes" parameter)
<messageProcessor name="MYSQL_JNDI_PROC01" class="org.apache.synapse.message.processor.impl.forwarder.ScheduledMessageForwardingProcessor" targetEndpoint="POSTEP" messageStore="MYSQL_JNDI_1" xmlns="http://ws.apache.org/ns/synapse">
   <parameter name="interval">100000</parameter>
   <parameter name="client.retry.interval">5000</parameter>
   <parameter name="max.delivery.attempts">3</parameter>
   <parameter name="message.processor.fault.sequence">fault</parameter>
   <parameter name="is.active">true</parameter>
   <parameter name="non.retry.status.codes">304</parameter>
   <parameter name="max.delivery.drop">Enabled</parameter>
   <parameter name="member.count">1</parameter>
</messageProcessor>
2. Now activate the message processor.
Issue : MP tries to resend the message even after setting "Non retry http status codes" Refer the following wirelogs.

```
[2015-08-12 12:48:19,747] DEBUG - header >> "POST /postesb HTTP/1.1[\r][\n]"
[2015-08-12 12:48:19,747] DEBUG - header >> "Content-Type: text/xml; charset=UTF-8[\r][\n]"
[2015-08-12 12:48:19,747] DEBUG - header >> "SOAPAction: ""[\r][\n]"
[2015-08-12 12:48:19,747] DEBUG - header >> "User-Agent: Axis2[\r][\n]"
[2015-08-12 12:48:19,748] DEBUG - header >> "Host: localhost:8080[\r][\n]"
[2015-08-12 12:48:19,748] DEBUG - header >> "Transfer-Encoding: chunked[\r][\n]"
[2015-08-12 12:48:19,748] DEBUG - header >> "[\r][\n]"
[2015-08-12 12:48:19,748] DEBUG - content >> "204[\r][\n]"
[2015-08-12 12:48:19,748] DEBUG - content >> "<?xml version='1.0' encoding='UTF-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><jsonObject><menu><id>file</id><value>File</value><popup><menuitem><value>New</value><onclick>XXXXXXXXXXXXXXXXXXXXXXXXXXX</onclick></menuitem><menuitem><value>Open</value><onclick>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</onclick></menuitem><menuitem><value>Close</value><onclick>ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ</onclick></menuitem></popup></menu></jsonObject></soapenv:Body></soapenv:Envelope>"
[2015-08-12 12:48:19,748] DEBUG - content >> "[\r][\n]"
[2015-08-12 12:48:19,748] DEBUG - content >> "0"
[2015-08-12 12:48:19,748] DEBUG - content >> "[\r][\n]"
[2015-08-12 12:48:19,748] DEBUG - content >> "[\r][\n]"
[2015-08-12 12:48:19,749] DEBUG - header << "HTTP/1.1 304 Not Modified[\r][\n]"
[2015-08-12 12:48:19,749] DEBUG - header << "HTTP/1.1 304 Not Modified[\r][\n]"
[2015-08-12 12:48:19,749] DEBUG - header << "Content-Type: [\r][\n]"
[2015-08-12 12:48:19,749] DEBUG - header << "Server: Jetty(6.1.26)[\r][\n]"
[2015-08-12 12:48:19,749] DEBUG - header << "[\r][\n]"
[2015-08-12 12:48:19,750]  INFO - HTTPSender Unable to sendViaPost to url[http://localhost:8080/postesb]
org.apache.axis2.AxisFault: InputStream cannot be NULL.
	at org.apache.axis2.transport.http.AbstractHTTPSender.processResponse(AbstractHTTPSender.java:228)
	at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:326)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:196)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:77)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:297)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendRobust(BlockingMsgSender.java:233)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:171)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.dispatch(ForwardingService.java:437)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.execute(ForwardingService.java:184)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:81)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2015-08-12 12:48:19,750] ERROR - BlockingMsgSender Error sending Message to url : http://localhost:8080/postesb
org.apache.axis2.AxisFault: InputStream cannot be NULL.
	at org.apache.axis2.transport.http.AbstractHTTPSender.processResponse(AbstractHTTPSender.java:228)
	at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:326)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:196)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:77)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:297)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendRobust(BlockingMsgSender.java:233)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:171)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.dispatch(ForwardingService.java:437)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.execute(ForwardingService.java:184)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:81)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2015-08-12 12:48:19,751] ERROR - ForwardingService BlockingMessageSender of message processor [MYSQL_JNDI_PROC01] failed to send message to the endpoint
[2015-08-12 12:48:19,829]  INFO - LogMediator To: /api01, MessageID: urn:uuid:734d2372-0a86-4d31-9ef9-0ac85eb8aa19, Direction: request, MESSAGE = Executing default 'fault' sequence, ERROR_CODE = null, ERROR_MESSAGE = null, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><jsonObject><menu><id>file</id><value>File</value><popup><menuitem><value>New</value><onclick>XXXXXXXXXXXXXXXXXXXXXXXXXXX</onclick></menuitem><menuitem><value>Open</value><onclick>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</onclick></menuitem><menuitem><value>Close</value><onclick>ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ</onclick></menuitem></popup></menu></jsonObject></soapenv:Body></soapenv:Envelope>
[2015-08-12 12:48:24,833] DEBUG - header >> "POST /postesb HTTP/1.1[\r][\n]"
[2015-08-12 12:48:24,834] DEBUG - header >> "Content-Type: text/xml; charset=UTF-8[\r][\n]"
[2015-08-12 12:48:24,834] DEBUG - header >> "SOAPAction: ""[\r][\n]"
[2015-08-12 12:48:24,834] DEBUG - header >> "User-Agent: Axis2[\r][\n]"
[2015-08-12 12:48:24,835] DEBUG - header >> "Host: localhost:8080[\r][\n]"
[2015-08-12 12:48:24,835] DEBUG - header >> "Transfer-Encoding: chunked[\r][\n]"
[2015-08-12 12:48:24,836] DEBUG - header >> "[\r][\n]"
[2015-08-12 12:48:24,837] DEBUG - content >> "204[\r][\n]"
[2015-08-12 12:48:24,837] DEBUG - content >> "<?xml version='1.0' encoding='UTF-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><jsonObject><menu><id>file</id><value>File</value><popup><menuitem><value>New</value><onclick>XXXXXXXXXXXXXXXXXXXXXXXXXXX</onclick></menuitem><menuitem><value>Open</value><onclick>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</onclick></menuitem><menuitem><value>Close</value><onclick>ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ</onclick></menuitem></popup></menu></jsonObject></soapenv:Body></soapenv:Envelope>"
[2015-08-12 12:48:24,838] DEBUG - content >> "[\r][\n]"
[2015-08-12 12:48:24,838] DEBUG - content >> "0"
[2015-08-12 12:48:24,838] DEBUG - content >> "[\r][\n]"
[2015-08-12 12:48:24,838] DEBUG - content >> "[\r][\n]"
[2015-08-12 12:48:24,841] DEBUG - header << "HTTP/1.1 304 Not Modified[\r][\n]"
[2015-08-12 12:48:24,841] DEBUG - header << "HTTP/1.1 304 Not Modified[\r][\n]"
[2015-08-12 12:48:24,842] DEBUG - header << "Content-Type: [\r][\n]"
[2015-08-12 12:48:24,842] DEBUG - header << "Server: Jetty(6.1.26)[\r][\n]"
[2015-08-12 12:48:24,842] DEBUG - header << "[\r][\n]"
[2015-08-12 12:48:24,843]  INFO - HTTPSender Unable to sendViaPost to url[http://localhost:8080/postesb]
org.apache.axis2.AxisFault: InputStream cannot be NULL.
	at org.apache.axis2.transport.http.AbstractHTTPSender.processResponse(AbstractHTTPSender.java:228)
	at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:326)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:196)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:77)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:297)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendRobust(BlockingMsgSender.java:233)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:171)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.dispatch(ForwardingService.java:437)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.execute(ForwardingService.java:184)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:81)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2015-08-12 12:48:24,845] ERROR - BlockingMsgSender Error sending Message to url : http://localhost:8080/postesb
org.apache.axis2.AxisFault: InputStream cannot be NULL.
	at org.apache.axis2.transport.http.AbstractHTTPSender.processResponse(AbstractHTTPSender.java:228)
	at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:326)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:196)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:77)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:297)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendRobust(BlockingMsgSender.java:233)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:171)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.dispatch(ForwardingService.java:437)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.execute(ForwardingService.java:184)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:81)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2015-08-12 12:48:24,846] ERROR - ForwardingService BlockingMessageSender of message processor [MYSQL_JNDI_PROC01] failed to send message to the endpoint
[2015-08-12 12:48:24,854]  INFO - LogMediator To: , MessageID: urn:uuid:734d2372-0a86-4d31-9ef9-0ac85eb8aa19, Direction: request, MESSAGE = Executing default 'fault' sequence, ERROR_CODE = null, ERROR_MESSAGE = null, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><jsonObject><menu><id>file</id><value>File</value><popup><menuitem><value>New</value><onclick>XXXXXXXXXXXXXXXXXXXXXXXXXXX</onclick></menuitem><menuitem><value>Open</value><onclick>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</onclick></menuitem><menuitem><value>Close</value><onclick>ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ</onclick></menuitem></popup></menu></jsonObject></soapenv:Body></soapenv:Envelope>
[2015-08-12 12:48:29,858] DEBUG - header >> "POST /postesb HTTP/1.1[\r][\n]"
[2015-08-12 12:48:29,858] DEBUG - header >> "Content-Type: text/xml; charset=UTF-8[\r][\n]"
[2015-08-12 12:48:29,859] DEBUG - header >> "SOAPAction: ""[\r][\n]"
[2015-08-12 12:48:29,859] DEBUG - header >> "User-Agent: Axis2[\r][\n]"
[2015-08-12 12:48:29,859] DEBUG - header >> "Host: localhost:8080[\r][\n]"
[2015-08-12 12:48:29,859] DEBUG - header >> "Transfer-Encoding: chunked[\r][\n]"
[2015-08-12 12:48:29,860] DEBUG - header >> "[\r][\n]"
[2015-08-12 12:48:29,860] DEBUG - content >> "204[\r][\n]"
[2015-08-12 12:48:29,861] DEBUG - content >> "<?xml version='1.0' encoding='UTF-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><jsonObject><menu><id>file</id><value>File</value><popup><menuitem><value>New</value><onclick>XXXXXXXXXXXXXXXXXXXXXXXXXXX</onclick></menuitem><menuitem><value>Open</value><onclick>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</onclick></menuitem><menuitem><value>Close</value><onclick>ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ</onclick></menuitem></popup></menu></jsonObject></soapenv:Body></soapenv:Envelope>"
[2015-08-12 12:48:29,861] DEBUG - content >> "[\r][\n]"
[2015-08-12 12:48:29,861] DEBUG - content >> "0"
[2015-08-12 12:48:29,861] DEBUG - content >> "[\r][\n]"
[2015-08-12 12:48:29,861] DEBUG - content >> "[\r][\n]"
[2015-08-12 12:48:29,863] DEBUG - header << "HTTP/1.1 304 Not Modified[\r][\n]"
[2015-08-12 12:48:29,863] DEBUG - header << "HTTP/1.1 304 Not Modified[\r][\n]"
[2015-08-12 12:48:29,863] DEBUG - header << "Content-Type: [\r][\n]"
[2015-08-12 12:48:29,863] DEBUG - header << "Server: Jetty(6.1.26)[\r][\n]"
[2015-08-12 12:48:29,864] DEBUG - header << "[\r][\n]"
[2015-08-12 12:48:29,864]  INFO - HTTPSender Unable to sendViaPost to url[http://localhost:8080/postesb]
org.apache.axis2.AxisFault: InputStream cannot be NULL.
	at org.apache.axis2.transport.http.AbstractHTTPSender.processResponse(AbstractHTTPSender.java:228)
	at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:326)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:196)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:77)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:297)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendRobust(BlockingMsgSender.java:233)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:171)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.dispatch(ForwardingService.java:437)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.execute(ForwardingService.java:184)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:81)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2015-08-12 12:48:29,865] ERROR - BlockingMsgSender Error sending Message to url : http://localhost:8080/postesb
org.apache.axis2.AxisFault: InputStream cannot be NULL.
	at org.apache.axis2.transport.http.AbstractHTTPSender.processResponse(AbstractHTTPSender.java:228)
	at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:326)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:196)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:77)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:297)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendRobust(BlockingMsgSender.java:233)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:171)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.dispatch(ForwardingService.java:437)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.execute(ForwardingService.java:184)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:81)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2015-08-12 12:48:29,866] ERROR - ForwardingService BlockingMessageSender of message processor [MYSQL_JNDI_PROC01] failed to send message to the endpoint
[2015-08-12 12:48:29,872]  INFO - LogMediator To: , MessageID: urn:uuid:734d2372-0a86-4d31-9ef9-0ac85eb8aa19, Direction: request, MESSAGE = Executing default 'fault' sequence, ERROR_CODE = null, ERROR_MESSAGE = null, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><jsonObject><menu><id>file</id><value>File</value><popup><menuitem><value>New</value><onclick>XXXXXXXXXXXXXXXXXXXXXXXXXXX</onclick></menuitem><menuitem><value>Open</value><onclick>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</onclick></menuitem><menuitem><value>Close</value><onclick>ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ</onclick></menuitem></popup></menu></jsonObject></soapenv:Body></soapenv:Envelope>
[2015-08-12 12:48:29,886]  INFO - ForwardingService Removed failed message and continue the message processor [MYSQL_JNDI_PROC01]
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-4051

**Comment by nandika** [comment]
After debugging the code it is found that the root cause for this issue is that the blocking sender throws an exception where it does not have the status code. Our code expects that this exception should have the status code. But there are instances where we don't get the status code inside the exception and leading to this kind of a situation.

[getQuote.TXT](https://github.com/wso2/product-ei/files/3285489/getQuote.TXT)

[curlRequest.TXT](https://github.com/wso2/product-ei/files/3285490/curlRequest.TXT)
[placeOrder.TXT](https://github.com/wso2/product-ei/files/3285492/placeOrder.TXT)
[synapse-configs.zip](https://github.com/wso2/product-ei/files/3285493/synapse-configs.zip)
