### ISSUE TITLE
NullPointerException in message store mediator

### ISSUE THREAD

**Issue by sharathbhaskara** [wso2/product-ei#427]
Hi when saving the records in the message store, using the MSMF pattern to deliver the messages for other sequences we are getting an Null Pointer Exception.
> Note: The issue is not reproducible consitently, while it occurs intermittently

```
[2017-03-21 12:05:49,942] [] ERROR - SamplingService Error occurred while executing the message
org.apache.synapse.SynapseException: Runtime error occurred while mediating the message
        at org.apache.synapse.mediators.AbstractMediator.handleException(AbstractMediator.java:367)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:127)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.message.processor.impl.sampler.SamplingService$1.run(SamplingService.java:211)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.apache.synapse.mediators.store.MessageStoreMediator.getAxis2ParameterValue(MessageStoreMediator.java:226)
        at org.apache.synapse.mediators.store.MessageStoreMediator.mediate(MessageStoreMediator.java:108)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
```

**Comment by prabushi** [comment]
We tried to reproduce this issue using a message sampling processor and a jms message store with ActiveMQ. But we were not able reproduce this error. Can you please provide us more information about the EI configurations and the broker you have used to create this error?

**Comment by prabushi** [comment]
Possible fix: https://github.com/wso2/wso2-synapse/pull/725

**Comment by jagathsisira** [comment]
Fix merged hence resolving.
