### ISSUE TITLE
Error when deactivating a message processor while messages are being consumed

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#4284]
**Description:**
Intermittently observed the following exception when the processor is deactivated while processing messages. (JDBC message store)

```
ERROR - ForwardingService Message processor [Testprocessor] failed to send the message to client
org.apache.synapse.SynapseException: Removing message with id = null failed !
	at org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore.remove(JDBCMessageStore.java:365)
	at org.apache.synapse.message.store.impl.jdbc.JDBCConsumer.ack(JDBCConsumer.java:88)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.dropMessageAndContinueMessageProcessor(ForwardingService.java:676)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.checkAndDeactivateProcessor(ForwardingService.java:612)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.prepareToRetry(ForwardingService.java:636)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.dispatch(ForwardingService.java:507)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.execute(ForwardingService.java:184)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:81)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.synapse.SynapseException: Processing Statement failed : SELECT indexId,message FROM jdbc_message_store WHERE msg_id=? against DataSource : jdbc:mysql://localhost:3306/ESB49MESSAGESTORE
	at org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore.processResultingStatement(JDBCMessageStore.java:191)
	at org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore.get(JDBCMessageStore.java:444)
	at org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore.remove(JDBCMessageStore.java:360)
	... 14 more
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1094)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:997)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:983)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:928)
	at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2487)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2462)
	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2386)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2186)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore.processResultingStatement(JDBCMessageStore.java:158)
	... 16 more
```
Steps to reproduce

Created a JDBC message store, via a proxy added some messages to it. 
Then created a 'Scheduled Message Forwarding Processor' and the Exception occurred. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-4032

**Comment by sbouadar** [comment]
Hello,

Is this issue resolved ? Is there any workaround solution ?
I can reproduce it on WSO2EI 6.6.0
