### ISSUE TITLE
[MB 3.2.0][Intermittent] A spark exception thrown intermittently in analytic nodes

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4308]
**Description:**
Background:-

Long running scripts were interrupted due to Jmeter client machine HDD running out of space.
One analytic node was switched off over night (Not sure how about the reason)
Steps:-
1. Once above happened restarted both analytic nodes one by one using sh.wso2server.sh restart command.
2. Observe the server logs

Expected Results:-

Analytics nodes should be gracefully restarted
Actual Results:-

Following exception was thrown continuously when restarted the analytic nodes
Note:-
I was able to get rid of this error after cleaning index folders and databases of both MB and Analytic clusters.

```
TID: [-1234] [] [2016-09-21 11:17:28,355] INFO {org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor} - Retrying executing On Becoming Leader flow. Retry count = 8 {org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor}
TID: [-1234] [] [2016-09-21 11:17:53,962] INFO {org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor} - Redundant master count fulfilled : 2 {org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor}
TID: [-1] [] [2016-09-21 11:17:53,984] INFO {org.wso2.carbon.analytics.spark.core.deploy.CheckElectedLeaderExecutionCall} - Check Elected Leader Request: true {org.wso2.carbon.analytics.spark.core.deploy.CheckElectedLeaderExecutionCall}
TID: [-1] [] [2016-09-21 11:17:53,991] INFO {org.wso2.carbon.analytics.spark.core.deploy.CheckElectedLeaderExecutionCall} - Check Elected Leader Request: true {org.wso2.carbon.analytics.spark.core.deploy.CheckElectedLeaderExecutionCall}
TID: [-1] [] [2016-09-21 11:17:53,999] INFO {org.wso2.carbon.analytics.spark.core.deploy.CheckElectedLeaderExecutionCall} - Check Elected Leader Request: true {org.wso2.carbon.analytics.spark.core.deploy.CheckElectedLeaderExecutionCall}
TID: [-1234] [] [2016-09-21 11:17:54,044] INFO {org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor} - Initializing new spark client app... {org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor}
TID: [-1234] [] [2016-09-21 11:17:54,044] INFO {org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor} - Sending a cluster message to the leader to initialize the Spark application {org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor}
TID: [-1] [] [2016-09-21 11:17:54,047] WARN {org.apache.spark.SparkContext} - Another SparkContext is being constructed (or threw an exception in its constructor). This may indicate an error, since only one SparkContext may be running in this JVM (see SPARK-2243). The other SparkContext was created at:
org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:59)
org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.initializeSparkContext(SparkAnalyticsExecutor.java:319)
org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.initializeAnalyticsClientLocal(SparkAnalyticsExecutor.java:303)
org.wso2.carbon.analytics.spark.core.deploy.InitClientExecutionCall.call(InitClientExecutionCall.java:39)
org.wso2.carbon.analytics.spark.core.deploy.InitClientExecutionCall.call(InitClientExecutionCall.java:29)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:202)
com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) {org.apache.spark.SparkContext}
TID: [-1] [] [2016-09-21 11:17:54,066] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13001. Attempting port 13002. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,068] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13002. Attempting port 13003. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,070] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13003. Attempting port 13004. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,071] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13004. Attempting port 13005. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,073] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13005. Attempting port 13006. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,075] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13006. Attempting port 13007. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,077] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13007. Attempting port 13008. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,079] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13008. Attempting port 13009. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,081] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13009. Attempting port 13010. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,083] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13010. Attempting port 13011. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,084] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13011. Attempting port 13012. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,086] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13012. Attempting port 13013. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,087] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13013. Attempting port 13014. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,088] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13014. Attempting port 13015. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,090] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13015. Attempting port 13016. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,091] WARN {org.apache.spark.util.Utils} - Service 'sparkDriver' could not bind on port 13016. Attempting port 13017. {org.apache.spark.util.Utils}
TID: [-1] [] [2016-09-21 11:17:54,095] ERROR {org.apache.spark.SparkContext} - Error initializing SparkContext. {org.apache.spark.SparkContext}
java.net.BindException: Cannot assign requested address: Service 'sparkDriver' failed after 16 retries! Consider explicitly setting the appropriate port for the service 'sparkDriver' (for example spark.ui.port for SparkUI) to an available port or increasing spark.port.maxRetries.
at sun.nio.ch.Net.bind0(Native Method)
at sun.nio.ch.Net.bind(Net.java:433)
at sun.nio.ch.Net.bind(Net.java:425)
at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:485)
at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1089)
at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430)
at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415)
at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903)
at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198)
at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
at java.lang.Thread.run(Thread.java:745)
TID: [-1234] [] [2016-09-21 11:17:54,098] WARN {org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor} - Error in processing on becoming leader cluster message: Error in cluster execute one: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsException: Unable to create analytics client. Cannot assign requested address: Service 'sparkDriver' failed after 16 retries! Consider explicitly setting the appropriate port for the service 'sparkDriver' (for example spark.ui.port for SparkUI) to an available port or increasing spark.port.maxRetries. {org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor}
org.wso2.carbon.analytics.dataservice.core.clustering.AnalyticsClusterException: Error in cluster execute one: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsException: Unable to create analytics client. Cannot assign requested address: Service 'sparkDriver' failed after 16 retries! Consider explicitly setting the appropriate port for the service 'sparkDriver' (for example spark.ui.port for SparkUI) to an available port or increasing spark.port.maxRetries.
at org.wso2.carbon.analytics.dataservice.core.clustering.AnalyticsClusterManagerImpl.executeOne(AnalyticsClusterManagerImpl.java:264)
at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.initializeAnalyticsClient(SparkAnalyticsExecutor.java:288)
at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeOnBecomingLeaderFlow(SparkAnalyticsExecutor.java:1070)
at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.onBecomingLeader(SparkAnalyticsExecutor.java:1029)
at org.wso2.carbon.analytics.dataservice.core.clustering.AnalyticsClusterManagerImpl.executeJoinGroupFlow(AnalyticsClusterManagerImpl.java:118)
at org.wso2.carbon.analytics.dataservice.core.clustering.AnalyticsClusterManagerImpl.joinGroup(AnalyticsClusterManagerImpl.java:89)
at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.runClusteredSetupLogic(SparkAnalyticsExecutor.java:233)
at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.initializeSparkServer(SparkAnalyticsExecutor.java:190)
at org.wso2.carbon.analytics.spark.core.internal.AnalyticsComponent.activate(AnalyticsComponent.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:950)
at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceComponent.activate(AnalyticsDataServiceComponent.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
at org.wso2.carbon.ntask.core.internal.TasksDSComponent.activate(TasksDSComponent.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:199)
at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:288)
at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
at org.wso2.carbon.server.admin.internal.ServerAdminServiceComponent.activate(ServerAdminServiceComponent.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:514)
at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManager.java:219)
at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(CarbonCoreServiceComponent.java:94)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)
at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)
at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)
at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1282)
at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1195)
at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1085)
at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5349)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5641)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1571)
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1561)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsException: Unable to create analytics client. Cannot assign requested address: Service 'sparkDriver' failed after 16 retries! Consider explicitly setting the appropriate port for the service 'sparkDriver' (for example spark.ui.port for SparkUI) to an available port or increasing spark.port.maxRetries.
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:204)
at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
Caused by: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsException: Unable to create analytics client. Cannot assign requested address: Service 'sparkDriver' failed after 16 retries! Consider explicitly setting the appropriate port for the service 'sparkDriver' (for example spark.ui.port for SparkUI) to an available port or increasing spark.port.maxRetries.
at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.initializeSparkContext(SparkAnalyticsExecutor.java:321)
at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.initializeAnalyticsClientLocal(SparkAnalyticsExecutor.java:303)
at org.wso2.carbon.analytics.spark.core.deploy.InitClientExecutionCall.call(InitClientExecutionCall.java:39)
at org.wso2.carbon.analytics.spark.core.deploy.InitClientExecutionCall.call(InitClientExecutionCall.java:29)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:202)
... 6 more
Caused by: java.net.BindException: Cannot assign requested address: Service 'sparkDriver' failed after 16 retries! Consider explicitly setting the appropriate port for the service 'sparkDriver' (for example spark.ui.port for SparkUI) to an available port or increasing spark.port.maxRetries.
at sun.nio.ch.Net.bind0(Native Method)
at sun.nio.ch.Net.bind(Net.java:433)
at sun.nio.ch.Net.bind(Net.java:425)
at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:485)
at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1089)
at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430)
at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415)
at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903)
at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198)
at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
at java.lang.Thread.run(Thread.java:745)
TID: [-1234] [] [2016-09-21 11:17:54,102] INFO {org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor} - Retrying executing On Becoming Leader flow. Retry count = 9 {org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor}
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:** 
pack :- MB 3.2.0 M3 
setup:- 2 MB nodes/ 2 Analyticsnodes
DB:- PostgreSQL
JDK:- Oracle 1.8  

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ANLYMB-18

**Comment by GDLMadushanka** [comment]
Analytics upgraded to a new product (Stream Processor)
