### ISSUE TITLE
[ ESB 4.9.0 ]  - Tasks are not getting scheduled when Location based Resolving Fails.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#4335]
**Description:**
The deployment is as follows.

1 Manager Node and 4 Worker Nodes.

Tasks are scheduled based on Rules and task server count it 2. Following is the task-config.xml

```
 <tasks-configuration xmlns:svns="http://org.wso2.securevault/configuration">

    <!-- 
      The currently running server mode; possible values are:-
      STANDALONE, CLUSTERED, REMOTE, AUTO.
      In AUTO mode, the server startup checks whether clustering is enabled in the system, 
      if so, CLUSTERED mode will be used, or else, the the server mode will be STANDALONE.
    -->
    <taskServerMode>AUTO</taskServerMode>
    
    <!-- 
      To be used in CLUSTERED mode to notify how many servers are there in 
      the task server cluster, the servers wait till this amount of servers
      are activated before the tasks are scheduled -->
    <taskServerCount>2</taskServerCount>

    <!-- The default location resolver configuration -->
 <!--  <defaultLocationResolver>
        <locationResolverClass>org.wso2.carbon.ntask.core.impl.RoundRobinTaskLocationResolver</locationResolverClass>
    </defaultLocationResolver> -->

<defaultLocationResolver>
        <locationResolverClass>org.wso2.carbon.ntask.core.impl.RuleBasedLocationResolver</locationResolverClass>
        <properties>
            <property name="rule-1">ESB_TASK,.*,worker1*</property>
        </properties>
</defaultLocationResolver>

    <!-- 
      if task-type-pattern matches and task-name-pattern matches, check existing addresses of address-pattern,
      and if addresses exist, select address in round-robin fashion, if not move onto next rule in sequence.
      <property name="rule-[order]">[task-type-pattern],[task-name-pattern],[address-pattern]</property>
    -->
    <!--defaultLocationResolver>
        <locationResolverClass>org.wso2.carbon.ntask.core.impl.RuleBasedLocationResolver</locationResolverClass>
        <properties>
            <property name="rule-1">HIVE_TASK,.*,192.168.2.*</property>
            <property name="rule-5">.*,.*,.*</property>
        </properties>
    </defaultLocationResolver-->

    <!-- The address to which the remote task server should dispatch the trigger messages to, 
      usually this would be an endpoint to a load balancer -->
    <taskClientDispatchAddress>https://localhost:9448</taskClientDispatchAddress>
    
    <!-- The address of the remote task server -->
    <remoteServerAddress>https://localhost:9443</remoteServerAddress>
    
    <!-- The username to authenticate to the remote task server -->
    <remoteServerUsername>admin</remoteServerUsername>
    
    <!-- The password to authenticate to the remote task server -->
    <remoteServerPassword>admin</remoteServerPassword>

    <!-- Below contain a sample to be used when using with secure vault -->
    <!--remoteServerPassword svns:secretAlias="remote.task.server.password"></remoteServerPassword-->

</tasks-configuration>
```

Here in the available 4 nodes, 
2 are API Nodes - ( which cannot run the tasks ) ( Restricted via rule based ).
2 are Task Nodes - ( Which can run the task ).

**Steps to reproduce:**
1) Deploy a MP as follows ( please note that it is deactivated in the beginning itself )

```
<?xml version="1.0" encoding="UTF-8"?>
<messageProcessor class="org.apache.synapse.message.processor.impl.forwarder.ScheduledMessageForwardingProcessor" messageStore="InMemoryMessageStore" name="TestMessageProcessor1234" targetEndpoint="JSON_EP" xmlns="http://ws.apache.org/ns/synapse">
    <parameter name="client.retry.interval">1000</parameter>
    <parameter name="max.delivery.attempts">4</parameter>
    <parameter name="member.count">1</parameter>
    <parameter name="store.connection.retry.interval">1000</parameter>
    <parameter name="max.store.connection.attempts">-1</parameter>
    <parameter name="max.delivery.drop">Disabled</parameter>
    <parameter name="interval">1000</parameter>
    <parameter name="is.active">true</parameter>
</messageProcessor>
```

2. Start the Manager Node.

Following logs will be printed

```
INFO - ClusterGroupCommunicator Waiting for 2 [registryTasks] task executor nodes...
```

3. Start the API Node 1

Following logs will be printed in the API Node 1

```
INFO - ClusterGroupCommunicator Waiting for 2 [ESB_TASK] task executor nodes...
```

4 . Start the API Node 2

Following error is now thrown in API Node 1

```
ERROR - NTaskTaskManager Cannot pause task [MSMP_TestMessageProcessor12340]. Error: The task server cannot be located for task: MSMP_TestMessageProcessor12340
org.wso2.carbon.ntask.common.TaskException: The task server cannot be located for task: MSMP_TestMessageProcessor12340
	at org.wso2.carbon.ntask.core.impl.clustered.ClusteredTaskManager.getMemberIdFromTaskName(ClusteredTaskManager.java:292)
	at org.wso2.carbon.ntask.core.impl.clustered.ClusteredTaskManager.pauseTask(ClusteredTaskManager.java:163)
	at org.wso2.carbon.mediation.ntask.NTaskTaskManager.pause(NTaskTaskManager.java:211)
	at org.apache.synapse.message.processor.impl.ScheduledMessageProcessor.pauseService(ScheduledMessageProcessor.java:386)
	at org.apache.synapse.message.processor.impl.ScheduledMessageProcessor.deactivate(ScheduledMessageProcessor.java:333)
	at org.apache.synapse.message.processor.impl.ScheduledMessageProcessor.start(ScheduledMessageProcessor.java:189)
	at org.apache.synapse.message.processor.impl.ScheduledMessageProcessor.update(ScheduledMessageProcessor.java:472)
	at org.wso2.carbon.mediation.ntask.NTaskTaskManager.updateAndCleanupObservers(NTaskTaskManager.java:724)
	at org.wso2.carbon.mediation.ntask.NTaskTaskManager.init(NTaskTaskManager.java:359)
	at org.wso2.carbon.mediation.ntask.NTaskTaskManager.update(NTaskTaskManager.java:424)
	at org.wso2.carbon.mediation.ntask.internal.NtaskService.updateAndCleanupObservers(NtaskService.java:103)
	at org.wso2.carbon.mediation.ntask.internal.NtaskService.setConfigurationContextService(NtaskService.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:430)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bind(ServiceComponentProp.java:218)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:343)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
	at org.wso2.carbon.ntask.core.internal.TasksDSComponent.activate(TasksDSComponent.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:213)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:302)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:123)
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:517)
	at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManager.java:219)
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(CarbonCoreServiceComponent.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)
	at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1269)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1182)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1072)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5362)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5660)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1700)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1690)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This is because we are trying to deactivate a task which is not scheduled yet. Since it is not scheduled we can't resolve a node associated with it and it ends up in the above error.

This error is initiated form the below line

https://github.com/wso2-support/wso2-synapse/blob/support-2.1.3-wso2v11/modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java#L188

**as a fix** , we need to check whether it is running somewhere and and if it is so , we need ot deactivate it.

A similar issue has been fixed in https://github.com/wso2/wso2-synapse/pull/791 . How ever this is not fixing ESB 4.9.0 as I have tried it locally.

In addition to the above following logs also got printed ( this is expected as no servers found to 
 schedule the task )

```
ERROR - ClusterGroupCommunicator Encountered error(s) in scheduling missing tasks [ESB_TASK][-1234]:- 
Task location unavailable for RuleBasedLocationResolver: ESB_TASK#MSMP_TestMessageProcessor12340

Retrying [1]...
[2019-06-24 14:24:48,212] ERROR - ClusterGroupCommunicator Encountered error(s) in scheduling missing tasks [ESB_TASK][-1234]:- 
Task location unavailable for RuleBasedLocationResolver: ESB_TASK#MSMP_TestMessageProcessor12340

Retrying [2]...
[2019-06-24 14:24:48,228] ERROR - ClusterGroupCommunicator Encountered error(s) in scheduling missing tasks [ESB_TASK][-1234]:- 
Task location unavailable for RuleBasedLocationResolver: ESB_TASK#MSMP_TestMessageProcessor12340

Giving up.
```

5 . Start the worker Node 1

**Expectation**:- Task Getting Scheduled In Worker 1

**Result** :-  It is not scheduled.

In is shown as Not active in Mgt console 

![Screenshot from 2019-06-24 14-28-46](https://user-images.githubusercontent.com/24619763/60005598-72601c80-968c-11e9-90d0-650fbcc15cf0.png)

However clicking the activate button from there do nothing.

___________________________________________________________________________

**Related Issues:**

**Comment by Nirothipan** [comment]
In the above setup.

Deploy the below MP ( is.active true at begining )

```
<?xml version="1.0" encoding="UTF-8"?>
<messageProcessor class="org.apache.synapse.message.processor.impl.forwarder.ScheduledMessageForwardingProcessor" messageStore="InMemoryMessageStore" name="TestMessageProcessor1234" targetEndpoint="JSON_EP" xmlns="http://ws.apache.org/ns/synapse">
    <parameter name="client.retry.interval">1000</parameter>
    <parameter name="max.delivery.attempts">4</parameter>
    <parameter name="member.count">1</parameter>
    <parameter name="store.connection.retry.interval">1000</parameter>
    <parameter name="max.store.connection.attempts">-1</parameter>
    <parameter name="max.delivery.drop">Disabled</parameter>
    <parameter name="interval">1000</parameter>
    <parameter name="is.active">true</parameter>
</messageProcessor>
```

1 ) Start the Manager Node

2) Start the API Node 1

Getting following logs 

```
INFO - ClusterGroupCommunicator Waiting for 2 [ESB_TASK] task executor nodes...
```

3) Start the API Node 2

Getting below logs in API node 1

```
ERROR - ClusterGroupCommunicator Encountered error(s) in scheduling missing tasks [ESB_TASK][-1234]:- 
Task location unavailable for RuleBasedLocationResolver: ESB_TASK#MSMP_TestMessageProcessor12340

Retrying [1]...
[2019-06-24 14:37:28,767] ERROR - ClusterGroupCommunicator Encountered error(s) in scheduling missing tasks [ESB_TASK][-1234]:- 
Task location unavailable for RuleBasedLocationResolver: ESB_TASK#MSMP_TestMessageProcessor12340

Retrying [2]...
[2019-06-24 14:37:28,786] ERROR - ClusterGroupCommunicator Encountered error(s) in scheduling missing tasks [ESB_TASK][-1234]:- 
Task location unavailable for RuleBasedLocationResolver: ESB_TASK#MSMP_TestMessageProcessor12340

Giving up.
```

4 ) Start the worker Node 1

Expected:- Task getting scheduled in  this Node ( since it is capable of running the task )

Result:-  It is not scheduled.

In is shown as Not active in Mgt console

![Screenshot from 2019-06-24 14-28-46](https://user-images.githubusercontent.com/24619763/60006506-30d07100-968e-11e9-8d3a-55ecfee12feb.png)


However clicking the activate button from there do nothing.

**Comment by Nirothipan** [comment]
For the above scenario ( above comment ) , starting in the below order schedules the task properly.

1) Manager Node

2) Worker Node 1 ( Task Node )

3) Worker Node 2 ( Task Node )
