### ISSUE TITLE
NullPointerException in EI clusters when there are network delays

### ISSUE THREAD

**Issue by dilan-premarathna** [wso2/product-ei#4336]
**Description:**
In an EI cluster when there are connectivity issues with the DB EI cluster becomes unstable and produce NullPointerExceptions. 
<img width="390" alt="1" src="https://user-images.githubusercontent.com/39687099/60030841-4f9c2b00-96c1-11e9-9bc9-0021f88f1b02.png">

**Affected Product Version:**
EI 6.1.1

**Steps to reproduce:**
-Create an EI cluster(EI 6.1.1) with 2 nodes
-Start node 1 and then node2
-Suspend EI1 using kill -STOP <pid> after some time we could observe [1] in node 2
-Resume EI1 using kill -CONT <pid> 
-After some time we get the error [2]

[1] INFO {org.wso2.andes.kernel.disruptor.inbound.MessagePreProcessor} -  Message routing key: play No routes in cluster. Ignoring Message id 70331630148911104

[2]-[2019-06-23 10:52:46,302]  INFO {org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent} -  Running DB sync task.
[2019-06-23 10:52:46,304]  WARN {org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent} -  Recovering node. Removing queue from queue registry queueName=AMQP_Topic_play_NODE:192.168.1.101:4000,queueOwner=clientID,isExclusive=true,isDurable=false,isShared=false,lastPurgedTimestamp=0
[2019-06-23 10:52:46,304] ERROR {org.wso2.andes.kernel.disruptor.LogExceptionHandler} -  [ Sequence: 923 ] Exception occurred while processing inbound events.
java.lang.NullPointerException
at org.wso2.andes.kernel.AndesContextInformationManager.syncQueueDelete(AndesContextInformationManager.java:336)
at org.wso2.andes.kernel.disruptor.inbound.InboundQueueSyncEvent.updateState(InboundQueueSyncEvent.java:126)
at org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent.reloadQueuesFromDB(InboundDBSyncRequestEvent.java:160)
at org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent.updateState(InboundDBSyncRequestEvent.java:74)
at org.wso2.andes.kernel.disruptor.inbound.InboundEventContainer.updateState(InboundEventContainer.java:268)
at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:70)
at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:40)
at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by dulanjalidilmi** [comment]
This should be fixed in andes-3.2.82 (EI 6.4.0) as well
