### ISSUE TITLE
Unable to create a durable topic subscription with the same name when the servers crash

### ISSUE THREAD

**Issue by dilan-premarathna** [wso2/product-ei#4337]
**Description:**
Durable topic subscription with the same name cannot be created when the servers crash.
<img width="413" alt="2" src="https://user-images.githubusercontent.com/39687099/60031269-09939700-96c2-11e9-9125-9531a14237f9.png">

**Affected Product Version:**
EI 6.1.1

**Steps to reproduce:**
-Create an EI cluster(EI 6.1.1) with 2 nodes
-Start node 1 and then node2
-Create a durable topic subscriber(sub_1) to node 1 
-Kill node 1 and then kill node 2 just after the Member removed message
-Start node 2 and create a durable topic subscriber with the same name(sub_1)

We can observe the following error [1] when we try to create a durable topic subscription.

[1]-WARN {org.wso2.andes.amqp.QpidAndesBridge} -  Reverting already created subscription entries for subscription [channel=[/127.0.0.1:58072(admin):1], consumerTag=1, session=/127.0.0.1:58072] {org.wso2.andes.amqp.QpidAndesBridge}
org.wso2.andes.kernel.SubscriptionAlreadyExistsException: An active subscription already exists with same subscription id 25b79d0a-7af6-44a3-8a7d-feb8203841d5 bound to queue carbon:sub_1 by routing key games
        at org.wso2.andes.kernel.subscription.StorageQueue.bindSubscription(StorageQueue.java:300)
        at org.wso2.andes.kernel.subscription.AndesSubscriptionManager.addLocalSubscription(AndesSubscriptionManager.java:202)
        at org.wso2.andes.kernel.disruptor.inbound.InboundSubscriptionEvent.handleOpenSubscriptionEvent(InboundSubscriptionEvent.java:182)
        at org.wso2.andes.kernel.disruptor.inbound.InboundSubscriptionEvent.updateState(InboundSubscriptionEvent.java:154)
        at org.wso2.andes.kernel.disruptor.inbound.InboundEventContainer.updateState(InboundEventContainer.java:268)
        at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:70)
        at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:40)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by dulanjalidilmi** [comment]
This should be fixed in andes-3.2.82 (EI 6.4.0) as well
