### ISSUE TITLE
Implement Throttling in VFS Send Logic.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#4353]
**Description:**
$subject

When request are received concurrently, following exception is thrown in server side. 

```
TID: [-1234] [] [2019-07-04 09:26:17,010] ERROR {org.apache.synapse.transport.vfs.VFSTransportSender} -  IO Error while creating response file : ftp://admin":***@"10.100.7.35:2121/home/nirothipan/testFTP2/123-urn:uuid:211e041d-df8c-48b3-b498-2dbcb5da66c8.txt {org.apache.synapse.transport.vfs.VFSTransportSender}
org.apache.commons.vfs2.FileSystemException: Could not close the output stream for file "ftp://admin:***@10.100.7.35:2121/home/nirothipan/testFTP2/123-urn:uuid:211e041d-df8c-48b3-b498-2dbcb5da66c8.txt".
	at org.apache.commons.vfs2.provider.DefaultFileContent$FileContentOutputStream.close(DefaultFileContent.java:695)
	at org.apache.commons.io.output.ProxyOutputStream.close(ProxyOutputStream.java:117)
	at org.apache.synapse.transport.vfs.VFSTransportSender.populateResponseFile(VFSTransportSender.java:378)
	at org.apache.synapse.transport.vfs.VFSTransportSender.writeFile(VFSTransportSender.java:288)
	at org.apache.synapse.transport.vfs.VFSTransportSender.sendMessage(VFSTransportSender.java:194)
	at org.apache.axis2.transport.base.AbstractTransportSender.invoke(AbstractTransportSender.java:112)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:297)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:581)
	at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:78)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:548)
	at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:382)
	at org.apache.synapse.endpoints.AddressEndpoint.send(AddressEndpoint.java:65)
	at org.apache.synapse.mediators.builtin.CallMediator.handleNonBlockingCall(CallMediator.java:221)
	at org.apache.synapse.mediators.builtin.CallMediator.mediate(CallMediator.java:99)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:210)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:403)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.commons.vfs2.FileSystemException: Could not close the output stream for file "ftp://admin:***@10.100.7.35:2121/home/nirothipan/testFTP2/123-urn:uuid:211e041d-df8c-48b3-b498-2dbcb5da66c8.txt".
	at org.apache.commons.vfs2.provider.DefaultFileContent$FileContentOutputStream.onClose(DefaultFileContent.java:717)
	at org.apache.commons.vfs2.util.MonitorOutputStream.close(MonitorOutputStream.java:76)
	at org.apache.commons.vfs2.provider.DefaultFileContent$FileContentOutputStream.close(DefaultFileContent.java:691)
	... 26 more
Caused by: java.lang.NullPointerException
	at org.apache.commons.vfs2.provider.ftp.FtpFileObject.doGetChildren(FtpFileObject.java:169)
	at org.apache.commons.vfs2.provider.ftp.FtpFileObject.getChildFile(FtpFileObject.java:111)
	at org.apache.commons.vfs2.provider.ftp.FtpFileObject.getInfo(FtpFileObject.java:200)
	at org.apache.commons.vfs2.provider.ftp.FtpFileObject.onChange(FtpFileObject.java:319)
	at org.apache.commons.vfs2.provider.AbstractFileObject.endOutput(AbstractFileObject.java:1544)
	at org.apache.commons.vfs2.provider.DefaultFileContent.endOutput(DefaultFileContent.java:549)
	at org.apache.commons.vfs2.provider.DefaultFileContent.access$200(DefaultFileContent.java:44)
	at org.apache.commons.vfs2.provider.DefaultFileContent$FileContentOutputStream.onClose(DefaultFileContent.java:713)
	... 28 more
```

**Comment by Nirothipan** [comment]
Will be tracked in https://github.com/wso2/product-ei/issues/4382 as both as same.
