### ISSUE TITLE
Unable to start the Broker using "sh wso2server.sh" command

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#44]
**Environment**

OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version  53.0.2785.89
EI M1 snapshot pack

**Steps**
1. Go to <IE_HOME>/wso2/broker/bin 
2. Start the broker using "sh wso2server.sh"

**Observation**
1. Unable to start the server
2. Below error logged in the terminal

[2017-01-25 15:46:09,775] ERROR {org.wso2.carbon.event.processor.manager.core.internal.ds.EventManagementServiceDS} -  Could not create EventProcessorManagementService: Error getting management mode information
org.wso2.carbon.event.processor.manager.core.exception.EventManagementException: Error getting management mode information
	at org.wso2.carbon.event.processor.manager.core.internal.CarbonEventManagementService.<init>(CarbonEventManagementService.java:86)
	at org.wso2.carbon.event.processor.manager.core.internal.ds.EventManagementServiceDS.activate(EventManagementServiceDS.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.event.processor.manager.core.exception.ManagementConfigurationException: event-processor.xmlcannot be found in the path : /home/sashika/Apps/Applications/EI/SNAPSHOT/wso2ei-6.0.0-SNAPSHOT/wso2/broker/conf/event-processor.xml
	at org.wso2.carbon.event.processor.manager.core.internal.util.ManagementModeConfigurationLoader.loadConfigXML(ManagementModeConfigurationLoader.java:121)
	at org.wso2.carbon.event.processor.manager.core.internal.util.ManagementModeConfigurationLoader.loadManagementModeInfo(ManagementModeConfigurationLoader.java:49)
	at org.wso2.carbon.event.processor.manager.core.internal.CarbonEventManagementService.<init>(CarbonEventManagementService.java:82)
	... 16 more
Caused by: java.io.FileNotFoundException: /home/sashika/Apps/Applications/EI/SNAPSHOT/wso2ei-6.0.0-SNAPSHOT/wso2/broker/conf/event-processor.xml (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at org.wso2.carbon.event.processor.manager.core.internal.util.ManagementModeConfigurationLoader.loadConfigXML(ManagementModeConfigurationLoader.java:113)
	... 18 more

**Comment by mpmunasinghe** [comment]
Added the fixed with https://github.com/wso2/product-ei/pull/66/commits/b08b73a50010aef7c50b2db86b7366934a1eac37

**Comment by sashikamw** [comment]
Verified the fix in 27/01/2017 Jenkins build.
