### ISSUE TITLE
IndexOutOfBoundsException while continue the mediation flow after response from call mediator

### ISSUE THREAD

**Issue by dilee** [wso2/product-ei#4409]
**Description:**
Getting the below error when a foreach meadiator is used inside the iterator and a call mediator is reached afterwards in a sequence template. This issue happens because of the issue [1].

```
[2019-07-25 11:56:15,036] [EI-Core] ERROR [PassThroughMessageProcessor-19] - NativeWorkerPool Uncaught exception
java.lang.IndexOutOfBoundsException: Index: 3, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.apache.synapse.mediators.AbstractListMediator.getChild(AbstractListMediator.java:155)
	at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:240)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:267)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.mediateFromContinuationStateStack(Axis2SynapseEnvironment.java:775)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:282)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:535)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:188)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:262)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
[1] https://wso2.org/jira/browse/ESBJAVA-5122

**Affected Product Version:**
6.1.0

**Comment by dilee** [comment]
Fixed in https://github.com/wso2-support/wso2-synapse/pull/656
