### ISSUE TITLE
[DSS] Unable to reuse same parameter in query

### ISSUE THREAD

**Issue by milindaperera** [wso2/product-ei#4558]
**Description:**
Unable to reuse same parameter multiple times in same query.

Eaxmple:
```xml
<query id="GetEmpNotWork" useConfig="Datasource">
      <sql>select EM.EmployeeNumber, EM.FirstName, EM.LastName, EM.Email, EM.Salary from Employees EM where EM.EmployeeNumber=:EmployeeNumber and EM.EmployeeNumber=:EmployeeNumber order by EM.FirstName</sql>
      <result element="Entries" rowName="Entry">
         <element column="EmployeeNumber" name="EmployeeNumber" xsdType="string"/>
         <element column="FirstName" name="FirstName" xsdType="string"/>
         <element column="LastName" name="LastName" xsdType="string"/>
         <element column="Email" name="Email" xsdType="string"/>
         <element column="Salary" name="Salary" xsdType="string"/>
      </result>
      <param name="EmployeeNumber" sqlType="STRING"/>
   </query>
```

This works fine with EI 6.4.0, but fails in 6.5.0

Error:
```
DS Code: DATABASE_ERROR
Nested Exception:-
javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'SQLQuery.processPreNormalQuery': null
DS Code: DATABASE_ERROR
Source Data Service:-
Name: AccountDetailsService
Location: /AccountDetailsService.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: GetCustaNotWork
Current Params: {EmployeeNumber=3}
Nested Exception:-
java.lang.NullPointerException


	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:75)
	at org.wso2.carbon.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:359)
	at org.wso2.carbon.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:41)
	at org.wso2.carbon.dataservices.core.DBInOutMessageReceiver.invokeBusinessLogic(DBInOutMessageReceiver.java:82)
	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:42)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:415)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by robchur** [comment]
Problem exists in 7.1.0

Same error is thrown.

By removing the second instances the error does not occour.

SELECT
smssubscribernumber,
(
    SELECT UpdateMessage
    FROM wp_database.wp_SMSSubscriberUpdateMessages
    WHERE LocationID = **:idlocation** and NRUCMD = **:smscommand** and Active = 'Yes' OR Active = 'Once'
    ORDER BY RAND()
    LIMIT 1
 ) as UpdateMessage

FROM wp_smssubscriptions_v2
WHERE LocationID = **:idlocation** and smscommand = **:smscommand**
