### ISSUE TITLE
Callout mediator failed for some status codes.

### ISSUE THREAD

**Issue by jsdjayanga** [wso2/product-ei#4559]
refer: https://wso2.org/jira/browse/CARBON-16105

**Comment by totolook** [comment]
Same problem with 422 http code


`[2019-08-09 11:49:08,373] [EI-Core]  INFO - HTTPSender Unable to sendViaGet to url[http://totolook:80/class/cf-validator/cong?cf=39E&surname=Seed&country=F839&birthDate=1993-04-20&name=&sex=M]
org.apache.axis2.AxisFault: Transport error: 422 Error: 
	at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:371)
	at org.apache.axis2.transport.http.HTTPSender.sendViaGet(HTTPSender.java:109)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:63)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:454)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:281)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:441)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:227)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendReceive(BlockingMsgSender.java:490)
	at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:382)
	at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:88)
	at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:85)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:547)
	at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:384)
	at org.apache.synapse.endpoints.HTTPEndpoint.send(HTTPEndpoint.java:85)
	at org.apache.synapse.endpoints.IndirectEndpoint.send(IndirectEndpoint.java:55)
	at org.apache.synapse.mediators.builtin.CallMediator.handleBlockingCall(CallMediator.java:164)
	at org.apache.synapse.mediators.builtin.CallMediator.mediate(CallMediator.java:119)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:351)
	at org.apache.synapse.rest.API.process(API.java:399)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:123)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:101)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by GDLMadushanka** [comment]
Closing the issue since callout mediator is deprecated
