### ISSUE TITLE
Sending message HL7 over proxy with HL7_APPLICATION_ACK=true cause return of ack with error: Message may not be null

### ISSUE THREAD

**Issue by marcses** [wso2/product-ei#462]
In EI 6.0.0 sending a HL7 message through proxy with HL7_APPLICATION_ACK=true throws following error:
`[2017-03-31 16:43:09,755] [] DEBUG - Receiver Failed to read a message
[2017-03-31 16:43:09,865] [] ERROR - ApplicationRouterImpl Attempting to send error message to remote system.
java.lang.NullPointerException: Message may not be null
        at ca.uhn.hl7v2.validation.AbstractValidator.validate(AbstractValidator.java:75)
        at ca.uhn.hl7v2.parser.Parser.assertMessageValidates(Parser.java:611)
        at ca.uhn.hl7v2.parser.Parser.encode(Parser.java:246)
        at ca.uhn.hl7v2.protocol.impl.ApplicationRouterImpl.processMessage(ApplicationRouterImpl.java:149)
        at ca.uhn.hl7v2.protocol.impl.ApplicationRouterImpl.processMessage(ApplicationRouterImpl.java:79)
        at ca.uhn.hl7v2.app.Responder.processMessage(Responder.java:90)
        at ca.uhn.hl7v2.app.Receiver$Grunt.run(Receiver.java:121)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-03-31 16:43:09,890] [] DEBUG - DefaultModelClassFactory Trying to load: ca.uhn.hl7v2.model.v25.message.ACK
[2017-03-31 16:43:09,894] [] DEBUG - DefaultModelClassFactory Loaded: ca.uhn.hl7v2.model.v25.message.ACK class: class ca.uhn.hl7v2.model.v25.message.ACK`

This exception cause a generated ack with error: `207^Application internal error^HL70357^^^^^^Message may not be null`

The same test on ESB 5.0.0 work good
I attach the logs

[log_esb500.txt](https://github.com/wso2/product-ei/files/886064/log_esb500.txt)
[log_ei600.txt](https://github.com/wso2/product-ei/files/886065/log_ei600.txt)
[proxy_hl7.txt](https://github.com/wso2/product-ei/files/886068/proxy_hl7.txt)

**Comment by nandika** [comment]
Hi marcses,

Thank you for reporting the issue. Can you try this out with EI 6.1.0 alpha packs. 

https://github.com/wso2/product-ei/releases/tag/v6.1.0-ALPHA

Regards
Nandika

**Comment by marcses** [comment]
Thanks Nandika,
I will try.

Regards
Marco

Il 31 mar 2017 6:34 PM, "Nandika Jayawardana" <notifications@github.com> ha
scritto:

Hi marcses,

Thank you for reporting the issue. Can you try this out with EI 6.1.0 alpha
packs.

https://github.com/wso2/product-ei/releases/tag/v6.1.0-ALPHA

Regards
Nandika

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wso2/product-ei/issues/462#issuecomment-290762936>, or mute
the thread

**Comment by marcses** [comment]
Hi Nandika,
also EI 6.1.0 alpha packs is affected from the same error.
More detail:
On the first invocation of the proxy, the EI throws a "NullPointerException: Message may not be null" and send back an autogenerated ack with error to the client(see img1)
![img1](https://cloud.githubusercontent.com/assets/26251486/24601185/3e035b6e-1858-11e7-993d-c970c57c74fe.PNG)


But after few seconds the EI receives the response ACK from the service previously invocked. 
[log.txt](https://github.com/wso2/product-ei/files/889372/log.txt)

If I resend to the proxy the same message the EI respond with previous ACK and not with the ACK from the last invocation.
If I send a new message(with new identifier) the EI call the back end service and receive the ack response, but not send nothing to the client(see img2) 
![img2](https://cloud.githubusercontent.com/assets/26251486/24601492/66a58c3a-1859-11e7-8639-a3975e107891.PNG)

It is as if some timeout trigger before receive the back end ACK

**Comment by marcses** [comment]
The problem seems to be caused not from WSO2 EI but from a randomly erroneus ACK of the back end service. I'm sorry.
I close the issue.
