### ISSUE TITLE
write a custom handler error

### ISSUE THREAD

**Issue by TwinsDestiny** [wso2/product-ei#4683]
I wrote a custom handler class, configured into axis2.xml, but I can't start EI, what am I missing?
handler code:
```
package org.apache.rampart.handler;

import org.apache.axiom.om.util.Base64;
import org.apache.axis2.AxisFault;
import org.apache.axis2.context.MessageContext;
import org.apache.axis2.description.AxisService;
import org.apache.axis2.description.HandlerDescription;
import org.apache.axis2.description.Parameter;
import org.apache.axis2.engine.Handler;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.Map;

public class RoleSampleHandler implements Handler {

    private static Log log = LogFactory.getLog(RoleSampleHandler.class);

    @Override
    public void cleanup() {

    }

    @Override
    public void init(HandlerDescription handlerDescription) {

    }

    @Override
    public InvocationResponse invoke(MessageContext messageContext) throws AxisFault {
        AxisService service = messageContext.getAxisService();
        String basicAuthHeader = getBasicAuthHeaders(messageContext);
        String username = null;
        String password = null;
        if (basicAuthHeader != null && basicAuthHeader.startsWith("Basic ")) {
            basicAuthHeader = new String(Base64.decode(basicAuthHeader.substring(6)));
            int i = basicAuthHeader.indexOf(':');
            if (i == -1) {
                username = basicAuthHeader;
            } else {
                username = basicAuthHeader.substring(0, i);
            }

            if (i != -1) {
                password = basicAuthHeader.substring(i + 1);
                if (StringUtils.equals("", password)) {
                    password = null;
                }
            }
        }
        log.error("service:"+service.getName());
        log.error("username:"+username);
        log.error("password:"+password);
        return InvocationResponse.CONTINUE;
    }

    @Override
    public void flowComplete(MessageContext messageContext) {

    }

    @Override
    public HandlerDescription getHandlerDesc() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public Parameter getParameter(String s) {
        return null;
    }

    /**
     * Utility method to return basic auth transport headers if present
     *
     * @return
     */
    private String getBasicAuthHeaders(MessageContext msgCtx) {

        Map map = (Map) msgCtx.getProperty(MessageContext.TRANSPORT_HEADERS);
        if (map == null) {
            return null;
        }
        String tmp = (String) map.get("Authorization");
        if (tmp == null) {
            tmp = (String) map.get("authorization");
        }
        if (tmp != null && tmp.trim().startsWith("Basic ")) {
            return tmp;
        } else {
            return null;
        }
    }
}
```

axis2.xml
```
<phase name="PreDispatch">
            <handler name="RoleSampleHandler"
                     class="org.apache.rampart.handler.RoleSampleHandler">
                <order phase="PreDispatch"/>
            </handler>
        </phase>
```

console log
```
[2019-09-25 18:27:23,040] [EI-Core]  INFO - CarbonCoreActivator Starting WSO2 Carbon...
[2019-09-25 18:27:23,048] [EI-Core]  INFO - CarbonCoreActivator Operating System : Linux 3.10.0-862.el7.x86_64, amd64
[2019-09-25 18:27:23,048] [EI-Core]  INFO - CarbonCoreActivator Java Home        : /u01/jdk1.8.0_161/jre
[2019-09-25 18:27:23,049] [EI-Core]  INFO - CarbonCoreActivator Java Version     : 1.8.0_161
[2019-09-25 18:27:23,049] [EI-Core]  INFO - CarbonCoreActivator Java VM          : Java HotSpot(TM) 64-Bit Server VM 25.161-b12,Oracle Corporation
[2019-09-25 18:27:23,049] [EI-Core]  INFO - CarbonCoreActivator Carbon Home      : /u01/wso2ei-6.5.0
[2019-09-25 18:27:23,049] [EI-Core]  INFO - CarbonCoreActivator Java Temp Dir    : /u01/wso2ei-6.5.0/wso2/tmp
[2019-09-25 18:27:23,049] [EI-Core]  INFO - CarbonCoreActivator User             : root, zh-CN, Asia/Shanghai
[2019-09-25 18:27:23,337] [EI-Core]  INFO - DefaultCryptoProviderComponent 'CryptoService.Secret' property has not been set. 'org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider' won't be registered as an internal crypto provider. Please set the secret if the provider needs to be registered.
[2019-09-25 18:27:23,366] [EI-Core]  INFO - GoogleTokenGenDSComponent Activating GoogleTokengen DS component
[2019-09-25 18:27:23,513] [EI-Core]  INFO - KafkaEventAdapterServiceDS Successfully deployed the Kafka output event adaptor service
[2019-09-25 18:27:27,245] [EI-Core]  INFO - EmbeddedRegistryService Configured Registry in 97ms
[2019-09-25 18:27:27,487] [EI-Core]  INFO - RegistryCoreServiceComponent Registry Mode    : READ-WRITE
[2019-09-25 18:27:31,488] [EI-Core]  INFO - SolrClient Default Embedded Solr Server Initialized
[2019-09-25 18:27:31,747] [EI-Core]  INFO - UserStoreMgtDSComponent Carbon UserStoreMgtDSComponent activated successfully.
[2019-09-25 18:27:49,476] [EI-Core]  INFO - TaglibUriRule TLD skipped. URI: http://tiles.apache.org/tags-tiles is already defined
[2019-09-25 18:27:50,693] [EI-Core] FATAL - CarbonServerManager WSO2 Carbon initialization Failed
java.lang.NullPointerException
        at org.apache.axis2.engine.Phase.insertHandler(Phase.java:206)
        at org.apache.axis2.engine.Phase.addHandler(Phase.java:151)
        at org.apache.axis2.deployment.AxisConfigBuilder.processPhaseList(AxisConfigBuilder.java:551)
        at org.apache.axis2.deployment.AxisConfigBuilder.processPhaseOrders(AxisConfigBuilder.java:580)
        at org.apache.axis2.deployment.AxisConfigBuilder.populateConfig(AxisConfigBuilder.java:150)
        at org.wso2.carbon.core.CarbonAxisConfigurator.populateAxisConfiguration(CarbonAxisConfigurator.java:341)
        at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:192)
        at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:64)
        at org.wso2.carbon.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:65)
        at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:401)
        at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManager.java:220)
        at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(CarbonCoreServiceComponent.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
        at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
        at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)
        at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)
        at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1230)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1174)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1066)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5433)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5731)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1707)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1697)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by sameeragunarathne** [comment]
Hi since this is a issue regarding to a customization, can you join our slack channel to put these type issues? you can register to our slack channel from [here](http://tiny.cc/wso2-ei-slack-invite)
