### ISSUE TITLE
[Bug][Synapse] Templates does not work with expressions with json-eval()

### ISSUE THREAD

**Issue by milindaperera** [wso2/product-ei#4712]
**Description:**
Following error json-eval() expression with template parameters.

Related issue: https://wso2.org/jira/browse/ESBJAVA-3517

```
[2019-10-17 10:31:48,427] [EI-Core] ERROR - elkTestAPI org.apache.synapse.core.axis2.Axis2MessageContext cannot be cast to org.apache.axiom.om.OMNode
java.lang.ClassCastException: org.apache.synapse.core.axis2.Axis2MessageContext cannot be cast to org.apache.axiom.om.OMNode
	at org.apache.axiom.om.xpath.DocumentNavigator.getDocumentNode(DocumentNavigator.java:602)
	at org.jaxen.expr.DefaultAbsoluteLocationPath.evaluate(DefaultAbsoluteLocationPath.java:102)
	at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:102)
	at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:677)
	at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:216)
	at org.jaxen.BaseXPath.selectSingleNode(BaseXPath.java:237)
	at org.apache.synapse.mediators.Value.resolveObject(Value.java:165)
	at org.apache.synapse.mediators.template.TemplateContext.resolveExpressionValue(TemplateContext.java:106)
	at org.apache.synapse.mediators.template.TemplateContext.getEvaluatedParamValue(TemplateContext.java:95)
	at org.apache.synapse.mediators.template.TemplateContext.setupParams(TemplateContext.java:69)
	at org.apache.synapse.mediators.template.TemplateMediator.pushFuncContextTo(TemplateMediator.java:160)
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:130)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:148)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:84)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:376)
	at org.apache.synapse.rest.API.process(API.java:431)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:135)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:113)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:338)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:383)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Affected Product Version:**
6.5.0
All versions that use Synspase versions after v2.1.7-wso2v35 (works fine in EI 6.1.1)

**Steps to reproduce:**
```xml
<sequence name="publishToELK" xmlns="http://ws.apache.org/ns/synapse">
    <elasticsearch.init>
        <apiUrl>http://localhost:9200</apiUrl>
    </elasticsearch.init>
    <elasticsearch.createDocumentWithIndex>
        <indexName>{json-eval($.indexName)}</indexName>
        <type>{json-eval($.type)}</type>
        <message>{json-eval($.message)}</message>
    </elasticsearch.createDocumentWithIndex>
    <drop/>
</sequence>
```

**Comment by malakaganga** [comment]
Fixed with:
https://github.com/wso2/wso2-synapse/pull/1366
