### ISSUE TITLE
[EI61] [Cluster] Odata invocation failed due to connection refused exception

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#474]
Environment
OS -redhat6, redhat7, debian
JAVA -jdk 1.8
DB - oracle

**Steps**
1. Set up cluster as documented in [1]
2. deploy a data service enabling odata
3. Invoke the service

**Observations**
1. Invocation failed with following exceptions

```
TID: [-1] [] [2017-04-03 11:00:35,210]  WARN {org.apache.synapse.transport.passthru.ConnectCallback} -  Connection refused or failed for : ei.wso2.com/192.168.48.132:9763 {org.apache.synapse.transport.passthru.ConnectCallback}
TID: [-1234] [] [2017-04-03 11:00:35,213]  WARN {org.apache.synapse.endpoints.EndpointContext} -  Endpoint : AnonymousEndpoint with address http://ei.wso2.com:9763 will be marked SUSPENDED as it failed {org.apache.synapse.endpoints.EndpointContext}
TID: [-1234] [] [2017-04-03 11:00:35,213]  WARN {org.apache.synapse.endpoints.EndpointContext} -  Suspending endpoint : AnonymousEndpoint with address http://ei.wso2.com:9763 - last suspend duration was : 30000ms and current suspend duration is : 30000ms - Next retry after : Mon Apr 03 11:01:05 IST 2017 {org.apache.synapse.endpoints.EndpointContext}

```

```
TID: [-1234] [] [2017-04-03 14:04:36,555]  WARN {org.apache.synapse.endpoints.EndpointContext} -  Endpoint : AnonymousEndpoint with address https://ei.wso2.com:9443 will be marked SUSPENDED as it failed {org.apache.synapse.endpoints.EndpointContext}
TID: [-1234] [] [2017-04-03 14:04:36,556]  WARN {org.apache.synapse.endpoints.EndpointContext} -  Suspending endpoint : AnonymousEndpoint with address https://ei.wso2.com:9443 - last suspend duration was : 30000ms and current suspend duration is : 30000ms - Next retry after : Mon Apr 03 14:05:06 IST 2017 {org.apache.synapse.endpoints.EndpointContext}
```
**Note** - When a user invoke odata service, service call handled by the nginx and directed to the EI. since we have mapped the nginx ip to the hostname in /etc/hosts file of the EI nodes, internal service call redirects to the nginx and failed. 
As a workaround for this odata issue, I have mapped the IP of the EI node to the hostname in the /etc/hosts file.

After this workaround, scheduled task failed with below exception

```
TID: [-1234] [] [2017-04-04 10:50:00,025]  INFO {org.apache.axis2.transport.http.HTTPSender} -  Unable to sendViaPost to url[http://ei.wso2.com:80/services/mysqltest] {org.apache.axis2.transport.http.HTTPSender}
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(AbstractHTTPSender.java:659)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:195)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:77)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:430)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.axis2.client.ServiceClient.sendReceive(ServiceClient.java:554)
	at org.apache.axis2.client.ServiceClient.sendReceive(ServiceClient.java:530)
	at org.wso2.carbon.ntask.solutions.webservice.WebServiceCallTask.execute(WebServiceCallTask.java:131)
	at org.wso2.carbon.dataservices.task.DSTask.execute(DSTask.java:88)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
TID: [-1234] [] [2017-04-04 10:50:00,029] ERROR {org.wso2.carbon.ntask.solutions.webservice.WebServiceCallTask} -  Error in executing web service call task: Connection refused {org.wso2.carbon.ntask.solutions.webservice.WebServiceCallTask}
org.apache.axis2.AxisFault: Connection refused
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:199)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:77)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:430)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.axis2.client.ServiceClient.sendReceive(ServiceClient.java:554)
	at org.apache.axis2.client.ServiceClient.sendReceive(ServiceClient.java:530)
	at org.wso2.carbon.ntask.solutions.webservice.WebServiceCallTask.execute(WebServiceCallTask.java:131)
	at org.wso2.carbon.dataservices.task.DSTask.execute(DSTask.java:88)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(AbstractHTTPSender.java:659)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:195)
	... 18 more
```

[1] https://docs.wso2.com/display/EI610/Clustering+the+Integration+Profile#497427d176394f6cb1b19cb297511f39

**Comment by Vathsan** [comment]
The issue is not reproducible in EI 6.5.0-m5 pack. The error occurs due to some misconfigurations. With IP of the EI node set for the hostname in the /etc/hosts file, scheduled task works fine.
