### ISSUE TITLE
[EI61][DSS] Failed to invoke rest service POST method with path parameters

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#484]
**Environment**
OS -redhat6, redhat7, debian
JAVA -jdk 1.8
DB - oracle12c
Pack - 03/04/2017 snapshot

**Steps**
1. Create a datasource with insert query

```
 <query id="addresource" useConfig="persdb">
      <sql>INSERT INTO TestResource (ID,LastName,FirstName,Age) VALUES (:id,:Lname,:Fname,:age);</sql>
      <param name="id" sqlType="INTEGER"/>
      <param name="Lname" sqlType="STRING"/>
      <param name="Fname" sqlType="STRING"/>
      <param name="age" sqlType="INTEGER"/>
   </query>
```
2. Create rest resource for above query as below

 ```
  <resource method="POST" path="addresource/{id}/{Lname}/{Fname}/{age}">
      <call-query href="addresource">
         <with-param name="id" query-param="id"/>
         <with-param name="Lname" query-param="Lname"/>
         <with-param name="Fname" query-param="Fname"/>
         <with-param name="age" query-param="age"/>
      </call-query>
   </resource>
```
3. Invoke the REST service
POST  http://ei.wso2.com:80/services/mysqltest/addresource/70/Neem/Peter/28

**Observation**
Following exception observed

```
TID: [-1234] [] [2017-04-04 20:56:15,307] ERROR {org.wso2.carbon.dataservices.core.DBInOnlyMessageReceiver} -  Error in in-only message receiver {org.wso2.carbon.dataservices.core.DBInOnlyMessageReceiver}
DS Fault Message: Error in DS non result invoke.
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Nested Exception:-
javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:Lname
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Source Data Service:-
Name: mysqltest
Location: /mysqltest.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: _postaddresource_id_lname_fname_age
Current Params: {}


	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processSingleRequest(SingleDataServiceRequest.java:118)
	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:67)
	at org.wso2.carbon.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:354)
	at org.wso2.carbon.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:41)
	at org.wso2.carbon.dataservices.core.DBInOnlyMessageReceiver.invokeBusinessLogic(DBInOnlyMessageReceiver.java:53)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:372)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:Lname
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Source Data Service:-
Name: mysqltest
Location: /mysqltest.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: _postaddresource_id_lname_fname_age
Current Params: {}

	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.execute(DSOMDataSource.java:102)
	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.serialize(DSOMDataSource.java:107)
	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.executeInOnly(DSOMDataSource.java:80)
	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processSingleRequest(SingleDataServiceRequest.java:116)
	... 13 more
TID: [-1234] [] [2017-04-04 20:56:15,309] ERROR {org.apache.synapse.transport.passthru.ServerWorker} -  Error processing POST request for : /services/mysqltest/addresource/70/wijesiri/kaushi/28 {org.apache.synapse.transport.passthru.ServerWorker}
org.apache.axis2.AxisFault: DS Fault Message: Error in DS non result invoke.
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Nested Exception:-
javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:Lname
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Source Data Service:-
Name: mysqltest
Location: /mysqltest.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: _postaddresource_id_lname_fname_age
Current Params: {}


	at org.wso2.carbon.dataservices.core.DBUtils.createAxisFault(DBUtils.java:740)
	at org.wso2.carbon.dataservices.core.DBInOnlyMessageReceiver.invokeBusinessLogic(DBInOnlyMessageReceiver.java:57)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:372)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'CallQuery.extractParams', cannot find parameter with type:query-param name:Lname
DS Code: INCOMPATIBLE_PARAMETERS_ERROR
Source Data Service:-
Name: mysqltest
Location: /mysqltest.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: _postaddresource_id_lname_fname_age
Current Params: {}

	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.execute(DSOMDataSource.java:102)
	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.serialize(DSOMDataSource.java:107)
	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.executeInOnly(DSOMDataSource.java:80)
	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processSingleRequest(SingleDataServiceRequest.java:116)
	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:67)
	at org.wso2.carbon.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:354)
	at org.wso2.carbon.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:41)
	at org.wso2.carbon.dataservices.core.DBInOnlyMessageReceiver.invokeBusinessLogic(DBInOnlyMessageReceiver.java:53)
	... 9 more
```

**Comment by prabushi** [comment]
Was able to reproduce the same in Ubuntu.

**Comment by madhawa-gunasekara** [comment]
This is an invalid scenario, because When We use POST Method according to HTTP spec Payload is mandatory.
https://tools.ietf.org/html/rfc7231#section-4

**Comment by sashikamw** [comment]
Hi Madahawa,

According to the "Sample data service configuration" section in the document [1] we should be able to use to POST with path parameters. Also since we support POST with nobody for ESB [2] shouldn't we support this? 

And this works with curl.
curl -X POST http://ei.wso2.com:80/services/mysqltest/addperson/169/lastnametests/firstname/addresssame/city

If we do not support we have to correct the documentation [1].


[1] https://docs.wso2.com/display/DSS351/About+Data+Services+and+Resources
[2] https://docs.wso2.com/display/EI600/Unusual+Scenarios+for+HTTP+Methods+in+REST

**Comment by rdulmina** [comment]
This issue is still there in MI 8.2.0
