### ISSUE TITLE
SOAP message MUST NOT contain a Document Type Declaration

### ISSUE THREAD

**Issue by vishal-r-jain** [wso2/product-ei#4843]
I have a sample SOAP data of `<soapenv:Envelope
	xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:v1="http://autotask.net/ATWS/v1_5/">
	<soapenv:Header>
		<v1:AutotaskIntegrations>
			<v1:IntegrationCode>$1</v1:IntegrationCode>
		</v1:AutotaskIntegrations>
	</soapenv:Header>
	<soapenv:Body>
		<v1:query>
			<sXML><![CDATA[<queryxml><entity>$2</entity><query><condition><field>$3<expression op="equals">$4</expression></field></condition></query></queryxml>]]></sXML>
		</v1:query>
	</soapenv:Body>
</soapenv:Envelope>`

which is transformed and populated as per requirements but , during Call execution via Call mediator on a WSDL endpoint, WSO2 EI always throw the above error: `[2019-12-03 17:48:28,085] []  INFO - BuilderUtil OMException in getSOAPBuilder
org.apache.axiom.om.OMException: SOAP message MUST NOT contain a Document Type Declaration(DTD)
        at org.apache.axiom.soap.impl.builder.StAXSOAPModelBuilder.createDTD(StAXSOAPModelBuilder.java:462)
        at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:282)
        at org.apache.axiom.soap.impl.builder.StAXSOAPModelBuilder.getSOAPEnvelope(StAXSOAPModelBuilder.java:204)
        at org.apache.axiom.soap.impl.builder.StAXSOAPModelBuilder.<init>(StAXSOAPModelBuilder.java:154)
        at org.apache.axiom.soap.impl.builder.StAXSOAPModelBuilder.<init>(StAXSOAPModelBuilder.java:140)
        at org.apache.axis2.builder.BuilderUtil.getSOAPBuilder(BuilderUtil.java:658)
        at org.apache.axis2.transport.TransportUtils.createDocumentElement(TransportUtils.java:206)
        at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:146)
        at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:109)
        at org.apache.axis2.transport.TransportUtils.createSOAPMessage(TransportUtils.java:68)
        at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:352)
        at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:457)
        at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
        at org.apache.synapse.message.senders.blocking.BlockingMsgSender.sendReceive(BlockingMsgSender.java:492)
        at org.apache.synapse.message.senders.blocking.BlockingMsgSender.send(BlockingMsgSender.java:384)
        at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:92)
        at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:85)
        at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:569)
        at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:398)
        at org.apache.synapse.endpoints.WSDLEndpoint.send(WSDLEndpoint.java:75)
        at org.apache.synapse.endpoints.IndirectEndpoint.send(IndirectEndpoint.java:55)
        at org.apache.synapse.mediators.builtin.CallMediator.handleBlockingCall(CallMediator.java:165)
        at org.apache.synapse.mediators.builtin.CallMediator.mediate(CallMediator.java:120)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectInbound(Axis2SynapseEnvironment.java:467)
        at org.wso2.carbon.inbound.endpoint.protocol.jms.JMSInjectHandler.invoke(JMSInjectHandler.java:255)
        at org.wso2.carbon.inbound.endpoint.protocol.jms.JMSPollingConsumer.poll(JMSPollingConsumer.java:297)
        at org.wso2.carbon.inbound.endpoint.protocol.jms.JMSPollingConsumer.execute(JMSPollingConsumer.java:204)
        at org.wso2.carbon.inbound.endpoint.protocol.jms.JMSTask.taskExecute(JMSTask.java:47)
        at org.wso2.carbon.inbound.endpoint.common.InboundTask.execute(InboundTask.java:45)
        at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
        at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

I am using **WSO2 EI 6.5.0**

**Comment by vishal-r-jain** [comment]
Got the Resolution, as the issue was from the Hosting WebService.
