### ISSUE TITLE
AxisFault: Can not output XML declaration, after other output has already been done.

### ISSUE THREAD

**Issue by robbla** [wso2/product-ei#4871]
I am doing a xslt transformation. I am using the pizzashack.war file that originally was developed by WSO2 for training.  It is running on AS 5.3.0.

<?xml version="1.0" encoding="UTF-8"?>
<proxy name="XSLService" startOnLoad="true" transports="http https" xmlns="http://ws.apache.org/ns/synapse">
    <target>
        <inSequence>
            <send>
                <endpoint key="XSLEndpoint"/>
            </send>
        </inSequence>
        <outSequence>
            <log level="full"/>
            <property name="messageType" scope="axis2" type="STRING" value="text/xml"/>
            <log/>
            <xslt key="gov:xlst/transform_menu.xsl"/>
            <send/>
        </outSequence>
        <faultSequence/>
    </target>
</proxy>

xslt

<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	version="1.0">

	
    <xsl:template match="@*|node()">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()" />
        </xsl:copy>
    </xsl:template>
    
	
	<xsl:template match="jsonArray">
        <pizzas xmlns:wso2="training.yenlo.wso2.com">
          <xsl:apply-templates select="@*|node()" />
        </pizzas>
    </xsl:template>
	
	
    <xsl:template match="jsonElement">
        <pizza>
          <xsl:apply-templates select="@*|node()" />
        </pizza>
    </xsl:template>
    
	    
    <xsl:template match="toppings">
        <topping>
          <xsl:apply-templates select="name/text()" />
        </topping>
    </xsl:template>
  
</xsl:stylesheet>

TID: [-1234] [] [2019-12-09 09:48:24,470] ERROR {org.apache.synapse.transport.passthru.PassThroughHttpSender} - Failed to submit the response org.apache.axis2.AxisFault: Can not output XML declaration, after other output has already been done.
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:626)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:285)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:220)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:554)
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:120)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:360)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:578)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:195)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:284)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.stream.XMLStreamException: Can not output XML declaration, after other output has already been done.
	at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1522)
	at com.ctc.wstx.sw.BaseStreamWriter.reportNwfStructure(BaseStreamWriter.java:1551)
	at com.ctc.wstx.sw.BaseStreamWriter.doWriteStartDocument(BaseStreamWriter.java:650)
	at com.ctc.wstx.sw.BaseStreamWriter.writeStartDocument(BaseStreamWriter.java:638)
	at com.ctc.wstx.sw.BaseStreamWriter.writeStartDocument(BaseStreamWriter.java:626)
	at org.apache.axiom.om.impl.MTOMXMLStreamWriter.writeStartDocument(MTOMXMLStreamWriter.java:277)
	at org.apache.synapse.commons.json.JsonDataSource.serialize(JsonDataSource.java:88)
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.internalSerialize(OMSourcedElementImpl.java:694)
	at org.apache.axiom.om.impl.util.OMSerializerUtil.serializeChildren(OMSerializerUtil.java:562)
	at org.apache.axiom.om.impl.llom.OMElementImpl.internalSerialize(OMElementImpl.java:879)
	at org.apache.axiom.soap.impl.llom.SOAPEnvelopeImpl.serializeInternally(SOAPEnvelopeImpl.java:283)
	at org.apache.axiom.soap.impl.llom.SOAPEnvelopeImpl.internalSerialize(SOAPEnvelopeImpl.java:245)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.serializeAndConsume(OMSerializableImpl.java:193)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:74)
	... 18 more

TID: [-1234] [] [2019-12-09 09:48:24,815] ERROR {org.apache.synapse.core.axis2.Axis2Sender} - Content-Type:text/xml, Unexpected error sending message back org.apache.axis2.AxisFault: Failed to submit the response
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.handleException(PassThroughHttpSender.java:688)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:287)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:220)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:554)
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:120)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:360)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:578)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:195)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:284)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Can not output XML declaration, after other output has already been done.
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:626)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:285)
	... 16 more
Caused by: javax.xml.stream.XMLStreamException: Can not output XML declaration, after other output has already been done.
	at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1522)
	at com.ctc.wstx.sw.BaseStreamWriter.reportNwfStructure(BaseStreamWriter.java:1551)
	at com.ctc.wstx.sw.BaseStreamWriter.doWriteStartDocument(BaseStreamWriter.java:650)
	at com.ctc.wstx.sw.BaseStreamWriter.writeStartDocument(BaseStreamWriter.java:638)
	at com.ctc.wstx.sw.BaseStreamWriter.writeStartDocument(BaseStreamWriter.java:626)
	at org.apache.axiom.om.impl.MTOMXMLStreamWriter.writeStartDocument(MTOMXMLStreamWriter.java:277)
	at org.apache.synapse.commons.json.JsonDataSource.serialize(JsonDataSource.java:88)
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.internalSerialize(OMSourcedElementImpl.java:694)
	at org.apache.axiom.om.impl.util.OMSerializerUtil.serializeChildren(OMSerializerUtil.java:562)
	at org.apache.axiom.om.impl.llom.OMElementImpl.internalSerialize(OMElementImpl.java:879)
	at org.apache.axiom.soap.impl.llom.SOAPEnvelopeImpl.serializeInternally(SOAPEnvelopeImpl.java:283)
	at org.apache.axiom.soap.impl.llom.SOAPEnvelopeImpl.internalSerialize(SOAPEnvelopeImpl.java:245)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.serializeAndConsume(OMSerializableImpl.java:193)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:74)
	... 18 more

**Comment by Nirothipan** [comment]
Could you specify the product version and provide simplified artifacts to reproduce the issue if possible

**Comment by robbla** [comment]
i am using the pizzashack.war file as described here https://docs.wso2.com/display/AM160/Invoking+APIs+using+a+Web+App+Deployed+in+WSO2+AS , rather on an AS instead of APIM.

create a custom proxy called XSLservice
Define a new endpoint with the following content:
Uri-template: http://localhost:9764/pizzashop-rs_1.0/services/menu/pizza/all/
method: GET 
Add to the InSequence a Send mediator and a HTTP endpoint you just defined. Drag the endpoint from the Defined Endpoints 

We use the technique of lab 9 to transform the response back to XML. Add the following properties to the OutSequence:
<property name="messageType" scope="axis2" value="text/xml"/>
<property name="ContentType" scope="axis2" value="text/xml"/>
 Also add a LOG mediator, log-level ‘full’ and a SEND mediator to the outSequence. The outSequence now looks like this from a graphical overview:
Add the two artifacts to the server using an existing CAR file or create a new one. Deploy the CAR file in the regular way.


Test using SOAP-UI. (create new soap service using http://localhost:8280/services/XSLService?wsdl as wsdl)
As the request translates to a ‘GET’ request at the backend you do not need to change anything to the request.

Does this suffice? I can show you in na zoom meeting if desired

**Comment by robbla** [comment]
beta 660, soap 5.2.1, as 5.3.0 (downloaded OOTB)
