### ISSUE TITLE
Error occurs when it is trying to deploy the SimpleStockQuote service. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#4905]
**Description:**
Once it starts the axis2Server and deploys the SimpleStock quote service, it's getting the following error in axis2server. 

```
org.apache.axis2.deployment.DeploymentException: The following error occurred during schema generation: Error looking for paramter names in bytecode: unexpected bytes in file
	at org.apache.axis2.deployment.repository.util.ArchiveReader.processServiceGroup(ArchiveReader.java:150)
	at org.apache.axis2.deployment.ServiceDeployer.deploy(ServiceDeployer.java:82)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.axis2.deployment.DeploymentException: The following error occurred during schema generation: Error looking for paramter names in bytecode: unexpected bytes in file
	at org.apache.axis2.deployment.ServiceGroupBuilder.populateServiceGroup(ServiceGroupBuilder.java:106)
	at org.apache.axis2.deployment.repository.util.ArchiveReader.buildServiceGroup(ArchiveReader.java:109)
	at org.apache.axis2.deployment.repository.util.ArchiveReader.processServiceGroup(ArchiveReader.java:143)
	... 15 more
Caused by: org.apache.axis2.deployment.DeploymentException: The following error occurred during schema generation: Error looking for paramter names in bytecode: unexpected bytes in file
	at org.apache.axis2.deployment.ServiceBuilder.populateService(ServiceBuilder.java:441)
	at org.apache.axis2.deployment.ServiceGroupBuilder.populateServiceGroup(ServiceGroupBuilder.java:101)
	... 17 more
Caused by: org.apache.axis2.deployment.DeploymentException: The following error occurred during schema generation: Error looking for paramter names in bytecode: unexpected bytes in file
	at org.apache.axis2.deployment.ServiceBuilder.populateService(ServiceBuilder.java:405)
	... 18 more
Caused by: java.lang.IllegalStateException: Error looking for paramter names in bytecode: unexpected bytes in file
	at org.apache.axis2.description.java2wsdl.bytecode.ClassReader.readCpool(ClassReader.java:354)
	at org.apache.axis2.description.java2wsdl.bytecode.ParamReader.<init>(ParamReader.java:78)
	at org.apache.axis2.description.java2wsdl.bytecode.ParamReader.<init>(ParamReader.java:57)
	at org.apache.axis2.description.java2wsdl.bytecode.ChainedParamReader.<init>(ChainedParamReader.java:52)
	at org.apache.axis2.description.java2wsdl.bytecode.MethodTable.<init>(MethodTable.java:31)
	at org.apache.axis2.description.java2wsdl.DefaultSchemaGenerator.<init>(DefaultSchemaGenerator.java:143)
	at org.apache.axis2.deployment.util.Utils.fillAxisService(Utils.java:457)
	at org.apache.axis2.deployment.ServiceBuilder.populateService(ServiceBuilder.java:397)
	... 18 more
[2019-12-17 11:38:49,089] ERROR {org.apache.axis2.deployment.ServiceDeployer} - The SimpleStockQuoteService.aar service, which is not valid, caused The following error occurred during schema generation: Error looking for paramter names in bytecode: unexpected bytes in file
org.apache.axis2.deployment.DeploymentException: The following error occurred during schema generation: Error looking for paramter names in bytecode: unexpected bytes in file
	at org.apache.axis2.deployment.repository.util.ArchiveReader.processServiceGroup(ArchiveReader.java:150) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.ServiceDeployer.deploy(ServiceDeployer.java:82) [axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136) [axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807) [axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144) [axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377) [axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254) [axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371) [axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59) [axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67) [axis2_1.6.1.wso2v40.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.apache.axis2.deployment.DeploymentException: The following error occurred during schema generation: Error looking for paramter names in bytecode: unexpected bytes in file
	at org.apache.axis2.deployment.ServiceGroupBuilder.populateServiceGroup(ServiceGroupBuilder.java:106) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.repository.util.ArchiveReader.buildServiceGroup(ArchiveReader.java:109) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.repository.util.ArchiveReader.processServiceGroup(ArchiveReader.java:143) ~[axis2_1.6.1.wso2v40.jar:?]
	... 15 more
Caused by: org.apache.axis2.deployment.DeploymentException: The following error occurred during schema generation: Error looking for paramter names in bytecode: unexpected bytes in file
	at org.apache.axis2.deployment.ServiceBuilder.populateService(ServiceBuilder.java:441) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.ServiceGroupBuilder.populateServiceGroup(ServiceGroupBuilder.java:101) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.repository.util.ArchiveReader.buildServiceGroup(ArchiveReader.java:109) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.repository.util.ArchiveReader.processServiceGroup(ArchiveReader.java:143) ~[axis2_1.6.1.wso2v40.jar:?]
	... 15 more
Caused by: org.apache.axis2.deployment.DeploymentException: The following error occurred during schema generation: Error looking for paramter names in bytecode: unexpected bytes in file
	at org.apache.axis2.deployment.ServiceBuilder.populateService(ServiceBuilder.java:405) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.ServiceGroupBuilder.populateServiceGroup(ServiceGroupBuilder.java:101) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.repository.util.ArchiveReader.buildServiceGroup(ArchiveReader.java:109) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.repository.util.ArchiveReader.processServiceGroup(ArchiveReader.java:143) ~[axis2_1.6.1.wso2v40.jar:?]
	... 15 more
Caused by: java.lang.IllegalStateException: Error looking for paramter names in bytecode: unexpected bytes in file
	at org.apache.axis2.description.java2wsdl.bytecode.ClassReader.readCpool(ClassReader.java:354) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.description.java2wsdl.bytecode.ParamReader.<init>(ParamReader.java:78) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.description.java2wsdl.bytecode.ParamReader.<init>(ParamReader.java:57) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.description.java2wsdl.bytecode.ChainedParamReader.<init>(ChainedParamReader.java:52) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.description.java2wsdl.bytecode.MethodTable.<init>(MethodTable.java:31) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.description.java2wsdl.DefaultSchemaGenerator.<init>(DefaultSchemaGenerator.java:143) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.util.Utils.fillAxisService(Utils.java:457) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.ServiceBuilder.populateService(ServiceBuilder.java:397) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.ServiceGroupBuilder.populateServiceGroup(ServiceGroupBuilder.java:101) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.repository.util.ArchiveReader.buildServiceGroup(ArchiveReader.java:109) ~[axis2_1.6.1.wso2v40.jar:?]
	at org.apache.axis2.deployment.repository.util.ArchiveReader.processServiceGroup(ArchiveReader.java:143) ~[axis2_1.6.1.wso2v40.jar:?]
	... 15 more
[2019-12-17 11:38:49,100]  INFO {org.apache.axis2.deployment.DeploymentEngine} - org.apache.axis2.deployment.DeploymentException: The following error occurred during schema generation: Error looking for paramter names in bytecode: unexpected bytes in file


```
**Affected Product Version:**
wso2ei-6.6.0-rc2
openjdk version "11.0.5" 2019-10-15

**OS, DB, other environment details and versions:**    
macOS/ Windows 10

**Comment by milindaperera** [comment]
This isssue is when building the .aar file using ant in JDK 11. As a solution we can do ant build in JDK 8

**Comment by isuruuy429** [comment]
Shall we add that into docs?
