### ISSUE TITLE
Hospital service jar hosted in QSG is not working in JDK 11

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#4918]
**Description:**
[QSG](https://docs.wso2.com/display/EI660/Quick+Start+Guide#ba002576187447b8ae425b539a0f6095) hosts a Hospital-Service-2.0.0-EI7.jar which is written in ballerina. 
It's not working in JDK 11 and giving the following exception

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.wso2.msf4j.internal.router.MicroserviceMetadata.<init>(MicroserviceMetadata.java:68)
	at org.wso2.msf4j.internal.MicroservicesRegistryImpl.updateMetadata(MicroservicesRegistryImpl.java:171)
	at org.wso2.msf4j.internal.MicroservicesRegistryImpl.addService(MicroservicesRegistryImpl.java:78)
	at org.wso2.msf4j.MicroservicesRunner.deploy(MicroservicesRunner.java:84)
	at org.wso2.service.hospital.Application.main(Application.java:29)
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
```

**Suggested Labels:**
Bug

**Affected Product Version:**
EI 6.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Start the Hospital-Service jar file in JDK 11

**Comment by nilminiwso2** [comment]
Docs are updated with the updated JAR [1].
[1] https://github.com/wso2-docs/WSO2_EI/blob/master/Back-End-Service/Hospital-Service-JDK11-2.0.0.jar
