### ISSUE TITLE
Move to MsSQL Server Errors - 6.6.0

### ISSUE THREAD

**Issue by scholtz** [wso2/product-ei#4945]
**Description:**
Hi, my intention is to change server to MsSQL, but errors occure. 

I assume that the problem is that the database is not initialized properly.

master-datasources.xml:
```
<datasources-configuration xmlns:svns="http://org.wso2.securevault/configuration">
        <providers>
            <provider>org.wso2.carbon.ndatasource.rdbms.RDBMSDataSourceReader</provider>
        </providers>
        <datasources>
           <datasource>
                <name>WSO2_CARBON_DB</name>
                <description>The datasource used for registry and user manager</description>
                <jndiConfig>
                       <name>jdbc/WSO2CarbonDB</name>
                </jndiConfig>
                <definition type="RDBMS">
                       <configuration>
                          <url>jdbc:sqlserver://MsSQLServer;databaseName=WSO2EI</url>
                          <username>MsSQLServerUser</username>
                          <password>MsSQLServerPassword</password>
                         <driverClassName>com.microsoft.sqlserver.jdbc.SQLServerDriver</driverClassName>
                          <maxActive>80</maxActive>
                          <maxWait>60000</maxWait>
                          <testOnBorrow>true</testOnBorrow>
                          <validationQuery>SELECT 1</validationQuery>
                          <validationInterval>30000</validationInterval>
                          <defaultAutoCommit>false</defaultAutoCommit>
                       </configuration>
                </definition>
            </datasource>  
        </datasources>
    </datasources-configuration>
```

As the [documentation says](https://docs.wso2.com/display/EI660/Changing+to+MSSQL+): 

> You can create database tables automatically when starting the product for the first time by using the -Dsetup parameter as follows:
> For Windows: <PRODUCT_HOME>/bin/wso2server.bat -Dsetup
> For Linux: <PRODUCT_HOME>/bin/wso2server.sh -Dsetup
> Deprecation of -DSetup
> When proper Database Administrative (DBA) practices are followed, the systems (except analytics products) are not granted DDL (Data Definition) rights on the schema. Therefore, maintaining the -DSetup option is redundant and typically unusable. As a result, from January 2018 onwards WSO2 has deprecated the  -DSetup option. Note that the proper practice is for the DBA to run the DDL statements manually so that the DBA can examine and optimize any DDL statement (if necessary) based on the DBA best practices that are in place within the organization.

I have run scripts from dbscripts\mssql.sql to create database schema, but i have [not found](https://www.google.com/search?q=%22insert+into+REG_PATH%22) any scripts to populated the basic data

Also note that file wso2ei-6.6.0/bin/wso2server.sh does not exists in wso2/wso2ei-integrator:6.6.0 docker image.

Connection to MsSQL server works. From SQL Profiler i see the queries:
```sql
set implicit_transactions on 
go
IF @@TRANCOUNT > 0 COMMIT TRAN
go
IF @@TRANCOUNT > 0 COMMIT TRAN
go
IF @@TRANCOUNT > 0 COMMIT TRAN
go
IF @@TRANCOUNT > 0 COMMIT TRAN
go
IF @@TRANCOUNT > 0 COMMIT TRAN
go
set implicit_transactions on 
go
select system_user
go
set implicit_transactions on 
go
select system_user
go
select system_user
go
select system_user
go
select system_user
go
select system_user
go
select system_user
go
select system_user
go
select system_user
go
select system_user
go
select system_user
go
select system_user
go

SELECT REG_PATH_ID FROM REG_PATH WHERE REG_PATH_VALUE='/' AND REG_TENANT_ID=-1234            
   
IF @@TRANCOUNT > 0 ROLLBACK TRAN
go

```
I dont want to start discussion why it tries to select 10 times the system user at the start, but someone perhaps should look to it in the future..

Nevertheless.. the table REG_PATH is empty, so the query returns zero rows, so i get these errors in the log:
```
JAVA_HOME environment variable is set to /opt/java/openjdk
CARBON_HOME environment variable is set to /home/wso2carbon/wso2ei-6.6.0
Using Java memory options: -Xms256m -Xmx1024m
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[2020-01-23 14:55:56,039]  INFO {org.ops4j.pax.logging.spi.support.EventAdminConfigurationNotifier} - Sending Event Admin nofification (configuration successful) to org/ops4j/pax/logging/Configuration
[2020-01-23 14:55:56,673]  INFO {org.apache.aries.blueprint.container.BlueprintExtender} - No quiesce support is available, so blueprint components will not participate in quiesce operations
[2020-01-23 14:55:58,142]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Starting WSO2 Carbon...
[2020-01-23 14:55:58,150]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Operating System : Linux 4.19.81, amd64
[2020-01-23 14:55:58,151]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Home        : /opt/java/openjdk
[2020-01-23 14:55:58,151]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Version     : 11.0.5
[2020-01-23 14:55:58,151]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java VM          : OpenJDK 64-Bit Server VM 11.0.5+10,AdoptOpenJDK
[2020-01-23 14:55:58,151]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Carbon Home      : /home/wso2carbon/wso2ei-6.6.0
[2020-01-23 14:55:58,152]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Temp Dir    : /home/wso2carbon/wso2ei-6.6.0/wso2/tmp
[2020-01-23 14:55:58,152]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - User             : root, en-US, GMT
[2020-01-23 14:55:58,360]  INFO {org.wso2.carbon.dataservices.google.tokengen.servlet.internal.GoogleTokenGenDSComponent} - Activating GoogleTokengen DS component
[2020-01-23 14:55:58,718]  INFO {org.wso2.carbon.event.output.adapter.kafka.internal.ds.KafkaEventAdapterServiceDS} - Successfully deployed the Kafka output event adaptor service
[2020-01-23 14:56:03,051] ERROR {org.wso2.carbon.registry.core.jdbc.dao.JDBCPathCache} - Failed to retrieving resource from /. Invalid object name 'REG_PATH'. com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'REG_PATH'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1624)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:594)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
```

```
[2020-01-23 14:56:03,076] ERROR {org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO} - Failed to get ID of the resource at path /. Invalid object name 'REG_PATH'. com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'REG_PATH'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1624)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:594)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
```
```
[2020-01-23 14:56:03,088] FATAL {org.wso2.carbon.registry.core.session.UserRegistry} - Failed to add the root collection to the coreRegistry. org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to get ID of the resource at path /. Invalid object name 'REG_PATH'.
	at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.getResourceID(JDBCResourceDAO.java:97)
	at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:151)
	at org.wso2.carbon.registry.core.utils.RegistryUtils.systemResourceShouldBeAdded(RegistryUtils.java:656)
	at org.wso2.carbon.registry.core.session.UserRegistry.addRootCollection(UserRegistry.java:390)
	at org.wso2.carbon.registry.core.session.UserRegistry.init(UserRegistry.java:328)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$100(UserRegistry.java:61)
	at org.wso2.carbon.registry.core.session.UserRegistry$2.run(UserRegistry.java:249)

```

```
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'REG_PATH'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1624)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:594)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)

```

```
[2020-01-23 14:56:03,129] ERROR {org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent} - Failed to activate Registry Core bundle org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to add the root collection to the coreRegistry.
	at org.wso2.carbon.registry.core.session.UserRegistry.addRootCollection(UserRegistry.java:443)
	at org.wso2.carbon.registry.core.session.UserRegistry.init(UserRegistry.java:328)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$100(UserRegistry.java:61)
	at org.wso2.carbon.registry.core.session.UserRegistry$2.run(UserRegistry.java:249)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.<init>(UserRegistry.java:246)

```
```
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to get ID of the resource at path /. Invalid object name 'REG_PATH'.
	at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.getResourceID(JDBCResourceDAO.java:97)
	at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:151)
	at org.wso2.carbon.registry.core.utils.RegistryUtils.systemResourceShouldBeAdded(RegistryUtils.java:656)
	at org.wso2.carbon.registry.core.session.UserRegistry.addRootCollection(UserRegistry.java:390)
	... 55 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'REG_PATH'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1624)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:594)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:446)
	at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy49.executeQuery(Unknown Source)
	at org.wso2.carbon.registry.core.jdbc.dao.JDBCPathCache.getPathID(JDBCPathCache.java:339)
	at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.getResourceID(JDBCResourceDAO.java:67)
	... 58 more
```

I suggest fixing this issue by providing complete installation script that not only create database schema, but also populate required data.

Other solution would be to provide documentation on how to populate default data.

**Suggested Labels:**
EI 6.6.0

**Suggested Assignees:**

**Affected Product Version:**
6.6.0

**OS, DB, other environment details and versions:**    
i use docker container as described in #4944 
regarding this issue, i modified the master-datasources.xml file in the k8s ConfigMap

**Steps to reproduce:**
Described above

**Related Issues:**
Not known

**Comment by arunans23** [comment]
@scholtz Did you try with -Dsetup or without it? For testing purposes you can try with -Dsetup and check whether the tables are getting created. Or else you can manually run the scripts.
Also note that the correct file to run is "EI-HOME/bin/integrator.sh" and not "EI-HOME/bin/wso2server.sh".
