### ISSUE TITLE
Sampling message processor is getting deactivated and not activated when the MP scheduled node is restarted

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/product-ei#4948]
**Description:**
Message processor created on a JDBCStore gets deactivated while shutting down the node on which it is scheduled. The following exception is thrown at the time.
```
[2019-12-20 13:06:03,483] [-1234] [] [pool-43-thread-2] FATAL {org.apache.synapse.message.processor.impl.sampler.SamplingService} - Deactivating the message processor [permissionsRBSMessageProcessor]
java.lang.NullPointerException
at org.apache.synapse.message.store.impl.jdbc.JDBCMessageStore.peek(JDBCMessageStore.java:433)
at org.apache.synapse.message.store.impl.jdbc.JDBCConsumer.receive(JDBCConsumer.java:70)
at org.apache.synapse.message.processor.impl.sampler.SamplingService.fetch(SamplingService.java:225)
at org.apache.synapse.message.processor.impl.sampler.SamplingService.execute(SamplingService.java:142)
at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
[2019-12-20 13:06:03,992] [-1234] [] [Thread-12] WARN {org.apache.synapse.message.processor.impl.ScheduledMessageProcessor} - [permissionsRBSMessageProcessor] Could not find the message consumer to cleanup.
```

**Affected Product Version:**
wso2ei-6.4.0 

**Steps to reproduce:**
1. Setup 2 node cluster and synchronize <EI_HOME>/repository/deployment folder of both nodes.
2. Create a JDBC message store, sampling processor and set the sampling interval(ms) as 1000.
3. Start one of the nodes and observe that the MP is started and scheduled.
4. Start the other node.
5. Observe the state of the MP as ‘Active’ in the management console.
6. Shutdown the node that MP is scheduled.
7. Observe the exception.
8. Observe the state of the MP as ‘Inactive’ in the management console.
9. Start the node again and observe the state of the MP still as ‘Inactive’.

**Comment by sachithKay** [comment]
This is present in JMS message stores as well.
