### ISSUE TITLE
[EI 6.1][VFS-File Inbound for Tenant] Error and warning is printed continously

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#498]
Tried this for tenant in https://docs.wso2.com/pages/viewpage.action?pageId=59577305. 
File is moved to the specified location but and error and a warning log is printed continuously.

`[2017-04-05 17:51:47,251] [EI-Core]  INFO - InboundEndpoint Destroying Inbound Endpoint: file_inbound
[2017-04-05 17:51:47,310] [EI-Core]  INFO - InboundRequestProcessorImpl Inbound endpoint file_inbound stopping.
[2017-04-05 17:51:47,368] [EI-Core]  INFO - AbstractQuartzTaskManager Task deleted: [1][ESB_TASK][file_inbound-FILE--SYNAPSE_INBOUND_ENDPOINT]
[2017-04-05 17:51:47,432] [EI-Core]  INFO - InboundEndpoint Initializing Inbound Endpoint: file_inbound
[2017-04-05 17:51:47,480] [EI-Core]  INFO - VFSProcessor Inbound file listener file_inbound starting ...
[2017-04-05 17:51:47,543] [EI-Core]  INFO - InboundRequestProcessorImpl Starting the inbound endpoint file_inbound, with coordination true. Interval : 1000. Type : FILE--SYNAPSE_INBOUND_ENDPOINT
[2017-04-05 17:51:47,595] [EI-Core]  INFO - AbstractQuartzTaskManager Task scheduled: [1][ESB_TASK][file_inbound-FILE--SYNAPSE_INBOUND_ENDPOINT]
[2017-04-05 17:51:47,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:51:47,645] [EI-Core]  INFO - NTaskTaskManager Scheduled task [NTask::1::file_inbound-FILE--SYNAPSE_INBOUND_ENDPOINT]
[2017-04-05 17:51:47,763] [EI-Core]  INFO - DependencyTracker Inbound Endpoint : file_inbound was updated from the Synapse configuration successfully
[2017-04-05 17:51:47,815] [EI-Core]  INFO - InboundEndpointDeployer Inbound Endpoint: file_inbound has been updated from the file: /home/ushani/WSO2_WORK/Products/EI/6.1.0-Release/3-April-localybuild/fresh/wso2ei-6.1.0-SNAPSHOT/repository/tenants/1/synapse-configs/default/inbound-endpoints/file_inbound.xml
[2017-04-05 17:51:48,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:51:49,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:51:50,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:51:51,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:51:52,407] [EI-Core] ERROR - ClientUtils Address information does not exist in the Endpoint Reference (EPR).The system cannot infer the transport mechanism.
[2017-04-05 17:51:52,407] [EI-Core] ERROR - Axis2Sender Unexpected error during sending message out
org.apache.axis2.AxisFault: Address information does not exist in the Endpoint Reference (EPR).The system cannot infer the transport mechanism.
	at org.apache.axis2.description.ClientUtils.inferOutTransport(ClientUtils.java:73)
	at org.apache.synapse.core.axis2.DynamicAxisOperation$DynamicOperationClient.executeImpl(DynamicAxisOperation.java:115)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:595)
	at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:83)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:548)
	at org.apache.synapse.mediators.builtin.CallMediator.handleNonBlockingCall(CallMediator.java:243)
	at org.apache.synapse.mediators.builtin.CallMediator.mediate(CallMediator.java:115)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectInbound(Axis2SynapseEnvironment.java:446)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FileInjectHandler.invoke(FileInjectHandler.java:163)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.processFile(FilePollingConsumer.java:763)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.directoryHandler(FilePollingConsumer.java:543)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.poll(FilePollingConsumer.java:214)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer.execute(FilePollingConsumer.java:134)
	at org.wso2.carbon.inbound.endpoint.protocol.file.FileTask.taskExecute(FileTask.java:47)
	at org.wso2.carbon.inbound.endpoint.common.InboundTask.execute(InboundTask.java:45)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-04-05 17:51:52,410] [EI-Core]  WARN - Axis2SynapseEnvironment Executing fault handler due to exception encountered
[2017-04-05 17:51:52,411] [EI-Core]  INFO - LogMediator To: , MessageID: urn:uuid:2855377C1ABF37D3171491394912413, Direction: request, MESSAGE = Executing default 'fault' sequence, ERROR_CODE = 0, ERROR_MESSAGE = Unexpected error during sending message out, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsa="http://www.w3.org/2005/08/addressing"><soapenv:Body>
        <m0:getQuote xmlns:m0="http://services.samples">
            <m0:request>
                <m0:symbol>IBM</m0:symbol>
            </m0:request>
        </m0:getQuote>
    </soapenv:Body></soapenv:Envelope>
[2017-04-05 17:51:52,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:51:53,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:51:55,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:51:56,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:51:57,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:51:59,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:00,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:01,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:02,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:03,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:05,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:07,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:08,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:10,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:11,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:12,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:14,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:15,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:16,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:17,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:18,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:20,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:21,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:22,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:23,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:24,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:25,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:27,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:28,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:29,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:30,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:31,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:33,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:35,962] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:37,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:38,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:40,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:42,955] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:44,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:45,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:46,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:47,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:48,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:50,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:52,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:53,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:54,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:55,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:57,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:52:59,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:00,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:01,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:02,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:04,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:05,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:06,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:07,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:09,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:10,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:11,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:13,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:14,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:15,596] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!
[2017-04-05 17:53:16,595] [EI-Core]  WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!`

**Comment by milindaperera** [comment]
tested in latest wso2ei-6.1.0-SNAPSHOT for tenant following [1], not reproducible
this may be due to the directory (mentioned in Warning) is not created

> [2017-04-05 17:52:44,595] [EI-Core] WARN - FilePollingConsumer Unable to access or read file or directory : file:///home/user/test/in. Reason: The file does not exists!

[1] https://docs.wso2.com/pages/viewpage.action?pageId=59577305.

**Comment by ushanib** [comment]
Seems to be a configuring issue from my side. Hence closing.
