### ISSUE TITLE
Data Services, POST in REST with JSON Payloads

### ISSUE THREAD

**Issue by knightbeat** [wso2/product-ei#4981]
**Description:**

This is observed in the `wso2ei-6.6.0+1581092000578.full.zip`.

### Attempt with XML
```

POST http://localhost:8282/services/CUSTOMERS_DataService/customers
Content-Type: : application/xml

<p:_post_customers xmlns:p="http://demo.workshop.com">
    <p:customer_id>CU06576</p:customer_id>
    <p:first_name>Gustavo</p:first_name>
    <p:last_name>Fring</p:last_name>
    <p:dat_of_birth>1961-09-27</p:dat_of_birth>
    <p:gender>M</p:gender>
</p:_post_customers>
```
**Result**
```
HTTP/1.1 202 Accepted
Date: Fri, 21 Feb 2020 12:43:13 GMT
Transfer-Encoding: chunked
Connection: close
```

### Attempt with JSON
```

POST http://chathurak.local:8282/services/CUSTOMERS_DataService/customers
Content-Type: : application/json

{
    "_post_customers":
    {
        "customer_id" : "CU06577",
        "first_name" : "Hank",
        "last_name" : "Shrader",
        "dat_of_birth" : "1964-02-22",
        "gender" : "M"
    }
}
```

**Result**
```
HTTP/1.1 500 Internal Server Error
Content-Type: application/xml; charset=UTF-8
Date: Fri, 21 Feb 2020 12:45:44 GMT
Transfer-Encoding: chunked
Connection: close

<faultstring>I/O  Exception occured while building the data service request</faultstring>
```

### The relevant error log
```
[2020-02-21 12:46:51,335] ERROR {org.apache.synapse.transport.passthru.util.RelayUtils} - Error while building Passthrough stream org.apache.axiom.om.OMException: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '{' (code 123) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
	at org.apache.axiom.om.impl.llom.OMDocumentImpl.getOMDocumentElement(OMDocumentImpl.java:109)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:570)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:566)
	at org.apache.synapse.transport.passthru.util.DeferredMessageBuilder.getDocument(DeferredMessageBuilder.java:165)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:168)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:121)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:88)
	at org.wso2.carbon.integrator.core.handler.IntegratorStatefulHandler.invoke(IntegratorStatefulHandler.java:94)
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:368)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:427)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:182)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '{' (code 123) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:639)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2052)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1134)
	at org.apache.axiom.util.stax.wrapper.XMLStreamReaderWrapper.next(XMLStreamReaderWrapper.java:225)
	at org.apache.axiom.util.stax.dialect.DisallowDoctypeDeclStreamReaderWrapper.next(DisallowDoctypeDeclStreamReaderWrapper.java:34)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
	... 19 more

[2020-02-21 12:46:51,338] ERROR {org.apache.axis2.engine.AxisEngine} - I/O  Exception occured while building the data service request org.apache.axis2.AxisFault: I/O  Exception occured while building the data service request
	at org.wso2.carbon.integrator.core.handler.IntegratorStatefulHandler.invoke(IntegratorStatefulHandler.java:133)
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:368)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:427)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:182)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Error while building Passthrough stream
	at org.apache.synapse.transport.passthru.util.RelayUtils.handleException(RelayUtils.java:451)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:214)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:121)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:88)
	at org.wso2.carbon.integrator.core.handler.IntegratorStatefulHandler.invoke(IntegratorStatefulHandler.java:94)
	... 11 more
Caused by: org.apache.axiom.om.OMException: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '{' (code 123) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
	at org.apache.axiom.om.impl.llom.OMDocumentImpl.getOMDocumentElement(OMDocumentImpl.java:109)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:570)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:566)
	at org.apache.synapse.transport.passthru.util.DeferredMessageBuilder.getDocument(DeferredMessageBuilder.java:165)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:168)
	... 14 more
Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '{' (code 123) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:639)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2052)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1134)
	at org.apache.axiom.util.stax.wrapper.XMLStreamReaderWrapper.next(XMLStreamReaderWrapper.java:225)
	at org.apache.axiom.util.stax.dialect.DisallowDoctypeDeclStreamReaderWrapper.next(DisallowDoctypeDeclStreamReaderWrapper.java:34)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
	... 19 more

[2020-02-21 12:46:51,339] ERROR {org.apache.synapse.transport.passthru.ServerWorker} - Error processing POST request for : /services/CUSTOMERS_DataService/customers org.apache.axis2.AxisFault: I/O  Exception occured while building the data service request
	at org.wso2.carbon.integrator.core.handler.IntegratorStatefulHandler.invoke(IntegratorStatefulHandler.java:133)
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:368)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:427)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:182)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: Error while building Passthrough stream
	at org.apache.synapse.transport.passthru.util.RelayUtils.handleException(RelayUtils.java:451)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:214)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:121)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:88)
	at org.wso2.carbon.integrator.core.handler.IntegratorStatefulHandler.invoke(IntegratorStatefulHandler.java:94)
	... 11 more
Caused by: org.apache.axiom.om.OMException: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '{' (code 123) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
	at org.apache.axiom.om.impl.llom.OMDocumentImpl.getOMDocumentElement(OMDocumentImpl.java:109)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:570)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.getDocumentElement(StAXOMBuilder.java:566)
	at org.apache.synapse.transport.passthru.util.DeferredMessageBuilder.getDocument(DeferredMessageBuilder.java:165)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:168)
	... 14 more
Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '{' (code 123) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:639)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2052)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1134)
	at org.apache.axiom.util.stax.wrapper.XMLStreamReaderWrapper.next(XMLStreamReaderWrapper.java:225)
	at org.apache.axiom.util.stax.dialect.DisallowDoctypeDeclStreamReaderWrapper.next(DisallowDoctypeDeclStreamReaderWrapper.java:34)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
	... 19 more
```

**Suggested Labels:**
EI-6.6.0, Data-services, POST, REST, JSON

**Affected Product Version:**
EI-6.6.0

**Comment by GDLMadushanka** [comment]
We could reproduce the issue by sending the JSON object with application/xml content-type header. 
Could you please verify you are calling the data-service with matching content-type headers.

**Comment by knightbeat** [comment]
Yes. The content-type was `application/json` with a JSON payload and I have added the request, response and the logs in my previous response. Now, this is the same behaviour I observe on EI7 - micro integrator as well.
