### ISSUE TITLE
CAPP undeployment error when deploying class mediator through the CAPP

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#4995]
**Description:**
When a class mediator is deployed using a CAPP and an API that uses this class mediator is deployed using the same CAPP, when undeploying the CAPP it fails to undeploy the API which uses the class mediator. 
It properly removes the CAPP from the management console but the API is not getting removed from the management console and throws a class not found error when trying to undeploy the API.
This happens only when deploying class mediator using CAPP.

**Affected Product Version:**
EI-6.5.0, EI-6.6.0

**Steps to reproduce:**
Deploy a car file using the management console having a ClassMediator
Undeploy the car.
Following error will print

[2020-03-06 11:23:40,694] [EI-Core] ERROR - ClassMediatorFactory Error loading class : sampleservices.mediators.SValidator - Class not found
java.lang.ClassNotFoundException: com.prime.enterpriseservices.sampleservices.mediators.SValidator cannot be found by synapse-core_2.1.7.wso2v111
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.synapse.config.xml.ClassMediatorFactory.createSpecificMediator(ClassMediatorFactory.java:100)

**Comment by oscarvesga** [comment]
@malakaganga hello, how i get this fix into my open versión of EI v6.5.0?
