### ISSUE TITLE
[EI610][Broker Cluster]When one node reconnecting, error logs in the exsisting node

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#500]
**Environment**
Operating Systems : Redhat and Debian
Java Version : JDK1.8
Packs : EI610 03/04/2017 snapshot
ESB Setup: Cluster
DB - Oracle 12c
Broker setup - Cluster

**Steps to reproduce**
While publishing messages in to broker queue, one node should shut down.
When that node going to reconnect, get the following error logs:

```
TID: [-1] [] [2017-04-05 22:47:53,620] ERROR {org.wso2.andes.thrift.MBThriftClient} -  Attempt 0 failed requesting a slot from coordinator 
org.apache.thrift.TApplicationException: Internal error processing getSlotInfo
	at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
	at org.wso2.andes.thrift.slot.gen.SlotManagementService$Client.recv_getSlotInfo(SlotManagementService.java:101)
	at org.wso2.andes.thrift.slot.gen.SlotManagementService$Client.getSlotInfo(SlotManagementService.java:87)
	at org.wso2.andes.thrift.MBThriftClient.getSlot(MBThriftClient.java:101)
	at org.wso2.andes.kernel.slot.SlotCoordinatorCluster$ThriftSlotCoordinator.getSlot(SlotCoordinatorCluster.java:145)
	at org.wso2.andes.kernel.slot.SlotCoordinatorCluster.getSlot(SlotCoordinatorCluster.java:49)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.requestSlot(MessageDeliveryTask.java:158)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:75)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:32)
	at org.wso2.andes.task.TaskHolder.executeTask(TaskHolder.java:75)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:85)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

TID: [-1] [] [2017-04-05 22:47:58,675] ERROR {org.wso2.andes.kernel.slot.DeliveryTaskExceptionHandler} -  Error occurred while processing task. Task id jmsproxy 
org.wso2.andes.kernel.slot.ConnectionException: Coordinator has changed
	at org.wso2.andes.thrift.MBThriftClient.getSlot(MBThriftClient.java:114)
	at org.wso2.andes.kernel.slot.SlotCoordinatorCluster$ThriftSlotCoordinator.getSlot(SlotCoordinatorCluster.java:145)
	at org.wso2.andes.kernel.slot.SlotCoordinatorCluster.getSlot(SlotCoordinatorCluster.java:49)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.requestSlot(MessageDeliveryTask.java:158)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:75)
	at org.wso2.andes.kernel.slot.MessageDeliveryTask.call(MessageDeliveryTask.java:32)
	at org.wso2.andes.task.TaskHolder.executeTask(TaskHolder.java:75)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:85)
	at org.wso2.andes.task.TaskProcessor.call(TaskProcessor.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Dilshani** [comment]
When broker cluster going to restart, got the following error:

```
TID: [-1] [] [2017-04-07 14:12:40,045] ERROR {org.wso2.andes.kernel.slot.SlotMessageCounter} -  Error occurred while executing SlotTimeoutTask 
java.lang.NullPointerException
	at org.wso2.andes.kernel.slot.SlotMessageCounter.submitCurrentSafeZone(SlotMessageCounter.java:153)
	at org.wso2.andes.kernel.slot.SlotMessageCounter.access$700(SlotMessageCounter.java:51)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.updateCoordinatorWithCurrentSafezone(SlotMessageCounter.java:380)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.run(SlotMessageCounter.java:326)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
TID: [-1] [] [2017-04-07 14:12:41,046] ERROR {org.wso2.andes.kernel.slot.SlotMessageCounter} -  Error occurred while executing SlotTimeoutTask 
java.lang.NullPointerException
	at org.wso2.andes.kernel.slot.SlotMessageCounter.submitCurrentSafeZone(SlotMessageCounter.java:153)
	at org.wso2.andes.kernel.slot.SlotMessageCounter.access$700(SlotMessageCounter.java:51)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.updateCoordinatorWithCurrentSafezone(SlotMessageCounter.java:380)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.run(SlotMessageCounter.java:326)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by danielelic** [comment]
Any update about this?

**Comment by a5anka** [comment]
This is the expected behavior. It should recover within some time.
