### ISSUE TITLE
RabbitMq 

### ISSUE THREAD

**Issue by uarulraj** [wso2/product-ei#5001]
**Description:**

I  am using windows, Openjdk java11,wso2ei6.6.0 and Rabbitmq 3.8.1 Please refer the below code . I am trying to receiving a message from Rabbitmq. I have been refereed this code from the below documentation link https://docs.wso2.com/display/EI640/RabbitMQ+Use+Cases--- WSO2 EI as a RabbitMQ Message Producer. 
Code
------
<?xml version="1.0" encoding="UTF-8"?>
<proxy name="AMQPProxy" startOnLoad="true" transports="http https rabbitmq" xmlns="http://ws.apache.org/ns/synapse">
    <target>
        <endpoint>
            <address uri="rabbitmq:/AMQPProxy?rabbitmq.server.host.name=localhost&amp;rabbitmq.server.port=5672&amp;rabbitmq.server.user.name=testuser&amp;rabbitmq.server.password=test&amp;rabbitmq.server.virtual.host=%2f&amp;rabbitmq.queue.name=firstq&amp;rabbitmq.queue.routing.key=firstrkS&amp;rabbitmq.exchange.name=firstex">
                <suspendOnFailure>
                    <initialDuration>-1</initialDuration>
                    <progressionFactor>1</progressionFactor>
                </suspendOnFailure>
                <markForSuspension>
                    <retriesBeforeSuspension>0</retriesBeforeSuspension>
                </markForSuspension>
            </address>
        </endpoint>
       <inSequence>
            <log level="full"/>
            <property name="OUT_ONLY" scope="default" type="STRING" value="true"/>
            <property name="FORCE_SC_ACCEPTED" scope="axis2" type="STRING" value="true"/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </target>
</proxy>

-----

If I run the proxy service in soapui linke http://localhost:8280/AMQPProxy.AMQProxyHttpsoap11EndPoint
It throws error in the log as  
ErrorMessage
TID: [PassThroughMessageProcessor-3enantId] [2020-03-09 23:00:53,134] ERROR {org.apache.axis2.description.ClientUtils} - The system cannot infer the transport information from the rabbitmq:/AMQPProxy?rabbitmq.server.host.name=localhost&rabbitmq.server.port=5672&rabbitmq.server.user.name=testuser&rabbitmq.server.password=1234&rabbitmq.server.virtual.host=%2f&rabbitmq.queue.routing.key=frk&rabbitmq.exchange.name=firstex URL.
TID: [PassThroughMessageProcessor-3enantId] [2020-03-09 23:00:53,135] ERROR {org.apache.synapse.core.axis2.Axis2Sender} - Unexpected error during sending message out org.apache.axis2.AxisFault: The system cannot infer the transport information from the rabbitmq:/AMQPProxy?rabbitmq.server.host.name=localhost&rabbitmq.server.port=5672&rabbitmq.server.user.name=testuser&rabbitmq.server.password=1234&rabbitmq.server.virtual.host=%2f&rabbitmq.queue.routing.key=frk&rabbitmq.exchange.name=firstex URL.
	at org.apache.axis2.description.ClientUtils.inferOutTransport(ClientUtils.java:86)
	at org.apache.axis2.client.OperationClient.prepareMessageContext(OperationClient.java:288)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:249)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:634)
	at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:85)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:569)
	at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:408)
	at org.apache.synapse.endpoints.AddressEndpoint.send(AddressEndpoint.java:74)
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:123)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:224)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:444)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
--------------------------------------
Axis2.xml
<transportReceiver class="org.apache.axis2.transport.rabbitmq.RabbitMQListener" name="rabbitmq">
	     <parameter locked="false" name="AMQPConnectionFactory">
    </parameter>		
    </transportReceiver>

<transportSender class="org.apache.axis2.transport.rabbitmq.RabbitMQSender" name="rabbitmq">
	</transportSender>
Error Message:
"org.apache.axis2.AxisFault: The system cannot infer the transport information from the rabbit
rabbitmq.server.host.name=localhost&rabbitmq.server.port=5672&a;rabbitmq.server.user.name=testuser&rabbitmq.server.password=test&rabbitmq.server.virtual.host=%2f&rabbitmq.queue.name=firstq&rabbitmq.queue.routing.key=firstrkS&rabbitmq.exchange.name=firstex URL"
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by uarulraj** [comment]
Any update on the above issue

**Comment by dinuish94** [comment]
@uarulraj - The transport sender / receiver for Rabbit MQ may not have been enabled in the conf/axis2/axis2.xml.

**Comment by uarulraj** [comment]
<transportReceiver class="org.apache.axis2.transport.rabbitmq.RabbitMQListener" name="rabbitmq">
	    
        <parameter locked="false" name="AMQPConnectionFactory">
            
			<parameter locked="false" name="rabbitmq.server.host.name">localhost</parameter>
            <parameter locked="false" name="rabbitmq.server.port">5672</parameter>
            <parameter locked="false" name="rabbitmq.server.user.name">testuser</parameter>
            <parameter locked="false" name="rabbitmq.server.password">1234</parameter>
			<parameter locked="false" name="rabbitmq.queue.routing.key">queueQBS</parameter>
			<parameter locked="false" name="rabbitmq.exchange.name">exchangeQBS</parameter>
            <parameter locked="false" name="rabbitmq.connection.retry.interval">10000</parameter>
            <parameter locked="false" name="rabbitmq.connection.retry.count">5</parameter>
			<parameter name="rabbitmq.message.content.type">application/xml</parameter>
		
        </parameter>
 </transportReceiver>
<transportSender class="org.apache.axis2.transport.rabbitmq.RabbitMQSender" name="rabbitmq"/>

Still I Ama getting the same error
