### ISSUE TITLE
MalformedJSONException in Enrich mediator when enriching Text property to body

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#5034]
**Description:**

When the following sequence is invoked, it throws MalformedJSONException.
```
<?xml version="1.0" encoding="UTF-8"?><sequence xmlns="http://ws.apache.org/ns/synapse" name="enrichMediator">
    <payloadFactory media-type="text">
        <format>
            Check
        </format>
        <args/>
    </payloadFactory>
    <property name="fixedLengthMessage" value="ABC DEFG" scope="default" type="STRING"/>
    <enrich>
        <source xmlns:ns="http://org.apache.synapse/xsd" clone="false" xpath="get-property('fixedLengthMessage')"/>
        <target type="body"/>
    </enrich>
    <respond/>
</sequence>
```

> [2020-04-02 08:25:13,179] ERROR {org.apache.synapse.mediators.base.SequenceMediator} - com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $ com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $
> 	at com.google.gson.JsonParser.parse(JsonParser.java:65)
> 	at com.google.gson.JsonParser.parse(JsonParser.java:45)
> 	at org.apache.synapse.mediators.elementary.Target.insertElementToBody(Target.java:285)
> 	at org.apache.synapse.mediators.elementary.Target.insert(Target.java:168)
> 	at org.apache.synapse.mediators.elementary.EnrichMediator.mediate(EnrichMediator.java:171)
> 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
> 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
> 	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
> 	at org.apache.synapse.rest.Resource.process(Resource.java:344)
> 	at org.apache.synapse.rest.API.process(API.java:441)
> 	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:135)
> 	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:113)
> 	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
> 	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:327)
> 	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98)
> 	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> 	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:368)
> 	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:189)
> 	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $
> 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
> 	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
> 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
> 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
> 	at com.google.gson.JsonParser.parse(JsonParser.java:60)
> 	... 21 more

This is because the property we are trying to enrich to the body has a space on it and it cannot be parsed as a valid JSON

A similar issue was there when enriching property to a custom path in the body.
https://github.com/wso2/product-ei/issues/4677

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Upto EI 6.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Mentioned in the description

**Related Issues:**

https://github.com/wso2/product-ei/issues/4677

**Comment by arunans23** [comment]
Workaround for this issue : Use PayloadFactory mediator instead of Enrich mediator to enrich the text payload to body.

```
<api xmlns="http://ws.apache.org/ns/synapse" name="check" context="/check">
   <resource methods="GET">
      <inSequence>
         <payloadFactory media-type="text">
            <format>            Check        </format>
            <args/>
         </payloadFactory>
         <property name="fixedLengthMessage" value="ABC DEFG" scope="default" type="STRING"/>
         <payloadFactory media-type="text">
            <format>$1</format>
            <args>
               <arg evaluator="xml" expression="$ctx:fixedLengthMessage"/>
            </args>
         </payloadFactory>
         <respond/>
      </inSequence>
   </resource>
</api>
```
