### ISSUE TITLE
File connector 2.0.22 issue - asking for optional param

### ISSUE THREAD

**Issue by lpastor74** [wso2/product-ei#5082]
**Description:**
Fille connector is not working, it is asking for param that is not even mentioned in the documentation.

**Suggested Labels:**

Connector bug. File connector 2.0.22
**Suggested Assignees:**

**Affected Product Version:**
EI 6.x, EI 7.x ...
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Downloaded from the store. Imported in carbon.
Created sequence and try to read context of the file with following :

> <fileconnector.read>
>         <source>file:///Users/laslopastor/Downloads/dummy/in.xml</source>
>         <filePattern>*.xml</filePattern>
>         <contentType>application/xml</contentType>
>     </fileconnector.read>

error:
WARN {org.wso2.carbon.connector.FileRead} -  **numberOfLinesToSkip** parameter is not an integer
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.wso2.carbon.connector.FileRead.connect(FileRead.java:92)
	at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32)
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:94)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:133)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:148)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:84)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectInbound(Axis2SynapseEnvironment.java:467)
	at org.wso2.carbon.inbound.endpoint.protocol.rabbitmq.RabbitMQInjectHandler.invoke(RabbitMQInjectHandler.java:142)
	at org.wso2.carbon.inbound.endpoint.protocol.rabbitmq.RabbitMQConnectionConsumer.startConsumer(RabbitMQConnectionConsumer.java:176)
	at org.wso2.carbon.inbound.endpoint.protocol.rabbitmq.RabbitMQConnectionConsumer.execute(RabbitMQConnectionConsumer.java:81)
	at org.wso2.carbon.inbound.endpoint.protocol.rabbitmq.RabbitMQTask.taskExecute(RabbitMQTask.java:39)
	at org.wso2.carbon.inbound.endpoint.common.OneTimeTriggerInboundTask.execute(OneTimeTriggerInboundTask.java:46)
	at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98)
	at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
**Related Issues:**

**Comment by dulanjalidilmi** [comment]
This issue is fixed by the latest file connector version (2.0.23).

**Comment by lpastor74** [comment]
nice :) 👍
