### ISSUE TITLE
[EI610][Broker] Get nullpointer exception when restart broker cluster

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#509]
**Environment**
Operating Systems : Redhat and Debian
Java Version : JDK1.8
Packs : EI610 07/04/2017 snapshot
ESB Setup: Cluster (3 nodes)
DB - Oracle 12c
Broker setup - Cluster (2 nodes)

**Steps to reproduce**
Configure broker with few subscribers/publishers.
Shutdown both nodes in cluster
Start one node in cluster

Get following error continuously: 

```
TID: [-1] [] [2017-04-07 14:12:40,045] ERROR {org.wso2.andes.kernel.slot.SlotMessageCounter} -  Error occurred while executing SlotTimeoutTask 
java.lang.NullPointerException
	at org.wso2.andes.kernel.slot.SlotMessageCounter.submitCurrentSafeZone(SlotMessageCounter.java:153)
	at org.wso2.andes.kernel.slot.SlotMessageCounter.access$700(SlotMessageCounter.java:51)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.updateCoordinatorWithCurrentSafezone(SlotMessageCounter.java:380)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.run(SlotMessageCounter.java:326)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
TID: [-1] [] [2017-04-07 14:12:41,046] ERROR {org.wso2.andes.kernel.slot.SlotMessageCounter} -  Error occurred while executing SlotTimeoutTask 
java.lang.NullPointerException
	at org.wso2.andes.kernel.slot.SlotMessageCounter.submitCurrentSafeZone(SlotMessageCounter.java:153)
	at org.wso2.andes.kernel.slot.SlotMessageCounter.access$700(SlotMessageCounter.java:51)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.updateCoordinatorWithCurrentSafezone(SlotMessageCounter.java:380)
	at org.wso2.andes.kernel.slot.SlotMessageCounter$SlotTimeoutTask.run(SlotMessageCounter.java:326)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
**Note** : Found a similar issue reported in: https://wso2.org/jira/browse/MB-1558

**Comment by sdkottegoda** [comment]
Closing since this is duplicated by https://github.com/wso2/product-ei/issues/2404 and the duplicate issue is fixed.
