### ISSUE TITLE
Data service request fails when sql query define with two input mappings

### ISSUE THREAD

**Issue by gvasanka** [wso2/product-ei#511]
Steps:
1. Follow the steps mentioned on doc https://docs.wso2.com/display/EI600/Exposing+an+RDBMS+as+a+Data+Service
2. Change the dataservices query to accept two input mappings 
ex.SELECT AccountID,Branch,AccountNumber,AccountType,Balance,ModifiedDate FROM ACCOUNT where AccountID=:AccountID and AccountType=:AccountType;
3. Open the WSDL service using SOAP UI and invoke the service

Note: Find the attached service, changed .dbs to .txt
[dsstestmany.txt](https://github.com/wso2/product-ei/files/905341/dsstestmany.txt)

Issue:
Observing following error on console and SOAP UI shows response with error messages

```
[2017-04-07 16:23:57,751] [EI-Core] ERROR - DBInOutMessageReceiver Error in in-out message receiver
DS Code: DATABASE_ERROR
Nested Exception:-
javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'SQLQuery.processPreNormalQuery': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':AccountType' at line 1
DS Code: DATABASE_ERROR
Source Data Service:-
Name: dsstestmany
Location: /dsstestmany.dbs
Description:            dsstestmany                     
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: operation1
Current Params: {AccountID=1, AccountType=CURRENT}
Nested Exception:-
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':AccountType' at line 1


	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:75)
	at org.wso2.carbon.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:357)
	at org.wso2.carbon.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:41)
	at org.wso2.carbon.dataservices.core.DBInOutMessageReceiver.invokeBusinessLogic(DBInOutMessageReceiver.java:57)
	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:42)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:404)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'SQLQuery.processPreNormalQuery': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':AccountType' at line 1
DS Code: DATABASE_ERROR
Source Data Service:-
Name: dsstestmany
Location: /dsstestmany.dbs
Description:            dsstestmany                     
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: operation1
Current Params: {AccountID=1, AccountType=CURRENT}
Nested Exception:-
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':AccountType' at line 1

	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.execute(DSOMDataSource.java:102)
	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:73)
	... 12 more
[2017-04-07 16:23:57,752] [EI-Core] ERROR - ServerWorker Error processing POST request for : /services/dsstestmany.SOAP11Endpoint
org.apache.axis2.AxisFault: DS Code: DATABASE_ERROR
Nested Exception:-
javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'SQLQuery.processPreNormalQuery': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':AccountType' at line 1
DS Code: DATABASE_ERROR
Source Data Service:-
Name: dsstestmany
Location: /dsstestmany.dbs
Description:            dsstestmany                     
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: operation1
Current Params: {AccountID=1, AccountType=CURRENT}
Nested Exception:-
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':AccountType' at line 1


	at org.wso2.carbon.dataservices.core.DBUtils.createAxisFault(DBUtils.java:740)
	at org.wso2.carbon.dataservices.core.DBInOutMessageReceiver.invokeBusinessLogic(DBInOutMessageReceiver.java:67)
	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:42)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:404)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'SQLQuery.processPreNormalQuery': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':AccountType' at line 1
DS Code: DATABASE_ERROR
Source Data Service:-
Name: dsstestmany
Location: /dsstestmany.dbs
Description:            dsstestmany                     
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: operation1
Current Params: {AccountID=1, AccountType=CURRENT}
Nested Exception:-
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':AccountType' at line 1

	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.execute(DSOMDataSource.java:102)
	at org.wso2.carbon.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:73)
	at org.wso2.carbon.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:357)
	at org.wso2.carbon.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:41)
	at org.wso2.carbon.dataservices.core.DBInOutMessageReceiver.invokeBusinessLogic(DBInOutMessageReceiver.java:57)
	... 9 more
```

**Comment by madhawa-gunasekara** [comment]
this is not a bug, We don't recommend to add ; in the query.
