### ISSUE TITLE
ClassNotFoundException when deploying inbound endpoints

### ISSUE THREAD

**Issue by shefandarren** [wso2/product-ei#5161]
**Description:**
When deploying an inbound endpoint configuration with registry references, you will see a ClassNotFoundException if the registry project does not have the media type defined for each artifact. A sample inbound endpoint config is as follows. 

```xml
<inboundEndpoint name="Sch_Test_IEP" onError="Test_Fault" protocol="jms" sequence="Test_Inbound" suspend="false" xmlns="http://ws.apache.org/ns/synapse">
    <parameters>
        <parameter name="interval">1000</parameter>
        <parameter name="sequential">true</parameter>
        <parameter name="coordination">true</parameter>
        <parameter key="conf:/custom/SCLFLUGEN1_DFE_QueueName/SCLFLUGEN1_DFE_QueueName" name="transport.jms.Destination"/>
        <parameter name="transport.jms.CacheLevel">1</parameter>
        <parameter name="transport.jms.ConnectionFactoryJNDIName">QueueConnectionFactory</parameter>
        <parameter key="conf:/custom/SCLFLUGEN1_DFE_FactoryInitial/SCLFLUGEN1_DFE_FactoryInitial" name="java.naming.factory.initial"/>
        <parameter key="conf:/custom/SCLFLUGEN1_DFE_ProviderUrl/SCLFLUGEN1_DFE_ProviderUrl" name="java.naming.provider.url"/>
        <parameter key="conf:/custom/SCLFLUGEN1_DFE_UserName/SCLFLUGEN1_DFE_UserName" name="transport.jms.UserName"/>
        <parameter name="transport.jms.SessionAcknowledgement">CLIENT_ACKNOWLEDGE</parameter>
        <parameter key="conf:/custom/SCLFLUGEN1_DFE_Password/SCLFLUGEN1_DFE_Password" name="transport.jms.Password"/>
        <parameter name="transport.jms.SessionTransacted">true</parameter>
        <parameter name="transport.jms.ConnectionFactoryType">queue</parameter>
        <parameter name="transport.jms.ReceiveTimeout">-1</parameter>
        <parameter name="transport.jms.ContentType">application/xml</parameter>
        <parameter name="transport.jms.SharedSubscription">false</parameter>
        <parameter name="transport.jms.ResetConnectionOnPollingSuspension">false</parameter>
    </parameters>
</inboundEndpoint>
```

**Affected Product Version:**
MI 1.1.0

**OS, DB, other environment details and versions:**
Docker    

**Steps to reproduce:**

1. Create a registry project without defining the media type for the artifact. 
2. Create a ESB solution project and refer the registry artifacts as shown in the description above. 
3. Deploy the carbon application and start the server. Then you will be faced with following stack trace. 

`Caused by: java.lang.ClassNotFoundException: class b3JnLmFwYWNoZS5hY3RpdmVtcS5qbmRpLkFjdGl2ZU1RSW5pdGlhbENvbnRleHRGYWN0b3J5Cg== not found
	at org.wso2.micro.core.context.CarbonContextDataHolder.classForName(CarbonContextDataHolder.java:1018) ~[org.wso2.micro.integrator.core_1.1.0.jar:?]
	at org.wso2.micro.core.context.CarbonContextDataHolder.access$600(CarbonContextDataHolder.java:85) ~[org.wso2.micro.integrator.core_1.1.0.jar:?]
	at org.wso2.micro.core.context.CarbonContextDataHolder$CarbonInitialJNDIContextFactoryBuilder.createInitialContextFactory(CarbonContextDataHolder.java:254) ~[org.wso2.micro.integrator.core_1.1.0.jar:?]
	... 74 more`

**Comment by shefandarren** [comment]
Wrong repo
