### ISSUE TITLE
Processing of multipart-form-data-requests are getting failed due to time out issues on WSO2 API Manager & Integrator

### ISSUE THREAD

**Issue by rajudevansh** [wso2/product-ei#5177]
Steps to reproduce:
Created REST Service for transferring the file in the form of multipart/form-data in wso2 integrator.

Any recommendations: Is there any specific properties need to be set in WSO2 Integrator/API Manager for doing fileUpload using multipart/form-data?

Integrator Logs:

{org.apache.synapse.transport.passthru.util.DeferredMessageBuilder} -  Error building message 
org.apache.axis2.AxisFault: Processing of multipart/form-data request failed. Stream ended unexpectedly
        at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
        at org.apache.axis2.builder.MultipartFormDataBuilder.processDocument(MultipartFormDataBuilder.java:96)
        at org.apache.synapse.transport.passthru.util.DeferredMessageBuilder.getDocument(DeferredMessageBuilder.java:153)
        at org.apache.synapse.transport.passthru.util.RelayUtils.builldMessage(RelayUtils.java:160)

Caused by: org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. Stream ended unexpectedly
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:351)
	at org.apache.axis2.builder.MultipartFormDataBuilder.parseRequest(MultipartFormDataBuilder.java:137)
	at org.apache.axis2.builder.MultipartFormDataBuilder.getParameterMap(MultipartFormDataBuilder.java:107)
	at org.apache.axis2.builder.MultipartFormDataBuilder.processDocument(MultipartFormDataBuilder.java:91)
	... 37 more
Caused by: org.apache.commons.fileupload.MultipartStream$MalformedStreamException: Stream ended unexpectedly
	at org.apache.commons.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:1005)
	at org.apache.commons.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:903)
	at java.io.InputStream.read(InputStream.java:101)

Environment: WSO2 API Manager 2.2.0/ WSO2 Integrator 6.2

Please provide any suggestions for resolving the issues.

@Nirothipan @Vathsan @sdkottegoda

**Comment by Nirothipan** [comment]
could you check this https://medium.com/wso2-enterprise-integrator-wso2-dev-studio-wso2/construct-and-send-multipart-form-data-using-wso2-ei-5cd548d095ee

**Comment by rajudevansh** [comment]
Thanks @Nirothipan for responding. We have followed the URL and implemented ESB proxy service for processing multipart/form-data file.

We have added following property for processing through proxy service
<property name="messageType" scope="axis2" type="STRING" value="multipart/form-data"/>

We have created new API in API Manager for invoking this integrator service and observed time out issues when we are hitting this service. 

Can you please check and let me know any specific properties need to be added in WSO2 Integrator/API Manager for doing fileUpload using multipart/form-data or improving the performance?

**Comment by Nirothipan** [comment]
The timeout issues consistent or intermittent ?

**Comment by rajudevansh** [comment]
Timeout issues which we are facing now are intermittent.

**Comment by Nirothipan** [comment]
It might be related to back end as well , could you try disabling keep alive and check

**Comment by rajudevansh** [comment]
I didn't get Nirothipan. Can you please explain what exactly you want me to try ?

**Comment by Nirothipan** [comment]
> I didn't get Nirothipan. Can you please explain what exactly you want me to try ?

Please try adding the following to service , but we need to find the real issue of timeout.
```bash
<property name="NO_KEEPALIVE" value="true" scope="axis2"/>
```

**Comment by rajudevansh** [comment]
Thanks @Nirothipan  for your details. We will try this and let you know.

**Comment by OdDev26** [comment]
@Nirothipan, I am trying to receive a multipart file from the backend in WSO2 ESB, do you know how I can go about it?

**Comment by shuimuxh** [comment]
@rajudevansh did you find the root cause for this issue? I think you can have a try to increase the global timeout which maybe interrupt the session when you upload big file.
