### ISSUE TITLE
Exception while running cipher tool batch file in micro integrator 7.0.2

### ISSUE THREAD

**Issue by gnvsnaren** [wso2/product-ei#5198]
**Description:**
Getting exception while running ciphertool.bat file.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Micro integrator 7.0.2
**OS, DB, other environment details and versions:**    
Windows 10
**Steps to reproduce:**
Getting exception when trying to activate the secure vault in mi-7.0.2
The exception is as given below.
C:\WSO2Integration\NewMI_7.0.2\wso2ei-7.0.2\micro-integrator\bin>ciphertool.bat -Dconfigure
.\wso2\lib\Saxon-HE-9.5.1-8.jar
Using CARBON_HOME:   C:\WSO2IN~1\NEWMI_~1.2\WSO2EI~1.2\MICRO-~1\bin\..
Using JAVA_HOME:    C:\Program Files\Java\jre1.8.0_241

Encrypting using Internal KeyStore.
{type: JKS, alias: wso2carbon, path: C:\WSO2IN~1\NEWMI_~1.2\WSO2EI~1.2\MICRO-~1\bin\../repository/resources/security/wso2carbon.jks}

[Please Enter Internal KeyStore Password of Carbon Server : ]

Internal KeyStore of Carbon Server is initialized Successfully

Protected Token [UserManager.AdminUser.Password] is updated in conf/user-mgt.xml successfully

Protected Token [Carbon.Security.KeyStore.KeyPassword] is updated in conf/carbon.xml successfully

Exception in thread "main" org.wso2.ciphertool.exception.CipherToolException: Element for secret alias 'Management.Api.AdminUser.Password' can not be found in conf/internal-apis.xml file or You have entered invalid Xpath value
        at org.wso2.ciphertool.CipherTool.tokenToConfigFile(CipherTool.java:257)
        at org.wso2.ciphertool.CipherTool.secureVaultConfigTokens(CipherTool.java:212)
        at org.wso2.ciphertool.CipherTool.main(CipherTool.java:78)
Can you please give a solution to this.

**Related Issues:**

**Comment by gnvsnaren** [comment]
issue resolved
