### ISSUE TITLE
Exception thrown property is used in PayloadFactory with xml special characters

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#5239]
**Description:**
Exception thrown property is used in PayloadFactory with xml special characters

**Steps to reproduce:**

In EI-6.4.0 add following API

```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/payload" name="Payload" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="POST">
        <inSequence>
            <property expression="json-eval($)" name="registerCasePayload" scope="default" type="STRING"/>
            <log>
                <property expression="get-property('registerCasePayload')" name="registerCase body"/>
            </log>
            <payloadFactory media-type="xml">
                <format>
                    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
                        <soapenv:Header/>
                        <soapenv:Body>
                            <mediate xmlns="">
                                <entity_document>$1</entity_document>
                            </mediate>
                        </soapenv:Body>
                    </soapenv:Envelope>
                </format>
                <args>
                    <arg evaluator="xml" expression="get-property('registerCasePayload')" xmlns:ns="http://org.apache.synapse/xsd"/>
                </args>
            </payloadFactory>
            <log>
                <property expression="$body/*" name="registerCase body"/>
            </log>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```

And invoke this api with following CURL command

```
curl -X POST \
  http://localhost:8280/malaka \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 461d305b-058e-3fb2-3bc5-fa26ac3c1b32' \
  -d '{"test":"error &"}'
```

Then following exception will be thrown

```
[2020-08-26 12:37:53,758] [EI-Core] ERROR - SequenceMediator javax.xml.stream.XMLStreamException
org.apache.axiom.om.OMException: javax.xml.stream.XMLStreamException
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.build(OMSerializableImpl.java:78)
	at org.apache.axiom.om.impl.llom.OMElementImpl.build(OMElementImpl.java:722)
	at org.apache.axiom.om.impl.llom.OMElementImpl.buildWithAttachments(OMElementImpl.java:1082)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.checkAndReplaceEnvelope(PayloadFactoryMediator.java:426)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.mediate(PayloadFactoryMediator.java:177)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.mediate(PayloadFactoryMediator.java:118)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:70)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:358)
	at org.apache.synapse.rest.API.process(API.java:426)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:135)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:113)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:365)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:411)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:179)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.stream.XMLStreamException
	at org.apache.axiom.om.impl.SwitchingWrapper.updateLastNode(SwitchingWrapper.java:1106)
	at org.apache.axiom.om.impl.SwitchingWrapper.next(SwitchingWrapper.java:1041)
	at javax.xml.stream.util.StreamReaderDelegate.next(Unknown Source)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
```

**Comment by LLC-BigInt** [comment]
Please, try "" in entity_document
<format>
                    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
                        <soapenv:Header/>
                        <soapenv:Body>
                            <mediate xmlns="">
                                <entity_document>"$1"</entity_document>
                            </mediate>
                        </soapenv:Body>
                    </soapenv:Envelope>
                </format>
