### ISSUE TITLE
Error occurs when for-each mediator is used with a JSON array

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#5255]
**Description:**
When the incoming payload is a JSON array we are getting the following exception in the for-each mediator
```
[2020-09-07 13:26:31,357] ERROR {org.apache.synapse.mediators.base.SequenceMediator} - Invalid delete operation com.jayway.jsonpath.InvalidModificationException: Invalid delete operation
	at com.jayway.jsonpath.internal.PathRef$RootPathRef.set(PathRef.java:110)
	at com.jayway.jsonpath.JsonPath.set(JsonPath.java:226)
	at com.jayway.jsonpath.internal.JsonContext.set(JsonContext.java:144)
	at org.apache.synapse.mediators.builtin.ForEachMediator.mediate(ForEachMediator.java:158)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:331)
	at org.apache.synapse.rest.API.process(API.java:442)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:135)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:113)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:327)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:369)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:190)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Suggested Labels:**
Bug

**Affected Product Version:**
EI 6.6.0

**Steps to reproduce:**
Create and invoke the following API
```
<api xmlns="http://ws.apache.org/ns/synapse" name="InfosysTestAPI" context="/test">
   <resource methods="GET">
      <inSequence>
         <payloadFactory media-type="json">
            <format>[  {    "test": "Value1"  },  {    "test": "Value2"  },  {    "test": "Value3"  }]</format>
            <args/>
         </payloadFactory>
         <foreach expression="json-eval($)">
            <sequence>
               <log level="full"/>
            </sequence>
         </foreach>
         <respond/>
      </inSequence>
      <outSequence/>
      <faultSequence/>
   </resource>
</api>
```

**Comment by GDLMadushanka** [comment]
duplicate https://github.com/wso2/product-ei/issues/5186
