### ISSUE TITLE
ESB server fails to establish connections to MB after a DB restart

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#5278]
**Description:**
The following exception printed continuously when the DB is disconnect and reconnected again. 
```
TID: [] [] [2020-09-17 19:59:31,790000] ERROR {org.wso2.carbon.inbound.endpoint.protocol.jms.factory.JMSConnectionFactory} -  JMS Exception while creating consumer. Object org.wso2.andes.client.AMQSession_0_8@629c7f4a has been closed {org.wso2.carbon.inbound.endpoint.protocol.jms.factory.JMSConnectionFactory}
TID: [] [] [2020-09-17 19:59:31,790000] ERROR {org.wso2.carbon.inbound.endpoint.protocol.jms.JMSPollingConsumer} -  Error while receiving JMS message. null {org.wso2.carbon.inbound.endpoint.protocol.jms.JMSPollingConsumer}
java.lang.NullPointerException
	at org.wso2.carbon.inbound.endpoint.protocol.jms.JMSPollingConsumer.receiveMessage(JMSPollingConsumer.java:378)
	at org.wso2.carbon.inbound.endpoint.protocol.jms.JMSPollingConsumer.poll(JMSPollingConsumer.java:238)
	at org.wso2.carbon.inbound.endpoint.protocol.jms.JMSPollingConsumer.execute(JMSPollingConsumer.java:181)
	at org.wso2.carbon.inbound.endpoint.protocol.jms.JMSTask.taskExecute(JMSTask.java:45)
	at org.wso2.carbon.inbound.endpoint.common.InboundRunner.run(InboundRunner.java:111)
```

**Suggested Labels:**
Bug

**Affected Product Version:**
ESB 4.9.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1) Setup a 2 node MB cluster with a single ESB node. Make sure you deploy a durable topic subscriber and a queue subscriber by creating an inbound endpoint.
2) Run a load test publishing to a queue and topic.
3) Disconnect the DB server.
4) Reconnect the DB server after a few seconds and then you will see the null pointer exception continuously printing in the ESB log.

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-4706

**Comment by GDLMadushanka** [comment]
Fixed with master PR https://github.com/wso2/carbon-mediation/pull/750
