### ISSUE TITLE
Enrich mediator throw exception for source with non json content

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/product-ei#5288]
**Description:**
Enrich mediator throw following JsonSyntaxException exception if the source is defined as non JSON content. Synapse try to parse this content and throw an error if it cannot parse it to JSON format.
```
[2020-10-12 13:00:37,839] ERROR {org.apache.synapse.mediators.base.SequenceMediator} - com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 25 path $[1] com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 25 path $[1]
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at org.apache.synapse.mediators.elementary.Target.insertElementToBody(Target.java:291)
	at org.apache.synapse.mediators.elementary.Target.insert(Target.java:174)
	at org.apache.synapse.mediators.elementary.EnrichMediator.mediate(EnrichMediator.java:224)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:331)
	at org.apache.synapse.rest.API.process(API.java:442)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:327)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:434)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:183)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 25 path $[1]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:476)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 24 more
```

**Comment by madushadhanushka** [comment]
Duplicated https://github.com/wso2/product-ei/issues/5034
