### ISSUE TITLE
Script Mediator Used To Set a Value with a Linebreak From The Incoming Message Fails

### ISSUE THREAD

**Issue by lafernando** [wso2/product-ei#530]
An example scenario would be, using a connector to read in a JSON value from a remote source, transform the JSON value using a loop in a script mediator, and set the values in the message payload again, where the values have line breaks, it will give the following error message:-

[2017-04-12 09:25:14,238] [EI-Core]  INFO - LogMediator To: /services/Proxy1.Proxy1HttpSoap12Endpoint, WSAction: urn:mediate, SOAPAction: urn:mediate, MessageID: urn:uuid:1bfdabf1-aa12-4584-88f7-6ac04a977b70, Direction: request, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Body/></soapenv:Envelope>
[2017-04-12 09:25:14,249] [EI-Core] ERROR - ScriptMediator The script engine returned an error executing the inlined js script function mediate
com.sun.phobos.script.util.ExtendedScriptException: org.mozilla.javascript.WrappedException: Wrapped com.sun.phobos.script.util.ExtendedScriptException: org.mozilla.javascript.EvaluatorException: unterminated string literal (<Unknown source>#1) in <Unknown source> at line number 1 (<Unknown Source>#1) in <Unknown Source> at line number 1
	at com.sun.phobos.script.javascript.RhinoCompiledScript.eval(RhinoCompiledScript.java:68)
	at javax.script.CompiledScript.eval(CompiledScript.java:92)
	at org.apache.synapse.mediators.bsf.ScriptMediator.mediateForInlineScript(ScriptMediator.java:345)
	at org.apache.synapse.mediators.bsf.ScriptMediator.invokeScript(ScriptMediator.java:265)
	at org.apache.synapse.mediators.bsf.ScriptMediator.mediate(ScriptMediator.java:233)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:213)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:403)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.mozilla.javascript.WrappedException: Wrapped com.sun.phobos.script.util.ExtendedScriptException: org.mozilla.javascript.EvaluatorException: unterminated string literal (<Unknown source>#1) in <Unknown source> at line number 1 (<Unknown Source>#1)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen._Unknown_Source__3657._c_script_0(<Unknown Source>:1)
	at org.mozilla.javascript.gen._Unknown_Source__3657.call(<Unknown Source>)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.mozilla.javascript.gen._Unknown_Source__3657.call(<Unknown Source>)
	at org.mozilla.javascript.gen._Unknown_Source__3657.exec(<Unknown Source>)
	at com.sun.phobos.script.javascript.RhinoCompiledScript.eval(RhinoCompiledScript.java:55)
	... 15 more
Caused by: com.sun.phobos.script.util.ExtendedScriptException: org.mozilla.javascript.EvaluatorException: unterminated string literal (<Unknown source>#1) in <Unknown source> at line number 1
	at com.sun.phobos.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:184)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
	at org.apache.synapse.mediators.bsf.ScriptMessageContext.setPayloadJSON(ScriptMessageContext.java:724)
	at sun.reflect.GeneratedMethodAccessor266.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 24 more
Caused by: org.mozilla.javascript.EvaluatorException: unterminated string literal (<Unknown source>#1)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:64)
	at org.mozilla.javascript.Parser.addError(Parser.java:188)
	at org.mozilla.javascript.Parser.addError(Parser.java:166)
	at org.mozilla.javascript.Parser.addError(Parser.java:162)
	at org.mozilla.javascript.TokenStream.getToken(TokenStream.java:516)
	at org.mozilla.javascript.Parser.peekToken(Parser.java:296)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:2029)
	at org.mozilla.javascript.Parser.plainProperty(Parser.java:3308)
	at org.mozilla.javascript.Parser.objectLiteral(Parser.java:3206)
	at org.mozilla.javascript.Parser.primaryExpr(Parser.java:2767)
	at org.mozilla.javascript.Parser.memberExpr(Parser.java:2406)
	at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2304)
	at org.mozilla.javascript.Parser.mulExpr(Parser.java:2229)
	at org.mozilla.javascript.Parser.addExpr(Parser.java:2213)
	at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2194)
	at org.mozilla.javascript.Parser.relExpr(Parser.java:2169)
	at org.mozilla.javascript.Parser.eqExpr(Parser.java:2141)
	at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2130)
	at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2119)
	at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2108)
	at org.mozilla.javascript.Parser.andExpr(Parser.java:2097)
	at org.mozilla.javascript.Parser.orExpr(Parser.java:2086)
	at org.mozilla.javascript.Parser.condExpr(Parser.java:2062)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:2033)
	at org.mozilla.javascript.Parser.expr(Parser.java:2012)
	at org.mozilla.javascript.Parser.parenExpr(Parser.java:2839)
	at org.mozilla.javascript.Parser.primaryExpr(Parser.java:2773)
	at org.mozilla.javascript.Parser.memberExpr(Parser.java:2406)
	at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2304)
	at org.mozilla.javascript.Parser.mulExpr(Parser.java:2229)
	at org.mozilla.javascript.Parser.addExpr(Parser.java:2213)
	at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2194)
	at org.mozilla.javascript.Parser.relExpr(Parser.java:2169)
	at org.mozilla.javascript.Parser.eqExpr(Parser.java:2141)
	at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2130)
	at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2119)
	at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2108)
	at org.mozilla.javascript.Parser.andExpr(Parser.java:2097)
	at org.mozilla.javascript.Parser.orExpr(Parser.java:2086)
	at org.mozilla.javascript.Parser.condExpr(Parser.java:2062)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:2033)
	at org.mozilla.javascript.Parser.expr(Parser.java:2012)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1039)
	at org.mozilla.javascript.Parser.statement(Parser.java:901)
	at org.mozilla.javascript.Parser.parse(Parser.java:540)
	at org.mozilla.javascript.Parser.parse(Parser.java:502)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2350)
	at org.mozilla.javascript.Context.compileReader(Context.java:1296)
	at org.mozilla.javascript.Context.compileReader(Context.java:1268)
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1107)
	at com.sun.phobos.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:172)
	... 30 more

A sample proxy to recreate the issue can be found here: https://pastebin.com/JXkXnRYS.

**Comment by nandika** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="Proxy1"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http,https">
   <target>
      <inSequence>
         <log level="full"/>
         <payloadFactory media-type="json">
            <format> { "description": "MMMM\r\nX"} </format>
            <args/>
         </payloadFactory>
         <script language="js">mc.setPayloadJSON(mc.getPayloadJSON());</script>
      </inSequence>
   </target>
   <description/>
</proxy>

**Comment by Subasinghe** [comment]
According to the JSON specification, control characters (\n, \r) are not allowed in JSON strings. If you want to use Script mediator as in the sample proxy, those characters must be escaped. (use double '\')

**Comment by himasha** [comment]
Resolving as per above comment.
