### ISSUE TITLE
MB blocking issue

### ISSUE THREAD

**Issue by Thilinika** [wso2/product-ei#5310]
**Description:**
In a WSO2 MB cluster, one MB node was blocked due to a socket reading during the communication with the coordinator node. It was observed that a large number of threads are in the blocked state waiting for a lock, and the lock is granted by a StoreFailure-NotifierPool thread which is waiting for another lock.
Please refer to the below stack trace.

```
"StoreFailure-NotifierPool" #1004 prio=5 os_prio=0 tid=0x00007fb7ecd93800 nid=0x3d5c2a waiting on condition [0x00007fb7aacc5000]
   java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x00000005c6e09550> (a com.google.common.util.concurrent.SettableFuture)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:523)
    at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:90)
    at org.wso2.andes.kernel.disruptor.inbound.InboundSubscriptionEvent.waitForCompletion(InboundSubscriptionEvent.java:218)
    at org.wso2.andes.kernel.Andes.closeLocalSubscription(Andes.java:270)
    at org.wso2.andes.amqp.QpidAndesBridge.closeLocalSubscriptionsForAllBindingsOfQueue(QpidAndesBridge.java:643)
    at org.wso2.andes.amqp.QpidAndesBridge.closeAMQPSubscription(QpidAndesBridge.java:373)
    at org.wso2.andes.server.queue.SimpleAMQQueue.stateChange(SimpleAMQQueue.java:998)
    at org.wso2.andes.server.subscription.SubscriptionImpl.close(SubscriptionImpl.java:611)
    at org.wso2.andes.server.queue.SimpleAMQQueue.unregisterSubscription(SimpleAMQQueue.java:501)
    - locked <0x00000005c4804e70> (a org.wso2.andes.server.queue.SimpleAMQQueue)
    at org.wso2.andes.server.AMQChannel.unsubscribeAllConsumers(AMQChannel.java:804)
    at org.wso2.andes.server.AMQChannel.close(AMQChannel.java:744)
    at org.wso2.andes.server.protocol.AMQProtocolEngine.closeChannel(AMQProtocolEngine.java:659)
    at org.wso2.andes.server.protocol.AMQProtocolEngine.mgmtCloseChannel(AMQProtocolEngine.java:1256)
    at org.wso2.andes.server.AMQChannel.mgmtClose(AMQChannel.java:1880)
    at org.wso2.andes.server.AMQChannel$2.disconnect(AMQChannel.java:257)
 at org.wso2.andes.kernel.AndesChannel.disconnect(AndesChannel.java:279)
    at org.wso2.andes.kernel.FlowControlManager.blockListenersOnErrorBasedFlowControl(FlowControlManager.java:299)
    - locked <0x00000005c2a74108> (a org.wso2.andes.kernel.FlowControlManager)
    at org.wso2.andes.kernel.FlowControlManager.storeNonOperational(FlowControlManager.java:383)
    at org.wso2.andes.store.FailureObservingStoreManager$StoreFailureNotifier.run(FailureObservingStoreManager.java:207)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

Please refer [1]

[1] https://github.com/wso2/andes/blob/master/modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlManager.java#L383 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sdkottegoda** [comment]
The other thread which is causing the dead lock is the following:
```
"DisruptorInboundEventThread-8" #161 prio=5 os_prio=0 tid=0x00007fb7d8a9a800 nid=0x3a7665 waiting for monitor entry [0x00007fb7c07ce000]                                   java.lang.Thread.State: BLOCKED (on object monitor)                                                                                                                          at org.wso2.andes.kernel.FlowControlManager.unblockListenersOnBufferBasedFlowControl(FlowControlManager.java:266)                                                       - waiting to lock <0x00000005c2a74108> (a org.wso2.andes.kernel.FlowControlManager)                                                                                     at org.wso2.andes.kernel.FlowControlManager.notifyRemoval(FlowControlManager.java:240)                                                                                  at org.wso2.andes.kernel.AndesChannel.recordRemovalFromBuffer(AndesChannel.java:264)                                                                                    at org.wso2.andes.kernel.disruptor.inbound.InboundMessageList.registerClear(InboundMessageList.java:49)                                                                 at org.wso2.andes.kernel.disruptor.inbound.InboundEventContainer.clearMessageList(InboundEventContainer.java:421)                                                       at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:57)                                                                         at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:40)                                                                         at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                      at java.lang.Thread.run(Thread.java:748)
```
