### ISSUE TITLE
[BPMN] Email is not sent when OpenJDK11 is used. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#5326]
**Description:**

[1] - https://docs.wso2.com/display/EI660/Working+with+Mail+Tasks#WorkingwithMailTasks-ConfiguringtheSendconfirmationemailMailTask

When OpenJDK 11 is used, the email is not sent. The stack trace is as below. 
```
Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:587
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1401)
	at org.apache.commons.mail.Email.send(Email.java:1428)
	at org.activiti.engine.impl.bpmn.behavior.MailActivityBehavior.execute(MailActivityBehavior.java:102)
	... 143 more
Caused by: java.lang.ClassCastException: class org.apache.geronimo.javamail.handlers.TextHtmlHandler cannot be cast to class javax.activation.DataContentHandler (org.apache.geronimo.javamail.handlers.TextHtmlHandler is in unnamed module of loader org.wso2.carbon.webapp.mgt.loader.CarbonWebappClassLoader @5e6c3835; javax.activation.DataContentHandler is in unnamed module of loader 'app')
	at javax.activation.MailcapCommandMap.getDataContentHandler(MailcapCommandMap.java:609)
	at javax.activation.MailcapCommandMap.createDataContentHandler(MailcapCommandMap.java:563)
	at javax.activation.DataHandler.getDataContentHandler(DataHandler.java:625)
	at javax.activation.DataHandler.writeTo(DataHandler.java:329)
	at javax.mail.internet.MimeUtility.getEncoding(MimeUtility.java:340)
	at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1575)
	at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1172)
	at javax.mail.internet.MimeMultipart.updateHeaders(MimeMultipart.java:522)
	at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1533)
	at javax.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2271)
	at javax.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2231)
	at javax.mail.Transport.send(Transport.java:123)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1391)
	... 145 more
```

**Affected Product Version:**
wso2ei-6.6.0+1606756734099

**OS, DB, other environment details and versions:**    
openjdk version "11.0.9.1"

**Comment by jaimeventura** [comment]
Hey @dulanjalidilmi.
There's  issue https://github.com/wso2/product-ei/issues/5092, which i believe is the same and should be linked to it if so.
Also, can you help me on understanding when a new version with this fix will be available for download? 
Thank you
