### ISSUE TITLE
High CPU load in EI 6.6.0

### ISSUE THREAD

**Issue by arabsoheyl** [wso2/product-ei#5351]
[**Description:**](url)
I have multiple Wso2 Ei 6.6.0 on Ubuntu separately on VM's, in all VM's I have CPU load problem. Every thing works well but java using cpu load until I restart the EI service the problem not resolve. 

![Screen Shot 2021-01-21 at 3 28 00 PM](https://user-images.githubusercontent.com/15069095/105349495-085c8000-5bff-11eb-8d29-aad714a00ba8.png)
> top command information

I have tried  to find problem with this [LINK](https://docs.wso2.com/display/CLUSTER420/Troubleshooting+in+Production+Environments) and find multiple thread that use cpu more than 75% !!
```
"PassThroughMessageProcessor-429" #748 prio=5 os_prio=0 tid=0x00007f02784bb000 nid=0xe65 runnable [0x00007f020d48d000]
   java.lang.Thread.State: RUNNABLE
        at org.apache.synapse.transport.passthru.util.RelayUtils.consume(RelayUtils.java:464)
        at org.apache.synapse.transport.passthru.util.RelayUtils.consumeAndDiscardMessage(RelayUtils.java:485)
        at org.apache.synapse.mediators.AbstractListMediator.consumeInputOnOmException(AbstractListMediator.java:246)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:137)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.mediators.MediatorFaultHandler.onFault(MediatorFaultHandler.java:96)
        at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:53)
        at org.apache.synapse.endpoints.AbstractEndpoint.invokeNextFaultHandler(AbstractEndpoint.java:745)
        at org.apache.synapse.endpoints.AbstractEndpoint.onFault(AbstractEndpoint.java:560)
        at org.apache.synapse.endpoints.HTTPEndpoint.onFault(HTTPEndpoint.java:67)
        at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:101)
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:317)
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:195)
        at org.apache.synapse.transport.passthru.TargetErrorHandler$1.run(TargetErrorHandler.java:140)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

"PassThroughMessageProcessor-432" #751 prio=5 os_prio=0 tid=0x00007f027c05c800 nid=0xe68 runnable [0x00007f020d18a000]
   java.lang.Thread.State: RUNNABLE
        at org.apache.synapse.transport.passthru.util.RelayUtils.consume(RelayUtils.java:464)
        at org.apache.synapse.transport.passthru.util.RelayUtils.consumeAndDiscardMessage(RelayUtils.java:485)
        at org.apache.synapse.mediators.AbstractListMediator.consumeInputOnOmException(AbstractListMediator.java:246)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:137)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.mediators.MediatorFaultHandler.onFault(MediatorFaultHandler.java:96)
        at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:53)
        at org.apache.synapse.endpoints.AbstractEndpoint.invokeNextFaultHandler(AbstractEndpoint.java:745)
        at org.apache.synapse.endpoints.AbstractEndpoint.onFault(AbstractEndpoint.java:560)
        at org.apache.synapse.endpoints.HTTPEndpoint.onFault(HTTPEndpoint.java:67)
        at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:101)
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:317)
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:195)
        at org.apache.synapse.transport.passthru.TargetErrorHandler$1.run(TargetErrorHandler.java:140)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

"PassThroughMessageProcessor-487" #806 prio=5 os_prio=0 tid=0x00007f026c093800 nid=0xea4 runnable [0x00007f0209a53000]
   java.lang.Thread.State: RUNNABLE
        at org.apache.synapse.transport.passthru.util.RelayUtils.consume(RelayUtils.java:464)
        at org.apache.synapse.transport.passthru.util.RelayUtils.consumeAndDiscardMessage(RelayUtils.java:485)
        at org.apache.synapse.mediators.AbstractListMediator.consumeInputOnOmException(AbstractListMediator.java:246)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:137)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.mediators.MediatorFaultHandler.onFault(MediatorFaultHandler.java:96)
        at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:53)
        at org.apache.synapse.endpoints.AbstractEndpoint.invokeNextFaultHandler(AbstractEndpoint.java:745)
        at org.apache.synapse.endpoints.AbstractEndpoint.onFault(AbstractEndpoint.java:560)
        at org.apache.synapse.endpoints.HTTPEndpoint.onFault(HTTPEndpoint.java:67)
        at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:101)
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:317)
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:195)
        at org.apache.synapse.transport.passthru.TargetErrorHandler$1.run(TargetErrorHandler.java:140)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

"PassThroughMessageProcessor-571" #890 prio=5 os_prio=0 tid=0x00007f0268068800 nid=0xf0b runnable [0x00007f02045ff000]
   java.lang.Thread.State: RUNNABLE
        at org.apache.synapse.transport.passthru.util.RelayUtils.consume(RelayUtils.java:464)
        at org.apache.synapse.transport.passthru.util.RelayUtils.consumeAndDiscardMessage(RelayUtils.java:485)
        at org.apache.synapse.mediators.AbstractListMediator.consumeInputOnOmException(AbstractListMediator.java:246)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:137)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.mediators.MediatorFaultHandler.onFault(MediatorFaultHandler.java:96)
        at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:53)
        at org.apache.synapse.endpoints.AbstractEndpoint.invokeNextFaultHandler(AbstractEndpoint.java:745)
        at org.apache.synapse.endpoints.AbstractEndpoint.onFault(AbstractEndpoint.java:560)
        at org.apache.synapse.endpoints.HTTPEndpoint.onFault(HTTPEndpoint.java:67)
        at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:101)
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:317)
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:195)
        at org.apache.synapse.transport.passthru.TargetErrorHandler$1.run(TargetErrorHandler.java:140)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
``` 
> every thread use more than 75% of cpu!

**Affected Product Version:**
`Wso2 EI 6.6.0`

**OS, DB, other environment details and versions:**    
OS Info: 

```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

Java Info:

```
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
```

**Comment by venkypn** [comment]
We are also facing the same issue, do we have work around for this. Please help us.
