### ISSUE TITLE
Can't parse Json with colon in key

### ISSUE THREAD

**Issue by peterkronenberg** [wso2/product-ei#5389]
Running EI 6.6

Using WSO2, I'm having problems parsing Json with a colon in one of the keys.  The value also has commas

For example,
```
{
   "foo:bar" : "a,b,c" 
}
```
I have this json in a property.  I'm using a payloadFactory like this:

```
<payloadFactory media-type="json">
  <format>
      {
        "data" : $1
      }
  </format>
  <args>
     <arg evaluator="xml" expression="get-property('json')"/>
  </args>
</payloadFactory>
```

I get error:
```
[2021-03-19 08:54:31,213] ERROR {org.apache.synapse.commons.json.JsonUtil} - #writeAsJson. Could not convert OMElement to JSON. Invalid XML payload. Error>>> Undeclared namespace prefix "foo"
 at [row,col {unknown-source}]: [1,447]
[2021-03-19 08:54:31,216] ERROR {org.wso2.carbon.integrator.core.json.JsonStreamFormatter} - Error occurred while writing to application/json java.lang.reflect.InvocationTargetException
```

If I try to put the value in quotes (which is not really the result I want)

```
<payloadFactory media-type="json">
  <format>
      {
        "data" : "$1"
      }
  </format>
  <args>
     <arg evaluator="xml" expression="get-property('json')"/>
  </args>
</payloadFactory>
```

This time I get the error
```
[2021-03-19 09:06:09,045] ERROR {org.apache.axiom.om.impl.llom.OMSourcedElementImpl} - Could not get parser from data source for element jsonObject javax.xml.stream.XMLStreamException: java.io.IOException: Illegal character: <f>
        at org.apache.synapse.commons.staxon.core.base.AbstractXMLStreamReader.initialize(AbstractXMLStreamReader.java:245)
```

Tried specifying `evaluator="json"`.  When using `"data" : $1` (without double-quotes), I get this weird error:

```
[2021-03-19 09:40:52,525] ERROR {org.apache.synapse.mediators.base.SequenceMediator} - javax.xml.stream.XMLStreamException: ParseError at [row,col]:[8,23]
Message: Unexpected symbol: COMMA org.apache.axiom.om.OMException: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[8,23]
Message: Unexpected symbol: COMMA
        at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
```
which I assume is complaining about the commas in the Json value

Is there any way to do this?

**Comment by venkateshj** [comment]
same problem i got . i'm struggling on this .
