### ISSUE TITLE
[EI610] Can not change the password using chpasswd.sh script

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#541]
**Environment**
OS - Ubuntu 15.10
JDK - Java 1.8
DB - H2

**Steps**
1) Run ./chpasswd.sh --db-url jdbc:h2:./repository/database/WSO2CARBON_DB form <EI_HOME>/bin location

**Observation**
1. ClassNotFound exception observed

```
sashika@sashika:~/Apps/Applications/EI/wso2ei-6.1.0/bin$ ./chpasswd.sh --db-url jdbc:h2:./repository/database/WSO2CARBON_DB
Buildfile: /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/bin/build.xml
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.

setup:
     [copy] Copying 43 files to /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/lib
    [mkdir] Created dir: /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/tmp/setup
    [unzip] Expanding: /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/components/plugins/org.wso2.carbon.security.mgt.stub_5.7.5.jar into /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/tmp/setup
    [unzip] Expanding: /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/components/plugins/org.wso2.carbon.security.mgt.ui_5.7.5.jar into /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/tmp/setup
    [unzip] Expanding: /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/components/plugins/org.wso2.carbon.security.mgt_5.7.5.jar into /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/tmp/setup
   [delete] Deleting directory /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/tmp/setup
    [unzip] Expanding: /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/components/plugins/h2_1.3.175.wso2v1.jar into /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/lib
    [unzip] Expanding: /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/components/plugins/org.wso2.carbon.utils_4.4.16.jar into /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/lib
     [move] Moving 96 files to /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/lib
   [delete] Deleting directory /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/lib/META-INF
   [delete] Deleting directory /home/sashika/Apps/Applications/EI/wso2ei-6.1.0/wso2/lib/org

BUILD SUCCESSFUL
Total time: 1 second
Username: admin
New password:           
                         
Re-enter new password:           
                                  
log4j:WARN Error during default initialization
java.lang.NoClassDefFoundError: org/wso2/carbon/bootstrap/logging/LoggingBridge
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.log4j.helpers.Loader.loadClass(Loader.java:198)
	at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:327)
	at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:124)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:785)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.apache.log4j.Logger.getLogger(Logger.java:104)
	at org.apache.commons.logging.impl.Log4JLogger.getLogger(Log4JLogger.java:262)
	at org.apache.commons.logging.impl.Log4JLogger.<init>(Log4JLogger.java:108)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.commons.logging.impl.LogFactoryImpl.createLogFromClass(LogFactoryImpl.java:1025)
	at org.apache.commons.logging.impl.LogFactoryImpl.discoverLogImplementation(LogFactoryImpl.java:844)
	at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:541)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:292)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:269)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
	at org.wso2.carbon.user.core.config.RealmConfigXMLProcessor.<clinit>(RealmConfigXMLProcessor.java:56)
	at org.wso2.carbon.core.util.PasswordUpdater.run(PasswordUpdater.java:158)
	at org.wso2.carbon.core.util.PasswordUpdater.main(PasswordUpdater.java:48)
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.bootstrap.logging.LoggingBridge
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
Error updating credentials for user admin : org.wso2.carbon.user.core.UserStoreException: Error while reading realm configuration from file
```

2. Permission denied when changing the password for broker and business-process servers

```
sashika@sashika:~/Apps/Applications/EI/wso2ei-6.1.0/wso2/broker/bin$ ./chpasswd.sh --db-url jdbc:h2:repository/database/WSO2CARBON_DB
bash: ./chpasswd.sh: Permission denied

```

**Comment by Tofdu31** [comment]
Hello,
I also posted the same bug and in the end nobody answers ...

Have you found a solution since?

Thanks

**Comment by fpants** [comment]
Hi,

This can be solved by setting the carbon.config.dir.path like:
-Dcarbon.config.dir.path=$CARBON_HOME\conf
