### ISSUE TITLE
Dynamic SQL queries to pass the entire query is not getting deployed

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#5443]
**Description:**
Dynamic sql queries similar to <sql>:query</sql> are not working in EI 6.5.0 and latest versions

```
<data name="sampleDS" transports="http https local">
   <config enableOData="false" id="default">
      <property name="driverClassName">com.mysql.jdbc.Driver</property>
      <property name="url">jdbc:mysql://localhost:3306/books</property>
      <property name="username">root</property>
   </config>
   <query id="insert" useConfig="default">
      <sql>:query</sql>
      <param name="query" optional="false" sqlType="QUERY_STRING"/>
   </query>
   <operation name="op">
      <call-query href="insert">
         <with-param name="query" query-param="query"/>
      </call-query>
   </operation>
</data>
```

The dataservice deployment fails with the following error.

```
[2021-05-28 13:38:22,055] [EI-Core] ERROR - DBDeployer The sampleDS.dbs service, which is not valid, caused {1}
DS Code: UNKNOWN_ERROR
Source Data Service:-
Name: sampleDS
Location: /sampleDS.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Nested Exception:-
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

	at org.wso2.carbon.dataservices.core.DataServiceFactory.createDataService(DataServiceFactory.java:208)
	at org.wso2.carbon.dataservices.core.DBDeployer.createDBService(DBDeployer.java:811)
	at org.wso2.carbon.dataservices.core.DBDeployer.processService(DBDeployer.java:1169)
	at org.wso2.carbon.dataservices.core.DBDeployer.deploy(DBDeployer.java:202)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at org.wso2.carbon.dataservices.core.description.query.SQLQuery.sqlQueryType(SQLQuery.java:2528)
	at org.wso2.carbon.dataservices.core.description.query.SQLQuery.setSqlQueryType(SQLQuery.java:2523)
	at org.wso2.carbon.dataservices.core.description.query.SQLQuery.init(SQLQuery.java:200)
	at org.wso2.carbon.dataservices.core.description.query.SQLQuery.<init>(SQLQuery.java:185)
	at org.wso2.carbon.dataservices.core.description.query.QueryFactory.createSQLQuery(QueryFactory.java:444)
	at org.wso2.carbon.dataservices.core.description.query.QueryFactory.createQuery(QueryFactory.java:95)
	at org.wso2.carbon.dataservices.core.DataServiceFactory.createDataService(DataServiceFactory.java:173)
	... 20 more
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by LLC-BigInt** [comment]
Maybe can try
1. select ? from dual
2. and where is tag <result outputType="json">{"Entries": {"Entry": {"res": $res} }}</result> between <query> and </query>
