### ISSUE TITLE
MBean Exception using cache mediator

### ISSUE THREAD

**Issue by sreenath-centime** [wso2/product-ei#5461]
We have come across a strange issue which occurs intermittently in our wso2 mediation flow.

**UseCase :**
We are using cache mediator to store our app secrets, so that first time when the service is deployed, it makes the api call to fetch the app secrets 
- We use call mediator in blocking mode to fetch our secrets and store in wso2 cache with a timeout of about 15hrs.
- We use a scheduler task to periodically trigger this mediation flow which internally invokes the sequence containing the cache mediator
- In all subsequent scheduler invocations, when the sequence is invoked, the cache mediator returns the secrets from cache instead of making a api call, and the flow continues.

Now we see the below issue intermittently in some of the scheduler invocations, where the flow stops with the below error..
[InboundWorker-2] o.w.c.m.c.CacheMediator : MBean implementation is not compliant with JMX specification standard MBean.
javax.management.InstanceAlreadyExistsException: org.wso2.carbon.mediator.cache:type=Cache,tenant=carbon.super
at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
at org.wso2.carbon.mediator.cache.CacheMediator.exposeInvalidator(CacheMediator.java:612)
at org.wso2.carbon.mediator.cache.CacheMediator.init(CacheMediator.java:201)
at org.apache.synapse.mediators.AbstractListMediator.init(AbstractListMediator.java:200)
at org.apache.synapse.mediators.base.SequenceMediator.init(SequenceMediator.java:315)
at org.apache.synapse.core.axis2.Axis2MessageContext.getSequence(Axis2MessageContext.java:182)
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:201)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
at org.apache.synapse.mediators.MediatorWorker.run(MediatorWorker.java:87)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

We tried reading about this issue online, but couldn't really understand anything concretely.
Could you please help us understand and resolve this issue. Thanks.

**Comment by prashant-centime** [comment]
@Shakila please help.
