### ISSUE TITLE
[EI-7.1MI] [MI-1.2.0]- Hashicorp vault cannot connect to https

### ISSUE THREAD

**Issue by isharac** [wso2/product-ei#5487]
**Description:**

MI-1.2.0 can connect into the hashicorp vault using http and cannot connect to https

Steps to reproduce:

I was able to observe the bug when trying out the following steps,

Download MI 1.2.0 and updated using the U2 to MI 1.2.0-36
Installed HashiCorp vault from https://www.vaultproject.io/downloads
Initialized the Server by running vault server -dev
Created a secret as follows: vault kv put secret/eai testKey071501=wso2carbon
Installed ngrok and hosted the vault's VAULT_ADDR port in ngrok
Created the following proxy
<?xml version="1.0" encoding="UTF-8"?>
<proxy name="TestVaultProxy" startOnLoad="true" transports="http https" xmlns="http://ws.apache.org/ns/synapse">
    <target>
        <inSequence>
            <log level="custom">
                <property name="MessageFlow" value="======================= 1.0 TestVaultProxy ======================="/>
            </log>
            <property expression="hashicorp:vault-lookup('secret/eai', 'testKey071501')" name="HashiCorpSecret" scope="default" type="STRING"/>
            <log level="custom" separator=",">
                <property name="MessageFlow" value="======================= 2.0 TestVaultProxy Response ======================="/>
                <property expression="$ctx:HashiCorpSecret" name="HashiCorpSecret"/>
            </log>
            <payloadFactory media-type="xml">
                <format>
                    <return>
                        <status>SUCCESS</status>
                    </return>
                </format>
                <args/>
            </payloadFactory>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </target>
</proxy>
Configured Hashicorp vault in deployment.toml as belows,
[[external_vault]]
name = "hashicorp"
#address = "http://127.0.0.1:8200"
address = "https://6ebbb938787c.ngrok.io"
# If Static Token authentication is used, apply the rootToken:
rootToken = "s.c4lxdlutv2qcjFrcVYpGu4tR" #If AppRole Pull authentication is used, apply the roleId and secretId:
#roleId = "ROLE_ID"
#secretId = "SECRET_ID"
cachableDuration = "15000"
engineVersion = "2"
#namespace = "NAMESPACE"
trustStoreFile = "${carbon.home}/repository/resources/security/client-truststore.jks"
keyStoreFile = "${carbon.home}/repository/resources/security/wso2carbon.jks"
keyStorePassword = "wso2carbon"

[synapse_properties]
"synapse.xpath.func.extensions"="org.wso2.micro.integrator.mediation.security.vault.xpath.SecureVaultLookupXPathFunctionProvider,org.wso2.micro.integrator.mediation.security.vault.external.hashicorp.HashiCorpVaultLookupXPathFunctionProvider"

 

Added the vault-java-driver-5.1.0.jar into the <mi-home>/lib folder.
Imported ngrok cert to the trustStore and Keystore.
Served and called the proxy.

Error observed in the log.

`[2021-07-15 10:58:23,364] ERROR {SynapseXPath} - Evaluation of the XPath expression hashicorp:vault-lookup('secret/eai', 'testKey071501') resulted in an error org.jaxen.UnresolvableException: No Such Function vault-lookup
        at org.jaxen.SimpleFunctionContext.getFunction(SimpleFunctionContext.java:127)
        at org.apache.synapse.util.xpath.SynapseXPathFunctionContext.getFunction(SynapseXPathFunctionContext.java:101)
        at org.jaxen.ContextSupport.getFunction(ContextSupport.java:242)
        at org.jaxen.Context.getFunction(Context.java:216)
        at org.jaxen.expr.DefaultFunctionCallExpr.evaluate(DefaultFunctionCallExpr.java:176)
        at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:102)
        at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:675)
        at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:215)
        at org.jaxen.BaseXPath.evaluate(BaseXPath.java:175)
        at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:407)
        at org.apache.synapse.mediators.builtin.PropertyMediator.getResultValue(PropertyMediator.java:387)`

**Comment by isharac** [comment]
fixed with https://github.com/wso2/micro-integrator/pull/2384
