### ISSUE TITLE
Cannot run ciphertool.sh from bin directory

### ISSUE THREAD

**Issue by jsdjayanga** [wso2/product-ei#549]
In EI 6.1.0 it is needed to run cipher tool from product home
./bin/ciphertool.sh -Dconfigure
If it is run from the bin directory, it gives the following error.
[PRODUCT_HOME]/bin>$ ./ciphertool.sh -Dconfigure
Exception in thread "main" org.wso2.ciphertool.exception.CipherToolException: File, cipher-standalone-config.properties does not exist.
	at org.wso2.ciphertool.utils.Utils.setSystemProperties(Utils.java:247)
	at org.wso2.ciphertool.CipherTool.initialize(CipherTool.java:93)
	at org.wso2.ciphertool.CipherTool.main(CipherTool.java:52)

But according to the 4.4.x documentation [1] instructions are given to run the cipher tool from the bin directory.

[1] https://docs.wso2.com/display/ADMIN44x/Encrypting+Passwords+with+Cipher+Tool

**Comment by Zfarmani** [comment]
In EI (6.1.0 and 6.2.0) packaging is changed. modify the path of secret-conf.properties and cipher-text.properties and cipher-tool.properties files in org.wso2.ciphertool.utils.Utils class and the problem is solved.

>                secretConfFile = homeFolder + File.separator + Constants.CONF_DIR + File.separator + Constants.SECURITY_DIR + File.separator + Constants.SECRET_PROPERTY_FILE;

>                 cipherToolPropFile =homeFolder+ File.separator + Constants.CONF_DIR + File.separator + Constants.SECURITY_DIR + File.separator + Constants.CIPHER_TOOL_PROPERTY_FILE;

>                 cipherTextPropFile = Constants.CONF_DIR + File.separator +Constants.SECURITY_DIR + File.separator + Constants.CIPHER_TEXT_PROPERTY_FILE;
