### ISSUE TITLE
[ESB 4.9.0] Intermittenly ConcurrentModification thrown when using Call Template mediator

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#5563]
**Description:**

$subject

```
TID: [-1] [] [2022-05-19 13:02:23,556] ERROR {org.apache.synapse.transport.passthru.SourceHandler} -  Unexpected error: null {org.apache.synapse.transport.passthru.SourceHandler}
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1473)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1507)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1505)
	at org.apache.synapse.transport.passthru.SourceResponse.start(SourceResponse.java:154)
	at org.apache.synapse.transport.passthru.SourceHandler.responseReady(SourceHandler.java:271)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.produceOutput(DefaultNHttpServerConnection.java:309)
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.produceOutput(LoggingNHttpServerConnection.java:114)
	at org.apache.synapse.transport.passthru.ServerIODispatch.onOutputReady(ServerIODispatch.java:87)
	at org.apache.synapse.transport.passthru.ServerIODispatch.onOutputReady(ServerIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:143)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:180)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:342)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce:**

Use the following artifacts. Use a backend which sends more than 10 headers. The issue will intermittenly reproduced.

```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="Respond"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="https,http">
   <target>
      <inSequence>
         <call>
            <endpoint>
               <address uri="http://localhost:8400"/>
            </endpoint>
         </call>
         <call-template target="SendResponse1">
            <with-param name="response_content_type" value="application/json"/>
            <with-param xmlns:ns="http://org.apache.synapse/xsd"
                        name="transaction_id"
                        value="{$ctx:TRANSACTION_ID}"/>
            <with-param xmlns:ns="http://org.apache.synapse/xsd"
                        name="service_id"
                        value="{$ctx:SERVICE_NAME}"/>
            <with-param xmlns:ns="http://org.apache.synapse/xsd"
                        name="operation_name"
                        value="{$ctx:OPERATION_NAME}"/>
         </call-template>
         <respond/>
      </inSequence>
      <outSequence/>
   </target>
   <description/>
</proxy>

<?xml version="1.0" encoding="UTF-8"?>
<template name="SendResponse1" xmlns="http://ws.apache.org/ns/synapse">
    <parameter name="response_content_type"/>
    <parameter name="transaction_id"/>
    <parameter name="service_id"/>
    <parameter name="operation_name"/>
    <parameter name="request_id"/>
    <parameter name="correlation_id"/>
    <sequence>
        <log level="custom">
            <property name="inside the template" value="inside the template"/>
        </log>
    </sequence>
</template>

```

**Comment by chanikag** [comment]
Fixed by https://github.com/wso2/wso2-synapse/pull/1607, https://github.com/wso2/wso2-synapse/pull/1616
