### ISSUE TITLE
NPE when invoking batchrequest with json payload in EI 6.1.1 

### ISSUE THREAD

**Issue by darshaka** [wso2/product-ei#582]
### Environment: EI 6.1.1

Reproducing steps:
1. Create a sample table in mysql
create table student_tb (
student_id varchar(6),
rnl_id varchar(30),
created_date varchar(40),
modified_date varchar(40),
segment_id int,
callable varchar(1),
source_pool_id int,
pool_name varchar(20)
)
2. Create a data service with enabling batch request:
&lt;data enableBatchRequests="true" name="mydataservice" transports="http https local"&gt;
   &lt;config enableOData="false" id="mydbid"&gt;
      &lt;property name="driverClassName"&gt;com.mysql.jdbc.Driver&lt;/property&gt;
      &lt;property name="url"&gt;jdbc:mysql://localhost:3306/mydb1&lt;/property&gt;
      &lt;property name="username"&gt;tharanga&lt;/property&gt;
      &lt;property name="password"&gt;tharanga&lt;/property&gt;
   &lt;/config&gt;
   &lt;query id="insertCallingPool" useConfig="mydbid"&gt;
      &lt;sql&gt;insert into student_tb (student_id, rnl_id, created_date, modified_date, segment_id, callable, source_pool_id, pool_name) values (:student_id, :rnl_id, :created_date, :modified_date, :segment_id, :callable, :source_pool_id, :pool_name);&lt;/sql&gt;
      &lt;param name="student_id" sqlType="STRING"/&gt;
      &lt;param name="rnl_id" sqlType="STRING"/&gt;
      &lt;param name="created_date" sqlType="STRING"/&gt;
      &lt;param name="modified_date" sqlType="STRING"/&gt;
      &lt;param name="segment_id" sqlType="INTEGER"/&gt;
      &lt;param name="callable" sqlType="STRING"/&gt;
      &lt;param name="source_pool_id" sqlType="INTEGER"/&gt;
      &lt;param name="pool_name" sqlType="STRING"/&gt;
   &lt;/query&gt;
   &lt;operation name="operation1"&gt;
      &lt;call-query href="insertCallingPool"/&gt;
   &lt;/operation&gt;
   &lt;resource method="POST" path="testpath"&gt;
      &lt;call-query href="insertCallingPool"&gt;
         &lt;with-param name="student_id" query-param="student_id"/&gt;
         &lt;with-param name="rnl_id" query-param="rnl_id"/&gt;
         &lt;with-param name="created_date" query-param="created_date"/&gt;
         &lt;with-param name="modified_date" query-param="modified_date"/&gt;
         &lt;with-param name="segment_id" query-param="segment_id"/&gt;
         &lt;with-param name="callable" query-param="callable"/&gt;
         &lt;with-param name="source_pool_id" query-param="source_pool_id"/&gt;
         &lt;with-param name="pool_name" query-param="pool_name"/&gt;
      &lt;/call-query&gt;
   &lt;/resource&gt;
&lt;/data&gt;
3. Create a end point as follows
&lt;endpoint xmlns="http://ws.apache.org/ns/synapse" name="PostInsertProgramsEP"&gt;
   &lt;http uri-template="http://tharanga:8280/services/mydataservice/testpath" method="post"&gt;
      &lt;suspendOnFailure&gt;
         &lt;progressionFactor&gt;1.0&lt;/progressionFactor&gt;
      &lt;/suspendOnFailure&gt;
      &lt;markForSuspension&gt;
         &lt;retriesBeforeSuspension&gt;0&lt;/retriesBeforeSuspension&gt;
         &lt;retryDelay&gt;0&lt;/retryDelay&gt;
      &lt;/markForSuspension&gt;
   &lt;/http&gt;
&lt;/endpoint&gt;
4. Create a proxy service as follows
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;proxy xmlns="http://ws.apache.org/ns/synapse"
       name="Proxy1"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http,https"&gt;
   &lt;target&gt;
      &lt;inSequence&gt;
         &lt;log level="full"&gt;
            &lt;property name="start" value="1111111111111111111"/&gt;
         &lt;/log&gt;
         &lt;property name="messageType"
                   scope="axis2"
                   type="STRING"
                   value="application/json"/&gt;
         &lt;log level="full"/&gt;
         &lt;call&gt;
            &lt;endpoint key="PostInsertProgramsEP"/&gt;
         &lt;/call&gt;
      &lt;/inSequence&gt;
   &lt;/target&gt;
   &lt;description/&gt;
&lt;/proxy&gt;

Call the proxy service with below json payload
{
    "_posttestpath_batch_req": {
        "_posttestpath": [
        {
            "student_id": "80781",
            "rnl_id": "000000000002",
            "created_date": "2017-05-23 07:10:40.545",
            "modified_date": "2017-05-23 07:10:40.545",
            "segment_id": 1835,
            "callable": "Y",
            "source_pool_id": 1149,
            "pool_name": "xxxe_1383"
        },
        {
            "student_id": "80782",
            "rnl_id": "000000000002",
            "created_date": "2017-05-23 07:10:40.545",
            "modified_date": "2017-05-23 07:10:40.545",
            "segment_id": 1835,
            "callable": "Y",
            "source_pool_id": 1149,
            "pool_name": "xxxe_1383"
        }
        ]
    }
}

### Now we can see bellow **NullPointerException** exception.

[2017-05-24 16:34:01,245] [EI-Core] ERROR - ServerWorker Error processing POST reguest for : /services/mydataservice/testpath. Error detail: null. 
java.lang.NullPointerException
	at org.apache.axis2.json.gson.GsonXMLStreamReader.validateArgumentTypes(GsonXMLStreamReader.java:783)
	at org.apache.axis2.json.gson.GsonXMLStreamReader.nextValue(GsonXMLStreamReader.java:734)
	at org.apache.axis2.json.gson.GsonXMLStreamReader.readValue(GsonXMLStreamReader.java:626)
	at org.apache.axis2.json.gson.GsonXMLStreamReader.stateTransition(GsonXMLStreamReader.java:532)
	at org.apache.axis2.json.gson.GsonXMLStreamReader.next(GsonXMLStreamReader.java:178)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.build(OMSerializableImpl.java:78)
	at org.apache.axiom.om.impl.llom.OMElementImpl.build(OMElementImpl.java:722)
	at org.apache.axiom.om.impl.llom.OMElementImpl.detach(OMElementImpl.java:700)
	at org.apache.axiom.om.impl.llom.OMNodeImpl.setParent(OMNodeImpl.java:105)
	at org.apache.axiom.om.impl.llom.OMElementImpl.addChild(OMElementImpl.java:296)
	at org.apache.axiom.om.impl.llom.OMElementImpl.addChild(OMElementImpl.java:212)
	at org.apache.axiom.soap.impl.llom.SOAPBodyImpl.addChild(SOAPBodyImpl.java:231)
	at org.apache.axis2.json.gson.JSONMessageHandler.invoke(JSONMessageHandler.java:84)
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:372)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by madhawa-gunasekara** [comment]
Fixed this, relevant fixes were set to the axis2 repo. Need a kernel release.
