### ISSUE TITLE
SFTP exception from JSCH swallowed in vfs

### ISSUE THREAD

**Issue by shazni** [wso2/product-ei#648]
Got the following exception when fileconnector isExist operation is called.

Caused by: org.apache.commons.vfs2.FileSystemException: Could not determine the type of file "***".
at org.apache.commons.vfs2.provider.AbstractFileObject.getType(AbstractFileObject.java:506)
at org.apache.commons.vfs2.provider.sftp.SftpFileObject.refresh(SftpFileObject.java:92)
... 27 more
Caused by: org.apache.commons.vfs2.FileSystemException: Could not change to work directory "/".
at org.apache.commons.vfs2.provider.sftp.SftpFileSystem.getChannel(SftpFileSystem.java:144)
at org.apache.commons.vfs2.provider.sftp.SftpFileObject.statSelf(SftpFileObject.java:152)
at org.apache.commons.vfs2.provider.sftp.SftpFileObject.doGetType(SftpFileObject.java:115)
at org.apache.commons.vfs2.provider.AbstractFileObject.getType(AbstractFileObject.java:497)

But SftpFileSystem actually got an exception from JSch that it did not set as cause for the newly created exception, making debugging harder.
But the actual JSCH exception is swallowed.

**Comment by shazni** [comment]
Please find the PR for this

https://github.com/wso2/wso2-commons-vfs/pull/36

**Comment by vinok88** [comment]
PR merged in commit d779fe2dff4b834a139d7c99b3fa58fa49047921.
