### ISSUE TITLE
BPMN SOAP task not working in EI

### ISSUE THREAD

**Issue by vinok88** [wso2/product-ei#718]
When invoking a soap task, it gives following error. Same BPMN works fine in BPS 3.6.0. Process attached.
`java.lang.ClassCastException: org.apache.axis2.receivers.RawXMLINOnlyMessageReceiver cannot be cast to org.apache.axis2.engine.MessageReceiver
	at org.apache.axis2.deployment.DescriptionBuilder.loadMessageReceiver(DescriptionBuilder.java:192)
	at org.apache.axis2.deployment.DescriptionBuilder$1.run(DescriptionBuilder.java:145)
	at org.apache.axis2.deployment.DescriptionBuilder$1.run(DescriptionBuilder.java:142)
	at org.apache.axis2.java.security.AccessController.doPrivileged(AccessController.java:132)
	at org.apache.axis2.deployment.DescriptionBuilder.processMessageReceivers(DescriptionBuilder.java:141)
	at org.apache.axis2.deployment.AxisConfigBuilder.populateConfig(AxisConfigBuilder.java:107)
	at org.apache.axis2.deployment.DeploymentEngine.populateAxisConfiguration(DeploymentEngine.java:887)
	at org.apache.axis2.deployment.FileSystemConfigurator.getAxisConfiguration(FileSystemConfigurator.java:116)
	at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:64)
	at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContextFromFileSystem(ConfigurationContextFactory.java:210)
	at org.apache.axis2.client.ServiceClient.configureServiceClient(ServiceClient.java:150)
	at org.apache.axis2.client.ServiceClient.<init>(ServiceClient.java:143)
	at org.apache.axis2.client.ServiceClient.<init>(ServiceClient.java:250)
	at org.wso2.carbon.bpmn.extensions.soap.SOAPTask.execute(SOAPTask.java:247)
[ReportsProcess.bar.zip](https://github.com/wso2/product-ei/files/1132887/ReportsProcess.bar.zip)

`

**Comment by himasha** [comment]
This issue occurs because the underlying implementation of bpmn RESTTask uses axis2 ServiceClient. When configuring ServiceClient instance it is trying to resolve the classpath with axis2-kernel.jar located in business-process/repository/deployment/server/webapps/bpmn/WEB-INF/lib. As a workaround removing axis2-kernel-VERSION.jar from above location would resolve the issue. 

Fixed in current master with https://github.com/wso2/carbon-business-process/pull/487/commits/a24d2eecd25b3bd412a280fcfb7801039e6a7790.
