### ISSUE TITLE
[EI620] NullPointer Exception when using fn:replace() in Red Hat 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#719]
**Environment** 
OS - rhel-6.6.x86_64 , rhel-7.0.x86_64
JAVA - JDK 1.8
DB - Oracle 12c
Pack - EI620 Snapshot

Steps to reproduce the issue
1. Create a proxy using replace function as below

```
<?xml version="1.0" encoding="UTF-8"?><proxy xmlns="http://ws.apache.org/ns/synapse" name="Issue01" startOnLoad="true" statistics="disable" trace="disable" transports="http,https">
    <target>
        <inSequence>
            <log>
                <property xmlns:fn="http://www.w3.org/2005/xpath-functions" expression="fn:replace('Bella Italia', 'l', '*')" name="fn:replace() =="/>
            </log>
            <drop/>
        </inSequence>
    </target>
    <description/>
</proxy>
```
2. Invoke the proxy

**Observations**
When invoking the proxy in REDHAT Server following exception observed, However, the issue did not observe in other environments such as Ubuntu or Debian.

Following Null pointer exception observed

```
TID: [-1234] [] [2017-07-08 11:16:09,467] ERROR {org.apache.synapse.util.xpath.SynapseXPath} -  Evaluation of the XPath expression fn:replace('Bella Italia', 'l', '*') resulted in an error {org.apache.synapse.util.xpath.SynapseXPath}

javax.xml.transform.TransformerException: java.lang.NullPointerException
	at org.apache.xpath.jaxp.JAXPExtensionsProvider.extFunction(JAXPExtensionsProvider.java:204)
	at org.apache.xpath.functions.FuncExtFunction.execute(FuncExtFunction.java:208)
	at org.apache.xpath.XPath.execute(XPath.java:337)
	at org.apache.xpath.XPath.execute(XPath.java:303)
	at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:121)
	at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:91)
	at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:176)
	at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:221)
	at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:533)
	at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:367)
	at org.apache.synapse.mediators.MediatorProperty.getEvaluatedExpression(MediatorProperty.java:138)
	at org.apache.synapse.mediators.builtin.LogMediator.setCustomProperties(LogMediator.java:223)
	at org.apache.synapse.mediators.builtin.LogMediator.getSimpleLogMessage(LogMediator.java:168)
	at org.apache.synapse.mediators.builtin.LogMediator.getLogMessage(LogMediator.java:134)
	at org.apache.synapse.mediators.builtin.LogMediator.mediate(LogMediator.java:101)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:224)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:407)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.apache.xpath.jaxp.JAXPExtensionsProvider.extFunction(JAXPExtensionsProvider.java:197)
	... 25 more
--------------- linked to ------------------
javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: java.lang.NullPointerException
	at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:189)
	at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:221)
	at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:533)
	at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:367)
	at org.apache.synapse.mediators.MediatorProperty.getEvaluatedExpression(MediatorProperty.java:138)
	at org.apache.synapse.mediators.builtin.LogMediator.setCustomProperties(LogMediator.java:223)
	at org.apache.synapse.mediators.builtin.LogMediator.getSimpleLogMessage(LogMediator.java:168)
	at org.apache.synapse.mediators.builtin.LogMediator.getLogMessage(LogMediator.java:134)
	at org.apache.synapse.mediators.builtin.LogMediator.mediate(LogMediator.java:101)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:224)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:407)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.transform.TransformerException: java.lang.NullPointerException
	at org.apache.xpath.jaxp.JAXPExtensionsProvider.extFunction(JAXPExtensionsProvider.java:204)
	at org.apache.xpath.functions.FuncExtFunction.execute(FuncExtFunction.java:208)
	at org.apache.xpath.XPath.execute(XPath.java:337)
	at org.apache.xpath.XPath.execute(XPath.java:303)
	at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:121)
	at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:91)
	at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:176)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.apache.xpath.jaxp.JAXPExtensionsProvider.extFunction(JAXPExtensionsProvider.java:197)
	... 25 more
TID: [-1234] [] [2017-07-08 11:16:09,473]  INFO {org.apache.synapse.mediators.builtin.LogMediator} -  To: /services/Issue01.Issue01HttpSoap12Endpoint, WSAction: urn:mediate, SOAPAction: urn:mediate, MessageID: urn:uuid:bbef5865-02ca-48cd-9d32-2f1744ef757a, Direction: request, MESSAGE = Executing default 'fault' sequence, ERROR_CODE = 0, ERROR_MESSAGE = Evaluation of the XPath expression fn:replace('Bella Italia', 'l', '*') resulted in an error, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Body/></soapenv:Envelope> {org.apache.synapse.mediators.builtin.LogMediator}
```

**Comment by sashikamw** [comment]
Please note that this issue is observed for several functions such as fn:dateTime, fn:years-from-duration etc.

```
TID: [-1234] [] [2017-07-10 14:31:18,911] ERROR {org.apache.synapse.util.xpath.SynapseXPath} -  Evaluation of the XPath expression fn:years-from-duration(xs:yearMonthDuration("P20Y15M")) resulted in an error {org.apache.synapse.util.xpath.SynapseXPath}
javax.xml.transform.TransformerException: java.lang.NullPointerException
	at org.apache.xpath.jaxp.JAXPExtensionsProvider.extFunction(JAXPExtensionsProvider.java:204)
	at org.apache.xpath.functions.FuncExtFunction.execute(FuncExtFunction.java:208)
	at org.apache.xpath.functions.FuncExtFunction.execute(FuncExtFunction.java:199)
	at org.apache.xpath.XPath.execute(XPath.java:337)
	at org.apache.xpath.XPath.execute(XPath.java:303)
	at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:121)
	at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:91)
	at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:176)
	at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:221)
	at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:533)
	at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:367)
	at org.apache.synapse.mediators.builtin.PropertyMediator.getResultValue(PropertyMediator.java:355)
	at org.apache.synapse.mediators.builtin.PropertyMediator.mediate(PropertyMediator.java:108)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:224)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:407)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.apache.xpath.jaxp.JAXPExtensionsProvider.extFunction(JAXPExtensionsProvider.java:197)
	... 23 more
--------------- linked to ------------------
javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: java.lang.NullPointerException
	at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:189)
	at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:221)
	at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:533)
	at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:367)
	at org.apache.synapse.mediators.builtin.PropertyMediator.getResultValue(PropertyMediator.java:355)
	at org.apache.synapse.mediators.builtin.PropertyMediator.mediate(PropertyMediator.java:108)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:224)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:407)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.transform.TransformerException: java.lang.NullPointerException
	at org.apache.xpath.jaxp.JAXPExtensionsProvider.extFunction(JAXPExtensionsProvider.java:204)
	at org.apache.xpath.functions.FuncExtFunction.execute(FuncExtFunction.java:208)
	at org.apache.xpath.functions.FuncExtFunction.execute(FuncExtFunction.java:199)
	at org.apache.xpath.XPath.execute(XPath.java:337)
	at org.apache.xpath.XPath.execute(XPath.java:303)
	at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:121)
	at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:91)
	at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:176)
	... 16 more
Caused by: java.lang.NullPointerException
	at org.apache.xpath.jaxp.JAXPExtensionsProvider.extFunction(JAXPExtensionsProvider.java:197)
	... 23 more
TID: [-1234] [] [2017-07-10 14:31:18,921]  INFO {org.apache.synapse.mediators.builtin.LogMediator} -  To: /services/xpath20DateFunctions.xpath20DateFunctionsHttpSoap12Endpoint, WSAction: urn:mediate, SOAPAction: urn:mediate, MessageID: urn:uuid:194637dc-96aa-4b92-913d-fb1c7b70ddc1, Direction: request, MESSAGE = Executing default 'fault' sequence, ERROR_CODE = 0, ERROR_MESSAGE = Evaluation of the XPath expression fn:years-from-duration(xs:yearMonthDuration("P20Y15M")) resulted in an error, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Body/></soapenv:Envelope> {org.apache.synapse.mediators.builtin.LogMediator}


```
