### ISSUE TITLE
[EI620] Some of the xpath functions failed when saving 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#722]
**Environment**
Pack - EI620 Snapshot 
JAVA - JDK 1.8
OS - Ubuntu 15.10
DB - h2

**Steps to reproduce the issue**
1. Create a simple proxy and add property mediator or log mediator including the following xpath functions;

- fn:index-of ((15, 40, 25, 40, 10), 40))
- fn:distinct-values((1, 2, 3, 1, 2))

**Observations**
Some of the the xpath 2. 0 functions failed when saving the configuration
```
[2017-07-10 11:37:13,155] [EI-Core] ERROR - ApplicationDispatcher Servlet.service() for servlet bridgeservlet threw exception
class org.jaxen.saxpath.XPathSyntaxException: fn:index-of ((15, 40, 25, 40, 10), 40): 16: Expected: )
	at org.jaxen.saxpath.base.XPathReader.createSyntaxException(XPathReader.java:1085)
	at org.jaxen.saxpath.base.XPathReader.match(XPathReader.java:1038)
	at org.jaxen.saxpath.base.XPathReader.filterExpr(XPathReader.java:274)
	at org.jaxen.saxpath.base.XPathReader.pathExpr(XPathReader.java:142)
	at org.jaxen.saxpath.base.XPathReader.unionExpr(XPathReader.java:1007)
	at org.jaxen.saxpath.base.XPathReader.unaryExpr(XPathReader.java:995)
	at org.jaxen.saxpath.base.XPathReader.multiplicativeExpr(XPathReader.java:943)
	at org.jaxen.saxpath.base.XPathReader.additiveExpr(XPathReader.java:913)
	at org.jaxen.saxpath.base.XPathReader.relationalExpr(XPathReader.java:860)
	at org.jaxen.saxpath.base.XPathReader.equalityExpr(XPathReader.java:829)
	at org.jaxen.saxpath.base.XPathReader.andExpr(XPathReader.java:809)
	at org.jaxen.saxpath.base.XPathReader.orExpr(XPathReader.java:787)
	at org.jaxen.saxpath.base.XPathReader.expr(XPathReader.java:780)
	at org.jaxen.saxpath.base.XPathReader.arguments(XPathReader.java:238)
	at org.jaxen.saxpath.base.XPathReader.functionCall(XPathReader.java:227)
	at org.jaxen.saxpath.base.XPathReader.filterExpr(XPathReader.java:279)
	at org.jaxen.saxpath.base.XPathReader.pathExpr(XPathReader.java:161)
	at org.jaxen.saxpath.base.XPathReader.unionExpr(XPathReader.java:1007)
	at org.jaxen.saxpath.base.XPathReader.unaryExpr(XPathReader.java:995)
	at org.jaxen.saxpath.base.XPathReader.multiplicativeExpr(XPathReader.java:943)
	at org.jaxen.saxpath.base.XPathReader.additiveExpr(XPathReader.java:913)
	at org.jaxen.saxpath.base.XPathReader.relationalExpr(XPathReader.java:860)
	at org.jaxen.saxpath.base.XPathReader.equalityExpr(XPathReader.java:829)
	at org.jaxen.saxpath.base.XPathReader.andExpr(XPathReader.java:809)
	at org.jaxen.saxpath.base.XPathReader.orExpr(XPathReader.java:787)
	at org.jaxen.saxpath.base.XPathReader.expr(XPathReader.java:780)
	at org.jaxen.saxpath.base.XPathReader.parse(XPathReader.java:100)
	at org.jaxen.BaseXPath.<init>(BaseXPath.java:116)
	at org.jaxen.BaseXPath.<init>(BaseXPath.java:142)
	at org.apache.axiom.om.xpath.AXIOMXPath.<init>(AXIOMXPath.java:49)
	at org.apache.synapse.config.xml.SynapsePath.<init>(SynapsePath.java:53)
	at org.apache.synapse.util.xpath.SynapseXPath.<init>(SynapseXPath.java:139)
	at org.wso2.carbon.sequences.ui.util.ns.XPathFactory.createSynapseXPath(XPathFactory.java:66)
	at org.wso2.carbon.sequences.ui.util.ns.XPathFactory.createSynapseXPath(XPathFactory.java:80)
	at org.apache.jsp.property_002dmediator.update_002dmediator_jsp._jspService(update_002dmediator_jsp.java:131)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:603)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:542)
	at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:37)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor$RequestDispatcherAdaptor.include(ContextPathServletAdaptor.java:369)
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:897)
	at org.apache.jsp.sequences.mediator_002dupdate_002dajaxprocessor_jsp._jspService(mediator_002dupdate_002dajaxprocessor_jsp.java:102)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.URLBasedCachePreventionFilter.doFilter(URLBasedCachePreventionFilter.java:57)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.CSRFPreventionFilter.doFilter(CSRFPreventionFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.CRLFPreventionFilter.doFilter(CRLFPreventionFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
[2017-07-10 11:37:13,162] [EI-Core] ERROR - StandardWrapperValve Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception [An exception occurred processing JSP page /sequences/mediator-update-ajaxprocessor.jsp at line 26

23:     session.removeAttribute("mediator.position");
24:     if (updatePage != null) {
25: %>
26: <jsp:include page="<%= updatePage %>" flush="true"/>
27: <%}%>


Stacktrace:] with root cause
class org.jaxen.saxpath.XPathSyntaxException: fn:index-of ((15, 40, 25, 40, 10), 40): 16: Expected: )
	at org.jaxen.saxpath.base.XPathReader.createSyntaxException(XPathReader.java:1085)
	at org.jaxen.saxpath.base.XPathReader.match(XPathReader.java:1038)
	at org.jaxen.saxpath.base.XPathReader.filterExpr(XPathReader.java:274)
	at org.jaxen.saxpath.base.XPathReader.pathExpr(XPathReader.java:142)
	at org.jaxen.saxpath.base.XPathReader.unionExpr(XPathReader.java:1007)
	at org.jaxen.saxpath.base.XPathReader.unaryExpr(XPathReader.java:995)
	at org.jaxen.saxpath.base.XPathReader.multiplicativeExpr(XPathReader.java:943)
	at org.jaxen.saxpath.base.XPathReader.additiveExpr(XPathReader.java:913)
	at org.jaxen.saxpath.base.XPathReader.relationalExpr(XPathReader.java:860)
	at org.jaxen.saxpath.base.XPathReader.equalityExpr(XPathReader.java:829)
	at org.jaxen.saxpath.base.XPathReader.andExpr(XPathReader.java:809)
	at org.jaxen.saxpath.base.XPathReader.orExpr(XPathReader.java:787)
	at org.jaxen.saxpath.base.XPathReader.expr(XPathReader.java:780)
	at org.jaxen.saxpath.base.XPathReader.arguments(XPathReader.java:238)
	at org.jaxen.saxpath.base.XPathReader.functionCall(XPathReader.java:227)
	at org.jaxen.saxpath.base.XPathReader.filterExpr(XPathReader.java:279)
	at org.jaxen.saxpath.base.XPathReader.pathExpr(XPathReader.java:161)
	at org.jaxen.saxpath.base.XPathReader.unionExpr(XPathReader.java:1007)
	at org.jaxen.saxpath.base.XPathReader.unaryExpr(XPathReader.java:995)
	at org.jaxen.saxpath.base.XPathReader.multiplicativeExpr(XPathReader.java:943)
	at org.jaxen.saxpath.base.XPathReader.additiveExpr(XPathReader.java:913)
	at org.jaxen.saxpath.base.XPathReader.relationalExpr(XPathReader.java:860)
	at org.jaxen.saxpath.base.XPathReader.equalityExpr(XPathReader.java:829)
	at org.jaxen.saxpath.base.XPathReader.andExpr(XPathReader.java:809)
	at org.jaxen.saxpath.base.XPathReader.orExpr(XPathReader.java:787)
	at org.jaxen.saxpath.base.XPathReader.expr(XPathReader.java:780)
	at org.jaxen.saxpath.base.XPathReader.parse(XPathReader.java:100)
	at org.jaxen.BaseXPath.<init>(BaseXPath.java:116)
	at org.jaxen.BaseXPath.<init>(BaseXPath.java:142)
	at org.apache.axiom.om.xpath.AXIOMXPath.<init>(AXIOMXPath.java:49)
	at org.apache.synapse.config.xml.SynapsePath.<init>(SynapsePath.java:53)
	at org.apache.synapse.util.xpath.SynapseXPath.<init>(SynapseXPath.java:139)
	at org.wso2.carbon.sequences.ui.util.ns.XPathFactory.createSynapseXPath(XPathFactory.java:66)
	at org.wso2.carbon.sequences.ui.util.ns.XPathFactory.createSynapseXPath(XPathFactory.java:80)
	at org.apache.jsp.property_002dmediator.update_002dmediator_jsp._jspService(update_002dmediator_jsp.java:131)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:603)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:542)
	at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:37)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor$RequestDispatcherAdaptor.include(ContextPathServletAdaptor.java:369)
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:897)
	at org.apache.jsp.sequences.mediator_002dupdate_002dajaxprocessor_jsp._jspService(mediator_002dupdate_002dajaxprocessor_jsp.java:102)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.URLBasedCachePreventionFilter.doFilter(URLBasedCachePreventionFilter.java:57)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.CSRFPreventionFilter.doFilter(CSRFPreventionFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

```

**Comment by sashikamw** [comment]
Similar issue observed when using following functions with Dev Studio.

```
org.wso2.developerstudio.eclipse.gmf.esb.persistence.TransformerException: org.jaxen.XPathSyntaxException: Expected: )
	at org.wso2.developerstudio.eclipse.gmf.esb.internal.persistence.LogMediatorTransformer.transform(LogMediatorTransformer.java:58)
	at org.wso2.developerstudio.eclipse.gmf.esb.internal.persistence.AbstractEsbNodeTransformer.doTransform(AbstractEsbNodeTransformer.java:79)
	at org.wso2.developerstudio.eclipse.gmf.esb.internal.persistence.LogMediatorTransformer.transform(LogMediatorTransformer.java:56)
	at org.wso2.developerstudio.eclipse.gmf.esb.internal.persistence.AbstractEsbNodeTransformer.doTransform(AbstractEsbNodeTransformer.java:79)
	at org.wso2.developerstudio.eclipse.gmf.esb.internal.persistence.PropertyMediatorTransformer.transform(PropertyMediatorTransformer.java:63)
	at org.wso2.developerstudio.eclipse.gmf.esb.internal.persistence.AbstractEsbNodeTransformer.doTransform(AbstractEsbNodeTransformer.java:79)
	at org.wso2.developerstudio.eclipse.gmf.esb.internal.persistence.ProxyServiceTransformer.transformAsProxy(ProxyServiceTransformer.java:514)
	at org.wso2.developerstudio.eclipse.gmf.esb.internal.persistence.ProxyServiceTransformer.transform(ProxyServiceTransformer.java:113)
	at org.wso2.developerstudio.eclipse.gmf.esb.internal.persistence.DefaultEsbModelExporter.transformProxyService(DefaultEsbModelExporter.java:221)
	at org.wso2.developerstudio.eclipse.gmf.esb.internal.persistence.DefaultEsbModelExporter.designToSource(DefaultEsbModelExporter.java:443)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.part.EsbMultiPageEditor.updateAssociatedXMLFile(EsbMultiPageEditor.java:908)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.part.EsbMultiPageEditor.access$14(EsbMultiPageEditor.java:898)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.part.EsbMultiPageEditor$8.run(EsbMultiPageEditor.java:1040)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3794)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3433)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: org.jaxen.XPathSyntaxException: Expected: )
	at org.jaxen.BaseXPath.<init>(BaseXPath.java:121)
	at org.jaxen.BaseXPath.<init>(BaseXPath.java:142)
	at org.apache.axiom.om.xpath.AXIOMXPath.<init>(AXIOMXPath.java:49)
	at org.apache.synapse.config.xml.SynapsePath.<init>(SynapsePath.java:53)
	at org.apache.synapse.util.xpath.SynapseXPath.<init>(SynapseXPath.java:139)
	at org.wso2.developerstudio.eclipse.gmf.esb.internal.persistence.custom.CustomSynapsePathFactory.getSynapsePath(CustomSynapsePathFactory.java:96)
	at org.wso2.developerstudio.eclipse.gmf.esb.internal.persistence.LogMediatorTransformer.createLogMediator(LogMediatorTransformer.java:128)
	at org.wso2.developerstudio.eclipse.gmf.esb.internal.persistence.LogMediatorTransformer.transform(LogMediatorTransformer.java:54)
	... 38 more
Caused by: class org.jaxen.saxpath.XPathSyntaxException: fn:distinct-values((1, 2, 3, 1, 2)): 21: Expected: )
	at org.jaxen.saxpath.base.XPathReader.createSyntaxException(XPathReader.java:1085)
	at org.jaxen.saxpath.base.XPathReader.match(XPathReader.java:1038)
	at org.jaxen.saxpath.base.XPathReader.filterExpr(XPathReader.java:274)
	at org.jaxen.saxpath.base.XPathReader.pathExpr(XPathReader.java:142)
	at org.jaxen.saxpath.base.XPathReader.unionExpr(XPathReader.java:1007)
	at org.jaxen.saxpath.base.XPathReader.unaryExpr(XPathReader.java:995)
	at org.jaxen.saxpath.base.XPathReader.multiplicativeExpr(XPathReader.java:943)
	at org.jaxen.saxpath.base.XPathReader.additiveExpr(XPathReader.java:913)
	at org.jaxen.saxpath.base.XPathReader.relationalExpr(XPathReader.java:860)
	at org.jaxen.saxpath.base.XPathReader.equalityExpr(XPathReader.java:829)
	at org.jaxen.saxpath.base.XPathReader.andExpr(XPathReader.java:809)
	at org.jaxen.saxpath.base.XPathReader.orExpr(XPathReader.java:787)
	at org.jaxen.saxpath.base.XPathReader.expr(XPathReader.java:780)
	at org.jaxen.saxpath.base.XPathReader.arguments(XPathReader.java:238)
	at org.jaxen.saxpath.base.XPathReader.functionCall(XPathReader.java:227)
	at org.jaxen.saxpath.base.XPathReader.filterExpr(XPathReader.java:279)
	at org.jaxen.saxpath.base.XPathReader.pathExpr(XPathReader.java:161)
	at org.jaxen.saxpath.base.XPathReader.unionExpr(XPathReader.java:1007)
	at org.jaxen.saxpath.base.XPathReader.unaryExpr(XPathReader.java:995)
	at org.jaxen.saxpath.base.XPathReader.multiplicativeExpr(XPathReader.java:943)
	at org.jaxen.saxpath.base.XPathReader.additiveExpr(XPathReader.java:913)
	at org.jaxen.saxpath.base.XPathReader.relationalExpr(XPathReader.java:860)
	at org.jaxen.saxpath.base.XPathReader.equalityExpr(XPathReader.java:829)
	at org.jaxen.saxpath.base.XPathReader.andExpr(XPathReader.java:809)
	at org.jaxen.saxpath.base.XPathReader.orExpr(XPathReader.java:787)
	at org.jaxen.saxpath.base.XPathReader.expr(XPathReader.java:780)
	at org.jaxen.saxpath.base.XPathReader.parse(XPathReader.java:100)
	at org.jaxen.BaseXPath.<init>(BaseXPath.java:116)
	... 45 mor
```
