### ISSUE TITLE
[EI620] Xpath error functions failed

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#725]
**Environment**
OS - rhel-6.6.x86_64 , rhel-7.0.x86_64
JAVA - JDK 1.8
DB - Oracle 12c
Pack - EI620 Snapshot

**Steps to reproduce the issue**
1. Create a proxy using [error functions](https://www.w3.org/TR/xpath-functions/#func-error) as below

```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="xpath20errorfunctions"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http,https">
   <target>
      <inSequence>
         <log>
            <property xmlns:fn="http://www.w3.org/2005/xpath-functions"
                      expression="fn:error()"
                      name="error = = ="/>
         </log>
      </inSequence>
   </target>
   <description/>
</proxy>
```
After invoking the proxy following exception observed.
```
[2017-07-10 17:50:14,048] [EI-Core] ERROR - SynapseXPath Evaluation of the XPath expression fn:error() resulted in an error
; Line#: 1; Column#: -1
net.sf.saxon.trans.XPathException: Error signalled by application call on error()
	at net.sf.saxon.functions.Error.error(Error.java:98)
	at net.sf.saxon.functions.Error.evaluateItem(Error.java:55)
	at net.sf.saxon.expr.Expression.iterate(Expression.java:429)
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:326)
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:389)
	at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:533)
	at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:367)
	at org.apache.synapse.mediators.MediatorProperty.getEvaluatedExpression(MediatorProperty.java:138)
	at org.apache.synapse.mediators.builtin.LogMediator.setCustomProperties(LogMediator.java:223)
	at org.apache.synapse.mediators.builtin.LogMediator.getSimpleLogMessage(LogMediator.java:168)
	at org.apache.synapse.mediators.builtin.LogMediator.getLogMessage(LogMediator.java:134)
	at org.apache.synapse.mediators.builtin.LogMediator.mediate(LogMediator.java:101)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:224)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:407)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
--------------- linked to ------------------
javax.xml.xpath.XPathExpressionException: net.sf.saxon.trans.XPathException: Error signalled by application call on error()
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:371)
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:389)
	at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:533)
	at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:367)
	at org.apache.synapse.mediators.MediatorProperty.getEvaluatedExpression(MediatorProperty.java:138)
	at org.apache.synapse.mediators.builtin.LogMediator.setCustomProperties(LogMediator.java:223)
	at org.apache.synapse.mediators.builtin.LogMediator.getSimpleLogMessage(LogMediator.java:168)
	at org.apache.synapse.mediators.builtin.LogMediator.getLogMessage(LogMediator.java:134)
	at org.apache.synapse.mediators.builtin.LogMediator.mediate(LogMediator.java:101)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:224)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:407)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: net.sf.saxon.trans.XPathException: Error signalled by application call on error()
	at net.sf.saxon.functions.Error.error(Error.java:98)
	at net.sf.saxon.functions.Error.evaluateItem(Error.java:55)
	at net.sf.saxon.expr.Expression.iterate(Expression.java:429)
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:326)
	... 19 more
[2017-07-10 17:50:14,060] [EI-Core]  INFO - LogMediator To: /services/xpath20errorfunctions.xpath20errorfunctionsHttpSoap12Endpoint, WSAction: urn:mediate, SOAPAction: urn:mediate, MessageID: urn:uuid:6c3e7925-dc55-453d-ada0-0950e6593f40, Direction: request, MESSAGE = Executing default 'fault' sequence, ERROR_CODE = 0, ERROR_MESSAGE = Evaluation of the XPath expression fn:error() resulted in an error, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Body/></soapenv:Envelope>
```

2. Create the following proxy
```

<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="xpath20errorfunctions"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http,https">
   <target>
      <inSequence>
         <log>
            <property xmlns:fn="http://www.w3.org/2005/xpath-functions"
                      expression="fn:error(fn:QName('http://www.example.com/HR', 'myerr:toohighsal'), 'Does not apply because salary is too high')"
                      name="error = = ="/>
         </log>
      </inSequence>
   </target>
   <description/>
</proxy>
```
After invoking the proxy, following exception observed.
                  
```
[2017-07-10 17:51:44,941] [EI-Core] ERROR - SynapseXPath Evaluation of the XPath expression fn:error(fn:QName('http://www.example.com/HR', 'myerr:toohighsal'), 'Does not apply because salary is too high') resulted in an error
; Line#: 1; Column#: -1
net.sf.saxon.trans.XPathException: Does not apply because salary is too high
	at net.sf.saxon.functions.Error.error(Error.java:98)
	at net.sf.saxon.functions.Error.evaluateItem(Error.java:57)
	at net.sf.saxon.expr.Expression.iterate(Expression.java:429)
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:326)
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:389)
	at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:533)
	at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:367)
	at org.apache.synapse.mediators.MediatorProperty.getEvaluatedExpression(MediatorProperty.java:138)
	at org.apache.synapse.mediators.builtin.LogMediator.setCustomProperties(LogMediator.java:223)
	at org.apache.synapse.mediators.builtin.LogMediator.getSimpleLogMessage(LogMediator.java:168)
	at org.apache.synapse.mediators.builtin.LogMediator.getLogMessage(LogMediator.java:134)
	at org.apache.synapse.mediators.builtin.LogMediator.mediate(LogMediator.java:101)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:224)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:407)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
--------------- linked to ------------------
javax.xml.xpath.XPathExpressionException: net.sf.saxon.trans.XPathException: Does not apply because salary is too high
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:371)
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:389)
	at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:533)
	at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:367)
	at org.apache.synapse.mediators.MediatorProperty.getEvaluatedExpression(MediatorProperty.java:138)
	at org.apache.synapse.mediators.builtin.LogMediator.setCustomProperties(LogMediator.java:223)
	at org.apache.synapse.mediators.builtin.LogMediator.getSimpleLogMessage(LogMediator.java:168)
	at org.apache.synapse.mediators.builtin.LogMediator.getLogMessage(LogMediator.java:134)
	at org.apache.synapse.mediators.builtin.LogMediator.mediate(LogMediator.java:101)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:224)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:407)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: net.sf.saxon.trans.XPathException: Does not apply because salary is too high
	at net.sf.saxon.functions.Error.error(Error.java:98)
	at net.sf.saxon.functions.Error.evaluateItem(Error.java:57)
	at net.sf.saxon.expr.Expression.iterate(Expression.java:429)
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:326)
	... 19 more
```

**Comment by erandacr** [comment]
In Saxon, fn:error() function is written in a way that, when it gets called it throws an exception. [1] 
This is one of the use case,[2] 
I'm not sure whether we have to do anything extra as its expected behavior is to throw the exception

[1]. http://grepcode.com/file/repo1.maven.org/maven2/net.sf.saxon/Saxon-HE/9.5.1-8/net/sf/saxon/functions/Error.java?av=f#134
[2]. http://flylib.com/books/en/1.256.1.85/1/

**Comment by a5anka** [comment]
Closing the issue according to the previous comment.
