### ISSUE TITLE
[EI620]  Exception when editing HTTP/HTTPS inbound endpoints in windows OS

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#734]
**Environment**
Pack - EI 6.2.0 Snapshot
DB - h2
JDK - 1.8.0_101
OS - Windows Server 2012 R2 (6.3)

**Steps to reproduce the issue**
1. Create Inbound HTTP or HTTPS inbound endpoint without providing the sequence
2. Edit the inbound endpoint by selecting a sequence

**Observations**
1. Following exception observed

```
[2017-07-11 09:33:43,140] []  INFO - DependencyTracker Inbound Endpoint : abc was added to the Synapse configuration successfully
[2017-07-11 09:33:43,156] []  INFO - InboundEndpoint Initializing Inbound Endpoint: abc
[2017-07-11 09:33:43,171] []  INFO - PassThroughListeningIOReactorManager Pass-through abc Listener started on 0:0:0:0:0:0:0:0:2345
[2017-07-11 09:34:43,171] []  INFO - DependencyTracker Sequence : abcSequence was added to the Synapse configuration successfully
[2017-07-11 09:35:11,187] []  INFO - InboundEndpoint Destroying Inbound Endpoint: abc
[2017-07-11 09:35:11,202] []  INFO - PassThroughListeningIOReactorManager Closing Endpoint Listener for port 2345
[2017-07-11 09:35:11,202] []  INFO - PassThroughListeningIOReactorManager Successfully closed Endpoint Listener for port 2345
[2017-07-11 09:35:11,202] []  INFO - DependencyTracker Inbound Endpoint : abc was removed from the Synapse configuration successfully
[2017-07-11 09:35:11,202] []  INFO - DependencyTracker Inbound Endpoint : abc was added to the Synapse configuration successfully
[2017-07-11 09:35:11,202] []  INFO - InboundEndpoint Initializing Inbound Endpoint: abc
[2017-07-11 09:35:11,218] []  WARN - InboundHttpListener Port 2345 used by inbound endpoint abc is already used by another application hence undeploying inbound endpoint
[2017-07-11 09:35:11,218] [] ERROR - InboundEndpoint Error initializing inbound endpoint abc
[2017-07-11 09:35:11,218] []  INFO - InboundEndpoint Destroying Inbound Endpoint: abc
[2017-07-11 09:35:11,218] []  INFO - HTTPEndpointManager Listener Endpoint is not started
[2017-07-11 09:35:11,218] []  INFO - DependencyTracker Inbound Endpoint : abc was removed from the Synapse configuration successfully
[2017-07-11 09:35:11,218] []  INFO - DependencyTracker Inbound Endpoint : abc was added to the Synapse configuration successfully
[2017-07-11 09:35:11,234] []  INFO - InboundEndpoint Initializing Inbound Endpoint: abc
[2017-07-11 09:35:11,234] []  WARN - InboundHttpListener Port 2345 used by inbound endpoint abc is already used by another application hence undeploying inbound endpoint
[2017-07-11 09:35:11,234] [] ERROR - InboundEndpoint Error initializing inbound endpoint abc
[2017-07-11 09:35:11,234] [] ERROR - RPCInOnlyMessageReceiver Error initializing inbound endpoint abc
org.apache.synapse.SynapseException: Error initializing inbound endpoint abc
        at org.apache.synapse.inbound.InboundEndpoint.init(InboundEndpoint.java:83)
        at org.wso2.carbon.inbound.CarbonInboundManagementService.updateInboundEndpoint(CarbonInboundManagementService.java:232)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212)
        at org.apache.axis2.rpc.receivers.RPCInOnlyMessageReceiver.invokeBusinessLogic(RPCInOnlyMessageReceiver.java:66)
        at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
        at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:169)
        at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:82)
        at org.wso2.carbon.core.transports.local.CarbonLocalTransportSender.finalizeSendWithToAddress(CarbonLocalTransportSender.java:45)
        at org.apache.axis2.transport.local.LocalTransportSender.invoke(LocalTransportSender.java:77)
        at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
        at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:430)
        at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
        at org.wso2.carbon.inbound.stub.InboundAdminStub.updateInboundEndpoint(InboundAdminStub.java:1708)
        at org.wso2.carbon.inbound.ui.internal.InboundManagementClient.updteInboundEndpoint(InboundManagementClient.java:333)
        at org.apache.jsp.inbound.updateInbound_002dajaxprocessor_jsp._jspService(updateInbound_002dajaxprocessor_jsp.java:247)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
        at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:410)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
        at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.forward(RequestDispatcherAdaptor.java:30)
        at org.wso2.carbon.redirector.servlet.ui.filters.AllPagesFilter.doFilter(AllPagesFilter.java:156)
        at org.eclipse.equinox.http.helper.FilterServletAdaptor.service(FilterServletAdaptor.java:37)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.wso2.carbon.ui.filters.cache.URLBasedCachePreventionFilter.doFilter(URLBasedCachePreventionFilter.java:57)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.wso2.carbon.ui.filters.CSRFPreventionFilter.doFilter(CSRFPreventionFilter.java:88)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.wso2.carbon.ui.filters.CRLFPreventionFilter.doFilter(CRLFPreventionFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
        at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:63)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.synapse.SynapseException: Port 2345 used by inbound endpoint abc is already used by another application.
        at org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpListener.init(InboundHttpListener.java:64)
        at org.apache.synapse.inbound.InboundEndpoint.init(InboundEndpoint.java:79)
        ... 98 more
[2017-07-11 09:35:11,312] [] ERROR - InboundManagementClient org.apache.axis2.AxisFault: Error initializing inbound endpoint abc
```

2. Blank page appeared in the UI

![errorpage](https://user-images.githubusercontent.com/14962228/28062653-3cc11a74-664c-11e7-9523-8d2cf8bcf6b6.png)

**Comment by milindaperera** [comment]
Fixed in https://github.com/wso2/product-ei/issues/1730
