### ISSUE TITLE
 500 error when log in to Analytics dashboard via given URL

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#760]
**Environment**
OS - ubuntu 15.10
JAVA - JDK 1.8
DB - mysql 5.6
Pack - EI620 M1

**Pre Requisites**
User store is shared among EI profile and Analytics profile

**Steps to reproduce the issue**
1. Create a tenant user
2. Create an artefact (ex:proxy, endpoint etc.)
3. Enable statistics and Tracing
4. Log in to [Analytics dashboard](https://docs.wso2.com/display/ESB500/Monitoring+WSO2+ESB+with+WSO2+Analytics+in+a+Multi-tenant+Environment) using tenant user
https://<ANALYTICS_HOST>:<ANALYTICS_PORT>/portal/dashboards/esb-analytics/

**Observation**
1. 500 Error page appeared with the following exception

```
[2017-07-17 15:20:11,378] [EI-Analytics] ERROR {org.jaggeryjs.jaggery.core.manager.WebAppManager} -  org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "menu" from null (/portal/controllers/dashboards.jag#74) (/portal/routers/pages.jag#89) (/portal/routers/tenant.jag#89)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "menu" from null (/portal/controllers/dashboards.jag#74) (/portal/routers/pages.jag#89) (/portal/routers/tenant.jag#89)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.event.receiver.core.internal.tenantmgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:48)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "menu" from null (/portal/controllers/dashboards.jag#74) (/portal/routers/pages.jag#89) (/portal/routers/tenant.jag#89)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.portal.routers.c0._c_anonymous_1(/portal/routers/tenant.jag:89)
	at org.jaggeryjs.rhino.portal.routers.c0.call(/portal/routers/tenant.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.jaggeryjs.rhino.portal.routers.c0._c_script_0(/portal/routers/tenant.jag:29)
	at org.jaggeryjs.rhino.portal.routers.c0.call(/portal/routers/tenant.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.portal.routers.c0.call(/portal/routers/tenant.jag)
	at org.jaggeryjs.rhino.portal.routers.c0.exec(/portal/routers/tenant.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	... 45 more
Caused by: org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "menu" from null (/portal/controllers/dashboards.jag#74) (/portal/routers/pages.jag#89)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:309)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:149)
	at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 57 more
Caused by: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "menu" from null (/portal/controllers/dashboards.jag#74) (/portal/routers/pages.jag#89)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.portal.routers.c1._c_anonymous_1(/portal/routers/pages.jag:89)
	at org.jaggeryjs.rhino.portal.routers.c1.call(/portal/routers/pages.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.jaggeryjs.rhino.portal.routers.c1._c_script_0(/portal/routers/pages.jag:25)
	at org.jaggeryjs.rhino.portal.routers.c1.call(/portal/routers/pages.jag)
	at org.jaggeryjs.rhino.portal.routers.c1.exec(/portal/routers/pages.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	... 64 more
Caused by: org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "menu" from null (/portal/controllers/dashboards.jag#74)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:309)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:149)
	at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 73 more
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "menu" from null (/portal/controllers/dashboards.jag#74)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3693)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3712)
	at org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java:3725)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1483)
	at org.jaggeryjs.rhino.portal.controllers.c2._c_anonymous_3(/portal/controllers/dashboards.jag:74)
	at org.jaggeryjs.rhino.portal.controllers.c2.call(/portal/controllers/dashboards.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.jaggeryjs.rhino.<carbon>.scripts.server.c0._c_anonymous_5(<carbon>/scripts/server/tenant.js:62)
	at org.jaggeryjs.rhino.<carbon>.scripts.server.c0.call(<carbon>/scripts/server/tenant.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.portal.modules.c1._c_anonymous_3(/portal/modules/utils.js:40)
	at org.jaggeryjs.rhino.portal.modules.c1.call(/portal/modules/utils.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.portal.controllers.c2._c_anonymous_1(/portal/controllers/dashboards.jag:72)
	at org.jaggeryjs.rhino.portal.controllers.c2.call(/portal/controllers/dashboards.jag)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.jaggeryjs.rhino.portal.controllers.c2._c_script_0(/portal/controllers/dashboards.jag:21)
	at org.jaggeryjs.rhino.portal.controllers.c2.call(/portal/controllers/dashboards.jag)
	at org.jaggeryjs.rhino.portal.controllers.c2.exec(/portal/controllers/dashboards.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	... 80 more
[2017-07-17 15:20:30,092] [EI-Analytics] admin@tenant.com [1] [EI] INFO {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} -  'admin@tenant.com [1]' logged in at [2017-07-17 15:20:30,092+0530]
```

**Comment by sajithshn** [comment]
Tenants have not supported in SP based analytics. Therefore this is not applicable from EI - 6.4.0 onwards.
