### ISSUE TITLE
[6.2.0]jms message store cannot be deployed via management console and or capp

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#775]
6.2.0 m1 pack, fedora 23, JDK 1.8

Via management console
===================
1. Enable jms transport
2. Add JMS Message Store
3. Try to save or switch to source view.
Error will come in the UI : Message Store cannot be added : Caused by -unknown

Error In the backend 
------------------------------
```
[2017-07-18 15:54:00,958] [EI-Core]  INFO - MessageStoreFactory Successfully added Message Store configuration of : [JMSMS].
[2017-07-18 15:54:00,960] [EI-Core] ERROR - RPCInOnlyMessageReceiver Exception occurred while trying to invoke service method addMessageStore
java.lang.NullPointerException
[2017-07-18 15:54:00,961] [EI-Core] ERROR - MessageStoreAdminServiceClient Error Executing MessageStoreAdminServiceClientunknown
org.apache.axis2.AxisFault: unknown
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:445)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.message.store.stub.MessageStoreAdminServiceStub.addMessageStore(MessageStoreAdminServiceStub.java:2735)
	at org.wso2.carbon.message.store.ui.MessageStoreAdminServiceClient.addMessageStore(MessageStoreAdminServiceClient.java:76)
	at org.apache.jsp.message_005fstore.ServiceCaller_jsp._jspService(ServiceCaller_jsp.java:303)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:603)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:542)
	at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:37)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor$RequestDispatcherAdaptor.include(ContextPathServletAdaptor.java:369)
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:897)
	at org.apache.jasper.runtime.PageContextImpl.doInclude(PageContextImpl.java:688)
	at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:682)
	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tiles.jsp.context.JspUtil.doInclude(JspUtil.java:87)
	at org.apache.tiles.jsp.context.JspTilesRequestContext.include(JspTilesRequestContext.java:88)
	at org.apache.tiles.jsp.context.JspTilesRequestContext.dispatch(JspTilesRequestContext.java:82)
	at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:465)
	at org.apache.tiles.jsp.taglib.InsertAttributeTag.render(InsertAttributeTag.java:140)
	at org.apache.tiles.jsp.taglib.InsertAttributeTag.render(InsertAttributeTag.java:117)
	at org.apache.tiles.jsp.taglib.RenderTagSupport.execute(RenderTagSupport.java:171)
	at org.apache.tiles.jsp.taglib.RoleSecurityTagSupport.doEndTag(RoleSecurityTagSupport.java:75)
	at org.apache.tiles.jsp.taglib.ContainerTagSupport.doEndTag(ContainerTagSupport.java:80)
	at org.apache.jsp.admin.layout.template_jsp._jspx_meth_tiles_005finsertAttribute_005f7(template_jsp.java:749)
	at org.apache.jsp.admin.layout.template_jsp._jspService(template_jsp.java:385)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:410)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.forward(RequestDispatcherAdaptor.java:30)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor$RequestDispatcherAdaptor.forward(ContextPathServletAdaptor.java:362)
	at org.apache.tiles.servlet.context.ServletTilesRequestContext.forward(ServletTilesRequestContext.java:198)
	at org.apache.tiles.servlet.context.ServletTilesRequestContext.dispatch(ServletTilesRequestContext.java:185)
	at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:419)
	at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:370)
	at org.wso2.carbon.ui.action.ActionHelper.render(ActionHelper.java:52)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:101)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.URLBasedCachePreventionFilter.doFilter(URLBasedCachePreventionFilter.java:57)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.CSRFPreventionFilter.doFilter(CSRFPreventionFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.CRLFPreventionFilter.doFilter(CRLFPreventionFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1719)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

Via capp
=======

```

[2017-07-18 15:55:08,195] [EI-Core]  INFO - CappAxis2Deployer Undeploying Faulty Carbon Application On : /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/repository/deployment/server/carbonapps/cappjms_1.0.0.car
[2017-07-18 15:55:08,196] [EI-Core]  INFO - ApplicationManager Deploying Carbon Application : cappjms_1.0.0.car...
[2017-07-18 15:55:08,278] [EI-Core]  INFO - LibraryArtifactDeployer Synapse Library named '{org.wso2.carbon.connector}salesforce' has been deployed from file : /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/wso2/tmp/carbonapps/-1234/1500373508196cappjms_1.0.0.car/salesforce-connector_2.0.1/salesforce-connector-2.0.1.zip
[2017-07-18 15:55:08,279] [EI-Core]  INFO - SynapseImportFactory Successfully created Synapse Import: salesforce
[2017-07-18 15:55:08,367] [EI-Core]  INFO - DependencyTracker Local entry : MySFConfig was added to the Synapse configuration successfully - [ Deployed From Artifact Container: cappjms ] 
[2017-07-18 15:55:08,367] [EI-Core]  INFO - LocalEntryDeployer LocalEntry named 'MySFConfig' has been deployed from file : /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/wso2/tmp/carbonapps/-1234/1500373508196cappjms_1.0.0.car/MySFConfig_1.0.0/MySFConfig-1.0.0.xml
[2017-07-18 15:55:08,368] [EI-Core]  INFO - DependencyTracker Local entry : stockquoteScript was added to the Synapse configuration successfully - [ Deployed From Artifact Container: cappjms ] 
[2017-07-18 15:55:08,368] [EI-Core]  INFO - LocalEntryDeployer LocalEntry named 'stockquoteScript' has been deployed from file : /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/wso2/tmp/carbonapps/-1234/1500373508196cappjms_1.0.0.car/stockquoteScript_1.0.0/stockquoteScript-1.0.0.xml
[2017-07-18 15:55:08,368] [EI-Core]  INFO - MessageStoreFactory Successfully added Message Store configuration of : [JMSMS].
[2017-07-18 15:55:08,368] [EI-Core] ERROR - MessageStoreDeployer Message Store Deployment from the file : /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/wso2/tmp/carbonapps/-1234/1500373508196cappjms_1.0.0.car/JMSMS_1.0.0/JMSMS-1.0.0.xml : Failed.
java.lang.NullPointerException
[2017-07-18 15:55:08,368] [EI-Core] ERROR - AbstractSynapseArtifactDeployer Deployment of the Synapse Artifact from file : /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/wso2/tmp/carbonapps/-1234/1500373508196cappjms_1.0.0.car/JMSMS_1.0.0/JMSMS-1.0.0.xml : Failed!
org.apache.synapse.deployers.SynapseArtifactDeploymentException: Message Store Deployment from the file : /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/wso2/tmp/carbonapps/-1234/1500373508196cappjms_1.0.0.car/JMSMS_1.0.0/JMSMS-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.handleSynapseArtifactDeploymentError(AbstractSynapseArtifactDeployer.java:474)
	at org.apache.synapse.deployers.MessageStoreDeployer.deploySynapseArtifact(MessageStoreDeployer.java:76)
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:194)
	at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifacts(SynapseAppDeployer.java:131)
	at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:272)
	at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:72)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
[2017-07-18 15:55:08,369] [EI-Core]  INFO - AbstractSynapseArtifactDeployer The file has been backed up into : NO_BACKUP_ON_WORKER.INFO
[2017-07-18 15:55:08,369] [EI-Core] ERROR - AbstractSynapseArtifactDeployer Deployment of synapse artifact failed. Error reading /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/wso2/tmp/carbonapps/-1234/1500373508196cappjms_1.0.0.car/JMSMS_1.0.0/JMSMS-1.0.0.xml : Message Store Deployment from the file : /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/wso2/tmp/carbonapps/-1234/1500373508196cappjms_1.0.0.car/JMSMS_1.0.0/JMSMS-1.0.0.xml : Failed.
org.apache.axis2.deployment.DeploymentException: Message Store Deployment from the file : /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/wso2/tmp/carbonapps/-1234/1500373508196cappjms_1.0.0.car/JMSMS_1.0.0/JMSMS-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:201)
	at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifacts(SynapseAppDeployer.java:131)
	at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:272)
	at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:72)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.synapse.deployers.SynapseArtifactDeploymentException: Message Store Deployment from the file : /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/wso2/tmp/carbonapps/-1234/1500373508196cappjms_1.0.0.car/JMSMS_1.0.0/JMSMS-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.handleSynapseArtifactDeploymentError(AbstractSynapseArtifactDeployer.java:474)
	at org.apache.synapse.deployers.MessageStoreDeployer.deploySynapseArtifact(MessageStoreDeployer.java:76)
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:194)
	... 20 more
Caused by: java.lang.NullPointerException
[2017-07-18 15:55:08,370] [EI-Core] ERROR - ApplicationManager Error occurred while deploying Carbon Application
org.apache.axis2.deployment.DeploymentException: Message Store Deployment from the file : /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/wso2/tmp/carbonapps/-1234/1500373508196cappjms_1.0.0.car/JMSMS_1.0.0/JMSMS-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:213)
	at org.wso2.carbon.application.deployer.synapse.SynapseAppDeployer.deployArtifacts(SynapseAppDeployer.java:131)
	at org.wso2.carbon.application.deployer.internal.ApplicationManager.deployCarbonApp(ApplicationManager.java:272)
	at org.wso2.carbon.application.deployer.CappAxis2Deployer.deploy(CappAxis2Deployer.java:72)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.deployment.DeploymentException: Message Store Deployment from the file : /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/wso2/tmp/carbonapps/-1234/1500373508196cappjms_1.0.0.car/JMSMS_1.0.0/JMSMS-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:201)
	... 20 more
Caused by: org.apache.synapse.deployers.SynapseArtifactDeploymentException: Message Store Deployment from the file : /home/ushani/WSO2_WORK/Products/EI/6.2.0/m1/wso2ei-6.2.0-m1/wso2/tmp/carbonapps/-1234/1500373508196cappjms_1.0.0.car/JMSMS_1.0.0/JMSMS-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.handleSynapseArtifactDeploymentError(AbstractSynapseArtifactDeployer.java:474)
	at org.apache.synapse.deployers.MessageStoreDeployer.deploySynapseArtifact(MessageStoreDeployer.java:76)
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:194)
	... 20 more
Caused by: java.lang.NullPointerException
[2017-07-18 15:55:08,371] [EI-Core]  INFO - ApplicationManager Reverting successfully deployed artifcats in this CApp : cappjms_1.0.0
[2017-07-18 15:55:08,446] [EI-Core]  INFO - DependencyTracker Local entry : MySFConfig was removed from the Synapse configuration successfully - [ Deployed From Artifact Container: cappjms ] 
[2017-07-18 15:55:08,446] [EI-Core]  INFO - LocalEntryDeployer LocalEntry named 'MySFConfig' has been undeployed
[2017-07-18 15:55:08,446] [EI-Core]  INFO - DependencyTracker Local entry : stockquoteScript was removed from the Synapse configuration successfully - [ Deployed From Artifact Container: cappjms ] 
[2017-07-18 15:55:08,446] [EI-Core]  INFO - LocalEntryDeployer LocalEntry named 'stockquoteScript' has been undeployed
[2017-07-18 15:55:08,447] [EI-Core]  INFO - LibraryArtifactDeployer Synapse Library named '{org.wso2.carbon.connector}salesforce' has been undeployed
```

You cannot even switch to source view.
![screenshot from 2017-07-18 15-55-55](https://user-images.githubusercontent.com/12966170/28312696-b0b95f38-6bd1-11e7-8122-8b9caee36729.png)

**Comment by vinok88** [comment]
This is already fixed in https://github.com/wso2/wso2-synapse/pull/775. Please verify in a newer build pack and close the issue.
