### ISSUE TITLE
[BPS] Backend gives an error when uploading the user signup BPEL for APIM workflows

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#78]
**Enviornment**
OS-Ubuntu 14.04
JAVA-jdk 1.7.0_51
Browser-chrome 51.0, firefox 47.0
wso2ei-6.0.0-SNAPSHOT 27th of jan pack

**Steps**

1. WSO2 API Manager and start the server 
2. Copy <AM_HOME>/business-process/epr folder into the wso2ei-6.0.0-SNAPSHOT/wso2/business-process/conf folder and start the server.
3. Log into the BPS management Console
4. Deploy  Business Process zip file from the <AM_Home>/business-process/user-signup .

**Error**
BPEL process uploaded successfully but following error can be seen in the back end

`[2017-01-27 15:18:02,957] [EI-Business-Process] ERROR {org.apache.ode.bpel.engine.NStateLatch} -  Latch error, was releasing for state 1 but actually in -1
java.lang.Exception
	at org.apache.ode.bpel.engine.NStateLatch.release(NStateLatch.java:113)
	at org.apache.ode.bpel.engine.BpelProcess.hydrate(BpelProcess.java:727)
	at org.apache.ode.bpel.engine.BpelServerImpl.register(BpelServerImpl.java:337)
	at org.wso2.carbon.bpel.core.ode.integration.BPELServerImpl$ProcessStoreListenerImpl.onProcessStoreEvent(BPELServerImpl.java:804)
	at org.wso2.carbon.bpel.core.ode.integration.store.ProcessStoreImpl.fireEvent(ProcessStoreImpl.java:745)
	at org.wso2.carbon.bpel.core.ode.integration.store.ProcessStoreImpl.fireStateChange(ProcessStoreImpl.java:725)
	at org.wso2.carbon.bpel.core.ode.integration.store.ProcessStoreImpl.onBPELPackageDeployment(ProcessStoreImpl.java:397)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.deployBPELPackageInODE(TenantProcessStoreImpl.java:717)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.deploy(TenantProcessStoreImpl.java:253)
	at org.wso2.carbon.bpel.deployer.BPELDeployer.deploy(BPELDeployer.java:107)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

[2017-01-27 15:18:02,958] [EI-Business-Process] ERROR {org.apache.ode.bpel.engine.BpelServerImpl} -  org.apache.ode.bpel.iapi.ContextException: Error creating external service! name:{http://org.wso2.carbon/claims/}UserApprovalService, port:UserApprovalPort
[2017-01-27 15:18:03,006] [EI-Business-Process] ERROR {org.wso2.carbon.bpel.deployer.BPELDeployer} -  Error deploying BPEL package: UserSignupApprovalProcess_1.0.0.zip
org.apache.ode.bpel.iapi.BpelEngineException: org.apache.ode.bpel.iapi.ContextException: Error creating external service! name:{http://org.wso2.carbon/claims/}UserApprovalService, port:UserApprovalPort
	at org.apache.ode.bpel.engine.BpelServerImpl.register(BpelServerImpl.java:346)
	at org.wso2.carbon.bpel.core.ode.integration.BPELServerImpl$ProcessStoreListenerImpl.onProcessStoreEvent(BPELServerImpl.java:804)
	at org.wso2.carbon.bpel.core.ode.integration.store.ProcessStoreImpl.fireEvent(ProcessStoreImpl.java:745)
	at org.wso2.carbon.bpel.core.ode.integration.store.ProcessStoreImpl.fireStateChange(ProcessStoreImpl.java:725)
	at org.wso2.carbon.bpel.core.ode.integration.store.ProcessStoreImpl.onBPELPackageDeployment(ProcessStoreImpl.java:397)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.deployBPELPackageInODE(TenantProcessStoreImpl.java:717)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.deploy(TenantProcessStoreImpl.java:253)
	at org.wso2.carbon.bpel.deployer.BPELDeployer.deploy(BPELDeployer.java:107)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.apache.ode.bpel.iapi.ContextException: Error creating external service! name:{http://org.wso2.carbon/claims/}UserApprovalService, port:UserApprovalPort
	at org.wso2.carbon.bpel.core.ode.integration.BPELBindingContextImpl.createPartnerService(BPELBindingContextImpl.java:179)
	at org.wso2.carbon.bpel.core.ode.integration.BPELBindingContextImpl.createPartnerRoleChannel(BPELBindingContextImpl.java:137)
	at org.apache.ode.bpel.engine.BpelProcess$HydrationLatch.doHydrate(BpelProcess.java:923)
	at org.apache.ode.bpel.engine.BpelProcess$HydrationLatch.access$100(BpelProcess.java:812)
	at org.apache.ode.bpel.engine.BpelProcess$HydrationLatch$2.run(BpelProcess.java:822)
	at org.apache.ode.bpel.engine.NStateLatch.latch(NStateLatch.java:92)
	at org.apache.ode.bpel.engine.BpelProcess.hydrate(BpelProcess.java:723)
	at org.apache.ode.bpel.engine.BpelServerImpl.register(BpelServerImpl.java:337)
	... 24 more
Caused by: org.apache.axis2.AxisFault: Could not create endpoint from file path:/home/chalitha/RD/EI/27-sanpshot/wso2ei-6.0.0-SNAPSHOT/wso2/business-process/repository/bpel/-1234/UserSignupApprovalProcess_1.0.0-1/./../../../../repository/conf/epr/UserSignupService.epr
	at org.wso2.carbon.unifiedendpoint.core.UnifiedEndpointFactory.createVirtualEndpointFromFilePath(UnifiedEndpointFactory.java:60)
	at org.wso2.carbon.bpel.common.config.EndpointConfiguration.getUnifiedEndpoint(EndpointConfiguration.java:140)
	at org.wso2.carbon.bpel.core.ode.integration.PartnerService.initUEP(PartnerService.java:146)
	at org.wso2.carbon.bpel.core.ode.integration.PartnerService.<init>(PartnerService.java:125)
	at org.wso2.carbon.bpel.core.ode.integration.BPELBindingContextImpl.createPartnerService(BPELBindingContextImpl.java:174)
	... 31 more
Caused by: org.apache.axis2.deployment.DeploymentException: EPR file: /home/chalitha/RD/EI/27-sanpshot/wso2ei-6.0.0-SNAPSHOT/wso2/business-process/repository/bpel/-1234/UserSignupApprovalProcess_1.0.0-1/./../../../../repository/conf/epr/UserSignupService.epr not found.
	at org.wso2.carbon.unifiedendpoint.core.UnifiedEndpointFactory.getOmFromFile(UnifiedEndpointFactory.java:68)
	at org.wso2.carbon.unifiedendpoint.core.UnifiedEndpointFactory.createVirtualEndpointFromFilePath(UnifiedEndpointFactory.java:56)
	... 35 more
`

**Comment by himasha** [comment]
This is because bpels available in API Manager ( UserSignupApprovalProcess.zip etc) deploy.xml file refers to paths such as 'repository/conf' like below.

<endpoint xmlns="http://wso2.org/bps/bpel/endpoint/config" endpointReference="./../../../../repository/conf/epr/UserSignupService.epr"></endpoint>

Therefore those API Manager zips need to updated to be used in EI.
