### ISSUE TITLE
[Tenant] Failed to send the batch request with JSON payload 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#827]
**Environemnet**
Pack - EI620 M1
JAVA - JDK 1.8
OS - Ubuntu
Tenant User

**Pre requisites** 
User logged in to the tenant domain

**Steps to recreate the issue**
1. Create a data service with POST resource
ex:

```
   <query id="addperson" useConfig="dsid">
      <sql>INSERT INTO Persons (PersonID,LastName,FirstName,Address,City) VALUES (:id,:Lname,:Fname,:Address,:city);</sql>
      <param name="id" sqlType="INTEGER"/>
      <param name="Lname" sqlType="STRING"/>
      <param name="Fname" sqlType="STRING"/>
      <param name="Address" sqlType="STRING"/>
      <param name="city" sqlType="STRING"/>
   </query>

 <resource method="POST" path="/person/addperson" returnRequestStatus="true">
      <call-query href="addperson">
         <with-param name="id" query-param="id"/>
         <with-param name="Lname" query-param="Lname"/>
         <with-param name="Fname" query-param="Fname"/>
         <with-param name="Address" query-param="Address"/>
         <with-param name="city" query-param="city"/>
      </call-query>
   </resource>
```
2. Enbale batch request
3. Invoke the batch request for POST method using json payload
**Payload**

http://localhost:8280/services/t/tenant.com/mysqldss/addperson_batch_req

```
{
    "_post_person_addperson_batch_req": {
        "_post_person_addperson": [
            {
                "id" : 1160,
    "Lname": "Lname",
    "Fname": "Fname",
    "Address": "Address1",
    "city": "City1"
            },
            {
                "id" : 1161,
    "Lname": "Lname",
    "Fname": "Fname",
    "Address": "Address2",
    "city": "City1"
            }
        ]
    }
}
```

**Observations**
1. Unable to invoke the POST batch request with JSON payload

Please find the following wire logs

```
[2017-07-27 15:32:02,728] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "POST /services/t/tenant.com/mysqldss/addperson_batch_req HTTP/1.1[\r][\n]"
[2017-07-27 15:32:02,728] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "Connection: keep-alive[\r][\n]"
[2017-07-27 15:32:02,728] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "Accept: application/json[\r][\n]"
[2017-07-27 15:32:02,728] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "Content-Type: application/json[\r][\n]"
[2017-07-27 15:32:02,728] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "Content-Length: 413[\r][\n]"
[2017-07-27 15:32:02,728] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "Host: localhost:8280[\r][\n]"
[2017-07-27 15:32:02,728] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_66)[\r][\n]"
[2017-07-27 15:32:02,728] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "[\r][\n]"
[2017-07-27 15:32:02,728] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "{[\r][\n]"
[2017-07-27 15:32:02,728] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "    "_post_person_addperson_batch_req": {[\r][\n]"
[2017-07-27 15:32:02,728] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "        "_post_person_addperson": [[\r][\n]"
[2017-07-27 15:32:02,728] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "            {[\r][\n]"
[2017-07-27 15:32:02,728] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "                "id" : 1160,[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "    "Lname": "Lname",[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "    "Fname": "Fname",[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "    "Address": "Address1",[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "    "city": "City1"[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "            },[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "            {[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "                "id" : 1161,[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "    "Lname": "Lname",[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "    "Fname": "Fname",[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "    "Address": "Address2",[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "    "city": "City1"[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "            }[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "        ][\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "    }[\r][\n]"
[2017-07-27 15:32:02,729] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 >> "}"
[2017-07-27 15:32:02,737] [EI-Core] ERROR - AxisEngine The endpoint reference (EPR) for the Operation not found is local://axis2services/mysqldss/addperson_batch_req and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.
org.apache.axis2.AxisFault: The endpoint reference (EPR) for the Operation not found is local://axis2services/mysqldss/addperson_batch_req and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.
	at org.apache.axis2.engine.DispatchPhase.checkPostConditions(DispatchPhase.java:102)
	at org.apache.axis2.engine.Phase.invoke(Phase.java:329)
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRESTRequest(MultitenantMessageReceiver.java:641)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doNhttpREST(MultitenantMessageReceiver.java:578)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doREST(MultitenantMessageReceiver.java:383)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRequest(MultitenantMessageReceiver.java:233)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:83)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:329)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:375)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-07-27 15:32:02,738] [EI-Core] ERROR - AxisEngine The endpoint reference (EPR) for the Operation not found is local://axis2services/mysqldss/addperson_batch_req and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.
org.apache.axis2.AxisFault: The endpoint reference (EPR) for the Operation not found is local://axis2services/mysqldss/addperson_batch_req and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doNhttpREST(MultitenantMessageReceiver.java:611)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doREST(MultitenantMessageReceiver.java:383)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRequest(MultitenantMessageReceiver.java:233)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:83)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:329)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:375)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-07-27 15:32:02,739] [EI-Core] ERROR - ServerWorker Error processing POST request for : /services/t/tenant.com/mysqldss/addperson_batch_req
org.apache.axis2.AxisFault: The endpoint reference (EPR) for the Operation not found is local://axis2services/mysqldss/addperson_batch_req and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doNhttpREST(MultitenantMessageReceiver.java:611)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doREST(MultitenantMessageReceiver.java:383)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRequest(MultitenantMessageReceiver.java:233)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:83)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:329)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:375)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-07-27 15:32:02,741] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
[2017-07-27 15:32:02,741] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 << "Content-Type: application/json; charset=UTF-8[\r][\n]"
[2017-07-27 15:32:02,741] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 << "Date: Thu, 27 Jul 2017 10:02:02 GMT[\r][\n]"
[2017-07-27 15:32:02,741] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 << "Transfer-Encoding: chunked[\r][\n]"
[2017-07-27 15:32:02,741] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 << "Connection: keep-alive[\r][\n]"
[2017-07-27 15:32:02,741] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 << "[\r][\n]"
[2017-07-27 15:32:02,741] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 << "83a[\r][\n]"
[2017-07-27 15:32:02,742] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 << "{"Fault":{"faultcode":"axis2ns26:Client","faultstring":"The endpoint reference (EPR) for the Operation not found is local://axis2services/mysqldss/addperson_batch_req and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.","detail":{"Exception":"org.apache.axis2.AxisFault: The endpoint reference (EPR) for the Operation not found is local://axis2services/mysqldss/addperson_batch_req and the WSA Action = null. If this EPR was previously reachable, please contact the server administrator.\n\tat org.apache.axis2.engine.DispatchPhase.checkPostConditions(DispatchPhase.java:102)\n\tat org.apache.axis2.engine.Phase.invoke(Phase.java:329)\n\tat org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)\n\tat org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)\n\tat org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRESTRequest(MultitenantMessageReceiver.java:641)\n\tat org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doNhttpREST(MultitenantMessageReceiver.java:578)\n\tat org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.doREST(MultitenantMessageReceiver.java:383)\n\tat org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processRequest(MultitenantMessageReceiver.java:233)\n\tat org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:83)\n\tat org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)\n\tat org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:329)\n\tat org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:375)\n\tat org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)\n\tat org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\n"}}}[\r][\n]"
[2017-07-27 15:32:02,742] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 << "0[\r][\n]"
[2017-07-27 15:32:02,742] [EI-Core] DEBUG - wire HTTP-Listener I/O dispatcher-2 << "[\r][\n]"
```

This works for super tenant user
```
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "POST /services/mysqldss/person/addperson_batch_req HTTP/1.1[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "Connection: keep-alive[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "Accept: application/json[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "Content-Type: application/json[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "Content-Length: 413[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "Host: localhost:8243[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_66)[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "{[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "    "_post_person_addperson_batch_req": {[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "        "_post_person_addperson": [[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "            {[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "                "id" : 1165,[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "    "Lname": "Lname",[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "    "Fname": "Fname",[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "    "Address": "Address1",[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "    "city": "City1"[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "            },[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "            {[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "                "id" : 1166,[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "    "Lname": "Lname",[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "    "Fname": "Fname",[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "    "Address": "Address2",[\r][\n]"
[2017-07-27 15:32:02,780] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "    "city": "City1"[\r][\n]"
[2017-07-27 15:32:02,781] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "            }[\r][\n]"
[2017-07-27 15:32:02,781] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "        ][\r][\n]"
[2017-07-27 15:32:02,781] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "    }[\r][\n]"
[2017-07-27 15:32:02,781] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 >> "}"
[2017-07-27 15:32:02,813] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 << "HTTP/1.1 200 OK[\r][\n]"
[2017-07-27 15:32:02,813] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 << "Content-Type: application/json; charset=UTF-8[\r][\n]"
[2017-07-27 15:32:02,813] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 << "Date: Thu, 27 Jul 2017 10:02:02 GMT[\r][\n]"
[2017-07-27 15:32:02,813] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 << "Transfer-Encoding: chunked[\r][\n]"
[2017-07-27 15:32:02,813] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 << "Connection: keep-alive[\r][\n]"
[2017-07-27 15:32:02,813] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 << "[\r][\n]"
[2017-07-27 15:32:02,813] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 << "1f[\r][\n]"
[2017-07-27 15:32:02,813] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 << "{"REQUEST_STATUS":"SUCCESSFUL"}[\r][\n]"
[2017-07-27 15:32:02,813] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 << "0[\r][\n]"
[2017-07-27 15:32:02,813] [EI-Core] DEBUG - wire HTTPS-Listener I/O dispatcher-3 << "[\r][\n]"
```

**Comment by arukshani** [comment]
This is not a bug. URL should be
"http://localhost:8280/services/t/tenant.com/mysqldss/person/addperson_batch_req" then it works fine for the tenant as well.
