### ISSUE TITLE
[BPS][tenant]  tenant login failed in bpmn-explorer

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#87]
**Environment**

-  OS-ubuntu
-  JAVA- jdk 1.7.0_51
-  Browser-Chrome 51.o.27, Firefox 47
-  wso2ei-6.0.0-SNAPSHOT 27th pack

**Steps**

**1**. Make a copy of <BPS_HOME>/repository/deployment/server/jaggeryapps/bpmn-explorer directory

**2**. Update <COPY_DIRECTORY>/bpmn-explorer/config/config.json configuration file
               eg: if tenant domain id wso2.bps.com
              "bpsTenantDomain": "wso2.bps.com"
               update bpsTenantId with tenant id

**3**. Copy above bpmn-explorer.zip to <BPS_HOME>/repository/tenants/<TENANT_ID>/jaggeryapps directory

**4**. Browse the https://172.17.0.1:9445/t/tenantdomain/jaggeryapps/bpmn-explorer/ and login through the tenant.

**Error**

- Login failed and frontend redirect to a 500 error page

- Back end throws the following exception

`[2017-01-30 14:16:42,851] [EI-Business-Process] @chal.com [1] [BPS]ERROR {org.jaggeryjs.jaggery.core.manager.WebAppManager} -  org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (<<http>>/META-INF/scripts/http.js#17) (/t/chal.com/jaggeryapps/bpmn-explorer/controller/statsController.jag#17)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (<<http>>/META-INF/scripts/http.js#17) (/t/chal.com/jaggeryapps/bpmn-explorer/controller/statsController.jag#17)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:113)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:958)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1756)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1715)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (<<http>>/META-INF/scripts/http.js#17) (/t/chal.com/jaggeryapps/bpmn-explorer/controller/statsController.jag#17)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.t.chal.com.jaggeryapps.bpmn_explorer.controller.c1._c_script_0(/t/chal.com/jaggeryapps/bpmn-explorer/controller/statsController.jag:17)
	at org.jaggeryjs.rhino.t.chal.com.jaggeryapps.bpmn_explorer.controller.c1.call(/t/chal.com/jaggeryapps/bpmn-explorer/controller/statsController.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.t.chal.com.jaggeryapps.bpmn_explorer.controller.c1.call(/t/chal.com/jaggeryapps/bpmn-explorer/controller/statsController.jag)
	at org.jaggeryjs.rhino.t.chal.com.jaggeryapps.bpmn_explorer.controller.c1.exec(/t/chal.com/jaggeryapps/bpmn-explorer/controller/statsController.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	... 41 more
Caused by: org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (<<http>>/META-INF/scripts/http.js#17)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:309)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 50 more
Caused by: org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (<<http>>/META-INF/scripts/http.js#17)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665)
	at org.mozilla.javascript.NativeJSON.parse(NativeJSON.java:112)
	at org.mozilla.javascript.NativeJSON.execIdCall(NativeJSON.java:88)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.jaggeryjs.rhino.<<http>>.META_INF.scripts.c0._c_anonymous_2(<<http>>/META-INF/scripts/http.js:17)
	at org.jaggeryjs.rhino.<<http>>.META_INF.scripts.c0.call(<<http>>/META-INF/scripts/http.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.<<http>>.META_INF.scripts.c0._c_anonymous_5(<<http>>/META-INF/scripts/http.js:221)
	at org.jaggeryjs.rhino.<<http>>.META_INF.scripts.c0.call(<<http>>/META-INF/scripts/http.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.<<http>>.META_INF.scripts.c0._c_anonymous_7(<<http>>/META-INF/scripts/http.js:228)
	at org.jaggeryjs.rhino.<<http>>.META_INF.scripts.c0.call(<<http>>/META-INF/scripts/http.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.t.chal.com.jaggeryapps.bpmn_explorer.model.c0._c_script_0(/t/chal.com/jaggeryapps/bpmn-explorer/model/common.jag:130)
	at org.jaggeryjs.rhino.t.chal.com.jaggeryapps.bpmn_explorer.model.c0.call(/t/chal.com/jaggeryapps/bpmn-explorer/model/common.jag)
	at org.jaggeryjs.rhino.t.chal.com.jaggeryapps.bpmn_explorer.model.c0.exec(/t/chal.com/jaggeryapps/bpmn-explorer/model/common.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	... 58 more

`

**Comment by himasha** [comment]
This is reproducible in WSO2-BPS 3.6.0 as well.

**Comment by himasha** [comment]
This issue is due to missing REST API deployed under specific tenant. Updated the steps in https://wso2.org/jira/browse/BPS-821.

**Comment by milindaperera** [comment]
Add instructions available in https://wso2.org/jira/browse/BPS-821
