### ISSUE TITLE
Connection close failure due to a server exception

### ISSUE THREAD

**Issue by a5anka** [wso2/product-ei#871]
Publisher connection failed when the connection was closed immediately after publishing message. You will have to use a fresh pack to reproduce the issue.

## Sample code used.
```java
        ConnectionFactory connectionFactory = (ConnectionFactory) initialContextForQueue
                .lookup(JMSClientHelper.QUEUE_CONNECTION_FACTORY);

        // Initialize publisher
        Connection publisherConnection = connectionFactory.createConnection();
        publisherConnection.start();

        Session publisherSession1 = publisherConnection.createSession(false, Session.AUTO_ACKNOWLEDGE);

        Destination publisherDestination = (Destination) initialContextForQueue.lookup("MyQueue1");
        MessageProducer producer1 = publisherSession1.createProducer(publisherDestination);

        producer1.send(publisherSession1.createTextMessage("Test P1 " + 1));

        publisherConnection.close();
```

## Server side exception
```
[2017-08-15 09:50:32,879]  INFO {qpid.message.connection.close} - [con:54,996,456,575,598,592(admin@/127.0.0.1:36560/carbon)] [con:54,996,456,575,598,592(admin@/127.0.0.1:36560/carbon)] CON-1002 : Close
[2017-08-15 09:50:32,880]  WARN {org.wso2.andes.pool.Job} - Thread pool shutdown while tasks still outstanding:Task org.wso2.andes.pool.Job@d4156ed rejected from java.util.concurrent.ThreadPoolExecutor@4843d921[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 14] java.util.concurrent.RejectedExecutionException: Task org.wso2.andes.pool.Job@d4156ed rejected from java.util.concurrent.ThreadPoolExecutor@4843d921[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 14]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at org.wso2.andes.pool.Job.fireAsynchEvent(Job.java:197)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.writeFrame(AMQProtocolEngine.java:502)
	at org.wso2.andes.server.handler.ConnectionCloseMethodHandler.methodReceived(ConnectionCloseMethodHandler.java:66)
	at org.wso2.andes.server.handler.ServerMethodDispatcherImpl.dispatchConnectionClose(ServerMethodDispatcherImpl.java:354)
	at org.wso2.andes.framing.amqp_0_91.ConnectionCloseBodyImpl.execute(ConnectionCloseBodyImpl.java:140)
	at org.wso2.andes.server.state.AMQStateManager.methodReceived(AMQStateManager.java:169)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.methodFrameReceived(AMQProtocolEngine.java:388)
	at org.wso2.andes.framing.AMQMethodBodyImpl.handle(AMQMethodBodyImpl.java:92)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.frameReceived(AMQProtocolEngine.java:333)
	at org.wso2.andes.server.protocol.AMQProtocolEngine.dataBlockReceived(AMQProtocolEngine.java:282)
	at org.wso2.andes.server.protocol.AMQProtocolEngine$1.run(AMQProtocolEngine.java:251)
	at org.wso2.andes.pool.Job.processAll(Job.java:111)
	at org.wso2.andes.pool.Job.run(Job.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Client side exception

```
Exception in thread "main" javax.jms.JMSException: Error closing connection: org.wso2.andes.AMQException: AMQP timed out when attempting to close the connection 
	at org.wso2.andes.client.AMQConnection.doClose(AMQConnection.java:970)
	at org.wso2.andes.client.AMQConnection.doClose(AMQConnection.java:913)
	at org.wso2.andes.client.AMQConnection.close(AMQConnection.java:896)
	at org.wso2.andes.client.AMQConnection.close(AMQConnection.java:887)
	at org.wso2.andes.client.AMQConnection.close(AMQConnection.java:882)
	at org.wso2.mb.testing.client.JMSPublisher.main(JMSPublisher.java:55)
Caused by: org.wso2.andes.AMQException: AMQP timed out when attempting to close the connection 
	at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:726)
	at org.wso2.andes.client.AMQConnectionDelegate_8_0.closeConnection(AMQConnectionDelegate_8_0.java:67)
	at org.wso2.andes.client.AMQConnection.doClose(AMQConnection.java:954)
	... 5 more
Caused by: org.wso2.andes.AMQTimeoutException: Server did not respond in a timely fashion [error code 408: Request Timeout]
	at org.wso2.andes.client.util.BlockingWaiter.waitForFrame(BlockingWaiter.java:206)
	at org.wso2.andes.client.util.BlockingWaiter.writeAndWait(BlockingWaiter.java:380)
	at org.wso2.andes.client.protocol.BlockingMethodFrameListener.writeAndBlockForFrame(BlockingMethodFrameListener.java:147)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.writeCommandFrameAndWaitForReply(AMQProtocolHandler.java:662)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.syncWrite(AMQProtocolHandler.java:689)
	at org.wso2.andes.client.protocol.AMQProtocolHandler.closeConnection(AMQProtocolHandler.java:720)
	... 7 more
```

**Comment by sdkottegoda** [comment]
Ran a test of 1000 tests runs against Ei 6.5.0-M4 and the issue was not reproducible.
