### ISSUE TITLE
[BPS][Humantask] While deploying the "HTWithServiceDescriptorANDUnifiedEndpoint" human task throws an error.

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#89]
**Enviornment**
-  OS-ubuntu
-  JAVA- jdk 1.7.0_51
-  Browser-Chrome 51.o.27, Firefox 47
-  wso2ei-6.0.0-SNAPSHOT 27th pack

**Steps**
Deploy the **HTWithServiceDescriptorANDUnifiedEndpoint** sample for the first time and backend throws the following error
`[EI-Business-Process] ERROR {org.wso2.carbon.humantask.core.store.HumanTaskStore} -  Error populating the service
[2017-01-30 15:30:45,502] [EI-Business-Process] ERROR {org.wso2.carbon.humantask.deployer.HumanTaskDeployer} -  Error deploying HumanTask package : HTWithServiceDescriptorANDUnifiedEndpoint.zip
org.wso2.carbon.humantask.core.deployment.HumanTaskDeploymentException: Error populating the service
	at org.wso2.carbon.humantask.core.store.HumanTaskStore.deploy(HumanTaskStore.java:691)
	at org.wso2.carbon.humantask.core.store.HumanTaskStore.deploy(HumanTaskStore.java:186)
	at org.wso2.carbon.humantask.core.store.HumanTaskStore.deployNewTaskVersion(HumanTaskStore.java:524)
	at org.wso2.carbon.humantask.core.store.HumanTaskStore.deploy(HumanTaskStore.java:479)
	at org.wso2.carbon.humantask.deployer.HumanTaskDeployer.deploy(HumanTaskDeployer.java:65)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.apache.axis2.AxisFault: Two services cannot have same name.  A service with the HTWSDAUEService [null] name already exists in the system.
	at org.apache.axis2.engine.AxisConfiguration.addToAllServicesMap(AxisConfiguration.java:510)
	at org.apache.axis2.description.AxisServiceGroup.addService(AxisServiceGroup.java:110)
	at org.apache.axis2.deployment.DeploymentEngine.fillServiceGroup(DeploymentEngine.java:745)
	at org.apache.axis2.deployment.DeploymentEngine.addServiceGroup(DeploymentEngine.java:601)
	at org.wso2.carbon.humantask.core.store.HumanTaskStore.deploy(HumanTaskStore.java:680)
	... 21 more
`

**Comment by chalitha87** [comment]
This is due to a same service has used in both ClaimsApprovalTaskWithMultipleDomains and HTWithServiceDescriptorANDUnifiedEndpoint samples. Better to mention on docs.

**Comment by praneesha** [comment]
Added the following note in all samples under [1].

"If you already deployed a human task sample, delete the relevant ZIP file from the <EI_HOME>/wso2/business-process/repository/deployment/server/humantasks/ directory to undeploy it before deploying another sample."

[1] https://docs.wso2.com/display/EI600/Human+Task+Samples
