### ISSUE TITLE
Move MB tests to product-ei repository

### ISSUE THREAD

**Issue by Manuri** [wso2/product-ei#928]
Move integration tests at [1] to product-ei repo.

[1] https://github.com/wso2-attic/product-mb

**Comment by hastef88** [comment]
As per PR : https://github.com/wso2/product-ei/pull/1339 we have in theory moved the tests in to the EI repo. But facing a connectivity error when running the MB test profile. 

INFO  [org.wso2.carbon.automation.engine.testlisteners.TestManagerListener] - =================== Running the test method org.wso2.ei.mb.integration.tests.amqp.functional.ClientAcknowledgementsTestCase.performClientAcknowledgementsTestCase ===================
Jan 18, 2018 11:31:44 AM org.wso2.andes.client.AMQConnectionFactory createConnection
SEVERE: Error while creating connection
org.wso2.andes.AMQConnectionFailureException: Unable to Connect
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:485)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:328)
	at org.wso2.andes.client.AMQConnectionFactory.createQueueConnection(AMQConnectionFactory.java:420)
	at org.wso2.ei.mb.integration.common.clients.AndesJMSConsumer.createQueueConnection(AndesJMSConsumer.java:186)
	at org.wso2.ei.mb.integration.common.clients.AndesJMSConsumer.<init>(AndesJMSConsumer.java:119)
	at org.wso2.ei.mb.integration.common.clients.AndesClient.<init>(AndesClient.java:110)
	at org.wso2.ei.mb.integration.common.clients.AndesClient.<init>(AndesClient.java:76)
	at org.wso2.ei.mb.integration.tests.amqp.functional.ClientAcknowledgementsTestCase.performClientAcknowledgementsTestCase(ClientAcknowledgementsTestCase.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by dilee** [comment]
Fixed in https://github.com/wso2/product-ei/pull/2849
