### ISSUE TITLE
Exception thrown for some HTTP error codes when call mediator is used 

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#951]
I have an API which uses a blocking call mediator to call an HTTP endpoint. When the endpoint responds with a 401 error code, the ESB throws an exception[1] and triggers the fault sequence. If I use a non-blocking call mediator the response comes to the out sequence without errors.

[1]
```
org.apache.axis2.AxisFault: Failed to submit the response
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.handleException(PassThroughHttpSender.java:610)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:269)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:212)
	at org.apache.synapse.mediators.builtin.RespondMediator.mediate(RespondMediator.java:28)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:81)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:48)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:149)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:81)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:48)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:149)
	at org.apache.synapse.rest.Resource.process(Resource.java:297)
	at org.apache.synapse.rest.API.process(API.java:378)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:97)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:65)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:266)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:83)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:317)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:149)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
```

**Comment by sdkottegoda** [comment]
We need to hold this change as this will affect a wider audience than just Call mediator and Message processor.
Also, we need to invest some cycles to see whether we can use a single transport implementation for both blocking and non-blocking behaviours.
That will be the most reliable solution to address the inconsistencies in blocking vs non-blocking behaviours.
