### ISSUE TITLE
Exception when reloading durable subscription 

### ISSUE THREAD

**Issue by a5anka** [wso2/product-ei#985]
### Steps to reproduce

1. Create a two node cluster pointing to a MySQL database
1. Subscribe to a queue using a JMS consumer
1. Restart the broker node

Following exception was observed when the MB node was restarted. 

```
[2017-09-07 11:05:26,402] ERROR {org.wso2.andes.kernel.disruptor.LogExceptionHandler} - [ Sequence: 18 ] Exception occurred while processing inbound events. java.lang.NumberFormatException: For input string: "651fa5df973"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:776)
	at java.lang.Long.decode(Long.java:928)
	at java.util.UUID.fromString(UUID.java:206)
	at org.wso2.andes.kernel.subscription.SubscriberConnection.<init>(SubscriberConnection.java:142)
	at org.wso2.andes.kernel.subscription.AndesSubscription.<init>(AndesSubscription.java:145)
	at org.wso2.andes.kernel.subscription.AndesSubscriptionManager.addRemoteSubscription(AndesSubscriptionManager.java:201)
	at org.wso2.andes.kernel.disruptor.inbound.InboundSubscriptionSyncEvent.handleOpenSubscriptionEvent(InboundSubscriptionSyncEvent.java:127)
	at org.wso2.andes.kernel.disruptor.inbound.InboundSubscriptionSyncEvent.updateState(InboundSubscriptionSyncEvent.java:99)
	at org.wso2.andes.kernel.disruptor.inbound.InboundEventContainer.updateState(InboundEventContainer.java:238)
	at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:55)
	at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:31)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by a5anka** [comment]
Fixed in https://github.com/a5anka/andes/commit/d6a8a9ae3ab3ce801a5ab20fcd7e5761e4370e2d

**Comment by vinok88** [comment]
Fixed for master branch as well in https://github.com/wso2/andes/pull/931.
