### ISSUE TITLE
[ESB490] Unable to use script mediator as a registry entry to inject CDATA into an XML payload

### ISSUE THREAD

**Issue by hastef88** [wso2/product-ei#997]
This works in EI 6.1.1 even though failing in ESB 4.9.0.

**Example Proxy** : 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="myproxy"
       transports="http,https"
       statistics="disable"
       trace="disable"
       startOnLoad="true">
   <target>
      <inSequence>
         <send>
            <endpoint>
               <address uri="http://www.mocky.io/v2/59afe88c1000002a04db2070"/>
            </endpoint>
         </send>
      </inSequence>
      <outSequence>
         <property xmlns:ns="http://ws.apache.org/commons/ns/payload"
                   name="msgbody"
                   expression="//ns:text"/>
         <script language="js" key="conf:/jscript" function="samplefunction"/>
         <send/>
      </outSequence>
   </target>
   <description/>
</proxy>
```

**Script function** : 

```javascript
function samplefunction(mc) {
var xml_ref = "&lt;rootlevel&gt;" 
               + "&lt;PVC&gt;&lt;![CDATA[" + mc.getProperty('msgbody') + "]]&gt;&lt;/PVC&gt;"
                + "&lt;/rootlevel&gt;";
            var  result = new XML(xml_ref);
print(result);
}
```

**Response from mocky back-end** : 

< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
```xml
<soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
<soapenv:Body>
<text xmlns="http://ws.apache.org/commons/ns/payload">
   [OK| |CB| [0|18940429| |CHAMPU BRILLO&LUMINOSIDAD|S|000000|000000000.00|0000001.65| ]]
</text>
</soapenv:Body>
</soapenv:Envelope>
```

**Error**

[2017-09-08 14:24:48,022] ERROR - ScriptMediator The script engine returned an error executing the external js script : Value {name ='null', keyValue ='conf:/jscript'} function gocraycray
com.sun.phobos.script.util.ExtendedScriptException: org.mozilla.javascript.EcmaError: TypeError: error: Unexpected element: CDATA (<Unknown source>#5) in <Unknown source> at line number 5
	at com.sun.phobos.script.javascript.RhinoScriptEngine.invokeMethod(RhinoScriptEngine.java:259)
	at com.sun.phobos.script.javascript.RhinoScriptEngine.invokeFunction(RhinoScriptEngine.java:216)
	at org.apache.synapse.mediators.bsf.ScriptMediator.mediateWithExternalScript(ScriptMediator.java:279)
	at org.apache.synapse.mediators.bsf.ScriptMediator.invokeScript(ScriptMediator.java:237)
	at org.apache.synapse.mediators.bsf.ScriptMediator.mediate(ScriptMediator.java:207)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:81)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:48)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:149)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:297)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:529)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:172)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:247)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.mozilla.javascript.EcmaError: TypeError: error: Unexpected element: CDATA (<Unknown source>#5)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3350)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3340)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3356)
	at org.mozilla.javascript.xml.impl.xmlbeans.XML.createFromJS(XML.java:388)
	at org.mozilla.javascript.xml.impl.xmlbeans.XML.jsConstructor(XML.java:3065)
	at org.mozilla.javascript.xml.impl.xmlbeans.XMLObjectImpl.execIdCall(XMLObjectImpl.java:549)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:127)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:313)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2132)
	at org.mozilla.javascript.gen.c4._c1(<Unknown source>:5)
	at org.mozilla.javascript.gen.c4.call(<Unknown source>)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:2834)
	at org.mozilla.javascript.gen.c4.call(<Unknown source>)
	at com.sun.phobos.script.javascript.RhinoScriptEngine.invokeMethod(RhinoScriptEngine.java:245)
	... 16 more

**Comment by hastef88** [comment]
While trying out different approaches to escape special characters from a backend payload using CDATA, We were able to create a working and cleaner proxy+script configuration without the need for a fix. refer minimal sample herewith (escapaSpecialCharactersESB.zip).

Essentially the following guidelines, together, will allow you to accept a backend response, modify it to include CDATA, and respond from the proxy retaining the same, while avoiding any errors at the admin console.

1. Refer the javascript from a registry entry - to avoid admin console issue. 

a. Access the registry as explained in [1].
b. add a resource using "Create text content" option, and copy a script similar to attached jscript.js, and set the resource media type to "application/javascript".

2. Instead of writing the XML as escaped strings in javascript, use the XML type to directly write the unescaped XML body. (refer attached jscript.js file)

3. Instead of setting the XML as a payload within the script mediator, set it as a property in the message context. 

4. Use a payload mediator to inject the above set property into the response xml template.

Make sure to include the CDATA element in the XML written at step #2.

[1] : https://docs.wso2.com/display/ESB490/Working+with+the+Registry
[escapaSpecialCharactersESB_WA.zip](https://github.com/wso2/product-ei/files/1420809/escapaSpecialCharactersESB_WA.zip)
